### PR TITLE
`azurerm_mssql_server` - prevent aadOnly deletion before update

### LINKED ISSUE #22059: Changes to the mssql_server/azuread_administrator block cause the AD Administrator to be deleted then recreated.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.54

### Affected Resource(s)/Data Source(s)

azurerm_mssql_server

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_server" "sql_server" {
  name                          = local.sql_server_name
  resource_group_name           = azurerm_resource_group.sql.name
  location                      = var.location
  version                       = var.sql_server_version

  identity {
    type = "SystemAssigned"
  }

  azuread_administrator {
    login_username              = var.ad_admin_name
    object_id                   = var.ad_admin_object
    tenant_id                   = data.azurerm_client_config.current.tenant_id
    azuread_authentication_only = true
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

When editing the `azuread_administrator` block, the existing AAD Administrator of the SQL Server should be **updated** without being deleted and recreated.

### Actual Behaviour

When editing the `azuread_administrator` block, the existing AAD Administrator of the SQL Server is deleted and recreated.
The deletion conflicts with Azure Policy that requires a SQL Server to have an AAD Administrator causing the Terraform Apply operation to fail.

### Steps to Reproduce

1. Have an Azure Policy in-place that requires SQL Server have an AAD Administrator.
1. Create an `azurerm_mssql_server` resource with an `azuread_administrator` block via Terraform Apply.
2. Edit the `azuread_administrator` block and re-run Terraform Apply.

### Important Factoids

The Azure Policy that requires SQL Server have an AAD Administrator is the key to this issue.

### References

[mssql_server_resource.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/mssql/mssql_server_resource.go) - line 419 onwards.

### PR DESCRIPTION
**Pull request by catriona-m**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

This pr refactors the update of the `azuread_administrator` so that it doesn't get deleted and recreated by default on update, to allow for azure policy compliance. It now gets updated if there's a change and deleted if it is disabled.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #22059

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/mssql/mssql_server_resource.go [hunk 1]
```diff
@@ -461,22 +461,38 @@ func resourceMsSqlServerUpdate(d *pluginsdk.ResourceData, meta interface{}) erro
...
-
-		resp, err := adminClient.Get(ctx, pointer.From(id))
-		if err != nil {
-			if !response.WasNotFound(resp.HttpResponse) {
-				return fmt.Errorf("retrieving Azure Active Directory Administrators %s: %+v", pointer.From(id), err)
+		log.Printf("[INFO] Expanding 'azuread_administrator' to see if we need Create or Delete")
+		if adminProps := expandMsSqlServerAdministrator(d.Get("azuread_administrator").([]interface{})); adminProps != nil {
+			err := adminClient.CreateOrUpdateThenPoll(ctx, *id, pointer.From(adminProps))
+			if err != nil {
+				return fmt.Errorf("creating Azure Active Directory Administrator %s: %+v", id, err)
```
Comment (sreallymatt) [inline internal/services/mssql/mssql_server_resource.go]: nit: should this say updating since we're in the update func and this can do in-place updates now rather than delete+recreate?

```suggestion
				return fmt.Errorf("updating Azure Active Directory Administrator %s: %+v", id, err)
```
