### PR TITLE
`data.azurerm_function_app_host_keys` - Fix crash when no id is present

### LINKED ISSUE #8428: Using 2.27 with new data source azurerm_function_app_host_keys crashes terraform
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform 13.2
AzureRM 2.27

### Affected Resource(s)

* `azurerm_function_app_host_keys `

### Terraform Configuration Files

```hcl
data "azurerm_function_app_host_keys" "azfun_deletemessages_keys" {
  name                = "azfun-deletemessages-${var.environment}"
  resource_group_name = data.azurerm_resource_group.main.name
}

resource "azurerm_key_vault_secret" "kvs_deletemessages_function_key" {
  name          = "FUNCTION--KEY--DELETEMESSAGES"
  value         = data.azurerm_function_app_host_keys.azfun_deletemessages_keys.default_function_key
  key_vault_id  = module.kv_main.id
  tags          = local.tags_timeseries
}
```

### Debug Output
https://gist.github.com/Renetnielsen/e81ecce58ddfb68f2ee8a1c449d9694e

### Panic Output

Since our terraform only runs in a pipeline on a virtual machine in DevOps i can't access this file.

### Expected Behavior

The function key would have been inserted as a secret in our keyvault.

### Actual Behavior

_!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!_

### Steps to Reproduce

1. Create a function app using terraform
2. Use new azurerm_function_app_host_keys data source to get function key
3. Run `terraform init`
4. Run `terraform plan`
5. Crash

### PR DESCRIPTION
**Pull request by mbfrahry**
Fixes #8428

### CODE REVIEW

File: azurerm/internal/services/web/data_source_function_app_host_keys.go [hunk 1]
```diff
@@ -58,6 +58,9 @@ func dataSourceArmFunctionAppHostKeysRead(d *schema.ResourceData, meta interface
 		return fmt.Errorf("Error making Read request on AzureRM Function App %q: %+v", name, err)
 	}
 
+	if functionSettings.ID == nil {
+		return fmt.Errorf("cannot read ID for AzureRM Function App %q (Resource Group %q) was not found", name, resourceGroup)
```
Comment (manicminer) [inline azurerm/internal/services/web/data_source_function_app_host_keys.go:62]:
```suggestion
		return fmt.Errorf("cannot read ID for AzureRM Function App %q (Resource Group %q)", name, resourceGroup)
```

**Review by manicminer — APPROVED** [review]
@mbfrahry Just a minor wording suggestion, otherwise LGTM

**Comment by mbfrahry** [comment]
Thanks @manicminer!
