### PR TITLE
data source: `azurerm_ssh_public_key` - normalize ssh public key attribute

### LINKED ISSUE #12794: data.azurerm_ssh_public_key.{key_name}.public_key returns an improperly formatted key.
### Terraform Version
```
Terraform v1.0.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.69.0
```
### Expected Behavior
When trying to access the `public_key` attribute of an existing `azurerm_ssh_public_key` resource (via `data.azurerm_ssh_public_key.{key_name}.public_key`) the string returned should be a properly formatted public key. This key should be usable in other resources that require a public key. 
#### Example: 
```
data "azurerm_ssh_public_key" "example" {
  name                = "resource_name"
  resource_group_name = "rg_name"
}
```
should produce a `azurerm_ssh_public_key.example.public_key` output that can be used in a resource such as:

```
resource "azurerm_linux_virtual_machine" "example" {
  name                            = "example"
  resource_group_name             = azurerm_resource_group.example.name
  location                        = azurerm_resource_group.example.location
  size                            = "Standard_B2s"
  admin_username                  = "username"
  disable_password_authentication = true

  admin_ssh_key {
    username = "username"
    public_key = data.azurerm_ssh_public_key.example.public_key     # <<<<< This should be valid
  }
```

### Actual Behavior
When trying to access the `public_key` attribute of an existing `azurerm_ssh_public_key` resource (via `azurerm_ssh_public_key.{key_name}.public_key`) the string returned contains the escape characters `\r` and `\n` which leads to a failed validation check on resource creation.

The returned value for the `data.azurerm_ssh_public_key.example.public_key` would look something similar to:
```
"ssh-rsa ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSkT3A1j89RT/54\r\n0ghIMHXIVwNlAEM3WtmqVG7YN/wYwtsJ8iCszg4/lXQsfLFxYmEVe8L9\r\natgtMGCi5QdYPl4X/c+5YxFfm88Yjfx+2xEgUdOr864eaI22yaNMQ0AlyilmK+PcS\r\nyxKP4dzkf6B5Nsw8lhfB5n9F5md6GHLLjOGuBbH\r\nYlesKJKnt2cMzzS90BdRk73qW6wJ+MCUWo+cyBFZVGOzrjJGEcHewOCbVs+IJWBFSi6w1enbKGc+RY9KrnzeDKWWqzYnNofiHGVFAuMxrmZOasqlTIKiC2UK3RmLxZicWiQmPnpnjJRo\r\n7pL0oYM9r/sIWzD6i2S9szDy6aZ== generated-by-azure\r\n"
```
##### Note the `\r\n` characters which should not be present in the key.

This malformed key then triggers the following (not so helpful) error when code similar to what above is present on `terraform apply`:
`│ Error: Error parsing "admin_ssh_key.0.public_key" as a public key object`

### Workaround
This can be worked around by modifying the above line as such:
```
public_key = replace(data.azurerm_ssh_public_key.example.public_key, "\r\n", "")
```
This removes the `\r\n` characters from the key which allows `terraform apply` to succeed.

### PR DESCRIPTION
**Pull request by wasfree**
Fixes #12794

- rename NormaliseSSHKey func to NormalizeSSHKey (better fit in naming compared to other functions)
- move NormalizeSSHKey to utils package, so we could use same func for other resources e.g. kubernetes_cluster_resource
- normalize public_key attribute in azurerm_ssh_public_key data source

### CODE REVIEW

File: azurerm/internal/services/compute/ssh_public_key_data_source.go [hunk 1]
```diff
@@ -67,7 +67,11 @@ func dataSourceSshPublicKeyRead(d *pluginsdk.ResourceData, meta interface{}) err
 	d.Set("resource_group_name", resGroup)
 
 	if props := resp.SSHPublicKeyResourceProperties; props != nil {
-		d.Set("public_key", props.PublicKey)
+		sshKey, err := utils.NormalizeSSHKey(*props.PublicKey)
+		if err != nil {
+			return fmt.Errorf("unable to remove invalid formatting and line breaks from SSH Public Key %q (Resource Group %q)", name, resGroup)
+		}
+		d.Set("public_key", sshKey)
```
Comment (tombuildsstuff) [inline azurerm/internal/services/compute/ssh_public_key_data_source.go:74]: there's a crash here if this is nil, can we make this:

```suggestion
		publicKey := ""
		if props.PublicKey != nil {
			publicKey, err = utils.NormalizeSSHKey(*props.PublicKey)
			if err != nil {
				return fmt.Errorf("normalising public key: %+v", err)
			}
		}
		d.Set("public_key", publicKey)
```

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
hey @wasfree 

Thanks for this PR - taking a look through I've left one comment inline but if we can fix that up then this is otherwise good to go 👍 

Thanks!

File: azurerm/internal/services/compute/ssh_public_key_data_source.go (hunk 1 above)
Comment (tombuildsstuff) [reply azurerm/internal/services/compute/ssh_public_key_data_source.go]: we return a pointer from these functions since if error is non-nil the object returned should be (to avoid coding errors)

instead we can make `publicKey` a `*string` via: `var publicKey *string` to avoid that

Comment (wasfree) [reply azurerm/internal/services/compute/ssh_public_key_data_source.go]: ok, thanks.

**Review by tombuildsstuff — APPROVED** [review]
LGTM - thanks for pushing those changes @wasfree
