### PR TITLE
azurerm_image - change os_disk property to a list

### LINKED ISSUE #234: "azurerm_image" gets recreated with every run
_This issue was originally opened by @spbreed as hashicorp/terraform#15773. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
Terraform v0.10.0

### Terraform Configuration Files
```hcl

resource "azurerm_image" "test" {
  name = "acctest"
  location = "East US 2"
  resource_group_name = "${azurerm_resource_group.test.name}"
  os_disk {
    os_type = "Linux"
    os_state = "Generalized"
    blob_uri = "https://pcsnonprodimages.blob.core.windows.net/system/Microsoft.Compute/Images/images/pcsnonprod-ubuntuv01-osDisk.6a65bac6-bc69-4785-948b-a419820c76f0.vhd"
    # size_gb = 30
  }
}


```

### Debug Output
```terraform apply```
``` json
azurerm_resource_group.test: Creating...
  location: "" => "eastus2"
  name:     "" => "acctestrg"
  tags.%:   "" => "<computed>"
azurerm_resource_group.test: Creation complete (ID: /subscriptions/9bc818d2-70ea-4c3a-9677-0d312a2e5b65/resourceGroups/acctestrg)
azurerm_image.test: Creating...
  location:                           "" => "eastus2"
  name:                               "" => "acctest"
  os_disk.#:                          "" => "1"
  os_disk.3156744706.blob_uri:        "" => "https://pcsnonprodimages.blob.core.windows.net/system/Microsoft.Compute/Images/images/pcsnonprod-ubuntuv01-osDisk.6a65bac6-bc69-4785-948b-a419820c76f0.vhd"
  os_disk.3156744706.managed_disk_id: "" => "<computed>"
  os_disk.3156744706.os_state:        "" => "Generalized"
  os_disk.3156744706.os_type:         "" => "Linux"
  os_disk.3156744706.size_gb:         "" => "<computed>"
  resource_group_name:                "" => "acctestrg"
  tags.%:                             "" => "<computed>"
azurerm_image.test: Still creating... (10s elapsed)
azurerm_image.test: Still creating... (20s elapsed)
azurerm_image.test: Still creating... (30s elapsed)
azurerm_image.test: Still creating... (40s elapsed)
azurerm_image.test: Still creating... (50s elapsed)
azurerm_image.test: Still creating... (1m0s elapsed)
azurerm_image.test: Creation complete (ID: /subscriptions/9bc818d2-70ea-4c3a-9677-...iders/Microsoft.Compute/images/acctest)
```
``` terraform plan```
``` json
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

azurerm_resource_group.test: Refreshing state... (ID: /subscriptions/9bc818d2-70ea-4c3a-9677-0d312a2e5b65/resourceGroups/acctestrg)
azurerm_image.test: Refreshing state... (ID: /subscriptions/9bc818d2-70ea-4c3a-9677-...iders/Microsoft.Compute/images/acctest)
The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

-/+ azurerm_image.test (new resource required)
      location:                           "eastus2" => "eastus2"
      name:                               "acctest" => "acctest"
      os_disk.#:                          "1" => "1"
      os_disk.2453480131.os_state:        "Generalized" => ""
      os_disk.2453480131.os_type:         "Linux" => ""
      os_disk.3156744706.blob_uri:        "" => "https://pcsnonprodimages.blob.core.windows.net/system/Microsoft.Compute/Images/images/pcsnonprod-ubuntuv01-osDisk.6a65bac6-bc69-4785-948b-a419820c76f0.vhd" (forces new resource)
      os_disk.3156744706.managed_disk_id: "" => "<computed>"
      os_disk.3156744706.os_state:        "" => "Generalized"
      os_disk.3156744706.os_type:         "" => "Linux"
      os_disk.3156744706.size_gb:         "" => "<computed>"
      resource_group_name:                "acctestrg" => "acctestrg"
      tags.%:                             "0" => "<computed>"


Plan: 1 to add, 0 to change, 1 to destroy.
```
### TF state file
``` json

"primary": {
                        "id": "/subscriptions/9bc818d2-70ea-4c3a-9677-0d312a2e5b65/resourceGroups/acctestrg/providers/Microsoft.Compute/images/acctest",
                        "attributes": {
                            "data_disk.#": "0",
                            "id": "/subscriptions/9bc818d2-70ea-4c3a-9677-0d312a2e5b65/resourceGroups/acctestrg/providers/Microsoft.Compute/images/acctest",
                            "location": "eastus2",
                            "name": "acctest",
                            "os_disk.#": "1",
                            "os_disk.2453480131.blob_uri": "https://pcsnonprodimages.blob.core.windows.net/system/Microsoft.Compute/Images/images/pcsnonprod-ubuntuv01-osDisk.6a65bac6-bc69-4785-948b-a419820c76f0.vhd",
                            "os_disk.2453480131.caching": "None",
                            "os_disk.2453480131.managed_disk_id": "",
                            "os_disk.2453480131.os_state": "Generalized",
                            "os_disk.2453480131.os_type": "Linux",
                            "os_disk.2453480131.size_gb": "0",
                            "resource_group_name": "acctestrg",
                            "tags.%": "0"
                        },
                        "meta": {},
                        "tainted": false
                    },
```
### Expected Behavior
Terraform plan should not recreate the resource

### Actual Behavior
with every run image is deleted and recreated. refer "Debug Output" section

### Steps to Reproduce
1. `terraform apply` (to create iy for the first time)
2. `terraform plan` or `terraform apply` -> recreates the image again

This in turn recreates the VM as Image_ID is referenced `storage_image_reference`

### PR DESCRIPTION
**Pull request by katbyte**
Should fix #234 

Also adds some validation

### CODE REVIEW

File: azurerm/helpers/validate/url.go [hunk 1]
```diff
@@ -0,0 +1,48 @@
+package validate
+
+import (
+	"fmt"
+	"net/url"
+
+	"github.com/hashicorp/terraform/helper/schema"
+	"strings"
```
Comment (paultyng) [inline azurerm/helpers/validate/url.go]: can you move this up to the first group of imports?

File: azurerm/helpers/validate/url.go [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+)
+
+func UrlIsHttpOrHttps(i interface{}, k string) (_ []string, errors []error) {
```
Comment (paultyng) [inline azurerm/helpers/validate/url.go]: There may have been a precedent here you are following, but traditionally initialisms in Go are capitalized: https://github.com/golang/go/wiki/CodeReviewComments#initialisms

`URLIsHTTPOrHTTPS` I think? I may be misreading this thing from Go, may want to run the linter on it.

File: azurerm/helpers/validate/url.go [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+	return UrlWithScheme([]string{"http", "https"})(i, k)
+}
+
+func UrlWithScheme(validSchemes []string) schema.SchemaValidateFunc {
```
Comment (paultyng) [inline azurerm/helpers/validate/url.go]: See other comment on initialisms.

File: azurerm/helpers/validate/url_test.go [hunk 4]
```diff
@@ -0,0 +1,45 @@
+package validate
+
+import (
+	"testing"
+)
+
+func TestHelper_Validate_UrlIsHttpOrHttps(t *testing.T) {
```
Comment (paultyng) [inline azurerm/helpers/validate/url_test.go]: I would just call this `Test<function name>` and if its one of many methods `Test<function name>_<description>`

**Comment by katbyte** [comment]
tests pass aside from failures due to too many virtual networks.
screen shot 2018-06-25 at 17 28 56
screen shot 2018-06-25 at 17 28 40

File: azurerm/helpers/validate/url_test.go [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+			Errors: 0,
+		},
+		{
+			Url:    "https://www.example.com",
+			Errors: 0,
+		},
+	}
+
+	for _, tc := range cases {
+		_, errors := UrlIsHttpOrHttps(tc.Url, "test")
```
Comment (paultyng) [inline azurerm/helpers/validate/url_test.go]: these cases should be inside a `t.Run`

**Comment by katbyte** [comment]
@paultyng,

Tests have been switched over to `t.Run()`.
