### PR TITLE
`azurerm_container_app_environment`: fix `infrastructure_resource_group_name` behavior with `workload_profile` set to `Consumption`

### LINKED ISSUE #27481: azurerm_container_app_environment with infrastructure_subnet_id set is not idempotent
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.5

### AzureRM Provider Version

4.2.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app_environment

### Terraform Configuration Files

```hcl
resource "azurerm_container_app_environment" "aca_env" {
  name                = "someapp-acae"
  resource_group_name = azurerm_resource_group.aca_env.name
  location            = azurerm_resource_group.aca_env.location

  workload_profile {
    name                  = "Consumption"
    workload_profile_type = "Consumption"
  }

  infrastructure_subnet_id = azurerm_subnet.aca.id

  zone_redundancy_enabled = true
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Terraform apply should show no changes after initial apply. (Or at least it should update the `infrastructure_resource_group_name` in place as it is the case of other properties like static_ip_address, default_domain, etc.)

### Actual Behaviour

On every apply the Azure Container App Environment get recreated because of unexpected change of `infrastructure_resource_group_name`.

```
  # azurerm_container_app_environment.aca_env must be replaced
-/+ resource "azurerm_container_app_environment" "aca_env" {
      ~ custom_domain_verification_id               = "9DE90601289144F1CE754CFCF7FBC4200AB19F87865A742718F04DF04EF0AC7C" -> (known after apply)
      ~ default_domain                              = "calmflower-41d484b5.switzerlandnorth.azurecontainerapps.io" -> (known after apply)
      + docker_bridge_cidr                          = (known after apply)
      ~ id                                          = "/subscriptions/fe95fcda-06db-4248-94ea-baaa100a2f87/resourceGroups/cip-keycloakpoc-cc506498850ff197-rg/providers/Microsoft.App/managedEnvironments/cip-keycloakpoc-acae" -> (known after apply)
      - infrastructure_resource_group_name          = "ME_cip-keycloakpoc-acae_cip-keycloakpoc-cc506498850ff197-rg_switzerlandnorth" -> null # forces replacement
        name                                        = "cip-keycloakpoc-acae"
      + platform_reserved_cidr                      = (known after apply)
      + platform_reserved_dns_ip_address            = (known after apply)
      ~ static_ip_address                           = "74.242.193.132" -> (known after apply)
```

### Steps to Reproduce

terraform apply ( a second time)

### Important Factoids

_No response_

### References

While a custom resouce group can be specified it should also work with the default name (without specify any name) as it is the recommend way by Microsoft:
image

Otherwise, the provider should give an error when `infrastructure_resource_group_name` is specified but `infrastructure_resource_group_name` not.

### PR DESCRIPTION
**Pull request by jiaweitao001**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

`infrastructure_resource_group_name` will be generated by the service even with `workload_profile` set to `Consumption`, this will cause unexpected changes in the state file.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [x] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_container_app_environment`: fix `infrastructure_resource_group_name` behavior with `workload_profile` set to `Consumption` [GH-27481]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #27481

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/containerapps/container_app_environment_resource.go [hunk 1]
```diff
@@ -103,13 +103,9 @@ func (r ContainerAppEnvironmentResource) Arguments() map[string]*pluginsdk.Schem
 			RequiredWith:          []string{"workload_profile"},
 			ValidateFunc:          resourcegroups.ValidateName,
 			DiffSuppressOnRefresh: true,
-			DiffSuppressFunc: func(k, oldValue, newValue string, d *pluginsdk.ResourceData) bool { // If this is omitted, and there is a non-consumption profile, then the service generates a value for the required manage resource group.
+			DiffSuppressFunc: func(k, oldValue, newValue string, d *pluginsdk.ResourceData) bool { // If this is omitted, then the service generates a value for the required manage resource group.
```
Comment (J0F3) [inline internal/services/containerapps/container_app_environment_resource.go:106]:
```suggestion
			DiffSuppressFunc: func(k, oldValue, newValue string, d *pluginsdk.ResourceData) bool { // If this is omitted and workload_profile is set, then the service generates a value for the required manage resource group.
```

Maybe?

File: internal/services/containerapps/container_app_environment_resource.go [hunk 2]
```diff
@@ -103,13 +103,9 @@ func (r ContainerAppEnvironmentResource) Arguments() map[string]*pluginsdk.Schem
...
 				if profiles := d.Get("workload_profile").(*pluginsdk.Set).List(); len(profiles) > 0 && newValue == "" {
-					for _, profile := range profiles {
-						if profile.(map[string]interface{})["workload_profile_type"].(string) != string(helpers.WorkloadProfileSkuConsumption) {
-							return true
-						}
-					}
+					return true
```
Comment (J0F3) [inline internal/services/containerapps/container_app_environment_resource.go:108]: LGTM 👍🏻

File: internal/services/containerapps/container_app_environment_resource.go (hunk 1 above)
Comment (jiaweitao001) [reply internal/services/containerapps/container_app_environment_resource.go:106]: Make sense, will add this line.

File: internal/services/containerapps/container_app_environment_resource_test.go [hunk 3]
```diff
@@ -581,3 +596,32 @@ resource "azurerm_container_app_environment" "test" {
...
+  resource_group_name      = azurerm_resource_group.test.name
+  location                 = azurerm_resource_group.test.location
+  infrastructure_subnet_id = azurerm_subnet.control.id
+
+  workload_profile {
+    name                  = "Consumption"
+    workload_profile_type = "Consumption"
+  }
+
+  zone_redundancy_enabled = true
```
[the remark this answers is not in the document]
Comment (jiaweitao001) [reply internal/services/containerapps/container_app_environment_resource_test.go:619]: Sure.

**Review by catriona-m — CHANGES_REQUESTED** [review]
Thanks for submitting this @jiaweitao001 - this looks good to me, however it seems there are merge conflicts on this pr now, but once that is fixed up I will take another look.

**Comment by jiaweitao001** [comment]
> Thanks for submitting this @jiaweitao001 - this looks good to me, however it seems there are merge conflicts on this pr now, but once that is fixed up I will take another look.

Sure. Rebased.

**Review by catriona-m — CHANGES_REQUESTED** [review]
Thanks @jiaweitao001 - I ran the tests on this and it looks like there is a failure, could you take a look?

```
------- Stdout: -------
=== RUN   TestAccContainerAppEnvironment_zoneRedundant
=== PAUSE TestAccContainerAppEnvironment_zoneRedundant
=== CONT  TestAccContainerAppEnvironment_zoneRedundant
    testcase.go:203: Step 1/3 error: After applying this test step, the non-refresh plan was not empty.
        stdout:
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
        -/+ destroy and then create replacement
        Terraform will perform the following actions:
          # azurerm_container_app_environment.test must be replaced
        -/+ resource "azurerm_container_app_environment" "test" {
              ~ custom_domain_verification_id               = "633CA537530783A9D6C4F655280B4FACA5D10CD906F227C70F7B5C7DD73DE026" -> (known after apply)
              ~ default_domain                              = "kindbush-b381635c.southcentralus.azurecontainerapps.io" -> (known after apply)
              + docker_bridge_cidr                          = (known after apply)
              ~ id                                          = "/subscriptions/*******/resourceGroups/acctestRG-CAE-260420111650481139/providers/Microsoft.App/managedEnvironments/acctest-CAEnv260420111650481139" -> (known after apply)
              - infrastructure_resource_group_name          = "ME_acctest-CAEnv260420111650481139_acctestRG-CAE-260420111650481139_southcentralus" -> null # forces replacement
              + logs_destination                            = (known after apply)
                name                                        = "acctest-CAEnv260420111650481139"
              + platform_reserved_cidr                      = (known after apply)
              + platform_reserved_dns_ip_address            = (known after apply)
              ~ public_network_access                       = "Disabled" -> (known after apply)
              ~ static_ip_address                           = "10.0.1.39" -> (known after apply)
                tags                                        = {
                    "Foo"    = "Bar"
                    "secret" = "sauce"
                }
                # (8 unchanged attributes hidden)
            }
        Plan: 1 to add, 0 to change, 1 to destroy.
--- FAIL: TestAccContainerAppEnvironment_zoneRedundant (1395.94s)
FAIL
```

**Comment by jiaweitao001** [comment]
> Thanks @jiaweitao001 - I ran the tests on this and it looks like there is a failure, could you take a look?
> 
> ```
> ------- Stdout: -------
> === RUN   TestAccContainerAppEnvironment_zoneRedundant
> === PAUSE TestAccContainerAppEnvironment_zoneRedundant
> === CONT  TestAccContainerAppEnvironment_zoneRedundant
>     testcase.go:203: Step 1/3 error: After applying this test step, the non-refresh plan was not empty.
>         stdout:
>         Terraform used the selected providers to generate the following execution
>         plan. Resource actions are indicated with the following symbols:
>         -/+ destroy and then create replacement
>         Terraform will perform the following actions:
>           # azurerm_container_app_environment.test must be replaced
>         -/+ resource "azurerm_container_app_environment" "test" {
>               ~ custom_domain_verification_id               = "633CA537530783A9D6C4F655280B4FACA5D10CD906F227C70F7B5C7DD73DE026" -> (known after apply)
>               ~ default_domain                              = "kindbush-b381635c.southcentralus.azurecontainerapps.io" -> (known after apply)
>               + docker_bridge_cidr                          = (known after apply)
>               ~ id                                          = "/subscriptions/*******/resourceGroups/acctestRG-CAE-260420111650481139/providers/Microsoft.App/managedEnvironments/acctest-CAEnv260420111650481139" -> (known after apply)
>               - infrastructure_resource_group_name          = "ME_acctest-CAEnv260420111650481139_acctestRG-CAE-260420111650481139_southcentralus" -> null # forces replacement
>               + logs_destination                            = (known after apply)
>                 name                                        = "acctest-CAEnv260420111650481139"
>               + platform_reserved_cidr                      = (known after apply)
>               + platform_reserved_dns_ip_address            = (known after apply)
>               ~ public_network_access                       = "Disabled" -> (known after apply)
>               ~ static_ip_address                           = "10.0.1.39" -> (known after apply)
>                 tags                                        = {
>                     "Foo"    = "Bar"
>                     "secret" = "sauce"
>                 }
>                 # (8 unchanged attributes hidden)
>             }
>         Plan: 1 to add, 0 to change, 1 to destroy.
> --- FAIL: TestAccContainerAppEnvironment_zoneRedundant (1395.94s)
> FAIL
> ```

Hi @catriona-m - This is an existing issue on this resource. It's irrelevant to the change here. I can create another PR for it.

**Comment by catriona-m** [comment]
> > Thanks @jiaweitao001 - I ran the tests on this and it looks like there is a failure, could you take a look?
> > ```
> > ------- Stdout: -------
> > === RUN   TestAccContainerAppEnvironment_zoneRedundant
> > === PAUSE TestAccContainerAppEnvironment_zoneRedundant
> > === CONT  TestAccContainerAppEnvironment_zoneRedundant
> >     testcase.go:203: Step 1/3 error: After applying this test step, the non-refresh plan was not empty.
> >         stdout:
> >         Terraform used the selected providers to generate the following execution
> >         plan. Resource actions are indicated with the following symbols:
> >         -/+ destroy and then create replacement
> >         Terraform will perform the following actions:
> >           # azurerm_container_app_environment.test must be replaced
> >         -/+ resource "azurerm_container_app_environment" "test" {
> >               ~ custom_domain_verification_id               = "633CA537530783A9D6C4F655280B4FACA5D10CD906F227C70F7B5C7DD73DE026" -> (known after apply)
> >               ~ default_domain                              = "kindbush-b381635c.southcentralus.azurecontainerapps.io" -> (known after apply)
> >               + docker_bridge_cidr                          = (known after apply)
> >               ~ id                                          = "/subscriptions/*******/resourceGroups/acctestRG-CAE-260420111650481139/providers/Microsoft.App/managedEnvironments/acctest-CAEnv260420111650481139" -> (known after apply)
> >               - infrastructure_resource_group_name          = "ME_acctest-CAEnv260420111650481139_acctestRG-CAE-260420111650481139_southcentralus" -> null # forces replacement
> >               + logs_destination                            = (known after apply)
> >                 name                                        = "acctest-CAEnv260420111650481139"
> >               + platform_reserved_cidr                      = (known after apply)
> >               + platform_reserved_dns_ip_address            = (known after apply)
> >               ~ public_network_access                       = "Disabled" -> (known after apply)
> >               ~ static_ip_address                           = "10.0.1.39" -> (known after apply)
> >                 tags                                        = {
> >                     "Foo"    = "Bar"
> >                     "secret" = "sauce"
> >                 }
> >                 # (8 unchanged attributes hidden)
> >             }
> >         Plan: 1 to add, 0 to change, 1 to destroy.
> > --- FAIL: TestAccContainerAppEnvironment_zoneRedundant (1395.94s)
> > FAIL
> > ```
> 
> Hi @catriona-m - This is an existing issue on this resource. It's irrelevant to the change here. I can create another PR for it.

Thanks @jiaweitao001, it would be good to fix this up in another pr

**Review by catriona-m — APPROVED** [review]
Thanks @jiaweitao001 LGTM!
