### PR TITLE
tags update for azurerm_container_group

### LINKED ISSUE #9612: Updating tags on azurerm_container_group forces a recreate
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: v0.12.21
AzureRM provider version: v2.38.0

### Affected Resource(s)

* `azurerm_container_group`

### Terraform Configuration Files

```hcl
provider azurerm {
  features {}
}

resource azurerm_resource_group example {
  name     = "example-resources"
  location = "centralus"
}

resource azurerm_container_group example {
  name                = "example-continst"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  ip_address_type     = "public"
  os_type             = "Linux"

  container {
    name   = "hello-world"
    image  = "microsoft/aci-helloworld:latest"
    cpu    = "0.5"
    memory = "1.5"

    ports {
      port     = 443
      protocol = "TCP"
    }
  }

  tags = {
    environment = "testing"
  }
}
```

### Expected Behaviour

Modifying `tags` after the resource has been created should not force a replacement of the resource. 

### Actual Behaviour

The container group is replaced after modifying tags.

### Steps to Reproduce

1. `terraform apply` the above Terraform.
2. Add another tag to the `tags` block, e.g. `foo = "bar"`
3. `terraform apply` these changes. The output indicates that "azurerm_container_group.example must be replaced".

### Important Factoids

Updating tags in the portal does not create the container group.

### References

* #0000

### PR DESCRIPTION
**Pull request by AliAllomani**
Fixes #9612 

```bash
$ make acctests SERVICE='containers' TESTARGS='-run=TestAccAzureRMContainerGroup_linuxBasicTagsUpdate'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./azurerm/internal/services/containers/tests/ -run=TestAccAzureRMContainerGroup_linuxBasicTagsUpdate -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccAzureRMContainerGroup_linuxBasicTagsUpdate
=== PAUSE TestAccAzureRMContainerGroup_linuxBasicTagsUpdate
=== CONT  TestAccAzureRMContainerGroup_linuxBasicTagsUpdate
--- PASS: TestAccAzureRMContainerGroup_linuxBasicTagsUpdate (216.53s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/containers/tests    219.088s


```

### CODE REVIEW

File: azurerm/internal/services/containers/container_group_resource.go [hunk 1]
```diff
@@ -597,6 +598,39 @@ func resourceArmContainerGroupCreate(d *schema.ResourceData, meta interface{}) e
...
+	read, err := client.Get(ctx, resGroup, name)
+	if err != nil {
+		return err
+	}
+
+	if read.ID == nil {
+		return fmt.Errorf("Cannot read container group %s (resource group %s) ID", name, resGroup)
+	}
+
+	d.SetId(*read.ID)
```
Comment (tombuildsstuff) [inline azurerm/internal/services/containers/container_group_resource.go:629]: since we're performing an update here, we can remove this ID update (and Get retrieval) here, since the ID won't change during an update

File: azurerm/internal/services/containers/container_group_resource.go [hunk 2]
```diff
@@ -597,6 +598,39 @@ func resourceArmContainerGroupCreate(d *schema.ResourceData, meta interface{}) e
 	return resourceArmContainerGroupRead(d, meta)
 }
 
+func resourceArmContainerGroupUpdate(d *schema.ResourceData, meta interface{}) error {
+	client := meta.(*clients.Client).Containers.GroupsClient
+	ctx, cancel := timeouts.ForUpdate(meta.(*clients.Client).StopContext, d)
+	defer cancel()
+
+	resGroup := d.Get("resource_group_name").(string)
+	name := d.Get("name").(string)
```
Comment (tombuildsstuff) [inline azurerm/internal/services/containers/container_group_resource.go:607]: where this is an update, can we parse the ID rather than retrieving these from the state:

```
id, err := azure.ParseAzureResourceID(d.Id())
	if err != nil {
		return err
	}
	resGroup := id.ResourceGroup
	name := id.Path["containerGroups"]
```

File: azurerm/internal/services/containers/container_group_resource.go [hunk 3]
```diff
@@ -155,7 +156,7 @@ func resourceArmContainerGroup() *schema.Resource {
 				},
 			},
 
-			"tags": tags.ForceNewSchema(),
+			"tags": tags.Schema(),
```
Comment (tombuildsstuff) [inline azurerm/internal/services/containers/container_group_resource.go:159]: we'll also need [to update the documentation](https://github.com/terraform-providers/terraform-provider-azurerm/blame/master/website/docs/r/container_group.html.markdown#L95) to reflect this is no longer ForceNew

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
hey @AliAllomani 

Thanks for this PR :)

I've taken a look through and left some comments inline but this is off to a good start, if we can fix up the comments (and the tests pass) then we should be able to get this merged 👍 

Thanks!

**Comment by AliAllomani** [comment]
Thanks @tombuildsstuff, updated and tested the code as per your recommendations.

**Review by tombuildsstuff — APPROVED** [review]
LGTM - thanks for pushing those changes @AliAllomani

**Comment by tombuildsstuff** [comment]
Tests pass:

Screenshot 2021-01-19 at 11 49 55
