### PR TITLE
2.0 Final Package Deprecations

### LINKED ISSUE #5464: azurerm_app_service_virtual_network_swift_connection constantly tries to set a value of virtual_network_name in a Webapp
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

v0.12.19
v1.40.0

### Affected Resource(s)

* `azurerm_app_service_virtual_network_swift_connection`
* `azurerm_app_service`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name     = "rg"
  location = "eastus"
}

resource "azurerm_virtual_network" "vnet" {
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  name                = "vnet"
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "subnet" {
  name                 = "subnet"
  virtual_network_name = azurerm_virtual_network.vnet.name
  resource_group_name  = azurerm_resource_group.rg.name
  address_prefix       = "10.0.0.0/24"

  delegation {
    name = "delegation"

    service_delegation {
      name    = "Microsoft.Web/serverFarms"
      actions = ["Microsoft.Network/virtualNetworks/subnets/action"]
    }
  }
}

resource "azurerm_app_service_plan" "asp" {
  name                = "asp-test123"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location

  sku {
    tier = "Free"
    size = "F1"
  }
}

resource "azurerm_app_service" "app" {
  name                = "app-test0369"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  app_service_plan_id = azurerm_app_service_plan.asp.id
  https_only          = "true"

  site_config {
    php_version               = "5.6"
    default_documents         = ["Default.htm", "Default.html", "Default.asp", "index.htm", "index.html", "iisstart.htm", "default.aspx", "index.php", "hostingstart.html"]
    use_32_bit_worker_process = "true"
  }
}

resource "azurerm_app_service_virtual_network_swift_connection" "integration" {
  app_service_id = azurerm_app_service.app.id
  subnet_id      = azurerm_subnet.subnet.id
}

```

### Expected Behavior

It is expected Terraform to create Vnet integration of the Webapp to the subnet, and it actually does this. But, on the second run it detects configuration drift within the Webapp config => Site settings => virtual_network_name. This happens every run. Could be a bug.

  ~ site_config {
            always_on                 = false
            default_documents         = [
                "Default.htm",
                "Default.html",
                "Default.asp",
                "index.htm",
                "index.html",
                "iisstart.htm",
                "default.aspx",
                "index.php",
                "hostingstart.html",
            ]
            dotnet_framework_version  = "v4.0"
            ftps_state                = "AllAllowed"
            http2_enabled             = false
            ip_restriction            = []
            local_mysql_enabled       = false
            managed_pipeline_mode     = "Integrated"
            min_tls_version           = "1.2"
            php_version               = "5.6"
            remote_debugging_enabled  = false
            remote_debugging_version  = "VS2019"
            scm_type                  = "None"
            use_32_bit_worker_process = true
          - virtual_network_name      = "c231c93d-9d9f-464d-987a-5fc34da0c2b9_subnet" -> null
            websockets_enabled        = false

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by mbfrahry**
Fixes #5464 (field removed)

### CODE REVIEW

File: azurerm/helpers/azure/app_service.go [hunk 1]
```diff
@@ -225,7 +225,6 @@ func SchemaAppServiceIdentity() *schema.Schema {
 					ValidateFunc: validation.StringInSlice([]string{
 						string(web.ManagedServiceIdentityTypeNone),
 						string(web.ManagedServiceIdentityTypeSystemAssigned),
-						string(web.ManagedServiceIdentityTypeSystemAssignedUserAssigned),
```
Comment (tombuildsstuff) [inline azurerm/helpers/azure/app_service.go]: we'll need to hard-code this value for the moment - I've got a PR tracking this here: https://github.com/Azure/azure-rest-api-specs/pull/8435

File: azurerm/helpers/azure/app_service.go [hunk 2]
```diff
@@ -1334,7 +1309,7 @@ func ExpandAppServiceIdentity(input []interface{}) *web.ManagedServiceIdentity {
 		Type: identityType,
 	}
 
-	if managedServiceIdentity.Type == web.ManagedServiceIdentityTypeUserAssigned || managedServiceIdentity.Type == web.ManagedServiceIdentityTypeSystemAssignedUserAssigned {
+	if managedServiceIdentity.Type == web.ManagedServiceIdentityTypeUserAssigned {
```
Comment (tombuildsstuff) [inline azurerm/helpers/azure/app_service.go]: same here - can we hard-code this for the moment?

File: website/docs/r/virtual_machine_extension.html.markdown [hunk 3]
```diff
@@ -132,8 +132,8 @@ The following arguments are supported:
 * `name` - (Required) The name of the virtual machine extension peering. Changing
     this forces a new resource to be created.
 
-* `virtual_machine_id` - (Required) The resource ID of the virtual machine. Changing this forces a new
-    resource to be created
+
+* `virtual_machine_id` - (Required) The resource ID of the virtual machine. Changing this forces a new resource to be created
```
Comment (tombuildsstuff) [inline website/docs/r/virtual_machine_extension.html.markdown]: we avoid the phrase Resource ID since it's ambiguous between Azure and Terraform - can we make this:

```suggestion
* `virtual_machine_id` - (Required) The ID of the Virtual Machine. Changing this forces a new resource to be created
```
