### PR TITLE
data source azurerm_client_config: always set all properties

### LINKED ISSUE #2108: Resource 'data.azurerm_client_config.current' does not have attribute 'service_principal_application_id'
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
provider.azurerm v1.16.0

### Affected Resource(s)

* azurerm_client_config

### Terraform Configuration Files

```hcl
data "azurerm_client_config" "current" {}

output "account_id" {
  value = "${data.azurerm_client_config.current.client_id}"
}

output "tenant_id" {
  value = "${data.azurerm_client_config.current.tenant_id}"
}

output "subscription_id" {
  value = "${data.azurerm_client_config.current.subscription_id }"
}

output "service_principal_application_id" {
  value = "${data.azurerm_client_config.current.service_principal_application_id}"
}

output "service_principal_object_id" {
  value = "${data.azurerm_client_config.current.service_principal_object_id}"
}
```

### Debug Output

https://gist.github.com/ahanoff/a90e87e18294ad1e0b0344a4b0ff75ba

### Expected Behavior

Return service_principal_object_id and service_principal_application_id as described in documentation

### Actual Behavior

Error output: Resource 'data.azurerm_client_config.current' does not have attribute 'service_principal_application_id'

### Steps to Reproduce

1. terraform init
2. terraform apply

### References

* #0000

### PR DESCRIPTION
**Pull request by katbyte**
Fixes #2108

### CODE REVIEW

**Comment by katbyte** [comment]
Tests pass:

```
gofmt -w $(find . -name '*.go' |grep -v vendor)
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./azurerm -v -test.run=TestAccDataSourceAzureRMClientConfig -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccDataSourceAzureRMClientConfig_basic
--- PASS: TestAccDataSourceAzureRMClientConfig_basic (19.47s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	19.504s
```

File: azurerm/data_source_client_config.go [hunk 1]
```diff
@@ -68,6 +68,9 @@ func dataSourceArmClientConfigRead(d *schema.ResourceData, meta interface{}) err
 	if principal := servicePrincipal; principal != nil {
 		d.Set("service_principal_application_id", principal.AppID)
 		d.Set("service_principal_object_id", principal.ObjectID)
+	} else {
+		d.Set("service_principal_application_id", "")
+		d.Set("service_principal_object_id", "")
 	}
```
Comment (tombuildsstuff) [inline azurerm/data_source_client_config.go]: as discussed IRL I think we should look to replace these in time with more generic `application_id` and `object_id` fields which are available for users too
