### PR TITLE
`mssql_database` Update documentation and print warning for secondary db with `max_size_gb`

### LINKED ISSUE #11282: Intermittent failure updating `sku_name` or `max_size_gb` on failover group secondary db
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform 0.12.26
terraform-provider-azurerm_v2.55

### Affected Resource(s)

* `azurerm_mssql_database`
* `azurerm_sql_failover_group`

### Terraform Configuration Files

```hcl
variable instance_name { 
    type = string
    default = "test-mssql-db" 
}
variable resource_group { 
    type = string
    default = "test-mssql-fog-rg" 
}
variable db_name { 
    type = string
    default = "test-db"
}
variable labels { 
    type = map
    default = {} 
}
variable sku_name { 
    type = string 
    default = "GP_Gen5_2"
}
variable max_storage_gb { 
    type = number 
    default = 10
}

variable primary_server_name {
    type = string
    default = "test-mssql-db-primary"
}

variable secondary_server_name {
    type = string
    default = "test-mssql-db-secondary"
}

variable short_term_retention_days {
    type = number
    default = 7
}

provider "azurerm" {
  version = ">= 2.53.0"
  features {}
}

data "azurerm_sql_server" "primary_azure_sql_db_server" {
    name = var.primary_server_name
    resource_group_name          = var.resource_group
}

data "azurerm_sql_server" "secondary_sql_db_server" {
    name = var.secondary_server_name
    resource_group_name = var.resource_group
}

resource "azurerm_mssql_database" "primary_db" {
  name                = var.db_name
  server_id           = data.azurerm_sql_server.primary_azure_sql_db_server.id
  sku_name            = var.sku_name
  max_size_gb         = var.max_storage_gb
  tags                = var.labels
  short_term_retention_policy {
    retention_days = var.short_term_retention_days
  }
  count = 1
}

resource "azurerm_mssql_database" "secondary_db" {
  depends_on = [azurerm_mssql_database.primary_db[0]]
  name                = var.db_name
  server_id           = data.azurerm_sql_server.secondary_sql_db_server.id
  sku_name            = var.sku_name
  tags                = var.labels
  create_mode         = "Secondary"
  max_size_gb         = var.max_storage_gb
  creation_source_database_id  = azurerm_mssql_database.primary_db[0].id

  count = 1
}

resource "azurerm_sql_failover_group" "failover_group" {
  depends_on = [ azurerm_mssql_database.primary_db[0], azurerm_mssql_database.secondary_db[0] ]
  name                = var.instance_name
  resource_group_name = var.resource_group
  server_name         = data.azurerm_sql_server.primary_azure_sql_db_server.name
  databases           = [azurerm_mssql_database.primary_db[0].id]
  partner_servers {
    id = data.azurerm_sql_server.secondary_sql_db_server.id
  }

  read_write_endpoint_failover_policy {
    mode          = "Automatic"
    grace_minutes = 5
  }

  count = 1
}

output sqldbName {value = azurerm_mssql_database.primary_db[0].name}
output sqlServerName { value = azurerm_sql_failover_group.failover_group[0].name}
output sqlServerFullyQualifiedDomainName {value = format("%s.database.windows.net", azurerm_sql_failover_group.failover_group[0].name)}
output hostname {value = format("%s.database.windows.net", azurerm_sql_failover_group.failover_group[0].name)}
output port {value = 1433}
output name {value = azurerm_mssql_database.primary_db[0].name}
```

### Debug Output

https://gist.github.com/erniebilling/72b85f67c25d9a1c415cf2a89d26bb05

### Expected Behaviour

Secondary database sku and/or max size should successfully update

### Actual Behaviour

Occasionally fails with:
```
The operation cannot be performed since the database 'test_db' is in a replication relationship.
```

### Steps to Reproduce

1. Create primary and secondary mssql servers
2. `terraform apply -var 'primary_server_name=<primary servername> -var 'secondary_server_name=<secondary servername>`
Should successfully create databases and failover group

3. `terraform apply -var 'primary_server_name=<primary servername> -var 'secondary_server_name=<secondary servername> -var 'sku_name=GP_Gen5_8'`

Occasionally fails with above error. See log [gist](https://gist.github.com/erniebilling/72b85f67c25d9a1c415cf2a89d26bb05) for details.

### References

Opened per @aristosvo comment on https://github.com/cloudfoundry-incubator/csb-brokerpak-azure/issues/20

### PR DESCRIPTION
**Pull request by aristosvo**
Fixes #11282

I don't know how to signal this warning more explicitly than proposed, without breaking anything.

### CODE REVIEW

File: azurerm/internal/services/mssql/mssql_database_resource.go [hunk 1]
```diff
@@ -388,6 +388,9 @@ func resourceMsSqlDatabaseCreateUpdate(d *schema.ResourceData, meta interface{})
 	}
 
 	if v, ok := d.GetOk("max_size_gb"); ok {
+		if createMode == string(sql.CreateModeOnlineSecondary) || createMode == string(sql.Secondary) {
```
Comment (magodo) [inline azurerm/internal/services/mssql/mssql_database_resource.go:391]: Shall we error out in this case, since a warn log here will only show up if the user is running Terraform with TF_LOG specified, which seems not so helpful?
Also, shall we move this checking to the `CustomizeDiff` function instead?

File: website/docs/r/mssql_database.html.markdown [hunk 2]
```diff
@@ -92,7 +92,7 @@ The following arguments are supported:
 
 * `long_term_retention_policy` - (Optional) A `long_term_retention_policy` block as defined below.
 
-* `max_size_gb` - (Optional) The max size of the database in gigabytes. 
+* `max_size_gb` - (Optional) The max size of the database in gigabytes. This value should not be configured when the `create_mode` is `Secondary` or `OnlineSecondary`, as the sizing of the primary is then used as per [Azure documentation](https://docs.microsoft.com/en-us/azure/azure-sql/database/single-database-scale#geo-replicated-database).
```
Comment (magodo) [inline website/docs/r/mssql_database.html.markdown:95]: Can we emphasize this like:

```suggestion
* `max_size_gb` - (Optional) The max size of the database in gigabytes.

~> **Note:** This value should not be configured when the `create_mode` is `Secondary` or `OnlineSecondary`, as the sizing of the primary is then used as per [Azure documentation](https://docs.microsoft.com/en-us/azure/azure-sql/database/single-database-scale#geo-replicated-database).
```

**Review by magodo — CHANGES_REQUESTED** [review]
@aristosvo Thanks for this PR! 👍 If we can move the check to the `CustomizeDiff`, it should be good to go.

File: azurerm/internal/services/mssql/mssql_database_resource.go (hunk 1 above)
Comment (tombuildsstuff) [reply azurerm/internal/services/mssql/mssql_database_resource.go:391]: Agreed we should probably error out here - but rather than moving this to the CustomizeDiff, we should probably copy it since it's likely the CustomizeDiff will have an interpolated value (from the initial server) - and so may not be able to catch this at that point

Comment (magodo) [reply azurerm/internal/services/mssql/mssql_database_resource.go:391]: These two properties here (`max_size_gb` and `create_mode`) seems not likely interpolated from external source. iirc the static configured values can be resolved in diff stage?

Comment (aristosvo) [reply azurerm/internal/services/mssql/mssql_database_resource.go:402]: I've added it to the `CustomizeDiff` and changed the warning to an error

**Comment by aristosvo** [comment]
To solve the issue completely we need probably more than the current functionality. It seems the state of the secondary database is not completely ready after our actions, resulting in an error when the update of the secondary is done.

Should I implement some kind of `SqlStateRefreshFunc` to fix the problem of the issuer or is this an API problem which should be fixed in a separate PR or upstream?

File: azurerm/internal/services/mssql/mssql_database_resource.go (hunk 1 above)
Comment (katbyte) [reply azurerm/internal/services/mssql/mssql_database_resource.go:402]: I imagine most people would set the size based on the source server - thus it would be interpolated and which makes the customize diss less then idea. the error on create should be enough

**Comment by magodo** [comment]
@aristosvo I prefer creating another PR for that.

File: azurerm/internal/services/mssql/mssql_database_resource.go (hunk 1 above)
Comment (aristosvo) [reply azurerm/internal/services/mssql/mssql_database_resource.go:391]: `CustomizeDiff` is removed

**Review by katbyte — APPROVED** [review]
Thanks @aristosvo - LGTM 👍

**Comment by aristosvo** [comment]
@katbyte Sorry to bother you again, but I introduced a bug, fixed it in #11401
