### PR TITLE
azurerm_ssh_public_key: using suppress.CaseDifference for resource_group_name

### LINKED ISSUE #10957: azurerm_ssh_public_key - resource group name is being uppercased
The azurerm_ssh_public_key resource is uppercasing the resource group name when running through a plan and will recreate the resource each time.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.51.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* `azurerm_ssh_public_key`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "Example-Title"
  location = "UK South"
}

resource "azurerm_ssh_public_key" "example" {
  name                = "mySshKey"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  public_key          = file("~/.ssh/id_rsa.pub")
}
```

### Expected Behaviour

No planned changes once the ssh key resource is created.

### Actual Behaviour

```text
Terraform will perform the following actions:

  # azurerm_ssh_public_key.example must be replaced
-/+ resource "azurerm_ssh_public_key" "example" {
      ~ id                  = "/subscriptions/2ca40be1-7e80-4f2b-92f7-06b2123a68cc/resourceGroups/EXAMPLE-TITLE/providers/Microsoft.Compute/sshPublicKeys/mySshKey" -> (known after apply)
        name                = "mySshKey"
      ~ resource_group_name = "EXAMPLE-TITLE" -> "Example-Title" # forces replacement
      - tags                = {} -> null
        # (2 unchanged attributes hidden)
    }

```

### Steps to Reproduce

1. `terraform apply`
1. `terraform plan`

### PR DESCRIPTION
**Pull request by AliAllomani**
Suppress case difference for resource group name as the api is always returning it in uppercase.

closes #10957 

```bash
$ make acctests SERVICE="compute" TESTARGS='-run=TestAccSshPublicKey_CreateUpdate'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./azurerm/internal/services/compute -run=TestAccSshPublicKey_CreateUpdate -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
2021/03/13 18:02:07 [DEBUG] not using binary driver name, it's no longer needed
2021/03/13 18:02:09 [DEBUG] not using binary driver name, it's no longer needed
=== RUN   TestAccSshPublicKey_CreateUpdate
=== PAUSE TestAccSshPublicKey_CreateUpdate
=== CONT  TestAccSshPublicKey_CreateUpdate

--- PASS: TestAccSshPublicKey_CreateUpdate (175.51s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute     180.450s
```

### CODE REVIEW

File: azurerm/internal/services/compute/ssh_public_key_resource.go [hunk 1]
```diff
@@ -50,7 +50,7 @@ func resourceSshPublicKey() *schema.Resource {
 				),
 			},
 
-			"resource_group_name": azure.SchemaResourceGroupName(),
+			"resource_group_name": azure.SchemaResourceGroupNameDiffSuppress(),
```
Comment (katbyte) [inline azurerm/internal/services/compute/ssh_public_key_resource.go:53]: This is a bug on the API side - could we raise an issue on the SDK or api specs and link to it here?

Comment (AliAllomani) [reply azurerm/internal/services/compute/ssh_public_key_resource.go:53]: raised an issue in api specs

https://github.com/Azure/azure-rest-api-specs/issues/13491

Comment (AliAllomani) [reply azurerm/internal/services/compute/ssh_public_key_resource.go:53]: based on the response https://github.com/Azure/azure-rest-api-specs/issues/13491#issuecomment-801693754 , seems it's intended to be that way and not a bug.

Comment (katbyte) [reply azurerm/internal/services/compute/ssh_public_key_resource.go:53]: Thanks, regardless of that comment it is still IMHO a bug (even if they have made choices preventing them from fixing it) - according to the arm spec and reasonable expectations we should be getting the correct casing for the RG. As such could we please add a comment inline linking to that issue to document their response?

Comment (AliAllomani) [reply azurerm/internal/services/compute/ssh_public_key_resource.go:55]: @katbyte added inline comment. Thanks.

**Review by katbyte — APPROVED** [review]
LGTM 👍
