### PR TITLE
fix synapse endpoint not available issue in other cloud

### LINKED ISSUE #9099: AzureRM Provider 2.34 fails to authenticate on US Government (Regression from 2.33)
In the latest azurerm provider 2.34, authenticating via Azure CLI against Azure Us Government no longer works:

This *does* still work in azurerm provider 2.33, it is a regression in 2.34

### Terraform (and AzureRM Provider) Version
```
az version
{
  "azure-cli": "2.14.0",
  "azure-cli-core": "2.14.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

Terraform v0.13.5

Linux my-ubuntu-20.04 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### Expected Result
terraform plan authorizes.

### Actual Behavior
```
Error: Error obtaining Authorization Token from the Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1

  on providers.tf line 3, in provider "azurerm":
   3: provider "azurerm" {
```

### Steps to Reproduce
```
Initializing provider plugins...
- Using previously-installed hashicorp/azurerm v2.34.0
```
```terraform
variable "cloud" {}

provider "azurerm" {
  version = "~> 2.34.0"
  tenant_id       = var.cloud.azure.tenant_id
  subscription_id = var.cloud.azure.subscription_id
  environment     = var.cloud.azure.environment
  features {}
}

resource "azurerm_resource_group" "foobar" {
  name                = "foobar"
  location            = "USGov Virginia"
}
```

### Debug Output
*** Azure CLI Log ***
```
_id":"****<masked>****",
"error_uri":"https://login.microsoftonline.us/error?code=500011"}

ERROR : cli.azure.cli.core.azclierror : 
Get Token request returned http error: 400 and server response: 

{"error":"invalid_resource",
"error_description":"AADSTS500011: The resource principal named N/A was not found in the tenant named ****<masked>****.

This can happen if the application has not been installed by the administrator of the tenant or consented to 
by any user in the tenant. 

{"error":"invalid_resource",
"error_description":"AADSTS500011: The resource principal named N/A was not found in the tenant named ***<masked>***. 

This can happen if the application has not been installed by the administrator of the tenant or consented to 
by any user in the tenant. You might have sent your authentication request to the wrong tenant.

Trace ID:****<masked>****
Correlation ID: ****<masked>****
error_codes:[500011],
error_uri":"https://login.microsoftonline.us/error?code=500011"

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 75, in get_access_token
    creds, subscription, tenant = profile.get_raw_token(subscription=subscription, resource=resource, tenant=tenant)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 650, in get_raw_token
    tenant_dest, resource)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 1019, in retrieve_token_for_user
    token_entry = context.acquire_token(resource, username, _CLIENT_ID)
  File "/opt/az/lib/python3.6/site-packages/adal/authentication_context.py", line 145, in acquire_token
    return self._acquire_token(token_func)
  File "/opt/az/lib/python3.6/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/opt/az/lib/python3.6/site-packages/adal/authentication_context.py", line 143, in token_func
    return token_request.get_token_from_cache_with_refresh(user_id)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 347, in get_token_from_cache_with_refresh
    return self._find_token_from_cache()
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 127, in _find_token_from_cache
    return self._cache_driver.find(cache_query)
  File "/opt/az/lib/python3.6/site-packages/adal/cache_driver.py", line 199, in find
    is_resource_tenant_specific)
  File "/opt/az/lib/python3.6/site-packages/adal/cache_driver.py", line 184, in _refresh_entry_if_necessary
    return self._acquire_new_token_from_mrrt(entry)
  File "/opt/az/lib/python3.6/site-packages/adal/cache_driver.py", line 160, in _acquire_new_token_from_mrrt
    token_response = self._refresh_function(entry, self._resource)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 137, in _get_token_with_token_response
    return self._get_token_with_refresh_token(refresh_token, resource, None)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 339, in _get_token_with_refresh_token
    return self._oauth_get_token(oauth_parameters)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 112, in _oauth_get_token
    return client.get_token(oauth_parameters)
  File "/opt/az/lib/python3.6/site-packages/adal/oauth2_client.py", line 289, in get_token
    raise AdalError(return_error_string, error_response)
adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: 
```

#### Previously Working Example
This results in a proper plan. Can be reproduced 100% of the time.

```bash
Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "~> 2.33.0"...
- Installing hashicorp/azurerm v2.33.0...
- Installed hashicorp/azurerm v2.33.0 (signed by HashiCorp)
```
```terraform
variable "cloud" {}

provider "azurerm" {
  version = "~> 2.33.0"
  tenant_id       = var.cloud.azure.tenant_id
  subscription_id = var.cloud.azure.subscription_id
  environment     = var.cloud.azure.environment
  features {}
}

resource "azurerm_resource_group" "foobar" {
  name                = "foobar"
  location            = "USGov Virginia"
}

```

### PR DESCRIPTION
**Pull request by njuCZ**
fix #9099

### CODE REVIEW

File: azurerm/internal/clients/builder.go [hunk 1]
```diff
@@ -98,9 +100,12 @@ func Build(ctx context.Context, builder ClientBuilder) (*Client, error) {
 	}
 
 	// Synapse Endpoints
-	synapseAuth, err := builder.AuthConfig.GetAuthorizationToken(sender, oauthConfig, env.ResourceIdentifiers.Synapse)
-	if err != nil {
-		return nil, err
+	var synapseAuth autorest.Authorizer
```
Comment (tombuildsstuff) [inline azurerm/internal/clients/builder.go:103]: this would give us a default authorizer with no auth configured in the event we're not in Azure Public.. instead this needs to become a pointer and threaded through correctly to conditionally omit setting these clients / raising an error in these regions

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
hi @njuCZ 

Thanks for this PR.

Whilst on first glance it appears this'd fix the issue - this'd end up creating a default authorizer object albeit with no authentication configured, creating a misleading set of errors here. Instead we'll need to make this a pointer, and thread this through appropriately - meaning that in the resources we'll need to check if the client is nil during the CRUD functions and raise a more descriptive error if appropriate.

Thanks!

File: azurerm/internal/clients/builder.go (hunk 1 above)
Comment (njuCZ) [reply azurerm/internal/clients/builder.go]: `autorest.Authorizer` is an interface, the default vaule is nil. I have changed to declared it to nil explicitly.

**Comment by njuCZ** [comment]
@tombuildsstuff  thanks for your suggestions. I have added some error handling if the synapse authorizer is nil.

File: azurerm/internal/services/synapse/synapse_role_assignment_resource.go [hunk 2]
```diff
@@ -163,7 +169,10 @@ func resourceArmSynapseRoleAssignmentDelete(d *schema.ResourceData, meta interfa
 		return err
 	}
 
-	client := synapseClient.AccessControlClient(id.Workspace.Name, environment.SynapseEndpointSuffix)
+	client, err := synapseClient.AccessControlClient(id.Workspace.Name, environment.SynapseEndpointSuffix)
+	if err != nil {
+		return nil
```
Comment (tombuildsstuff) [inline azurerm/internal/services/synapse/synapse_role_assignment_resource.go:174]: whilst this may seem odd, this should return the error here

File: azurerm/internal/services/synapse/tests/synapse_role_assignment_resource_test.go [hunk 3]
```diff
@@ -61,7 +61,10 @@ func testCheckAzureRMSynapseRoleAssignmentExists(resourceName string) resource.T
 		if err != nil {
 			return err
 		}
-		client := synapseClient.AccessControlClient(id.Workspace.Name, environment.SynapseEndpointSuffix)
+		client, err := synapseClient.AccessControlClient(id.Workspace.Name, environment.SynapseEndpointSuffix)
+		if err != nil {
+			return nil
```
Comment (tombuildsstuff) [inline azurerm/internal/services/synapse/tests/synapse_role_assignment_resource_test.go:66]: whilst this may seem odd, this should return the error here

File: azurerm/internal/clients/builder.go [hunk 4]
```diff
@@ -98,9 +100,12 @@ func Build(ctx context.Context, builder ClientBuilder) (*Client, error) {
...
-	synapseAuth, err := builder.AuthConfig.GetAuthorizationToken(sender, oauthConfig, env.ResourceIdentifiers.Synapse)
-	if err != nil {
-		return nil, err
+	var synapseAuth autorest.Authorizer = nil
+	if env.ResourceIdentifiers.Synapse != azure.NotAvailable {
+		synapseAuth, err = builder.AuthConfig.GetAuthorizationToken(sender, oauthConfig, env.ResourceIdentifiers.Synapse)
+		if err != nil {
+			return nil, err
+		}
 	}
```
Comment (tombuildsstuff) [inline azurerm/internal/clients/builder.go:109]:
```suggestion
	} else {
		log.Printf("[DEBUG] Skipping building the Synapse Authorizer since this is not supported in the current Azure Environment")
	}
```

File: azurerm/internal/services/synapse/client/client.go [hunk 5]
```diff
@@ -52,9 +52,12 @@ func NewClient(o *common.ClientOptions) *Client {
 	}
 }
 
-func (client Client) AccessControlClient(workspaceName, synapseEndpointSuffix string) *accesscontrol.BaseClient {
+func (client Client) AccessControlClient(workspaceName, synapseEndpointSuffix string) (*accesscontrol.BaseClient, error) {
+	if client.synapseAuthorizer == nil {
+		return nil, fmt.Errorf("synapse service is not supported in current environment")
```
Comment (tombuildsstuff) [inline azurerm/internal/services/synapse/client/client.go:57]: can we make this a little more specific via:

```suggestion
		return nil, fmt.Errorf("Synapse is not supported in this Azure Environment")
```

(environment is ambiguous, and could refer to the Azure Env or another type of environment, such as the CLI environment)

**Review by tombuildsstuff — APPROVED** [review]
otherwise LGTM 👍

**Comment by njuCZ** [comment]
@tombuildsstuff  thanks for your kindly review. I have updated the codes
