### PR TITLE
azurerm_postgres_server - fix #2819, #5121, #5865, #6180, #6216

### LINKED ISSUE #2819: PostgreSQL replica support
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Microsoft introduced PostgreSQL read replica support in Azure just recently. It'd be great to be able to manage them using Terraform!

There are my (semi-random) ideas about this. Please note I'm not TF developer so I'm unsure about style guidelines.. So please consider this as roughly draft or RFC.

* I was able to set `azure.replication_support=REPLICA` using `azurerm_postgresql_configuration` w/o any issues. So this step is already done. But this step requires server restart when changing pre-existing server. For newly created server restart it's not required **I guess** (depends on how those settings are applied to server).

* Replica is kind of yet another PostgreSQL server instance. So it should be possible to reuse current `azurerm_postgresql_server` for this from one side. But from other side replica means relation with master instance which should be described somehow. May be AWS RDS provider may give some ideas (didn't read it yet).

* It's impossible to change replica pricing tier, compute generation, vCores, storage and backup retention period during replica creation. It will be created as copy of master. But it's possible to change those params after creation independently.

* I'm not sure how to deal with role switchover. It's possible to break replication and promote replica to master in Azure portal. But I'm unsure how to describe this action in terms of "Configuration as a Code".

### New or Affected Resource(s)

* azurerm_postgresql_configuration
* azurerm_postgresql_server

May be we will need new resource to manage this. Can't propose anything here yet.

### Potential Terraform Configuration

```hcl
// To be defined
```

### References

* https://docs.microsoft.com/en-us/azure/postgresql/concepts-read-replicas
* https://docs.microsoft.com/en-us/azure/postgresql/howto-read-replicas-portal

### LINKED ISSUE #5121: Allow optional storage size with `auto_grow` enabled
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We're experiencing an undesired behavior when enabling `auto_grow` for a postgresql server.
As the `storage_mb` setting is required, each time the storage size is automatically increased via autogrow, terraform detects a change and `storage_mb` needs to be manually increased as well.
Ideally, `storage_mb` would be optionally if `auto_grow` is enabled.

### New or Affected Resource(s)

* `azurerm_postgresql_server`

### Potential Terraform Configuration

```hcl
resource "azurerm_postgresql_server" "db" {
...
  storage_profile {
    storage_mb            = var.storage_mb
    auto_grow             = "Enabled"
  }
```

### LINKED ISSUE #5865: azurerm_postgresql_server fails on update if auto_grow was triggered
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform and AzureRM Provider Version

terraform: 0.12.16
azurerm: 1.44.0

### Affected Resource(s)

* `azurerm_postgresql_server`

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_server" "db-server" {
  name = "myserver"
  location = "westeurope"
  resource_group_name = "some_resource_group"

  sku {
    name = "GP_Gen5_2"
    capacity = 2
    tier = "GeneralPurpose"
    family = "Gen5"
  }

  storage_profile {
    storage_mb = 5120
    backup_retention_days = 7
    geo_redundant_backup = "Disabled"
    auto_grow = "Enabled"
  }

  administrator_login = "postgres"
  administrator_login_password = "changeme"
  version = "11"
  ssl_enforcement = "Enabled"
}
```

### Expected Behavior

When the storage was already increased, because auto_grow was enabled, then storage_mb should be ignored.

### Actual Behavior

Terraform aborts with the following error from Azure: `Error: Error waiting for update of PostgreSQL Server "myserver" (Resource Group "some_resource_group"): Code="UnsupportedUpdate" Message="Cannot update StorageMB Downscaling for server"`

### LINKED ISSUE #6180: Terraform support for point on time server restore for Azure managed PostgreSQL
Hi,
We are using terraform for our couple cluster deployment for our product in MS Azure. But, in case of managed PostgreSQL, when we do a parallel upgrades we are not able to restore an existing PostgreSQL DB to a new instance with point in time restore option. Azure cli supports the same as below command. Azure managed PostgreSQL server restore (point in time) is not supported in terraform at present.

./az postgres server restore -g DatabaseTestingnPOC -n NewPrimary -s primary --restore-point-in-time "2020-03-17T16:50:30.0000Z"

Can you please help in getting this through terraform.

Thanks best regards
Krishna
Official email - ksingita@cisco.com

### LINKED ISSUE #6216: Support for "deny public network access" in Azure Database for PostgreSQL
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently when a PostgreSQL server is built and Private Link is used there is no way to enable the **Deny public network access** feature given by Microsoft. This should be something that is enabled through the `azurerm_postgresql_server` resource.

### New or Affected Resource(s)

* azurerm_postgresql_server

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "api-rg-pro"
  location = "West Europe"
}

resource "azurerm_postgresql_server" "example" {
  name                = "postgresql-server-1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  sku_name = "B_Gen5_2"

  storage_profile {
    storage_mb            = 5120
    backup_retention_days = 7
    geo_redundant_backup  = "Disabled"
    auto_grow             = "Enabled"
  }

  administrator_login          = "psqladminun"
  administrator_login_password = "H@Sh1CoR3!"
  version                      = "9.5"
  ssl_enforcement              = "Enabled"
  deny_public_network_access = true
}
```

### References

* [HowTo deny public network access](https://docs.microsoft.com/en-gb/azure/postgresql/howto-deny-public-network-access)

### PR DESCRIPTION
**Pull request by katbyte**
refactor code and tests to 
- support for `create_mode`, `creation_source_server_id`, `infrastructure_encryption_enabled`,`public_network_access_enabled`, `ssl_minimal_tls_version_enforced` properties
- support replicas
- computed `storage_mb` when `auto_grow_enabled` is true
- use booleans for toggle properties by renaming:
-- `ssl_enforcement` -> `ssl_enforcement_enabled`
-- `geo_redundant_backup` -> `backup_geo_redundant_enabled`
-- `auto_grow` -> `auto_grow_enabled`
- move all properties within the `storage_profile` block to the top level

superseeds #6241 
fixes #6216
fixes #6180
fixes #5865 
fixes #5121
fixed #2819

### CODE REVIEW

File: azurerm/internal/services/postgres/tests/resource_arm_postgresql_server_test.go [hunk 1]
```diff
@@ -20,15 +21,37 @@ func TestAccAzureRMPostgreSQLServer_basicNinePointFive(t *testing.T) {
...
+				Config: testAccAzureRMPostgreSQLServer_basic(data, "9.5"),
 				Check: resource.ComposeTestCheckFunc(
 					testCheckAzureRMPostgreSQLServerExists(data.ResourceName),
-					resource.TestCheckResourceAttr(data.ResourceName, "administrator_login", "acctestun"),
-					resource.TestCheckResourceAttr(data.ResourceName, "version", "9.5"),
-					resource.TestCheckResourceAttr(data.ResourceName, "ssl_enforcement", "Enabled"),
 				),
 			},
-			data.ImportStep("administrator_login_password"),
+			data.ImportStep("administrator_login_password", "create_mode"),
```
Comment (tombuildsstuff) [inline azurerm/internal/services/postgres/tests/resource_arm_postgresql_server_test.go:29]: since this is ForceNew and defaults - we'll probably want to set this during the import func?

**Comment by larryclaman** [comment]
@katbyte, you wrote that the following property was renamed: _geo_redundant_backup -> backup_geo_redundant_enabled_

There's a typo in your notes; from looking at the code, the new parameter is actually geo_redundant_backup_enabled

Can you edit your initial comment to reflect the correction?

**Comment by katbyte** [comment]
@larryclaman thanks for pointing that out! i've updated the pr description with the correct name
