### PR TITLE
azurerm_function_app: convert `connection_string`s from a `TypList` to a `TypeSet` (#3596)

### LINKED ISSUE #3596: Azurerm_function_app Connection Strings constantly over-write
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.0
+ provider.azurerm v1.28.0

### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

```resource "azurerm_function_app" "notif_fa" {
    # added us to the hardcoded value for now - needs to be removed once we can rename the whole rg appropriately.
  name                      = "${var.team}-${var.productShort}-fa-notif-us-${var.environment}"
  location            = "${azurerm_resource_group.audit_rg.location}"
  resource_group_name = "${azurerm_resource_group.audit_rg.name}"
  app_service_plan_id       = "${azurerm_app_service_plan.audit_asp.id}"
  storage_connection_string = "${azurerm_storage_account.sa_notification_fa.primary_connection_string}"
  version = "~2"
  
  app_settings = {
    "APPINSIGHTS_INSTRUMENTATIONKEY" = "${azurerm_application_insights.audit_ai.instrumentation_key}"
	.................
    "WEBSITE_NODE_DEFAULT_VERSION" = "6.5.0"
  }

        connection_string {
          name = "EmailApiKey" 
          type = "Custom" 
          value = "I am a first value"
    }

      connection_string {
          name  = "ServiceBus" 
          type  = "Custom" 
          value = "I am a second value"
  }

      connection_string {
          name  = "Slack" 
          type  = "Custom" 
          value = "I am a Third value"
  }

      site_config {
        always_on = false
      }
}	
```

### Expected Behavior

Terraform should identify no changes when running the plan- every time.

### Actual Behavior

Terraform randomly over-writes all connection strings- it doesn't maintain the order in which they are input.

### Steps to Reproduce

1. Create an azurerm_function_app resource with multiple connection string blocks
2.  terraform plan
3.  terraform apply (function app is successfully created)
4.  immediately (and with no changes) run terraform plan
5.  terraform identifies changes (randomly) as the connection strings are now in a random new order.  **NOTE - the randomness is in the order it reads from the state file, not the .tf file.  The order it assigns them to is static- it's the order that it reads them in as that doesn't want to stay the same. **

For example, with no changes:  
First Plan Run:
image

First Plan Apply
image

Second Plan Run:
image

Third Plan Run:
image

### References

It looks to me like someone addressed the order inconsistency when reading from the .tf file- but not the .tfstate file that it compares it to.  See #651 and related PR #2609.

### PR DESCRIPTION
**Pull request by levvko**
Converted function app connection strings to Set, as it was previously done for app service
#3596

Fixes #3596

### CODE REVIEW

File: azurerm/internal/services/web/resource_arm_function_app.go [hunk 1]
```diff
@@ -97,7 +97,7 @@ func resourceArmFunctionApp() *schema.Resource {
 			},
 
 			"connection_string": {
-				Type:     schema.TypeList,
+				Type:     schema.TypeSet,
```
Comment (tombuildsstuff) [inline azurerm/internal/services/web/resource_arm_function_app.go]: in addition to this we also need to update [the expand function](https://github.com/terraform-providers/terraform-provider-azurerm/pull/5319/files#diff-23333db7a329c446abb71d2877f1bcf1R803) to use: `d.Get("foo").(*schema.Set).([]interface{}` rather than `d.Get("foo").([]interface{})` since this is now a Set rather than a List
