### PR TITLE
azurerm_app_service - support for the acr_use_managed_identity_creds and acr_user_managed_identity_id properties

### LINKED ISSUE #7491: Authentication in Linux App Service Docker Container not working when System Assigned Identity is used
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.26
provider.azurerm v2.15.0

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

The config was taken from here:
https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/examples/app-service/docker-authentication

Then an "Identity" block to configure a system assigned identity was added to the app service resource.

```hcl
terraform {
  required_version = ">= 0.12"
}

provider "azurerm" {
  version = "~> 2.15.0"
  features {}
}

variable "client_id" {
  default = "xxx"
}

variable "client_secret" {
  default = "xxx"
}

variable "prefix" {
  default = "xxx"
}

variable "location" {
  default = "West Europe"
}

resource "azurerm_resource_group" "main" {
  name     = "${var.prefix}-rg"
  location = "${var.location}"
}

resource "azurerm_app_service_plan" "main" {
  name                = "${var.prefix}-asp"
  location            = "${azurerm_resource_group.main.location}"
  resource_group_name = "${azurerm_resource_group.main.name}"
  kind                = "Linux"
  reserved            = true

  sku {
    tier = "Standard"
    size = "S1"
  }
}

resource "azurerm_app_service" "main" {
  name                = "${var.prefix}-as"
  location            = "${azurerm_resource_group.main.location}"
  resource_group_name = "${azurerm_resource_group.main.name}"
  app_service_plan_id = "${azurerm_app_service_plan.main.id}"

  identity {
    type = "SystemAssigned"
  }

  site_config {
    app_command_line = ""
    linux_fx_version = "DOCKER|appsvcsample/python-helloworld:latest"
  }

  app_settings = {
    "WEBSITES_ENABLE_APP_SERVICE_STORAGE" = "false"
    "DOCKER_REGISTRY_SERVER_URL"          = "https://index.docker.io"
  }

  auth_settings {
    enabled                       = true
    issuer                        = "https://sts.windows.net/xxxxx"
    default_provider              = "AzureActiveDirectory"
    unauthenticated_client_action = "RedirectToLoginPage"

    active_directory {
      client_id     = var.client_id
      client_secret = var.client_secret
    }
  }
}
```

### Expected Behavior

When I open the host name of the app service in a browser I expected to be redirected to the login page.

### Actual Behavior

I could access the application without login.
After the "Identity" block was removed the login worked as expected.

### Steps to Reproduce

1. Manually create an App Registration with client secret
2. set Variables
3. `terraform apply`
2. Open website

### References

* #0000

### LINKED ISSUE #9962: CORS Allowed Origin list not being updated after initial creation of AppService
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5

### Affected Resource(s)

* azurerm_app_service

### Terraform Configuration Files

```hcl
resource azurerm_app_service web_app {
  name = local.app_service_name
  location = azurerm_app_service_plan.app_service.location
  resource_group_name = azurerm_app_service_plan.app_service.resource_group_name
  app_service_plan_id = azurerm_app_service_plan.app_service.id

  https_only = true
  client_cert_enabled = false
  app_settings = var.application_settings

  site_config {
    app_command_line  = "node server.js"
    scm_type          = "VSTSRM"
    health_check_path = var.health_check_path
    linux_fx_version  = "NODE|10.14"
    min_tls_version   = "1.2"
    http2_enabled     = true
    ftps_state        = "FtpsOnly"
    
    cors {
      allowed_origins = var.cors_allowed_origins
    }
  }
  
  identity {
    type = "SystemAssigned"
  }

  dynamic connection_string {
    for_each = var.connection_strings
    content {
      name  = connection_string.name
      type  = connection_string.type
      value = connection_string.value
    }
  }

  lifecycle {
    ignore_changes = [
      site_config["scm_type"],
    ]
  }

  tags = {
    application = var.environment.application_name
    environment = var.environment.env_name
  }
}
```

### Expected Behaviour

If my resource has already been created in Azure and the list of allowed origins changes, I would expect the list of allowed origins to be updated to reflect those in the terraform configuration

### Actual Behaviour

When the resource is created for the first time all CORS Allowed Origins are set correctly, however if the resource already exists and the CORS allowed origin list changes the changes are not applied.

Given a list of allowed origins:
A, B, C

Create the App_Service with the above list and note that the allowed origins are created correctly

Now update the list in terraform to:
A, C, D

Run Terraform apply and note that the app service is updated.

View the resource in azure portal and note that the allowed origins are still A, B, C

1. `terraform apply`

As above

### LINKED ISSUE #12277: Support for acrUseManagedIdentityCreds in azurerm_app_service
### Description

Add argument for enabling to use managed identity to login to ACR.

By now I have to add an execution of an az command to enable this.

```hcl
  resource "azurerm_app_service" "myapp" {
    ...

    # Use managed identity to login to ACR
    # https://github.com/Azure/app-service-linux-docs/blob/master/HowTo/use_system-assigned_managed_identities.md
    provisioner "local-exec" {
      command = "az resource update --ids ${self.id}/config/web --set properties.acrUseManagedIdentityCreds=True -o none"
    }
  }
```

### New or Affected Resource(s)

* azurerm_app_service

### References

https://github.com/Azure/app-service-linux-docs/blob/master/HowTo/use_system-assigned_managed_identities.md

### PR DESCRIPTION
**Pull request by mozts2005**
Fixes #12277
Fixes #7491 
Fixes #9962

I have opened this as an updated version of pr #12399 to make the history clean.

Depends on #12635 which has been merged.

### CODE REVIEW

**Comment by mozts2005** [comment]
@haraldatbmw the app_service_slot_resource does not need an update directly as it shares the siteConfig object with the app_service_resource.

File: azurerm/internal/services/web/app_service.go [hunk 1]
```diff
@@ -490,6 +491,19 @@ func schemaAppServiceSiteConfig() *pluginsdk.Schema {
 					Type:     pluginsdk.TypeString,
 					Optional: true,
 				},
+
+				"acr_use_managed_identity_creds": {
+					Type:     pluginsdk.TypeBool,
+					Optional: true,
+					Default:  false,
+				},
```
Comment (jackofallops) [inline azurerm/internal/services/web/app_service.go:499]: We should probably make this computed only and use the presence of `acr_user_managed_identity_id` to toggle this on / off? We also try to favour long-hand names for clarity.
```suggestion
				"acr_use_managed_identity_credentials": {
					Type:     pluginsdk.TypeBool,
					Computed: true,
				},
```

File: azurerm/internal/services/web/app_service.go [hunk 2]
```diff
@@ -490,6 +491,19 @@ func schemaAppServiceSiteConfig() *pluginsdk.Schema {
...
+
+				"acr_user_managed_identity_id": {
+					Type:         pluginsdk.TypeString,
+					ValidateFunc: msivalidate.UserAssignedIdentityID,
+					Optional:     true,
+				},
```
Comment (jackofallops) [inline azurerm/internal/services/web/app_service.go:505]:
```suggestion
				"acr_user_managed_identity_id": {
					Type:         pluginsdk.TypeString,
					Optional:     true,
					ValidateFunc: msivalidate.UserAssignedIdentityID,
				},
```

File: azurerm/internal/services/web/app_service.go [hunk 3]
```diff
@@ -1773,6 +1797,14 @@ func expandAppServiceSiteConfig(input interface{}) (*web.SiteConfig, error) {
...
 	}
 
+	if v, ok := config["acr_use_managed_identity_creds"]; ok {
+		siteConfig.AcrUseManagedIdentityCreds = utils.Bool(v.(bool))
+	}
+
+	if v, ok := config["acr_user_managed_identity_id"]; ok {
+		siteConfig.AcrUserManagedIdentityID = utils.String(v.(string))
+	}
+
```
Comment (jackofallops) [inline azurerm/internal/services/web/app_service.go:1807]:
```suggestion

	siteConfig.AcrUseManagedIdentityCreds = utils.Bool(false)

	if v, ok := config["acr_user_managed_identity_id"]; ok {
		siteConfig.AcrUseManagedIdentityCreds = utils.Bool(true)
		siteConfig.AcrUserManagedIdentityID = utils.String(v.(string))
	}

```

File: website/docs/d/app_service.html.markdown [hunk 4]
```diff
@@ -174,6 +174,10 @@ A `site_config` block exports the following:
 
 * `websockets_enabled` - Are WebSockets enabled for this App Service?
 
+* `acr_use_managed_identity_creds` - Are Managed Identity Creds be used for Azure Container Registry pull.
+
+* `acr_user_managed_identity_id` - The User Managed Identity, Client Id.
```
Comment (jackofallops) [inline website/docs/d/app_service.html.markdown:179]:
```suggestion
* `acr_use_managed_identity_creds` - Are Managed Identity Credentials used for Azure Container Registry pull.

* `acr_user_managed_identity_id` - The User Managed Identity ID.
```

File: website/docs/r/app_service.html.markdown [hunk 5]
```diff
@@ -249,6 +249,12 @@ Additional examples of how to run Containers via the `azurerm_app_service` resou
 
 * `websockets_enabled` - (Optional) Should WebSockets be enabled?
 
+* `acr_use_managed_identity_creds` - (Optional) Should Managed Identity Creds be used for Azure Container Registry pull
+
+* `acr_user_managed_identity_id` - (Optional) If using User Managed Identity, the User Managed Identity Client Id
```
Comment (jackofallops) [inline website/docs/r/app_service.html.markdown:254]: Reflecting the change of schema suggested above
```suggestion
* `acr_use_managed_identity_creds` - Are Managed Identity Credential used for Azure Container Registry.

* `acr_user_managed_identity_id` - (Optional) The User Managed Identity ID to use for accessing the Azure Container Registry.
```

File: website/docs/r/app_service_slot.html.markdown [hunk 6]
```diff
@@ -234,6 +234,12 @@ The following arguments are supported:
 
 * `auto_swap_slot_name` - (Optional) The name of the slot to automatically swap to during deployment
 
+* `acr_use_managed_identity_creds` - (Optional) Should Managed Identity Creds be used for Azure Container Registry pull
+
+* `acr_user_managed_identity_id` - (Optional) If using User Managed Identity, the User Managed Identity Client Id
```
Comment (jackofallops) [inline website/docs/r/app_service_slot.html.markdown:239]: as above
```suggestion
* `acr_use_managed_identity_creds` - Are Managed Identity Credential used for Azure Container Registry.

* `acr_user_managed_identity_id` - (Optional) The User Managed Identity ID to use for accessing the Azure Container Registry.
```

**Review by jackofallops — CHANGES_REQUESTED** [review]
Hi @mozts2005 - Thanks for this PR (and reworking it from the older one). I've left some comments inline below.
Also, can you add an acceptance test that confirms this is set as expected?

Thanks!

File: azurerm/internal/services/web/app_service.go (hunk 1 above)
Comment (mozts2005) [reply azurerm/internal/services/web/app_service.go:499]: this would not allow the use of the app service system assigned identity only user managed identities. So I will not be making that change as that is not the use case I need.

Comment (jackofallops) [reply azurerm/internal/services/web/app_service.go:499]: My mistake - I'm in the process of rewriting this service in preparation for 3.0 and my notes on this feature were incorrect. I'll dismiss the review and re-do it asap.

**Comment by mozts2005** [comment]
@jackofallops I have added acceptance test and found a bug. Please review.

**Comment by mozts2005** [comment]
the bug I found I think will fix issues #7491 and #9962

File: azurerm/internal/services/web/app_service.go [hunk 7]
```diff
@@ -490,6 +490,15 @@ func schemaAppServiceSiteConfig() *pluginsdk.Schema {
...
+				"acr_use_managed_identity_creds": {
+					Type:     pluginsdk.TypeBool,
+					Optional: true,
+					Default:  false,
+				},
+				"acr_user_managed_identity_id": {
+					Type:     pluginsdk.TypeString,
+					Optional: true,
+				},
 			},
```
Comment (jackofallops) [inline azurerm/internal/services/web/app_service.go:502]:
```suggestion
				},
				
				"acr_use_managed_identity_credentials": {
					Type:     pluginsdk.TypeBool,
					Optional: true,
					Default:  false,
				},
				
				"acr_user_managed_identity_id": {
					Type:     pluginsdk.TypeString,
					Optional: true,
					ValidateFunc: validate.UserAssignedIdentityID,
				},
			},
```
Can we add the validation back in here. Whilst this property can take just the client_id it's more common to use the full resource id to pass between resources, which is also valid here.

File: azurerm/internal/services/web/app_service_resource_test.go [hunk 8]
```diff
@@ -1862,6 +1862,39 @@ func TestAccAppService_basicWindowsContainer(t *testing.T) {
...
+			Config: r.AcrUseManagedIdentity(data),
+			Check: acceptance.ComposeTestCheckFunc(
+				check.That(data.ResourceName).ExistsInAzure(r),
+				check.That(data.ResourceName).Key("identity.0.type").HasValue("SystemAssigned"),
+				check.That(data.ResourceName).Key("identity.0.principal_id").MatchesRegex(validate.UUIDRegExp),
+				check.That(data.ResourceName).Key("identity.0.tenant_id").MatchesRegex(validate.UUIDRegExp),
+				check.That(data.ResourceName).Key("site_config.0.acr_use_managed_identity_creds").HasValue("true"),
+			),
+		},
+	})
```
Comment (jackofallops) [inline azurerm/internal/services/web/app_service_resource_test.go:1880]: We can make use of `ImportStep` here to check values:
```suggestion
	data.ResourceTest(t, r, []acceptance.TestStep{
		{
			Config: r.AcrUseManagedIdentity(data),
			Check: acceptance.ComposeTestCheckFunc(
				check.That(data.ResourceName).ExistsInAzure(r),
			),
		},
		data.ImportStep(),
	})
```

File: azurerm/internal/services/web/app_service_resource_test.go [hunk 9]
```diff
@@ -1862,6 +1862,39 @@ func TestAccAppService_basicWindowsContainer(t *testing.T) {
...
+
+	data.ResourceTest(t, r, []acceptance.TestStep{
+		{
+			Config: r.AcrUserAssignedIdentity(data),
+			Check: acceptance.ComposeTestCheckFunc(
+				check.That(data.ResourceName).ExistsInAzure(r),
+				check.That(data.ResourceName).Key("site_config.0.acr_user_managed_identity_id").MatchesRegex(validate.UUIDRegExp),
+			),
+		},
+	})
```
Comment (jackofallops) [inline azurerm/internal/services/web/app_service_resource_test.go:1895]: And the same here:
```suggestion
	data.ResourceTest(t, r, []acceptance.TestStep{
		{
			Config: r.AcrUserAssignedIdentity(data),
			Check: acceptance.ComposeTestCheckFunc(
				check.That(data.ResourceName).ExistsInAzure(r),
			),
		},
		data.ImportStep(),
	})
```

File: azurerm/internal/services/web/app_service_resource_test.go [hunk 10]
```diff
@@ -5387,3 +5420,87 @@ resource "azurerm_app_service" "test" {
...
+
+resource "azurerm_app_service" "test" {
+  name                = "acctestAS-%d"
+  location            = azurerm_resource_group.test.location
+  resource_group_name = azurerm_resource_group.test.name
+  app_service_plan_id = azurerm_app_service_plan.test.id
+
+  site_config {
+    acr_use_managed_identity_creds = true
+    acr_user_managed_identity_id   = azurerm_user_assigned_identity.test.client_id
```
Comment (jackofallops) [inline azurerm/internal/services/web/app_service_resource_test.go:5502]: As mentioned above, we should use the ID here.
```suggestion
    acr_user_managed_identity_id   = azurerm_user_assigned_identity.test.id
```

File: azurerm/internal/services/web/app_service.go [hunk 11]
```diff
@@ -819,6 +828,14 @@ func schemaAppServiceDataSourceSiteConfig() *pluginsdk.Schema {
 						},
 					},
 				},
+				"acr_use_managed_identity_creds": {
```
Comment (jackofallops) [inline azurerm/internal/services/web/app_service.go:831]:
```suggestion
				"acr_use_managed_identity_credentials": {
```

File: azurerm/internal/services/web/app_service.go [hunk 12]
```diff
@@ -1773,6 +1790,14 @@ func expandAppServiceSiteConfig(input interface{}) (*web.SiteConfig, error) {
 		siteConfig.AutoSwapSlotName = utils.String(v.(string))
 	}
 
+	if v, ok := config["acr_use_managed_identity_creds"]; ok {
```
Comment (jackofallops) [inline azurerm/internal/services/web/app_service.go:1793]:
```suggestion
	if v, ok := config["acr_use_managed_identity_credentials"]; ok {
```

File: azurerm/internal/services/web/app_service.go [hunk 13]
```diff
@@ -1884,6 +1909,14 @@ func flattenAppServiceSiteConfig(input *web.SiteConfig) []interface{} {
 		result["auto_swap_slot_name"] = *input.AutoSwapSlotName
 	}
 
+	if input.AcrUseManagedIdentityCreds != nil {
+		result["acr_use_managed_identity_creds"] = *input.AcrUseManagedIdentityCreds
```
Comment (jackofallops) [inline azurerm/internal/services/web/app_service.go:1913]:
```suggestion
		result["acr_use_managed_identity_credentials"] = *input.AcrUseManagedIdentityCreds
```

File: website/docs/r/app_service.html.markdown [hunk 14]
```diff
@@ -249,6 +249,12 @@ Additional examples of how to run Containers via the `azurerm_app_service` resou
 
 * `websockets_enabled` - (Optional) Should WebSockets be enabled?
 
+* `acr_use_managed_identity_creds` - (Optional) Are Managed Identity Credentials used for Azure Container Registry pull
```
Comment (jackofallops) [inline website/docs/r/app_service.html.markdown:252]:
```suggestion
* `acr_use_managed_identity_credentials` - (Optional) Are Managed Identity Credentials used for Azure Container Registry pull
```

File: website/docs/r/app_service_slot.html.markdown [hunk 15]
```diff
@@ -234,6 +234,12 @@ The following arguments are supported:
 
 * `auto_swap_slot_name` - (Optional) The name of the slot to automatically swap to during deployment
 
+* `acr_use_managed_identity_creds` - (Optional) Are Managed Identity Credential used for Azure Container Registry pull
```
Comment (jackofallops) [inline website/docs/r/app_service_slot.html.markdown:237]:
```suggestion
* `acr_use_managed_identity_credentials` - (Optional) Are Managed Identity Credential used for Azure Container Registry pull
```

**Review by jackofallops — CHANGES_REQUESTED** [review]
Hi @mozts2005 - Apologies for the delay in getting back to this review.  I've  left some comments / changes below. If those can be addressed, I'll get this through the test suite and we should be good to merge.
Thanks!

File: azurerm/internal/services/web/app_service.go (hunk 7 above)
Comment (mozts2005) [reply azurerm/internal/services/web/app_service.go:502]: No, as the SDK only works when I set the client ID. As in ￼will pull a container from an ARC.

Comment (mozts2005) [reply azurerm/internal/services/web/app_service.go:502]: I tried added a test that would pull the container but I could not complete a local run with null resource and the azure cli to import a container image.

File: azurerm/internal/services/web/app_service_resource_test.go (hunk 8 above)
Comment (mozts2005) [reply azurerm/internal/services/web/app_service_resource_test.go:1880]: I am new to Go. Can you explain how importSteps will validate the property values return?

**Comment by mozts2005** [comment]
I have some questions about your review. Thanks for your help.

File: azurerm/internal/services/web/app_service.go (hunk 7 above)
Comment (jackofallops) [reply azurerm/internal/services/web/app_service.go:502]: @mozts2005 - This feels like a bug in the service, however, if this the case, we should rename this property to match the required name `acr_user_managed_identity_client_id` to be specific about the value and avoid confusion about which ID is required. (since normal parlance means the resource ID).

File: azurerm/internal/services/web/app_service_resource_test.go (hunk 8 above)
Comment (jackofallops) [reply azurerm/internal/services/web/app_service_resource_test.go:1880]: It's a part of our test framework, rather than a Go specific thing. The `ImportStep` helper function reads the resource back and if there are differences between that view and what is configured, it errors out with the differences. It optionally takes a list of schema keys that are not returned by the API and should be ignored for the comparison. (e.g. if a read on a resource doesn't return a sensitive value like a password). Does that help?

Comment (mozts2005) [reply azurerm/internal/services/web/app_service_resource_test.go:1880]: That answered my question.

File: azurerm/internal/services/web/app_service.go (hunk 7 above)
Comment (mozts2005) [reply azurerm/internal/services/web/app_service.go:502]: Ok, I will change the name.

Comment (mozts2005) [reply azurerm/internal/services/web/app_service.go]: Change the names as requested

File: azurerm/internal/services/web/app_service_resource_test.go (hunk 10 above)
Comment (mozts2005) [reply azurerm/internal/services/web/app_service_resource_test.go]: did not change as it was conflict with property name change

**Review by jackofallops — APPROVED** [review]
Hi @mozts2005 - Thanks for the changes, this LGTM now 👍

**Comment by jackofallops** [comment]
Related tests looking good:

image
