### PR TITLE
d/logic_app_workflow - ensuing the parameters are a string prior to flattening

### LINKED ISSUE #2342: Terraform Crash: Data Source Logic App Workflow
_This issue was originally opened by @paultyrrell-bourne as hashicorp/terraform#19385. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

[

### Terraform Version

```
...
```

### Terraform Configuration Files

```hcl
...
```

### Actual Behavior
```
2018-11-16T16:38:20.293Z [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: panic: interface conversion: interface {} is map[string]interface {}, not string
2018-11-16T16:38:20.293Z [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: 
2018-11-16T16:38:20.293Z [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: goroutine 69 [running]:
2018-11-16T16:38:20.293Z [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.flattenLogicAppDataSourceWorkflowParameters(0xc00060af60, 0x21922b8)
2018-11-16T16:38:20.293Z [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/data_source_logic_app_workflow.go:98 +0x1b0
2018-11-16T16:38:20.293Z [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.dataSourceArmLogicAppWorkflowRead(0xc0001bb810, 0x2156020, 0xc0006c0000, 0xc0001bb810, 0x0)
2018-11-16T16:38:20.293Z [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/data_source_logic_app_workflow.go:73 +0x5e2
2018-11-16T16:38:20.293Z [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0xc000657b90, 0xc00084ad80, 0x2156020, 0xc0006c0000, 0xc000878538, 0x4c2201, 0x1dfbaa0)
2018-11-16T16:38:20.293Z [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:290 +0x88
2018-11-16T16:38:20.293Z [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0xc0006cd810, 0xc000628320, 0xc00084ad80, 0xc000480a80, 0x18, 0x7fe7a6c29000)
2018-11-16T16:38:20.293Z [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:426 +0x92
2018-11-16T16:38:20.293Z [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ReadDataApply(0xc000129f00, 0xc00048b0e0, 0xc00048b250, 0x0, 0x0)
2018-11-16T16:38:20.293Z [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:604 +0x4e
2018-11-16T16:38:20.293Z [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: reflect.Value.call(0xc000142ae0, 0xc00043a628, 0x13, 0x218cf71, 0x4, 0xc00009ff18, 0x3, 0x3, 0xc00084e780, 0xc00084e900, ...)
2018-11-16T16:38:20.293Z [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: 	/opt/goenv/versions/1.11.1/src/reflect/value.go:447 +0x449
2018-11-16T16:38:20.293Z [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: reflect.Value.Call(0xc000142ae0, 0xc00043a628, 0x13, 0xc00033ff18, 0x3, 0x3, 0x14, 0x0, 0xc00048a6a0)
2018-11-16T16:38:20.293Z [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: 	/opt/goenv/versions/1.11.1/src/reflect/value.go:308 +0xa4
2018-11-16T16:38:20.293Z [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: net/rpc.(*service).call(0xc00014b440, 0xc00042e780, 0xc000640bf0, 0xc000640c00, 0xc00045e680, 0xc00084a900, 0x1dfba60, 0xc00048b0e0, 0x16, 0x1dfbaa0, ...)
```

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Fixes #2342

### CODE REVIEW

File: azurerm/data_source_logic_app_workflow.go [hunk 1]
```diff
@@ -95,7 +96,13 @@ func flattenLogicAppDataSourceWorkflowParameters(input map[string]*logic.Workflo
 
 	for k, v := range input {
 		if v != nil {
-			output[k] = v.Value.(string)
+			// we only support string parameters at this time
+			val, ok := v.Value.(string)
+			if !ok {
+				log.Printf("[DEBUG] Skipping parameter %q since it's not a string", k)
```
Comment (katbyte) [inline azurerm/data_source_logic_app_workflow.go]: Should we maybe throw an error here instead of silently ignoring it?

Comment (tombuildsstuff) [reply azurerm/data_source_logic_app_workflow.go]: this is consistent with the behaviour of the Logic App Workflow resource (and the Template Deployment resource) - which states we only support string values at this time (such that I don't think this is necessary?)

**Comment by tombuildsstuff** [comment]
Tests pass:

screenshot 2018-11-19 at 12 53 17
