### PR TITLE
check for rules on the firewall and include in updates

### LINKED ISSUE #2621: Network rule collection deleted when updating tags on firewall
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

``` shell
$ terraform -v
Terraform v0.11.11
+ provider.azurerm v1.20.0
```

### Affected Resource(s)

* azurerm_firewall
* azurerm_firewall_network_rule_collection

### Terraform Configuration Files

All of the necessary Terraform templates to recreate this issue are in [this gist](https://gist.github.com/jlucktay/6b8c3c454d43cf4565779118e9bf5bbb).

### Expected Behavior

Terraform should have added/updated the tags on the Firewall.

### Actual Behavior

Terraform added/updated the tags on the Firewall, and also **deleted the network rule collection**.

A subsequent `terraform plan` included the (re)creation of the network rule collection.

### Steps to Reproduce

1. Using the Terraform templates in [the linked gist](https://gist.github.com/jlucktay/6b8c3c454d43cf4565779118e9bf5bbb), run `terraform plan` and `terraform apply`.
1. In the Azure portal, navigate to the firewall's network rule collections, and confirm the existence of the network rule collection described in the Terraform templates.
1. In the Terraform templates, make a change to the `azurerm_firewall` resource, e.g. add a new tag or edit an existing one in `terraform.tfvars`.
1. Run `terraform plan` and `terraform apply` again.
1. Refresh the network rule collections in the Azure portal.

### Important Factoids

Our discovery of this issue came when updating tags to meet compliance, and the inadvertent removal of the above network rule collection led to some resources not having internet access briefly.

### PR DESCRIPTION
**Pull request by hbuckle**
We need to check for the existence of any rules on the firewall before updating and include them in the update, otherwise they get wiped out
fixes #2621

### CODE REVIEW

File: azurerm/resource_arm_firewall.go [hunk 1]
```diff
@@ -127,6 +127,21 @@ func resourceArmFirewallCreateUpdate(d *schema.ResourceData, meta interface{}) e
...
+		}
+	}
+	if exists.ID != nil && *exists.ID != "" {
+		if exists.AzureFirewallPropertiesFormat != nil {
+			props := *exists.AzureFirewallPropertiesFormat
+			parameters.AzureFirewallPropertiesFormat.ApplicationRuleCollections = props.ApplicationRuleCollections
+			parameters.AzureFirewallPropertiesFormat.NetworkRuleCollections = props.NetworkRuleCollections
+			parameters.AzureFirewallPropertiesFormat.NatRuleCollections = props.NatRuleCollections
+		}
+	}
```
Comment (tombuildsstuff) [inline azurerm/resource_arm_firewall.go]: I believe we should be able to wrap this in: `!d.IsNewResource()` (so we only look this info up for Updates) to make this:

```
if !d.IsNewResource() {
  existing, err := client.Get(ctx, resourceGroup, name)
  if err != nil {
    if utils.ResponseWasNotFound(exists.Response) {
      return fmt.Errorf("Firewall %q was not found in Resource Group %q!", name, resourceGroup)
    }
    
    return fmt.Errorf("Error retrieving existing Firewall %q (Resource Group %q): %s", name, resourceGroup, err)
  }
  
  if existing.AzureFirewallPropertiesFormat == nil {
    return fmt.Errorf("Error retrieving existing Rules - `props` was nil")
  }
  
  props := *exists.AzureFirewallPropertiesFormat
  parameters.AzureFirewallPropertiesFormat.ApplicationRuleCollections = props.ApplicationRuleCollections
  parameters.AzureFirewallPropertiesFormat.NetworkRuleCollections = props.NetworkRuleCollections
  parameters.AzureFirewallPropertiesFormat.NatRuleCollections = props.NatRuleCollections
}
```

WDYT?

Comment (hbuckle) [reply azurerm/resource_arm_firewall.go]: Yup makes sense

**Comment by tombuildsstuff** [comment]
Tests pass:

screenshot 2019-01-14 at 14 16 19
