### PR TITLE
`azurerm_load_test` - improve validation to prevent unclear errors from Azure

### LINKED ISSUE #29388: azure_load_test resource failed due to Invalid URL for managed identity in encryption block
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.117.1

### Affected Resource(s)/Data Source(s)

azurerm_load_test

### Terraform Configuration Files

```hcl
resource "azurerm_load_test" "loadtest" {
  name                = var.loadtest_name
  resource_group_name = azurerm_resource_group.loadtestrg.name
  location            = azurerm_resource_group.loadtestrg.location

  encryption {
    identity {
      type        = "UserAssigned"
      identity_id = var.loadtest_user_identity_id
    }
    key_url = var.key_vault_key_url
  }

  
depends_on = [
 azurerm_resource_group.loadtestrg,
 azurerm_user_assigned_identity.loadtest_user_identity
 ]

}

I am getting value of loadtest_user_identity_id from a datasource.

data "azurerm_user_assigned_identity" "loadtest_user_identity" {
 name                = "xxxxxx"
 resource_group_name = "xxxxxx"
}
```

### Debug Output/Panic Output

```shell
Load Test Name: "mobilityss-dev-loadtest"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: ValidationFailed: Invalid UserAssigned identity in the Encryption properties.
```

### Expected Behaviour

the resource should have been created

### Actual Behaviour

It fails with invalid URL error for identity_id.

It is because the datasource provide url as 

/subscriptions/2926db75-xxxx-xxxx-xxxx-cxxxxxf09ca3/**resourceGroups**/rgdev-xxxx-azureloadtest/providers/Microsoft.ManagedIdentity/userAssignedIdentities/xxxx-loadtest-identity

and in the azure portal the url as
/subscriptions/2926db75-xxxx-xxxx-xxxx-cxxxxxf09ca3/**resourcegroups**/rgdev-xxxx-azureloadtest/providers/Microsoft.ManagedIdentity/userAssignedIdentities/xxxx-loadtest-identity

Also if i try to use direct url of managed identity (resource id from azure portal) i am getting a parsing error 

The parsed Resource ID was missing a value for the segment at position 2
2025-04-16T14:49:42.3957068Z (which should be the literal value "resourceGroups").

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by sreallymatt**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

When provisioning `azurerm_load_test` with a user managed identity for encryption, if this identity does not also exist in the `identity.identity_ids` list, Azure returns a vague 400 error. (`Invalid UserAssigned identity in the Encryption properties.`)

When encryption is added, or the UAI for encryption is modified, in portal, Azure automatically adds this to the assigned identities, however the API does not automatically create this connection.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #29388

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/loadtestservice/load_test_resource_test.go [hunk 1]
```diff
@@ -270,6 +283,109 @@ resource "azurerm_load_test" "test" {
...
+    key_permissions = ["Get", "WrapKey", "UnwrapKey"]
+  }
+
+  tags = {
+    environment = "Production"
+  }
+}
+
+resource "azurerm_key_vault_key" "test" {
+  name         = "key-%[2]d"
```
Comment (catriona-m) [inline internal/services/loadtestservice/load_test_resource_test.go]:
```suggestion
  name         = "acctestkey-%[2]d"
```

**Review by catriona-m — CHANGES_REQUESTED** [review]
Thanks @sreallymatt, one minor comment on test resource name but this looks good!

**Review by catriona-m — APPROVED** [review]
Thanks @sreallymatt LGTM!
