### PR TITLE
policy assignment - validate policy assignment name length

### LINKED ISSUE #30081: azurerm_management_group_policy_assignment should have a validation for max length of 24 characters
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

Receiving this at runtime, we should be able to check this in a validation function:
`unexpected status 400 (400 Bad Request) with error: InvalidPolicyAssignmentName: The policy assignment name 'lighthouse-security-baseline' is invalid. The policy assignment name length must not exceed '24' characters.`

### Terraform Version

1.9

### AzureRM Provider Version

4.32.0

### Affected Resource(s)/Data Source(s)

azurerm_management_group_policy_assignment

### Terraform Configuration Files

```hcl
resource "azurerm_management_group_policy_assignment" "lighthouse_security_baseline" {
  name                 = "lighthouse-security-baseline"
  policy_definition_id = azurerm_management_group_policy_set_definition.lighthouse_security_baseline.id
  management_group_id  = var.base_management_group_id
}
```

### Debug Output/Panic Output

```shell
unexpected status 400 (400 Bad Request) with error: InvalidPolicyAssignmentName: The policy assignment name 'lighthouse-security-baseline' is invalid. The policy assignment name length must not exceed '24' characters.
```

### Expected Behaviour

a terraform validate command should catch this error prior to apply

### Actual Behaviour

it allows you to run apply and fails at runtime

### Steps to Reproduce

create a management group policy assignment with a name too long

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by ezhong-msft**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description
Docs were added previously but the validation wasn't being enforced
https://github.com/hashicorp/terraform-provider-azurerm/pull/21549/files

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- (n/a) I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #30081

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/policy/management_group_policy_assignment_resource.go [hunk 1]
```diff
@@ -32,6 +32,7 @@ func (r ManagementGroupAssignmentResource) Arguments() map[string]*pluginsdk.Sch
 			ValidateFunc: validation.All(
 				validation.StringIsNotWhiteSpace,
 				validation.StringDoesNotContainAny("/"),
+				validation.StringLenBetween(3, 24),
```
Comment (sreallymatt) [inline internal/services/policy/management_group_policy_assignment_resource.go]: Quickly testing this, it seems the API does accept names of only 1 character like the other `*_policy_assignment` resources, so to avoid breaking existing configurations that may be using that we should change this to 1

```suggestion
				validation.StringLenBetween(1, 24),
```

E.g. this worked:

```hcl
resource "azurerm_management_group_policy_assignment" "test" {
  name                 = "a"
  management_group_id  = azurerm_management_group.test.id
  policy_definition_id = data.azurerm_policy_definition.test.id
  parameters = jsonencode({
    "listOfAllowedLocations" = {
      "value" = [azurerm_resource_group.test.location]
    }
  })
}
```

Could you update the documentation as well?

**Review by sreallymatt — CHANGES_REQUESTED** [review]
Thanks @ezhong-msft, left one comment inline

File: internal/services/policy/management_group_policy_assignment_resource.go (hunk 1 above)
Comment (stanleyz) [reply internal/services/policy/management_group_policy_assignment_resource.go]: And MS doc also states it accept 1-24 characters.

https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules

Screenshot 2025-07-19 at 3 41 03 PM

Can we have the provider document updated accordingly as well? Thanks.

Comment (ezhong-msft) [reply internal/services/policy/management_group_policy_assignment_resource.go]: Ah thanks for the docs, was not aware this existed. Updated the length and added the additional validations too.

**Comment by stanleyz** [comment]
Thanks @ezhong-msft , I'll leave this to @sreallymatt for review as he is the owner of this component. 

The code looks good to me in general, however wondering whether we should make it super clear in the doc as about what characters are not allowed, but I am not too fussy about this.

Thanks again for the work.

**Review by sreallymatt — APPROVED** [review]
Thanks @ezhong-msft LGTM ✅
