### PR TITLE
`azurerm_kubernetes_cluster` - fix validation for `advanced_networking` block

### LINKED ISSUE #30681: Support for ACNS for Non-Cilium AKS Clusters
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The newest feature that enables advanced network is a powerful update. But I noticed that it lacked the support for the Non-Cilium clusters like in the CLI sample from https://aka.ms/acns

The current version requires the cluster to have cilium as the network data plane.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubetnetes_cluster

### Potential Terraform Configuration

```hcl
network_data_plane: "azure"
advanced_networking {
 observability_enabled: true
 security_enabled: true
}
```

### References
https://aka.ms/acns

### PR DESCRIPTION
**Pull request by ms-henglu**
…

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

The advanced_networking block in azurerm_kubernetes_cluster was previously requiring both network_plugin = "azure" and network_data_plane = "cilium" any time the block was present. This is too restrictive — observability_enabled can be used with non-Cilium clusters (e.g. kubenet), and the Cilium requirement only applies when security_enabled = true.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-merging.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)

fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/30681

## AI Assistance Disclosure

- [ ] AI Assisted - This contribution was made by, or with the assistance of, AI/LLMs

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/containers/kubernetes_cluster_network_resource_test.go [hunk 1]
```diff
@@ -84,7 +84,7 @@ func TestAccKubernetesCluster_advancedNetworkingNetworkPluginError(t *testing.T)
 	data.ResourceTest(t, r, []acceptance.TestStep{
 		{
 			Config:      r.advancedNetworkingBlock(data, "kubenet", "cilium"),
-			ExpectError: regexp.MustCompile("when `network_profile.0.advanced_networking` is set, `network_profile.0.network_plugin` must be set to `azure`"),
+			ExpectError: regexp.MustCompile("when `network_profile.0.advanced_networking` has `security_enabled` set to true, `network_profile.0.network_plugin` must be set to `azure`"),
```
Comment (liuwuliuyun) [inline internal/services/containers/kubernetes_cluster_network_resource_test.go]: A small suggestion here: set to `true` would be clearer

**Review by liuwuliuyun — COMMENTED** [review]
Suggested a small change and the rest part LGTM!

File: internal/services/containers/kubernetes_cluster_network_resource_test.go (hunk 1 above)
Comment (ms-henglu) [reply internal/services/containers/kubernetes_cluster_network_resource_test.go]: Thanks for the suggestion! Updated.

**Review by ms-zhenhua — APPROVED** [review]
LGTM~

**Review by liuwuliuyun — APPROVED** [review]
LGTM, Thanks!

File: internal/services/containers/kubernetes_cluster_network_resource_test.go [hunk 2]
```diff
@@ -4664,3 +4664,91 @@ resource "azurerm_kubernetes_cluster" "test" {
...
+	data.ResourceTest(t, r, []acceptance.TestStep{
+		{
+			Config: r.advancedNetworkingObservabilityOnlyBlock(data, "kubenet", "azure"),
+			Check: acceptance.ComposeTestCheckFunc(
+				check.That(data.ResourceName).ExistsInAzure(r),
+			),
+		},
+		data.ImportStep(),
+	})
+}
```
Comment (gerrytan) [inline internal/services/containers/kubernetes_cluster_network_resource_test.go]: For consistency with other acctests please put the tests above all the configs

File: internal/services/containers/kubernetes_cluster_resource.go [hunk 3]
```diff
@@ -146,11 +146,15 @@ func resourceKubernetesCluster() *pluginsdk.Resource {
...
-					}
-					if d.Get("network_profile.0.network_plugin").(string) != string(managedclusters.NetworkPluginAzure) {
-						return fmt.Errorf("when `network_profile.0.advanced_networking` is set, `network_profile.0.network_plugin` must be set to `%s`", managedclusters.NetworkPluginAzure)
+					securityEnabled := d.Get("network_profile.0.advanced_networking.0.security_enabled").(bool)
+
+					if securityEnabled {
+						if d.Get("network_profile.0.network_data_plane").(string) != string(managedclusters.NetworkDataplaneCilium) {
+							return fmt.Errorf("when `network_profile.0.advanced_networking` has `security_enabled` set to `true`, `network_profile.0.network_data_plane` must be set to `%s`", managedclusters.NetworkDataplaneCilium)
+						}
+						if d.Get("network_profile.0.network_plugin").(string) != string(managedclusters.NetworkPluginAzure) {
```
Comment (gerrytan) [inline internal/services/containers/kubernetes_cluster_resource.go]: Add to top level:
Description needs to be added / updated
Title slightly misleading

Any impact to conditional force new logic?

File: website/docs/r/kubernetes_cluster.html.markdown [hunk 4]
```diff
@@ -718,15 +718,15 @@ Examples of how to use [AKS with Advanced Networking](https://docs.microsoft.com
...
+* `advanced_networking` - (Optional) An `advanced_networking` block as defined below.
 
 ---
 
 An `advanced_networking` block supports the following:
 
 * `observability_enabled` - (Optional) Is observability enabled? Defaults to `false`.
 
-* `security_enabled` - (Optional) Is security enabled? Defaults to `false`.
+* `security_enabled` - (Optional) Is security enabled? Defaults to `false`. This can only be specified when `network_plugin` is set to `azure` and `network_data_plane` is set to `cilium`.
```
[the remark this answers is not in the document]
Comment (gerrytan) [reply website/docs/r/kubernetes_cluster.html.markdown]: I agree with Copilot here, can this please be addressed?

**Review by gerrytan — CHANGES_REQUESTED** [review]
Thanks @ms-henglu, I looked at this PR together with HC folks during our session and this looks good in general except for few issues:

 1. Please provide PR description and fill the checklists
 1. Please note in the description this feature is not yet supported in portal (which is fine), the corresponding MS Learn doc: https://learn.microsoft.com/en-us/azure/aks/advanced-container-networking-services-overview
 1. Please provide TC acctest link

**Comment by gerrytan** [comment]
Thanks @ms-henglu this PR looks good to me except for latest acctest result.

I have triggered one: https://hashicorp.teamcity.com/buildConfiguration/TF_AzureRM_AZURERM_SERVICE_PUBLIC_CONTAINERS/630402?buildTab=

Will get HC to review this again

**Review by sreallymatt — CHANGES_REQUESTED** [review]
Thanks @ms-henglu - This LGTM but there are some conflicts, once those are resolved I'll merge this in

**Comment by gerrytan** [comment]
Ran acctest against latest commit: https://hashicorp.teamcity.com/viewQueued.html?itemId=635585

**Review by sreallymatt — APPROVED** [review]
Thanks @ms-henglu - LGTM ✅
