### PR TITLE
r/kubernetes_cluster: supporting conditional updates / introducing `default_node_pool`

### LINKED ISSUE #2993: Upgrading Kubernetes cluster via Azure Portal causes terraform to try to recreate it
### Terraform (and AzureRM Provider) Version
`terraform` **v0.11.7**
`azurerm` **1.22.1**

### Affected Resource(s)
`azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "main" {
...
 addon_profile {
    http_application_routing {
      enabled = false
    }
  }
...
}
```
### Expected Behavior
Nothing should happen. Terraform plan should return no changes after the cluster upgrade is done via azure portal.

### Actual Behavior
Terraform tries to recreate the cluster because of 2 problems:
1. `http_application_routing` addon profile
2. cluster `id`

```
-/+ azurerm_kubernetes_cluster.main (new resource required)
      id:                                                                            "/subscriptions/XXXXXX-XXXX-XXXX-XXX-XXXXX/resourcegroups/myResourceGroup/providers/Microsoft.ContainerService/managedClusters/myCluster" => <computed> (forces new resource)
      addon_profile.#:                                                               "1" => "1"
      addon_profile.0.http_application_routing.#:                                    "0" => "1" (forces new resource)
      addon_profile.0.http_application_routing.0.enabled:                            "" => "false" (forces new resource)
      addon_profile.0.http_application_routing.0.http_application_routing_zone_name: "" => <computed>
...
```

`id` does not change (as far as I can tell) during a upgrade and yet terraform think it does.
`http_application_routing` was already disabled but the sate doesnt seem to match the one from azure backend after the cluster upgrade.
Removing the `addon_profile` block seems to bypass the issue after the cluster upgrade but terraform still wants to recreate the cluster because of the `id` field anyway.

### Steps to Reproduce
1. Create cluster with terraform (with `addon_profile` containing `http_application_routing` **enabled=false**
2. Go to Azure Portal, upgrade your cluster version.
3. Run `terraform plan` (after fixing `kubernetes_version` to match the upgraded version, of course) and the errors will be displayed.

### LINKED ISSUE #3428: Provider produced invalid plan when addon_profile in ignore_changes
### Terraform (and AzureRM Provider) Version
```
Terraform v0.12.0-rc1
+ provider.azuread v0.3.1
+ provider.azurerm v1.27.1
+ provider.helm v0.9.1
+ provider.kubernetes v1.6.2
+ provider.random v2.1.2
```
### Affected Resource(s)
* `azurerm_kubernetes_cluster`

### Terraform Configuration Files
```resource "azurerm_kubernetes_cluster" "k8s" {
  lifecycle {
    ignore_changes = ["id", "service_principal", "addon_profile" ]
  }
...
}
```
### Expected Behavior

It should at least ignore the k8s cluster

### Actual Behavior

```Error: Provider produced invalid plan

Provider "azurerm" has indicated "requires replacement" on
module.glazeregion.module.k8s.azurerm_kubernetes_cluster.k8s for a
non-existent attribute path cty.Path{cty.GetAttrStep{Name:"addon_profile"},
cty.IndexStep{Key:cty.NumberIntVal(0)},
cty.GetAttrStep{Name:"http_application_routing"},
cty.IndexStep{Key:cty.NumberIntVal(0)}, cty.GetAttrStep{Name:"enabled"}}.
```

### Steps to Reproduce

I am trying to apply the workaround mentioned in https://github.com/terraform-providers/terraform-provider-azurerm/issues/2993#issuecomment-484415664 till that issue is fixed. But in my case (TF 0.12rc), once I add "addon_profile" to ignore_changes, the provider produces an invalid plan!

### LINKED ISSUE #3549: Node pool update via managed cluster not allowed. Use per nodepool operations
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.0
+ provider.azuread v0.3.1
+ provider.azurerm v1.29.0
+ provider.helm v0.9.1
+ provider.kubernetes v1.7.0
+ provider.random v2.1.2

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Diff
```
      ~ agent_pool_profile {
          ~ count           = 3 -> 5
            fqdn            = "foo-bar.hcp.westeurope.azmk8s.io"
            max_pods        = 30
            name            = "fast"
            os_disk_size_gb = 100
            os_type         = "Linux"
            type            = "VirtualMachineScaleSets"
            vm_size         = "Standard_F4s_v2"
            vnet_subnet_id  = "/subscriptions/REDACTED/resourceGroups/foo/providers/Microsoft.Network/virtualNetworks/foovnet/subnets/k8snodes"
        }
```

### Expected Behavior

TF scales the agent pool

### Actual Behavior

`Error: Error creating/updating Managed Kubernetes Cluster "dustydog" (Resource Group "dustydog"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="OperationNotAllowed" Message="Node pool update via managed cluster not allowed. Use per nodepool operations."`

### Steps to Reproduce

1. Create an aks cluster with 2 node pools
2. Change the size of a node pool within HCL
3. `terraform apply`

### LINKED ISSUE #3835: Terraform replacing AKS nodepool cluster when changing VM count
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.4
provider.azurerm v1.31.0

### Affected Resource(s)
azurerm_kubernetes_cluster

### Terraform Configuration Files

```
resource "azurerm_resource_group" "test" {
  location = "${var.location}"
  name = "${var.resource_group_name}"
}
resource "azurerm_kubernetes_cluster" "test" {
  name                = "${var.resource_group_name}"
  location            = "${var.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  dns_prefix          = "test"
  kubernetes_version  = "${var.kubernetes_version}"

  linux_profile {
      admin_username  = "${var.admin_user}"
      ssh_key {
            key_data  = "${var.ssh_key}"
        }
    }

  agent_pool_profile {
    name              = "${var.agent_pool1_name}"
    count             = "${var.agent_pool1_count}"
    vm_size           = "${var.agent_pool1_vm_size}"
    os_type           = "Linux"
    os_disk_size_gb   = "${var.agent_pool1_os_disk_size}"
    vnet_subnet_id    = "${var.subnet_id}"
    max_pods          = "${var.max_pods_per_node}"
    type              = "${var.agent_pool_scaling}"
  }

  agent_pool_profile {
    name              = "${var.agent_pool2_name}"
    count             = "${var.agent_pool2_count}"
    vm_size           = "${var.agent_pool2_vm_size}"
    os_type           = "Linux"
    os_disk_size_gb   = "${var.agent_pool2_os_disk_size}"
    vnet_subnet_id    = "${var.subnet_id}"
    max_pods          = "${var.max_pods_per_node}"
    type              = "${var.agent_pool_scaling}"
  }

  service_principal {
    client_id         = "is somewhere"
    client_secret     = "is somewhere"
  }

  network_profile {
    network_plugin    = "${var.network_plugin}"
  }

  role_based_access_control {
    enabled           = "true"
```

### Expected Behavior

Changing "count" in one of the "agent_pool_profile" and running "terraform apply" should add one more node to cluster. 

### Actual Behavior

Terraform replaces whole cluster ad adds new one with new number of nodes in the given nodepool. It also seems to be chaining the nodepool name around from looking at the plan

terraform plan output:

```
  # azurerm_kubernetes_cluster.cloudbees-jenkins-dev must be replaced

~ agent_pool_profile {
          ~ count           = 1 -> 2
          + dns_prefix      = (known after apply)
          ~ fqdn            = "test" -> (known after apply)
            max_pods        = 30
          ~ name            = "medium" -> "performance" # forces replacement
            os_disk_size_gb = 50
            os_type         = "Linux"
            type            = "VirtualMachineScaleSets"
          ~ vm_size         = "Standard_D4s_v3" -> "Standard_D8s_v3" # forces replacement
}

        }
      ~ agent_pool_profile {
            count           = 1
          + dns_prefix      = (known after apply)
          ~ fqdn            = "test" -> (known after apply)
            max_pods        = 30
          ~ name            = "performance" -> "medium" # forces replacement
            os_disk_size_gb = 50
            os_type         = "Linux"
            type            = "VirtualMachineScaleSets"
          ~ vm_size         = "Standard_D8s_v3" -> "Standard_D4s_v3" # forces replacement
}

      - service_principal {
          - client_id = "acutal_client_id" -> null
        }

### Steps to Reproduce

1. Change nodepool count from 1 to 2
2. `terraform plan or apply`

### LINKED ISSUE #3971: azurerm_kubernetes_cluster: Adding node pools causes AKS cluster replacement
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
$ terraform -v
Terraform v0.12.5
+ provider.azurerm v1.32.0
```

### Affected Resource(s)
azurerm_kubernetes_cluster

### Terraform Configuration Files
```hcl
resource "azurerm_kubernetes_cluster" "test" {
  name                = "test-k8s"
  resource_group_name = "test-rg"
  location            = "westus"
  dns_prefix          = "k8s"

  agent_pool_profile {
    name            = "poolone"
    count           = 1
    vm_size         = "Standard_B2ms"
    os_type         = "Linux"
    os_disk_size_gb = 30
  }

  /*
  agent_pool_profile {
    name            = "pooltwo"
    count           = 1
    vm_size         = "Standard_B2ms"
    os_type         = "Linux"
    os_disk_size_gb = 30
  }
  */

  network_profile {
    network_plugin     = "azure"
    network_policy     = "azure"
    service_cidr       = "172.0.0.0/24"
    dns_service_ip     = "172.0.0.10"
    docker_bridge_cidr = "172.17.0.1/16"
  }

  service_principal {
    client_id     = $MY_SP_ID
    client_secret = $MY_SP_SECRET
  }
}
```

### Expected Behavior
A node pool should have been added to the existing AKS cluster without needing to destroy it first.

### Actual Behavior
The entire AKS cluster is destroyed and recreated with the additional node pool

### Steps to Reproduce
1. Setup Terraform config for an AKS cluster with 1 node pool 
2. `terraform apply`
3. Add an additional `agent_pool_profile` nested resource
4. `terraform apply`
5. Observe the Terraform plan wants to destroy and re-created the entire AKS cluster

```
  # azurerm_kubernetes_cluster.test must be replaced
-/+ resource "azurerm_kubernetes_cluster" "test" {
      - api_server_authorized_ip_ranges = [] -> null
        dns_prefix                      = "k8s"
ter apply)
      ~ kube_admin_config               = [] -> (known after apply)
      + kube_admin_config_raw           = (sensitive value)
      ~ kube_config                     = [
etc...
```

```     
 ~ agent_pool_profile {
          - availability_zones  = [] -> null
            count               = 1
          + dns_prefix          = (known after apply)
          - enable_auto_scaling = false -> null
          ~ fqdn                = "k8s-1701e02c.hcp.westus.azmk8s.io" -> (known after apply)
          - max_count           = 0 -> null
          ~ max_pods            = 30 -> (known after apply)
          - min_count           = 0 -> null
            name                = "poolone"
          - node_taints         = [] -> null
            os_disk_size_gb     = 30
            os_type             = "Linux"
            type                = "AvailabilitySet"
            vm_size             = "Standard_B2ms"
        }
      + agent_pool_profile {
          + count           = 1
          + dns_prefix      = (known after apply)
          + fqdn            = (known after apply)
          + max_pods        = (known after apply)
          + name            = "pooltwo" # forces replacement
          + os_disk_size_gb = 30 # forces replacement
          + os_type         = "Linux" # forces replacement
          + type            = "AvailabilitySet" # forces replacement
          + vm_size         = "Standard_B2ms" # forces replacement
        }
```

### Important Factoids
N/A 

### References
This issue looks related (Terraform replacing AKS nodepool cluster when changing VM count)
https://github.com/terraform-providers/terraform-provider-azurerm/issues/3835

### LINKED ISSUE #4075: Autoscaling enabled AKS Cluster leads to error on terraform apply, tough no changes on aks planned
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```hcl
provider "azurerm" {
  version = "<= 1.32.0"
}

terraform {
  version = "0.11.14"
}
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "k8s" {
  name                = "${local.name}"
  location            = "${var.region}"
  resource_group_name = "${azurerm_resource_group.default.name}"
  tags                = "${local.tags}"

  dns_prefix = "dns-${local.name}"

  agent_pool_profile {
    name                = "default"
    count               = "2"
    vm_size             = "Standard_F4s_v2"
    enable_auto_scaling = true
    min_count           = "2"
    max_count           = "10"
    os_type             = "Linux"
    os_disk_size_gb     = 30
    vnet_subnet_id      = "${azurerm_subnet.default.id}"
    type                = "VirtualMachineScaleSets"
  }

  addon_profile {
    http_application_routing {
      enabled = true
    }
  }

  network_profile {
    network_plugin = "azure"
  }

  service_principal {
    client_id     = "${var.sp_client_id}"
    client_secret = "${var.sp_client_secret}"
  }

  linux_profile {
    admin_username = "kubernetes"

    ssh_key {
      key_data = "${var.ssh_public_key}"
    }
  }
}
```

### Terraform Plan Output
```shell
$ terraform plan --out terraformplan

Refreshing Terraform state in-memory prior to plan...


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  
~
 update in-place

Terraform will perform the following actions:

  
~
 
azurerm_kubernetes_cluster.k8s
      tags.IacVersion:  "" => "v1.4.0"

  
~
 
kubernetes_config_map.deployment_config_map
      data.DEPLOYTIME: "2019-08-13T11:47:25Z" => "2019-08-13T14:51:00Z"


Plan:
 0 to add, 2 to change, 0 to destroy.


------------------------------------------------------------------------

This plan was saved to: tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "terraformplan"

```

### Panic Output
```shell

$ terraform apply "terraformplan"

azurerm_kubernetes_cluster.k8s: Modifying...

  tags.IacVersion: "" => "v1.4.0"


Error: 
Error applying plan:

1 error occurred:
	* azurerm_kubernetes_cluster.k8s: 1 error occurred:
	* azurerm_kubernetes_cluster.k8s: Error creating/updating Managed Kubernetes Cluster "" (Resource Group ""): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="Cannot manually scale AgentPool 'default' of an AKS cluster with cluster autoscaler enabled. Please disable cluster autoscaler in the cluster to manually scale."

```
### Expected Behavior

As the terraform plan suggested no changes (only changes in the tags), the azurerm_kubernetes_cluster ressource should be stay untouched

### Steps to Reproduce

0. Make an iac change, that does not lead to any resource changes on azurerm_kubernetes_cluster
1. `terraform plan --out tfplan`
2. `terraform apply tfplan`

### LINKED ISSUE #4465: Support planned AKS API default swap to VMSS + SLB (from VMAS + BLB)
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AKS has made VMSS and SLB generally available. These two cluster configurations are the highly recommended options to be used for the long term and will be required for using future features such as availability zones and multiple node pools. To encourage adoption, the default configurations during cluster create will move from VMAS/basicLB to VMSS/standardLB. Given this is a behavior change AKS is phasing this in slowly.

In the first phase the Azure clients (Azure CLI and Azure portal) will update the client logic to use VMSS/SLB. These should be complete by November.

In the second phase the AKS API will update a new API version to default to using VMSS/SLB unless explicitly stated to use something else. This is planned for post-November in a new API version, each version release after that one will keep the new default setting.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### LINKED ISSUE #4560: azurerm_kubernetes_cluster with multiple agent pools keeps getting re-created
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.6

AzureRM provider 1.35.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster `

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
  name                = "${var.aks_cluster_name}"
  location            = "${var.location}"
  dns_prefix          = "${var.aks_cluster_name}"
  resource_group_name = "${var.rg_name}"
  node_resource_group = "${var.nodes_rg_name}"
  kubernetes_version  = "1.14.6"

  linux_profile {
    admin_username = "aks_admin"

    ssh_key {
      key_data = "ssh-rsa XYZ"
    }
  }

  agent_pool_profile {
    name                = "workers"
    count               = 1
    max_count           = 20
    min_count           = 1
    max_pods            = 50
    vm_size             = "Standard_B4ms"
    os_type             = "Linux"
    os_disk_size_gb     = 100
    enable_auto_scaling = true
    type                = "VirtualMachineScaleSets"
    vnet_subnet_id      = "${data.azurerm_subnet.aks_sub.id}"
    node_taints         = ["sku=workers:PreferNoSchedule"]
  }

  agent_pool_profile {
    name                = "gpularge"
    count               = 1
    max_count           = 20
    min_count           = 1
    max_pods            = 50
    vm_size             = "Standard_NC6_Promo"
    os_type             = "Linux"
    os_disk_size_gb     = 30
    enable_auto_scaling = true
    type                = "VirtualMachineScaleSets"
    vnet_subnet_id      = "${data.azurerm_subnet.aks_sub.id}"
    node_taints         = ["sku=gpularge:NoSchedule"]
  }

  agent_pool_profile {
    name                = "gpuxlarge"
    count               = 1
    max_count           = 10
    min_count           = 1
    max_pods            = 50
    vm_size             = "Standard_NC12_Promo"
    os_type             = "Linux"
    os_disk_size_gb     = 50
    enable_auto_scaling = true
    type                = "VirtualMachineScaleSets"
    vnet_subnet_id      = "${data.azurerm_subnet.aks_sub.id}"
    node_taints         = ["sku=gpuxlarge:NoSchedule"]
  } 

  agent_pool_profile {
    name                = "cpularge"
    count               = 1
    max_count           = 20
    min_count           = 1
    max_pods            = 50
    vm_size             = "Standard_F8s_v2"
    os_type             = "Linux"
    os_disk_size_gb     = 200
    enable_auto_scaling = true
    type                = "VirtualMachineScaleSets"
    vnet_subnet_id      = "${data.azurerm_subnet.aks_sub.id}"
    node_taints         = ["sku=cpularge:NoSchedule"]
  }    

  service_principal {
    client_id     = "${data.azuread_application.aks_sp.application_id}"
    client_secret = "${data.azurerm_key_vault_secret.aks_sp_secret.value}"
  }

  network_profile {
    network_plugin     = "azure"
    network_policy     = "calico"
    service_cidr       = "10.0.0.0/16"
    dns_service_ip     = "10.0.0.2"
    docker_bridge_cidr = "172.17.0.1/16"
  }

  role_based_access_control {
    enabled = true
    azure_active_directory {
      server_app_id     = "${var.aks_server_app_id}"
      server_app_secret = "${data.azurerm_key_vault_secret.aks_app_secret.value}"
      client_app_id     = "${var.aks_client_app_id}"
      tenant_id         = "${data.azurerm_client_config.current.tenant_id}"
    }
  }
}

```

### Debug Output

The first Terraform Apply is fine, the cluster is created, no issues whatsoever.

### Panic Output

On a second Terraform run, without **ANY** code changes, Terraform wants to replace the whole cluster because it thinks some `agent_pool_profile` have changed, which is false. It seems like the ordering of the `agent_pool_profile` is messed up in the statefile or something.

```hcl
  # module.aks.azurerm_kubernetes_cluster.aks must be replaced
-/+ resource "azurerm_kubernetes_cluster" "aks" {
      - api_server_authorized_ip_ranges = [] -> null
        dns_prefix                      = "[MASKED]"
      ~ enable_pod_security_policy      = false -> (known after apply)
      ~ fqdn                            = "[MASKED]" -> (known after apply)
      ~ id                              = "/subscriptions/[MASKED]/resourcegroups/[MASKED]/providers/Microsoft.ContainerService/managedClusters/[MASKED]" -> (known after apply)
      ~ kube_admin_config               = [
          - {
              - client_certificate     = "[MASKED]"
              - client_key             = "[MASKED]"
              - host                   = "[MASKED]:443"
              - password               = "[MASKED]"
              - username               = "[MASKED]"
            },
        ] -> (known after apply)
      ~ kube_admin_config_raw           = (sensitive value)
      ~ kube_config                     = [
          - {
              - client_certificate     = ""
              - client_key             = ""
              - cluster_ca_certificate = "[MASKED]"
              - host                   = "[MASKED]:443"
              - password               = ""
              - username               = "[MASKED]"
            },
        ] -> (known after apply)
      ~ kube_config_raw                 = (sensitive value)
        kubernetes_version              = "1.14.6"
        location                        = "northeurope"
        name                            = "[MASKED]"
        node_resource_group             = "[MASKED]"
        resource_group_name             = "[MASKED]"


      ~ addon_profile {
          + aci_connector_linux {
              + enabled     = (known after apply)
              + subnet_name = (known after apply)
            }

          + http_application_routing {
              + enabled                            = (known after apply)
              + http_application_routing_zone_name = (known after apply)
            }

          + kube_dashboard {
              + enabled = (known after apply)
            }

          + oms_agent {
              + enabled                    = (known after apply)
              + log_analytics_workspace_id = (known after apply)
            }
        }

      ~ agent_pool_profile {
          - availability_zones  = [] -> null
            count               = 1
          + dns_prefix          = (known after apply)
            enable_auto_scaling = true
          ~ fqdn                = "[MASKED]" -> (known after apply)
            max_count           = 20
            max_pods            = 50
            min_count           = 1
          ~ name                = "cpularge" -> "workers" # forces replacement
          ~ node_taints         = [
              - "sku=cpularge:NoSchedule",
              + "sku=workers:PreferNoSchedule",
            ]
          ~ os_disk_size_gb     = 200 -> 100 # forces replacement
            os_type             = "Linux"
            type                = "VirtualMachineScaleSets"
          ~ vm_size             = "Standard_F8s_v2" -> "Standard_B4ms" # forces replacement
            vnet_subnet_id      = "/subscriptions/[MASKED]/resourceGroups/[MASKED]/providers/Microsoft.Network/virtualNetworks/[MASKED]/subnets/tf-aks-sub-northeu-01"
        }
      ~ agent_pool_profile {
          - availability_zones  = [] -> null
            count               = 1
          + dns_prefix          = (known after apply)
            enable_auto_scaling = true
          ~ fqdn                = "[MASKED]" -> (known after apply)
            max_count           = 20
            max_pods            = 50
            min_count           = 1
            name                = "gpularge"
            node_taints         = [
                "sku=gpularge:NoSchedule",
            ]
            os_disk_size_gb     = 30
            os_type             = "Linux"
            type                = "VirtualMachineScaleSets"
            vm_size             = "Standard_NC6_Promo"
            vnet_subnet_id      = "/subscriptions/[MASKED]/resourceGroups/[MASKED]/providers/Microsoft.Network/virtualNetworks/[MASKED]/subnets/tf-aks-sub-northeu-01"
        }
      ~ agent_pool_profile {
          - availability_zones  = [] -> null
            count               = 1
          + dns_prefix          = (known after apply)
            enable_auto_scaling = true
          ~ fqdn                = "[MASKED]" -> (known after apply)
            max_count           = 10
            max_pods            = 50
            min_count           = 1
            name                = "gpuxlarge"
            node_taints         = [
                "sku=gpuxlarge:NoSchedule",
            ]
            os_disk_size_gb     = 50
            os_type             = "Linux"
            type                = "VirtualMachineScaleSets"
            vm_size             = "Standard_NC12_Promo"
            vnet_subnet_id      = "/subscriptions/[MASKED]/resourceGroups/[MASKED]/providers/Microsoft.Network/virtualNetworks/[MASKED]/subnets/tf-aks-sub-northeu-01"
        }
      ~ agent_pool_profile {
          - availability_zones  = [] -> null
            count               = 1
          + dns_prefix          = (known after apply)
            enable_auto_scaling = true
          ~ fqdn                = "[MASKED]" -> (known after apply)
            max_count           = 20
            max_pods            = 50
            min_count           = 1
          ~ name                = "workers" -> "cpularge" # forces replacement
          ~ node_taints         = [
              - "sku=workers:PreferNoSchedule",
              + "sku=cpularge:NoSchedule",
            ]
          ~ os_disk_size_gb     = 100 -> 200 # forces replacement
            os_type             = "Linux"
            type                = "VirtualMachineScaleSets"
          ~ vm_size             = "Standard_B4ms" -> "Standard_F8s_v2" # forces replacement
            vnet_subnet_id      = "/subscriptions/[MASKED]/resourceGroups/[MASKED]/providers/Microsoft.Network/virtualNetworks/[MASKED]/subnets/tf-aks-sub-northeu-01"
        }

        linux_profile {
            admin_username = "aks_admin"

            ssh_key {
                key_data = "ssh-rsa XYZ"
            }
        }

      ~ network_profile {
            dns_service_ip     = "10.0.0.2"
            docker_bridge_cidr = "172.17.0.1/16"
          ~ load_balancer_sku  = "Basic" -> "basic"
            network_plugin     = "azure"
            network_policy     = "calico"
          + pod_cidr           = (known after apply)
            service_cidr       = "10.0.0.0/16"
        }

        role_based_access_control {
            enabled = true

            azure_active_directory {
                client_app_id     = (sensitive value)
                server_app_id     = (sensitive value)
                server_app_secret = (sensitive value)
                tenant_id         = "[MASKED]"
            }
        }

        service_principal {
            client_id     = (sensitive value)
            client_secret = (sensitive value)
        }
    }
```

### Expected Behavior

Terraform should not detect any changes.

### Actual Behavior

Terraform detects changes in the agent_pools and attempts to re-create the AKS cluster.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### LINKED ISSUE #4830: azurerm_kubernetes_cluster with VirtualMachineScaleSets node pool reverts to min_count on subsequent apply
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.13
AzureRM 1.36.1

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "kubernetes_cluster" {
  name                = var.ClusterName
  location            = var.ClusterLocation
  resource_group_name = data.azurerm_resource_group.ResourceGroup.name
  dns_prefix          = var.ClusterName
  kubernetes_version  = var.KubernetesVersion
  node_resource_group = "MC_${data.azurerm_resource_group.ResourceGroup.name}_${var.ClusterName}_${var.ClusterLocation}"

  linux_profile {
    admin_username  = var.LinuxUserName
    ssh_key  {
      key_data = data.azurerm_key_vault_secret.ClusterSSHKey.value
    }       
  }

  agent_pool_profile {
    name            = var.AgentPool1Name
    enable_auto_scaling = "true"
    min_count       = var.AgentPool1MinCount
    max_count       = var.AgentPool1MaxCount
    vm_size         = var.AgentPool1VMSize
    os_type         = "Linux"
    os_disk_size_gb = 30
    vnet_subnet_id  = azurerm_subnet.ClusterSubnet.id
    type            = "VirtualMachineScaleSets"
  }

  agent_pool_profile {
    name            = var.AgentPool2Name
    enable_auto_scaling = "true"
    min_count       = var.AgentPool2MinCount
    max_count       = var.AgentPool2MaxCount
    vm_size         = var.AgentPool2VMSize
    os_type         = "Linux"
    os_disk_size_gb = 30
    vnet_subnet_id  = azurerm_subnet.ClusterSubnet.id
    type            = "VirtualMachineScaleSets"
  }

  service_principal {
    client_id     = data.azurerm_key_vault_secret.ServicePrincipalID.value
    client_secret = data.azurerm_key_vault_secret.ServicePrincipalSecret.value
  }

  addon_profile {
    oms_agent {
      enabled                    = true
      log_analytics_workspace_id = data.azurerm_log_analytics_workspace.LogAnalyticsWorkspace.id
    }
  }

  network_profile {
    network_plugin      = "azure"
    docker_bridge_cidr  = var.DockerBridgeCIDR
    service_cidr        = var.ServiceCIDR 
    dns_service_ip      = var.DNSServiceIP 
    load_balancer_sku   = "Standard"
  }

  role_based_access_control {
    enabled = true

    azure_active_directory {
      client_app_id     = data.azurerm_key_vault_secret.AADClientID.value
      server_app_id     = data.azurerm_key_vault_secret.AADServerID.value
      server_app_secret = data.azurerm_key_vault_secret.AADServerSecret.value
      tenant_id         = data.azurerm_key_vault_secret.TenantID.value
    }
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The cluster should see the node count being within the pool's expected range and leave it as is.

```hcl
agent_pool_profile {
            availability_zones  = []
            count               = 2
            enable_auto_scaling = true
            fqdn                = "$REDACTEDFQDN"
            max_count           = 2
            max_pods            = 30
            min_count           = 1
            name                = "clusterlarge"
            node_taints         = []
            os_disk_size_gb     = 30
            os_type             = "Linux"
            type                = "VirtualMachineScaleSets"
            vm_size             = "Standard_D4s_v3"
            vnet_subnet_id      = "$REDACTEDSUBNETID"
        }
```

### Actual Behavior

Terraform determines the pool count is greater than the min_count and reverts despite still being below the threshold of max_count

```hcl
agent_pool_profile {
            availability_zones  = []
          ~ count               = 2 -> 1
            enable_auto_scaling = true
            fqdn                = "$REDACTEDFQDN"
            max_count           = 2
            max_pods            = 30
            min_count           = 1
            name                = "clusterlarge"
            node_taints         = []
            os_disk_size_gb     = 30
            os_type             = "Linux"
            type                = "VirtualMachineScaleSets"
            vm_size             = "Standard_D4s_v3"
            vnet_subnet_id      = "$REDACTEDSUBNETID"
        }
```

### Steps to Reproduce

1. Create the cluster: `terraform apply`
2. Scale up the node pool within the threshold manually or automatically
3. Re-apply the template: `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by tombuildsstuff**
This PR introduces support for Conditional Updates for the `azurerm_kubernetes_cluster` resource - allowing users to use the `ignore_changes` functionality on the `lifecycle` block.

Since the resource was introduced there's been a breaking changes in the Azure Kubernetes Service API which requires that this resource behave differently - and there's another on the way:

* When multiple node pools are used the Primary needs to be specified within the main resource (and modified there) - secondaries are now modified using the separate Node Pools API.
* The default `type` for AKS Nodes is changing from `AvailabilitySet` to `VirtualMachineScaleSets` - as tracked in #4465

After spending a ton of time trying to reconcile the different AKS PR's (#4676, #4543, #4472 and #4256) this PR supersedes them by:

* introducing a new `default_node_pool` block which supersedes the `agent_pool_profile` block (which can then be removed in 2.0)
* requiring that additional node pools are managed via the `azurerm_kubernetes_cluster_node_pool` resource being tracked in #4046
* allowing partial/conditional updates to the AKS resource, so that Terraform's `ignore_changes` block can be used on fields / configuration updates are applied prior to kubernetes  updates

Whilst superseding PR's isn't ideal - introducing a replacement block with these changes allows this block to handle conditional updates from the start, rather than introducing a breaking behavioural change/waiting until 2.0.

Once this PR is merged, I'll rebase both #4046 (which adds support the `azurerm_kubernetes_cluster_node_pool` resource) and #4472 (which supports using Outbound IP's with a Standard Load Balancer) on top of this PR so that all of these changes can be shipped in the same release; and then open a separate PR which updates the examples to use the new `default_node_pool` block.

Fixes #3428
Fixes #3549
Fixes #3835
Fixes #3971
Fixes #4075
Fixes #4465
Fixes #4560
Fixes #4830

Supersedes #4256
Supersedes #4543
Supersedes #4676

~Waiting on https://github.com/Azure/azure-rest-api-specs/pull/7746~
~Waiting on https://github.com/Azure/azure-sdk-for-go/pull/6325 to be merged/released - at which point we'll upgrade the PR in another PR which should unblock this~

### CODE REVIEW

File: azurerm/internal/services/containers/kubernetes_nodepool.go [hunk 1]
```diff
@@ -0,0 +1,361 @@
...
+		OsType: containerservice.Linux,
+
+		//// TODO: support these in time
+		// OrchestratorVersion:    nil,
+		// ScaleSetEvictionPolicy: "",
+		// ScaleSetPriority:       "",
+	}
+
+	availabilityZonesRaw := raw["availability_zones"].([]interface{})
+	// TODO: can we remove the `if > 0` here?
```
Comment (mbfrahry) [inline azurerm/internal/services/containers/kubernetes_nodepool.go]: Can we or is this a question for later?

File: azurerm/resource_arm_kubernetes_cluster.go [hunk 2]
```diff
@@ -678,21 +592,47 @@ func resourceArmKubernetesClusterCreate(d *schema.ResourceData, meta interface{}
...
+
+	networkProfileRaw := d.Get("network_profile").([]interface{})
+	networkProfile := expandKubernetesClusterNetworkProfile(networkProfileRaw)
 
 	rbacRaw := d.Get("role_based_access_control").([]interface{})
 	rbacEnabled, azureADProfile := expandKubernetesClusterRoleBasedAccessControl(rbacRaw, tenantId)
 
+	// since the Create and Update use separate methods, there's no point extracting this out
+	servicePrincipalProfileRaw := d.Get("service_principal").([]interface{})
+	servicePrincipalProfileVal := servicePrincipalProfileRaw[0].(map[string]interface{})
```
Comment (mbfrahry) [inline azurerm/resource_arm_kubernetes_cluster.go]: Should we check for length > 0 and that it's not nil before casting this out?

File: azurerm/resource_arm_kubernetes_cluster.go [hunk 3]
```diff
@@ -1014,181 +1033,12 @@ func flattenKubernetesClusterAccessProfile(profile containerservice.ManagedClust
...
-
-func expandKubernetesClusterAgentPoolProfiles(d *schema.ResourceData) ([]containerservice.ManagedClusterAgentPoolProfile, error) {
-	configs := d.Get("agent_pool_profile").([]interface{})
-
+func expandKubernetesClusterAgentPoolProfiles(input []interface{}, isNewResource bool) ([]containerservice.ManagedClusterAgentPoolProfile, error) {
 	profiles := make([]containerservice.ManagedClusterAgentPoolProfile, 0)
-	for config_id := range configs {
-		config := configs[config_id].(map[string]interface{})
+
+	// TODO: fix this
```
Comment (mbfrahry) [inline azurerm/resource_arm_kubernetes_cluster.go]: Is this still something that needs fixed?

File: azurerm/resource_arm_kubernetes_cluster.go [hunk 4]
```diff
@@ -1340,14 +1190,12 @@ func flattenKubernetesClusterAgentPoolProfiles(profiles *[]containerservice.Mana
...
-	profiles := d.Get("linux_profile").([]interface{})
-
-	if len(profiles) == 0 {
+func expandKubernetesClusterLinuxProfile(input []interface{}) *containerservice.LinuxProfile {
+	if len(input) == 0 {
 		return nil
 	}
 
-	config := profiles[0].(map[string]interface{})
+	config := input[0].(map[string]interface{})
```
Comment (mbfrahry) [inline azurerm/resource_arm_kubernetes_cluster.go]: We should check that this isn't nil

File: azurerm/resource_arm_kubernetes_cluster.go [hunk 5]
```diff
@@ -1402,14 +1250,12 @@ func flattenKubernetesClusterLinuxProfile(profile *containerservice.LinuxProfile
...
-	profiles := d.Get("windows_profile").([]interface{})
-
-	if len(profiles) == 0 {
+func expandKubernetesClusterWindowsProfile(input []interface{}) *containerservice.ManagedClusterWindowsProfile {
+	if len(input) == 0 {
 		return nil
 	}
 
-	config := profiles[0].(map[string]interface{})
+	config := input[0].(map[string]interface{})
```
Comment (mbfrahry) [inline azurerm/resource_arm_kubernetes_cluster.go]: Nil check here

File: azurerm/resource_arm_kubernetes_cluster.go [hunk 6]
```diff
@@ -1446,13 +1292,12 @@ func flattenKubernetesClusterWindowsProfile(profile *containerservice.ManagedClu
...
-func expandKubernetesClusterNetworkProfile(d *schema.ResourceData) *containerservice.NetworkProfileType {
-	configs := d.Get("network_profile").([]interface{})
-	if len(configs) == 0 {
+func expandKubernetesClusterNetworkProfile(input []interface{}) *containerservice.NetworkProfileType {
+	if len(input) == 0 {
 		return nil
 	}
 
-	config := configs[0].(map[string]interface{})
+	config := input[0].(map[string]interface{})
```
Comment (mbfrahry) [inline azurerm/resource_arm_kubernetes_cluster.go]: Nil check here.

File: azurerm/resource_arm_kubernetes_cluster.go (hunk 2 above)
Comment (tombuildsstuff) [reply azurerm/resource_arm_kubernetes_cluster.go]: this is required - so fine for now - when this becomes optional in the future we can handle that then 👍

File: azurerm/resource_arm_kubernetes_cluster.go (hunk 3 above)
Comment (tombuildsstuff) [reply azurerm/resource_arm_kubernetes_cluster.go]: needs fixing - will push

File: azurerm/internal/services/containers/kubernetes_nodepool.go (hunk 1 above)
Comment (tombuildsstuff) [reply azurerm/internal/services/containers/kubernetes_nodepool.go]: it was a question whilst passing through - but in retrospect it looks like we can 👍

File: azurerm/internal/services/containers/kubernetes_nodepool.go [hunk 7]
```diff
@@ -0,0 +1,361 @@
...
+						string(containerservice.AvailabilitySet),
+						string(containerservice.VirtualMachineScaleSets),
+					}, false),
+				},
+
+				"vm_size": {
+					Type:     schema.TypeString,
+					Required: true,
+					ForceNew: true,
+					// TODO: can we remove this?
```
[the remark this answers is not in the document]
Comment (tombuildsstuff) [reply azurerm/internal/services/containers/kubernetes_nodepool.go]: looks like we can 👍

File: azurerm/resource_arm_kubernetes_cluster.go (hunk 4 above)
Comment (tombuildsstuff) [reply azurerm/resource_arm_kubernetes_cluster.go]: this should be fine - since it's valid for this to have no elements (so this should either be a concrete value or empty)

File: azurerm/resource_arm_kubernetes_cluster.go (hunk 6 above)
Comment (tombuildsstuff) [reply azurerm/resource_arm_kubernetes_cluster.go]: this is optional/computed - and the flatten handles making this an empty slice if nothing's configured - so this should be fine

File: azurerm/resource_arm_kubernetes_cluster.go (hunk 5 above)
Comment (tombuildsstuff) [reply azurerm/resource_arm_kubernetes_cluster.go]: same here - this should be fine 👍

File: azurerm/internal/services/containers/kubernetes_nodepool.go (hunk 1 above)
Comment (tombuildsstuff) [reply azurerm/internal/services/containers/kubernetes_nodepool.go]: >         Error: Error creating Managed Kubernetes Cluster "acctestaks191120080029703513" (Resource Group "acctestRG-191120080029703513"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="SLBRequiredForAvailabilityZone" Message="Standard Load Balancer is required for availability zone." Target="networkProfile.loadBalancerSku"

or not ¯\_(ツ)_/¯

**Comment by tombuildsstuff** [comment]
Tests pass:

Screenshot 2019-11-20 at 12 59 43

File: azurerm/resource_arm_kubernetes_cluster_auth_test.go [hunk 8]
```diff
@@ -0,0 +1,345 @@
...
+  name                = "acctestaks%d"
+  location            = azurerm_resource_group.test.location
+  resource_group_name = azurerm_resource_group.test.name
+  dns_prefix          = "acctestaks%d"
+
+  default_node_pool {
+    name           = "default"
+    node_count     = 1
+    vm_size        = "Standard_DS2_v2"
+    vnet_subnet_id = azurerm_subnet.test.id
```
Comment (artburkart) [inline azurerm/resource_arm_kubernetes_cluster_auth_test.go]: @tombuildsstuff – I was wondering, would it be worth surfacing the fact that the `vnet_subnet_id` on the `default_node_pool` is also the subnet that the entire cluster gets launched into?

```shell
az aks create -h | grep vnet-subnet -A1
    --vnet-subnet-id                          : The ID of a subnet in an existing VNet into which to
                                                deploy the cluster.
```

https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create

Comment (jluk) [reply azurerm/resource_arm_kubernetes_cluster_auth_test.go]: FWIW we plan to support assigning a separate subnet per agentpool, but haven't implemented it quite yet. Hence today the subnet property on additional agentpools doesn't do much yet.

Comment (artburkart) [reply azurerm/resource_arm_kubernetes_cluster_auth_test.go]: Oh interesting. I hadn't even considered that.

Comment (jluk) [reply azurerm/resource_arm_kubernetes_cluster_auth_test.go]: I agree with you surfacing that info is helpful, just want to make sure it's easily updated when that new func is available :)

Comment (tombuildsstuff) [reply azurerm/resource_arm_kubernetes_cluster_auth_test.go]: @jluk just to ensure I've got this right - from testing IIRC at this time all of the Subnet ID's need to be set to the same value for the meantime; rather than just being defined on the top level resource?

Comment (jluk) [reply azurerm/resource_arm_kubernetes_cluster_auth_test.go]: Correct today all of the subnetIds need to be the same.

Comment (jluk) [reply azurerm/resource_arm_kubernetes_cluster_auth_test.go]: When creating a new agent pool, if the subnetid is not provided, the default will be inferred from the primary node pool's subnetid. So you can either input the same id across all of them or not provide a value for it to be inferred, any other inputs will receive an error.

Comment (tombuildsstuff) [reply azurerm/resource_arm_kubernetes_cluster_auth_test.go]: @jluk thanks for confirming - will get that updated 👍

Comment (tombuildsstuff) [reply azurerm/resource_arm_kubernetes_cluster_auth_test.go]: PR: https://github.com/terraform-providers/terraform-provider-azurerm/pull/4946

**Comment by maarek** [comment]
@tombuildsstuff Should the data source for azurerm_kubernetes_cluster have been changed to represent this over agent_pool_profile as well? Is there a data source for the individual node pools as well?

**Comment by tombuildsstuff** [comment]
@maarek the Data Source intentionally still uses `agent_pool_profiles` since we didn't feel a separate data source for the individual node pools would be directly useful; that said we can add it if it is - mind opening a new issue if you're interested with a use-case? :)

**Comment by jmcshane** [comment]
Looks like @maarek has not submitted an issue, I'll write one up now.
