### PR TITLE
azurerm_public_ip: computed values now default to an empy string

### LINKED ISSUE #1234: azurerm_public_ip doesn't change from dynamic to static
_This issue was originally opened by @bernadinm as hashicorp/terraform#18045. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

When changing the azurerm_public_ip's public_ip_address_allocation from `dynamic` to `static` it fails to return a new IP. 

### Terraform Version

```
$ terraform -v
Terraform v0.11.7
+ provider.azurerm v1.4.0
```

### Terraform Configuration Files

```hcl
variable "azure_region" {
default = "West US"
}

resource "azurerm_public_ip" "frontend" {
  name                         = "frontend"
  location                     = "${var.azure_region}"
  resource_group_name          = "${azurerm_resource_group.testing.name}"
  public_ip_address_allocation = "dynamic"
}
output "voyager.default_ingress.ip" {
    value = "${azurerm_public_ip.frontend.ip_address}"
}

# Create a resource group
resource "azurerm_resource_group" "testing" {
  name     = "testing123"
  location = "${var.azure_region}"
}
```

### Debug Output

Error: Error running plan: 1 error(s) occurred:

* output.voyager.default_ingress.ip: Resource 'azurerm_public_ip.frontend' does not have attribute 'ip_address' for variable 'azurerm_public_ip.frontend.ip_address'

### Expected Behavior

An IP address should be returned after switching public_ip_address_allocation from `dynamic` to `static`. 

### Actual Behavior

It fails. 

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`
3. Observe failure
4. Change public_ip_address_allocation from `dynamic` to `static`
5. `terraform apply`
6. Observe failure as new IP address is not defined.

### PR DESCRIPTION
**Pull request by katbyte**
fixes #1234

### CODE REVIEW

File: azurerm/resource_arm_public_ip.go [hunk 1]
```diff
@@ -48,22 +49,27 @@ func resourceArmPublicIp() *schema.Resource {
 			"public_ip_address_allocation": {
 				Type:             schema.TypeString,
 				Required:         true,
-				ValidateFunc:     validatePublicIpAllocation,
+				ValidateFunc:     validation.StringInSlice([]string{"static", "dynamic"}, true),
```
Comment (tombuildsstuff) [inline azurerm/resource_arm_public_ip.go]: _minor_ I believe there's an Enum we can use for these values

Comment (katbyte) [reply azurerm/resource_arm_public_ip.go]: There is! thanks updated

**Comment by katbyte** [comment]
Tests pass: 
screen shot 2018-05-18 at 17 53 11
