### PR TITLE
Auto Scale: filter out the `$tags` tag

### LINKED ISSUE #1661: azurerm_autoscale_settings: tag "$type" is treated as changed on plan
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.azurerm v1.11.0
+ provider.random v1.3.1
+ provider.template v1.0.0

### Affected Resource(s)

* azurerm_autoscale_settings

### Terraform Configuration Files

```hcl
resource "azurerm_autoscale_setting" "app" {
  name                = "${var.label}DefaultSettings"
  resource_group_name = "${azurerm_resource_group.app.name}"
  location            = "${azurerm_resource_group.app.location}"
  target_resource_id  = "${azurerm_virtual_machine_scale_set.app.id}"

  tags {
    Cluster = "${var.label}"
    DC = "${terraform.workspace}"
  }
…
}
```

### Expected Behavior

After a clean apply, a re-plan should show no changes

### Actual Behavior

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.coffee_cluster.azurerm_autoscale_setting.app
      tags.$type: "Microsoft.WindowsAzure.Management.Common.Storage.CasePreservedDictionary, Microsoft.WindowsAzure.Management.Common.Storage" => ""
      tags.%:     "3" => "2"

  ~ module.discuss_cluster.azurerm_autoscale_setting.app
      tags.$type: "Microsoft.WindowsAzure.Management.Common.Storage.CasePreservedDictionary, Microsoft.WindowsAzure.Management.Common.Storage" => ""
      tags.%:     "3" => "2"

  ~ module.meta_cluster.azurerm_autoscale_setting.app
      tags.$type: "Microsoft.WindowsAzure.Management.Common.Storage.CasePreservedDictionary, Microsoft.WindowsAzure.Management.Common.Storage" => ""
      tags.%:     "3" => "2"

  ~ module.sushi_cluster.azurerm_autoscale_setting.app
      tags.$type: "Microsoft.WindowsAzure.Management.Common.Storage.CasePreservedDictionary, Microsoft.WindowsAzure.Management.Common.Storage" => ""
      tags.%:     "3" => "2"


Plan: 0 to add, 4 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform apply`
1. `terraform apply`

### References

* analogous to the following issue on a different resource: https://github.com/terraform-providers/terraform-provider-azurerm/issues/945

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Prior to this change (with the acctest fix contained in this PR):

```
$ acctests azurerm TestAccAzureRMAutoScaleSetting_basic
=== RUN   TestAccAzureRMAutoScaleSetting_basic
--- FAIL: TestAccAzureRMAutoScaleSetting_basic (400.30s)
	testing.go:513: Step 0 error: Check failed: Check 7/7 error: azurerm_autoscale_setting.test: Attribute 'tags.$type' found when not expected
FAIL
FAIL	github.com/terraform-providers/terraform-provider-azurerm/azurerm	400.721s
```

Now:

```
$ acctests azurerm TestAccAzureRMAutoScaleSetting_basic
=== RUN   TestAccAzureRMAutoScaleSetting_basic
--- PASS: TestAccAzureRMAutoScaleSetting_basic (399.98s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	400.321s
```

Fixes #1661

### CODE REVIEW

File: azurerm/resource_arm_autoscale_setting.go [hunk 1]
```diff
@@ -432,7 +432,9 @@ func resourceArmAutoScaleSettingRead(d *schema.ResourceData, meta interface{}) e
 		return fmt.Errorf("Error setting `notification` of Autoscale Setting %q (resource group %q): %+v", name, resourceGroup, err)
 	}
 
-	flattenAndSetTags(d, resp.Tags)
+	// Return a new tag map filtered by the specified tag names.
+	tagMap := filterTags(resp.Tags, "$type")
```
Comment (bflad) [inline azurerm/resource_arm_autoscale_setting.go]: Should this filtering be applied more globally? There seems to have been a few issues related to it across various resources.

**Comment by tombuildsstuff** [comment]
Tests pass:

screenshot 2018-08-15 at 13 59 15

File: azurerm/resource_arm_autoscale_setting.go (hunk 1 above)
Comment (tombuildsstuff) [reply azurerm/resource_arm_autoscale_setting.go]: Not necessarily unfortunately - this field's only applicable to certain API's (read: Monitor/App Insights) - such that it's potentially a valid key in other API's
