### PR TITLE
`azurerm_log_analytics_workspace` - validate SKU before creation

### LINKED ISSUE #30083: azurerm_log_analytics_workspace Standard and Premium sku no longer supported
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.11.2

### AzureRM Provider Version

4.30.0

### Affected Resource(s)/Data Source(s)

azurerm_log_analytics_workspace

### Terraform Configuration Files

```hcl
resource "azurerm_log_analytics_workspace" "this" {
  name = "name"
  resource_group_name = "resource_group_name"
  location = "East US"
  sku = "Standard"
  retention_in_days = 30
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Terraform applied successfully

### Actual Behaviour

Image

### Steps to Reproduce

1. terraform apply
2. ???
3. Profit

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by ziyeqf**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

create or update workspace to `free`, `standard` or `premium` sku is not allowed on API side, validate and throw the error earlier.
https://learn.microsoft.com/en-us/azure/azure-monitor/logs/cost-logs#free-trial-pricing-tier

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)
image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #30083

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/loganalytics/log_analytics_workspace_resource.go [hunk 1]
```diff
@@ -220,6 +221,13 @@ func resourceLogAnalyticsWorkspaceCustomDiff(_ context.Context, d *pluginsdk.Res
 		if !changingFromCapacityReservationToPerGB && !changingFromLACluster && !changingFromPerGBToCapacityReservation {
 			d.ForceNew("sku")
 		}
+
+		// Creation or update workspace to `free`, `standard` or `premium` sku is not allowed. Referrece: https://learn.microsoft.com/en-us/azure/azure-monitor/logs/cost-logs#standard-and-premium-pricing-tiers
+		if strings.EqualFold(new.(string), string(workspaces.WorkspaceSkuNameEnumFree)) ||
+			strings.EqualFold(new.(string), string(workspaces.WorkspaceSkuNameEnumStandard)) ||
+			strings.EqualFold(new.(string), string(workspaces.WorkspaceSkuNameEnumPremium)) {
+			return fmt.Errorf("Creation of workspace with `free`, `standard` or `premium` SKU is not allowed.")
+		}
```
Comment (sreallymatt) [inline internal/services/loganalytics/log_analytics_workspace_resource.go]: Since this resource doesn't support `Free` tier we can just check `Standard` and `Premium`. Also, could you update the error message and fix the typo in the comment?

```suggestion
		// Creation or update workspace to `standard` or `premium` SKU is not allowed. Reference:
		// https://learn.microsoft.com/en-us/azure/azure-monitor/logs/cost-logs#standard-and-premium-pricing-tiers
		if strings.EqualFold(new.(string), string(workspaces.WorkspaceSkuNameEnumStandard)) ||
			strings.EqualFold(new.(string), string(workspaces.WorkspaceSkuNameEnumPremium)) {
			return fmt.Errorf("creation of log analytics workspaces with `Standard` or `Premium` SKUs is no longer supported by Azure - see https://learn.microsoft.com/en-us/azure/azure-monitor/logs/cost-logs#standard-and-premium-pricing-tiers")
		}
```

File: internal/services/loganalytics/log_analytics_workspace_resource.go [hunk 2]
```diff
@@ -109,6 +109,7 @@ func resourceLogAnalyticsWorkspace() *pluginsdk.Resource {
 				Optional: true,
 				Computed: true,
 				ValidateFunc: validation.StringInSlice([]string{
+					// creation with `free`, `premium` and `standard` is not allowed on API side, keep these values for existing resources.
```
Comment (sreallymatt) [inline internal/services/loganalytics/log_analytics_workspace_resource.go]:
```suggestion
					// creation with `Premium` and `Standard` is not allowed on API side, keep these values for existing resources.
```

**Review by sreallymatt — APPROVED** [review]
Thanks @ziyeqf LGTM ✅
