### PR TITLE
azurerm_recovery_services_protected_vm can now be used when VM's are in a different resource group

### LINKED ISSUE #2215: Incorrect input generated for azurerm_recovery_services_protected_vm
> 
> The documentation was based on an draft version of the resource and is incorrect  As well as the field `backup_policy_id` should have been required. I have opened 2154 to fix it for the next release.

Yes though in our testing yesterday we did supply the following configuration (after looking into the code) and ran into the same errorcode:
```hcl 
resource "azurerm_recovery_services_protected_vm" "svc-rec-vm0" {
  resource_group_name = "${data.terraform_remote_state.bkp.out-bkp-rg-name}"
  recovery_vault_name = "${data.terraform_remote_state.bkp.out-bkp-rg-bkp014d}"
  source_vm_id        = "${azurerm_virtual_machine.svc-rg-vm0.id}"
  backup_policy_id  = "${data.terraform_remote_state.bkp.out-bkp-rg-bkp014d-pol[0]}"
}
```
This is a more complex configuration using remote state, but nevertheless it will run into the same error that @RobbieBinnie encountered.

Judging by the Azure JSON template parameters the following values should be needed:
```
recovery_vault_name = vaultName
resource_group_name = vaultRG
(vaultSubID)
policyName (calculated from backup_policy_id?)
(fabricName)
protectionContainers (which I suppose is a calculated value from source_vm_id or "sourceResourceIds"?)
"IaasVMContainer;iaasvmcontainerv2;(VM Resource Group);(VM Name)"
protectedItems (see above?)
"vm;iaasvmcontainerv2;(VM Resource Group);(VM Name)"
source_vm_id = sourceResourceIds
```

Note in my configuration the VM is not in the same resource group as the backup vault.
Which may produce errors which may not have been apparent in testing if the VM and the backup vault are in the same resource group.

EDIT: We just ran a test building a VM in the same resource group, which works fine, but using a different resource group will fail with what I predicted:

`* azurerm_recovery_services_protected_vm.svc-rec-vm1: Error creating/updating Recovery Service Protected VM "VM;iaasvmcontainerv2;"VaultRG";VMName" (Resource Group "VaultRG"): backup.ProtectedItemsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BMSUserErrorInvalidConfigureProtectionRequest" Message="Input for configure protection is not in proper format\r\nPlease ensure that container exists and other parameters are in valid format" `

So the value provided to either "protectionContainers" or "protectedItems" or both is the wrong one.

_Originally posted by @AndreasMWalter in https://github.com/terraform-providers/terraform-provider-azurerm/issues/2143#issuecomment-432960306_

### PR DESCRIPTION
**Pull request by katbyte**
Fixes #2215

### CODE REVIEW

**Comment by katbyte** [comment]
Tests pass:

```
==> Fixing source code with gofmt...
gofmt -s -w ./azurerm
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./azurerm -v -test.run=TestAccAzureRMRecoveryServicesProtectedVm -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccAzureRMRecoveryServicesProtectedVm_basic
=== PAUSE TestAccAzureRMRecoveryServicesProtectedVm_basic
=== RUN   TestAccAzureRMRecoveryServicesProtectedVm_separateResourceGroups
--- PASS: TestAccAzureRMRecoveryServicesProtectedVm_separateResourceGroups (688.47s)
=== CONT  TestAccAzureRMRecoveryServicesProtectedVm_basic
--- PASS: TestAccAzureRMRecoveryServicesProtectedVm_basic (669.43s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	1358.356s
```

File: azurerm/resource_arm_recovery_services_protected_vm_test.go [hunk 1]
```diff
@@ -259,3 +297,51 @@ resource "azurerm_recovery_services_protected_vm" "test" {
 
 `, testAccAzureRMRecoveryServicesProtectedVm_base(rInt, location))
 }
+
+func testAbcAzureRMRecoveryServicesProtectedVm_additionalVault(rInt int, location string) string {
```
Comment (tombuildsstuff) [inline azurerm/resource_arm_recovery_services_protected_vm_test.go]: Abc?

File: azurerm/resource_arm_recovery_services_protected_vm_test.go [hunk 2]
```diff
@@ -259,3 +297,51 @@ resource "azurerm_recovery_services_protected_vm" "test" {
...
+
+  retention_daily = {
+    count = 10
+  }
+}
+
+`, testAccAzureRMRecoveryServicesProtectedVm_base(rInt, location), rInt, location)
+}
+
+func testAbcAzureRMRecoveryServicesProtectedVm_separateResourceGroups(rInt int, location string) string {
```
Comment (tombuildsstuff) [inline azurerm/resource_arm_recovery_services_protected_vm_test.go]: Abc?
