### PR TITLE
`azurerm_kubernetes_cluster_node_pool`: max_surge and max_unavailable should not be required  for spot nodes pools

### LINKED ISSUE #29318: Don't force replace spot node pools nor try to set max_surge when upgrade_settings is changed
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.117.1

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool

### Terraform Configuration Files

```hcl
# We have made this workaround with the latest addition to being "ignore_changes = [upgrade_settings]" since upgrading the module past 3.106.0

resource "azurerm_kubernetes_cluster_node_pool" "nodepool" {
  dynamic "upgrade_settings" {
    for_each = var.priority != "Spot" ? [1] : []
    content {
      max_surge = var.max_surge
      drain_timeout_in_minutes = 30
      node_soak_duration_in_minutes = 0
    }
  }
  lifecycle {
    ignore_changes = [upgrade_settings]
  }

  tags = merge({ NodeType = "${var.instance_type}" }, var.tags)
}
```

### Debug Output/Panic Output

```shell
# First output

Resource Group Name: "k8s-cluster-rg"
Managed Cluster Name: "k8s-cluster-aks"
Agent Pool Name: "np"): agentpools.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidParameter" Message="The value of parameter agentPoolProfile.upgrade.maxSurge is invalid. Error details: Spot pools can't set max surge. Please see https://aka.ms/aks-naming-rules for more details." Target="agentPoolProfile.upgrade.maxSurge"

  with module.node_pools["spot_np"].azurerm_kubernetes_cluster_node_pool.nodepool,
  on modules/kubernetes_node_pool/main.tf line 2, in resource "azurerm_kubernetes_cluster_node_pool" "nodepool":
   2: resource "azurerm_kubernetes_cluster_node_pool" "nodepool" {


# Second output

 Error: Missing required argument

  with module.node_pools["spot_np"].azurerm_kubernetes_cluster_node_pool.nodepool,
  on modules/kubernetes_node_pool/main.tf line 34, in resource "azurerm_kubernetes_cluster_node_pool" "nodepool":
  34:       max_surge                   = var.priority != "Spot" ? var.max_surge : null

The argument "upgrade_settings.0.max_surge" is required, but no definition
was found.

# Third output

      - upgrade_settings {
          - drain_timeout_in_minutes      = 96 -> null # forces replacement
          - node_soak_duration_in_minutes = 0 -> null
        }
```

### Expected Behaviour

Remove the requirement of max_surge being set if the ScaleSetPriority is "Spot" but still make it possible to edit the values of drainTimeoutInMinutes and nodeSoakDurationInMinutes since it's possible thous avoiding the force replacement

### Actual Behaviour

Apply fails if max_surge is set or unset and if other upgrade_settings is set the deployment is getting force replaced 

### Steps to Reproduce

1. Create a K8s cluster with a node pool with scale policy set to "Spot" before with the provider version before 3.106.0
2. Upgrade the provider past 3.106.0
3. Run plan & apply

### Important Factoids

_No response_

### References

This regression was introduced with [#26137 ](https://github.com/hashicorp/terraform-provider-azurerm/pull/26137)

### PR DESCRIPTION
**Pull request by Kiliandeca**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

For regular nodes at least one of `max_surge` or `max_unavailable` must be specified but for Spot nodes theses properties are not supported and if you try to set them you'll get the followings errors:

```
│ Agent Pool Name: "foobar"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with response: {
│   "code": "InvalidParameter",
│   "details": null,
│   "message": "The value of parameter agentPoolProfile.upgradeSettings.maxUnavailable is invalid. Error details: Spot pools can't set maxUnavailable.",
│   "subcode": "",
│   "target": "agentPoolProfile.upgradeSettings.maxUnavailable"
│  }
│ 
```

```
│ Agent Pool Name: "foobar"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with response: {
│   "code": "InvalidParameter",
│   "details": null,
│   "message": "The value of parameter agentPoolProfile.upgradeSettings.maxSurge is invalid. Error details: Spot pools can't set max surge.",
│   "subcode": "",
│   "target": "agentPoolProfile.upgradeSettings.maxSurge"
│  }
│ 
```

The others `upgrade_settings` properties are supported for Spot nodes so the provider should support that. Previously I used this workaround https://github.com/hashicorp/terraform-provider-azurerm/issues/26568#issuecomment-2336841255 of setting `max_surge` to an empty string but it no longer works since https://github.com/hashicorp/terraform-provider-azurerm/pull/30563 broke it.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

I created a new subscription to run the tests I added but couldn't get it to works. I tried multiple region for `ARM_TEST_LOCATION` like `eastus`, `westus` and `westeurope` but I got the same error about the VM size not available on all of them:
```
 "message": "The VM size of Standard_DS2_v2 is not allowed in your subscription in location 'eastus'. The available VM sizes are
```
This VM size is used in a lot of tests and I didn't want to mess up things unrelated to this PR so can you please guide me on what region I should use to run the tests or tell me if I need to do something special on my subcription. Are all the tests borken for everyone because this VM size is no longer available anywhere?

Update: I could run the tests by changing the VM size of all of them to make sure they works, I will create a proper issue for that as it's the this PR goal to fix that

```
TF_ACC=true go test -v -run "TestAccKubernetesClusterNodePool_spotWithMaxSurge|TestAccKubernetesClusterNodePool_spotWithMaxUnavailable|TestAccKubernetesClusterNodePool_upgradeSettingsWithoutMaxSurgeOrMaxUnavailable|TestAccKubernetesClusterNodePool_spotWithOtherUpgradeSettings|TestAccKubernetesClusterNodePool_upgradeSettingsMaxSurge" ./internal/services/containers/ -timeout=30m
```
image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-merging.md).

* `azurerm_kubernetes_cluster_node_pool`: max_surge and max_unavailable should not be required  for spot nodes pools

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)

Fixes #29318

## AI Assistance Disclosure

- [x] AI Assisted - This contribution was made by, or with the assistance of, AI/LLMs

I used an LLM for code suggestion and autocomplete in my IDE

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Comment by Kiliandeca** [comment]
I managed to get the relevants tests running, could someone have a look at this PR please, this is preventing us (and everyone that used the same workaround) from upgrading.

**Comment by Kiliandeca** [comment]
Hello @catriona-m, sorry for tagging you directly but since you were the reviewer of the PR https://github.com/hashicorp/terraform-provider-azurerm/pull/30563 that introduced the regression I thought this might be in your scope. Well, I'm not sure this should be truly classified as a regression, as it was more of a workaround. Anyway, any help would be greatly appreciated :pray:

For others facing the same issue, you can vote on the PR with a :+1: reaction so it can be prioritised.

**Comment by d-mankowski-synerise** [comment]
Honestly, this is `<insert a word describing disappointment and/or rage>`.

First, there is a critical bug in provider that, if not spotted, recreates an entire cluster because `max_surge` is not supported for spots (https://github.com/hashicorp/terraform-provider-azurerm/issues/26568#issuecomment-2336841255). But thankfully there was a workaround (found by community). Microsoft didn't bother to fix it.

And [this PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/30563/changes) made provider completely unusable for spot node pools - it requires to set one of parameters for spot node pool, that is not supported (and Azure API rejects request). Community provided fix 4 months ago, Microsoft don't care. Sad.

Thanks @Kiliandeca for the PR, hopefully someone will finally look at this.

File: internal/services/containers/kubernetes_cluster_node_pool_resource.go [hunk 1]
```diff
@@ -1368,20 +1380,40 @@ func expandAgentPoolKubeletConfig(input []interface{}) *agentpools.KubeletConfig
...
+	maxUnavailableRaw := v["max_unavailable"].(string)
+
+	if isSpot {
+		if maxSurgeRaw != "" {
+			return nil, fmt.Errorf("`max_surge` cannot be set when `priority` is set to `Spot`. Spot pools do not support `max_surge`")
+		}
+		if maxUnavailableRaw != "" {
+			return nil, fmt.Errorf("`max_unavailable` cannot be set when `priority` is set to `Spot`. Spot pools do not support `max_unavailable`")
+		}
 	}
```
Comment (catriona-m) [inline internal/services/containers/kubernetes_cluster_node_pool_resource.go]: Could we move this check to a CustomizeDiff? That would allow us to see the error message at plan time rather than apply

File: internal/services/containers/kubernetes_cluster_node_pool_resource.go [hunk 2]
```diff
@@ -1265,21 +1275,23 @@ func upgradeSettingsSchemaNodePoolResource() *pluginsdk.Schema {
...
 				"max_surge": {
-					Type:         pluginsdk.TypeString,
-					Optional:     true,
-					ValidateFunc: validation.StringIsNotEmpty,
-					ExactlyOneOf: []string{"upgrade_settings.0.max_surge", "upgrade_settings.0.max_unavailable"},
+					Type:          pluginsdk.TypeString,
+					Optional:      true,
+					ValidateFunc:  validation.StringIsNotEmpty,
+					ConflictsWith: []string{"upgrade_settings.0.max_unavailable"},
+					Description:   "The maximum number of nodes that can be created during upgrade. This cannot be set when `priority` is set to `Spot`.",
```
Comment (catriona-m) [inline internal/services/containers/kubernetes_cluster_node_pool_resource.go]: these descriptions aren't currently used so we can omit these

**Comment by Kiliandeca** [comment]
Thanks for reviewing this PR, I made the changes you requested and also ran the tests again. Let me know if you need anything else.

image

File: internal/services/containers/kubernetes_cluster_node_pool_resource.go [hunk 3]
```diff
@@ -1368,20 +1397,27 @@ func expandAgentPoolKubeletConfig(input []interface{}) *agentpools.KubeletConfig
...
+	if !isSpot {
+		if maxSurgeRaw != "" {
+			setting.MaxSurge = pointer.To(maxSurgeRaw)
+			setting.MaxUnavailable = pointer.To("0")
+		}
+		if maxUnavailableRaw != "" {
+			setting.MaxUnavailable = pointer.To(maxUnavailableRaw)
+			setting.MaxSurge = pointer.To("0")
+		}
 	}
```
Comment (catriona-m) [inline internal/services/containers/kubernetes_cluster_node_pool_resource.go]: now that we are preventing `max_surge` and `max_unavailable` from being set in the CustomizeDiff, we should be able to remove this check here

```suggestion

	maxSurgeRaw := v["max_surge"].(string)
	maxUnavailableRaw := v["max_unavailable"].(string)

		if maxSurgeRaw != "" {
			setting.MaxSurge = pointer.To(maxSurgeRaw)
			setting.MaxUnavailable = pointer.To("0")
		}
		if maxUnavailableRaw != "" {
			setting.MaxUnavailable = pointer.To(maxUnavailableRaw)
			setting.MaxSurge = pointer.To("0")
		}
```

Comment (Kiliandeca) [reply internal/services/containers/kubernetes_cluster_node_pool_resource.go]: Done :+1:

**Comment by Kiliandeca** [comment]
Sorry about the linter errors, it should be good now.
