### PR TITLE
`azurerm_virtual_network_gateway`: add support for `ErGwScale` in `sku`

### LINKED ISSUE #31327: `azurerm_virtual_network_gateway` not support SKU `ErGwScale`
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.12.2

### AzureRM Provider Version

4.55.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_network_gateway

### Terraform Configuration Files

```hcl
data "azurerm_subnet" "gw-subnet" {
  name                 = "GatewaySubnet"
  resource_group_name  = "my-rg-name"
  virtual_network_name = "my-vnet-name"
}

resource "azurerm_public_ip" "pip-transit" {
  name                 = "my-ip"
  resource_group_name  = "my-rg-name"
  location             = "my-location"
  sku                  = "Standard"
  sku_tier             = "Regional"
  ddos_protection_mode = "VirtualNetworkInherited"
  allocation_method    = "Static"
  ip_version           = "IPv4"
  zones                = ["1", "2", "3"]
}

resource "azurerm_virtual_network_gateway" "vng-transit" {
  name                = "my-gateway"
  location            = "my-location"
  resource_group_name = "my-rg-name"
  sku                 = "ErGwScale"
  type                = "ExpressRoute"
  active_active       = false
  vpn_type            = "PolicyBased"

  remote_vnet_traffic_enabled = false
  virtual_wan_traffic_enabled = false


  ip_configuration {
    name                          = "default"
    public_ip_address_id          = azurerm_public_ip.pip-transit.id
    private_ip_address_allocation = "Dynamic"
    subnet_id                     = data.azurerm_subnet.gw-subnet.id
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: expected sku to be one of ["Basic"], got ErGwScale
│
│   with azurerm_virtual_network_gateway.vng-transit,
│   on main.tf line 22, in resource "azurerm_virtual_network_gateway" "vng-transit":
│   22:   sku                 = var.vng_sku
│
╵
╷
│ Error: expected sku to be one of ["Basic" "Standard" "HighPerformance" "VpnGw1" "VpnGw2" "VpnGw3" "VpnGw1AZ" "VpnGw2AZ" "VpnGw3AZ"], got ErGwScale
│
│   with azurerm_virtual_network_gateway.vng-transit,
│   on main.tf line 22, in resource "azurerm_virtual_network_gateway" "vng-transit":
│   22:   sku                 = var.vng_sku
│
╵
╷
│ Error: expected sku to be one of ["VpnGw2" "VpnGw3" "VpnGw4" "VpnGw5" "VpnGw2AZ" "VpnGw3AZ" "VpnGw4AZ" "VpnGw5AZ"], got ErGwScale
│
│   with azurerm_virtual_network_gateway.vng-transit,
│   on main.tf line 22, in resource "azurerm_virtual_network_gateway" "vng-transit":
│   22:   sku                 = var.vng_sku
│
╵
╷
│ Error: expected sku to be one of ["Standard" "HighPerformance" "UltraPerformance" "ErGw1AZ" "ErGw2AZ" "ErGw3AZ"], got ErGwScale
│
│   with azurerm_virtual_network_gateway.vng-transit,
│   on main.tf line 22, in resource "azurerm_virtual_network_gateway" "vng-transit":
│   22:   sku                 = var.vng_sku
```

### Expected Behaviour

Terraform must create a scalable ExpressRoute gateway. See https://learn.microsoft.com/en-us/azure/expressroute/expressroute-howto-scalable-portal.

### Actual Behaviour

Teraform encountered an error, to validate the sku.

### Steps to Reproduce

terraform plan

### Important Factoids

_No response_

### References

https://learn.microsoft.com/en-us/azure/expressroute/expressroute-howto-scalable-portal

### PR DESCRIPTION
**Pull request by jiaweitao001**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Now new option `ErGwScale` is available in `sku`. This PR adds support for it in AzureRM.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [x] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

```
--- PASS: TestAccVirtualNetworkGateway_expressRouteErGwScale (1797.67s)
PASS
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-merging.md).

* `azurerm_virtual_network_gateway`: add support for `ErGwScale` in `sku`

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)

Fixes #31327 

## AI Assistance Disclosure

- [ ] AI Assisted - This contribution was made by, or with the assistance of, AI/LLMs

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/network/virtual_network_gateway_resource.go [hunk 1]
```diff
@@ -1549,6 +1549,7 @@ func validateVirtualNetworkGatewayExpressRouteSku() pluginsdk.SchemaValidateFunc
 		string(virtualnetworkgateways.VirtualNetworkGatewaySkuNameErGwOneAZ),
 		string(virtualnetworkgateways.VirtualNetworkGatewaySkuNameErGwTwoAZ),
 		string(virtualnetworkgateways.VirtualNetworkGatewaySkuNameErGwThreeAZ),
+		string(virtualnetworkgateways.VirtualNetworkGatewaySkuTierErGwScale),
```
Comment (liuwuliuyun) [inline internal/services/network/virtual_network_gateway_resource.go]: Could you help confirm that this is `VirtualNetworkGatewaySkuTierErGwScale` not `VirtualNetworkGatewaySkuNameErGwScale` ?

File: internal/services/network/virtual_network_gateway_resource_test.go [hunk 2]
```diff
@@ -309,6 +309,22 @@ func TestAccVirtualNetworkGateway_expressRoute(t *testing.T) {
...
+		{
+			Config: r.expressRouteErGwScale(data),
+			Check: acceptance.ComposeTestCheckFunc(
+				check.That(data.ResourceName).ExistsInAzure(r),
+				check.That(data.ResourceName).Key("type").HasValue("ExpressRoute"),
+				check.That(data.ResourceName).Key("sku").HasValue("ErGwScale"),
+				check.That(data.ResourceName).Key("bgp_settings.#").HasValue("0"),
+			),
+		},
+	})
```
Comment (liuwuliuyun) [inline internal/services/network/virtual_network_gateway_resource_test.go:326]: Shall we include data.ImportStep() here?

**Comment by ziyeqf** [comment]
LGTM with addressing the above comments, thanks!

File: internal/services/network/virtual_network_gateway_resource.go (hunk 1 above)
Comment (jiaweitao001) [reply internal/services/network/virtual_network_gateway_resource.go]: Good catch. The strings are the same, but yes, we should use "name" instead of "tier" here.

File: internal/services/network/virtual_network_gateway_resource_test.go (hunk 2 above)
Comment (jiaweitao001) [reply internal/services/network/virtual_network_gateway_resource_test.go:326]: Will fix.

**Comment by aneeshakella-microsoft** [comment]
Hi @jiaweitao001 , I am checking what is the progress for this PR. When will it be approved and merged?

**Review by sreallymatt — APPROVED** [review]
Thanks @jiaweitao001 LGTM ✅
