### PR TITLE
`azurerm_mssql_managed_instance` - adding `general_purpose_v2_enabled` (Support next-gen general purpose service tier)

### LINKED ISSUE #29236: azurerm_mssql_managed_instance support "Next-gen General Purpose (preview)"
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Hello - the "Next-gen General Purpose (preview)" has been out for a year now.  It is not a different SKU, but requires you to toggle an "Enable/Disable" toggle in the portal.  If this is toggled to enabled manually, then azurerm is unable to manage the instance.  It returns this error:

```
╷
│ Error: updating Managed Instance (Subscription: "123456"
│ Resource Group Name: "rg-xxxx-sql-devtest-01"
│ Managed Instance Name: "sqlmi-laces-devtest-01"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: GPTargetEditionAndUnspecifiedGPV2NotAllowedInUpdateOFGPV2MI: Combination of General Purpose target edition (sku.name/sku.tier parameters) and unspecified value for the isGeneralPurposeV2 parameter is not allowed in the update operation of General Purpose V2 Managed Instance.
│
│   with module.sql_managed_instance.azurerm_mssql_managed_instance.sqlmi,
│   on ..\..\modules\sql_managed_instance\main.tf line 1, in resource "azurerm_mssql_managed_instance" "sqlmi":
│    1: resource "azurerm_mssql_managed_instance" "sqlmi" {
│
│ updating Managed Instance (Subscription: "123456"
│ Resource Group Name: "rg-xxxx-sql-devtest-01"
│ Managed Instance Name: "sqlmi-xxxx-devtest-01"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: GPTargetEditionAndUnspecifiedGPV2NotAllowedInUpdateOFGPV2MI: Combination of General Purpose target edition
│ (sku.name/sku.tier parameters) and unspecified value for the isGeneralPurposeV2 parameter is not allowed in the update operation of General Purpose V2 Managed Instance.
╵
```

### New or Affected Resource(s)/Data Source(s)

azurerm_mssql_managed_instance

### Potential Terraform Configuration

```hcl
...
is_general_purpose_v2 = true
...
```

### References

_No response_

### PR DESCRIPTION
**Pull request by spencerr**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Adds support for the Next-Gen General Purpose service tier.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

Running entire test suite for mssql_managed_instance is prohibitively expensive. I have ran my test, and confirmed the mssql_managed_instance is created with the flag enabled/disabled.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_mssql_managed_instance` - support for the `is_general_purpose_v2` property [GH-29236]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #29236 

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Comment by prr19776** [comment]
Anyone can check whether this can be merged and released

**Comment by cosminsimionescu** [comment]
Is there any chanche this PR could be prioritised? This becoms a very critical item for our team. 

It is also a hard blocker for the teams that have opted to use the SQLMI Next Gen preview which could be managed via Terraform before it reached GA.

**Comment by cosminsimionescu** [comment]
I know comments here don`t make much sense, but is it possible to move this forward? 

Balancing out wether we wait for this or just migrate my SQLMI Instances across the environments to AZ API..., Next gen is out of preview for a while now, and a lot of people have opted in for the Preview which is now no longer possible to manage via azurerm

@WodansSon  @magodo

File: internal/services/mssqlmanagedinstance/mssql_managed_instance_data_source.go [hunk 1]
```diff
@@ -102,6 +103,11 @@ func (d MsSqlManagedInstanceDataSource) Attributes() map[string]*pluginsdk.Schem
 
 		"identity": commonschema.SystemOrUserAssignedIdentityComputed(),
 
+		"is_general_purpose_v2": {
```
Comment (sreallymatt) [inline internal/services/mssqlmanagedinstance/mssql_managed_instance_data_source.go]: For booleans we use the `*_enabled` naming pattern ([ref](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/reference-naming.md#boolean-property-naming-conventions)), could you update this and the property in the resource to `general_purpose_v2_enabled`


```suggestion
		"general_purpose_v2_enabled": {
```

File: internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go [hunk 2]
```diff
@@ -256,6 +257,12 @@ func (r MsSqlManagedInstanceResource) Arguments() map[string]*pluginsdk.Schema {
 
 		"identity": commonschema.SystemAssignedUserAssignedIdentityOptional(),
 
+		"is_general_purpose_v2": {
+			Type:     schema.TypeBool,
+			Optional: true,
+			Default:  false,
+		},
```
Comment (sreallymatt) [inline internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go]: Given this is specifically for the general purpose SKUs (`GP_*`), we should validate that a user isn't setting this to `true` when using a business critical SKU (`BC_*`). This can be done using a `CustomizeDiff` function.

If you're unfamiliar with CustomizeDiff funcs and would prefer for me to add one please let me know!

File: internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go [hunk 3]
```diff
@@ -474,6 +481,7 @@ func (r MsSqlManagedInstanceResource) Create() sdk.ResourceFunc {
 					Administrators:       expandMsSqlManagedInstanceExternalAdministrators(model.AzureActiveDirectoryAdministrator),
 					DatabaseFormat:       pointer.To(managedinstances.ManagedInstanceDatabaseFormat(model.DatabaseFormat)),
 					HybridSecondaryUsage: pointer.To(managedinstances.HybridSecondaryUsage(model.HybridSecondaryUsage)),
+					IsGeneralPurposeV2:   pointer.To(model.IsGeneralPurposeV2),
```
Comment (sreallymatt) [inline internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go]: This is problematic when using a business critical (`BC_*`) SKU as the API expects `isGeneralPurposeV2` to not be set at all rather than being set to `true`/`false`

File: internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go [hunk 4]
```diff
@@ -688,6 +696,10 @@ func (r MsSqlManagedInstanceResource) Update() sdk.ResourceFunc {
 				props.HybridSecondaryUsage = pointer.To(managedinstances.HybridSecondaryUsage(state.HybridSecondaryUsage))
 			}
 
+			if metadata.ResourceData.HasChange("is_general_purpose_v2") {
+				props.IsGeneralPurposeV2 = pointer.To(state.IsGeneralPurposeV2)
```
Comment (sreallymatt) [inline internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go]: This is problematic when updating from a GP SKU to a BC SKU the API responds with an error as it expects `isGeneralPurposeV2` to not be set at all.

We're going to have the check the SKU and conditionally set this property to `nil` based on the SKU.

Error for reference:
```
BCTargetEditionAndSpecifiedGPV2ParamNotAllowedInCreateUpdateOfMI: Combination of Business Critical target edition (sku.name/sku.tier parameters) with a specified isGeneralPurposeV2 parameter is not allowed in the create/update operation.
```

**Review by sreallymatt — DISMISSED** [review]
Thanks for opening this PR @spencerr, apologies for the delayed review - I've left some comments inline that will need to be resolved before this can be merged.

**Review by katbyte — DISMISSED** [review]
LGTM ✏️

**Review by mstroob — APPROVED** [review]
LGTM
