### PR TITLE
`azurerm_postgres_database` allow `-`s in database collation

### LINKED ISSUE #4447: azurerm_postgresql_database.testdb: Code="InternalServerError" while destroying
### Terraform (and AzureRM Provider) Version
Terraform -v = 0.11.8
azurerm: version = "~> 1.30"

### Affected Resource(s)

* `azurerm_postgresql_database`

### Terraform Configuration Files

`{
  "resource" : {
    "azurerm_postgresql_server" : {
      "pgserver" : {
        "ssl_enforcement" : "Enabled",
        "administrator_login" : "${var.serveruser}",
        "administrator_login_password" : "${var.serverpassword}",
        "name" : "${var.pgservers[2]}",
        "storage_profile" : {
          "storage_mb" : "${var.storage_mb}",
          "backup_retention_days" : "${var.backup_retention_days}",
          "geo_redundant_backup" : "${var.geo_redundant_backup}"
        },
        "resource_group_name" : "${var.rgName}",
        "location" : "${var.location}",
        "sku" : {
          "family" : "${var.skufamily}",
          "name" : "${var.skuname}",
          "capacity" : "${var.skucapacity}",
          "tier" : "${var.skutier}"
        },
        "version" : "${var.pgversion}"
      }
    }
  }
}`

`{
  "resource" : {
    "azurerm_postgresql_database" : {
      "testdb" : {
        "charset" : "UTF8",
        "server_name" : "${azurerm_postgresql_server.pgserver.name}",
        "name" : "${var.pgDBs[2]}",
        "resource_group_name" : "${var.resource_group_name}",
        "collation" : "en_US"
      }
    }
  }
}`

### Expected Behavior

It should destroy the resources from Azure

### Actual Behavior

 Error: Error applying plan:
1 error(s) occurred:
* azurerm_postgresql_database.testdb (destroy): 1 error(s) occurred:
* azurerm_postgresql_database.testdb: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '5d3cfe7f-d576-4046-a48e-3f587064ed13'"
Terraform does not automatically rollback in the face of errors.

### Steps to Reproduce

1. `terraform apply`

2. `terraform destroy`

### PR DESCRIPTION
**Pull request by NickMetz**
According to feedback from Azure Support we should use hyphens instead of underscore if we create databases in azure postgresql. This PR adress issue #4447  

**Changes:**
- add - to database collation validation
- adjust validation test
- emove hyphen underscore rewrite

Fixes #4447

### CODE REVIEW

File: azurerm/helpers/validate/database.go [hunk 1]
```diff
@@ -12,7 +12,7 @@ func DatabaseCollation(i interface{}, k string) (warnings []string, errors []err
 		return
 	}
 
-	matched, _ := regexp.MatchString(`^[A-Za-z0-9_. ]+$`, v)
+	matched, _ := regexp.MatchString(`^[-A-Za-z0-9_. ]+$`, v)
 
 	if !matched {
 		errors = append(errors, fmt.Errorf("%s contains invalid characters, only underscores are supported, got %s", k, v))
```
Comment (katbyte) [inline azurerm/helpers/validate/database.go]: could we update this message?

Comment (NickMetz) [reply azurerm/helpers/validate/database.go]: Hi @katbyte,
thanks for your comment, error message is updated in new commit.

**Comment by NickMetz** [comment]
> Hi @NickMetz,
> 
> Thank you for this fix, in addition to the minor comment i've left inline could you add an acceptance test with a - in it to verify that it'll work with the api? thanks!

Hi @katbyte,
there was already an test with hyphen in database collation, but it was expected to cause an error. This behavior was changed. However it makes sense to have an test with failure, that for i have added an test "en@US" which is expected to fail.

**Comment by tombuildsstuff** [comment]
Tests pass:

Screenshot 2019-11-18 at 11 37 17
