### PR TITLE
CDN endpoint: Test for Premium_Verizon, optional values fix

### LINKED ISSUE #9895: Error 400 creating Azure Premium CDN endpoint
Sorry to bring the bad news but it seems there is another issue:

```
cdn.EndpointsClient#Create: Failure sending request: 
StatusCode=400 -- Original Error: Code="BadRequest" 
Message="We couldn’t configure QueryStringCachingBehavior, IsCompressionEnabled, ContentTypesToCompress, GeoFilters and DeliveryPolicy for premium profile endpoints. 
You’ll need to manage these endpoints in the supplemental portal."
```

The terraform provider seems to add the QueryStringCachingBehavior and ContentTypesToCompress by default like IsCompressionEnabled was before the PR.

eg:
```tf
resource "azurerm_cdn_endpoint" "cdn_endpoint" {
  name                          = "cdne${local.formatted_name}"
  profile_name                  = var.cdn_profile_name
  location                      = "global"
  resource_group_name           = var.resource_group_name
  origin_path                   = "/foo"
  origin_host_header            = var.originHostname
  is_https_allowed              = true
  is_http_allowed               = false
  origin {
    name      = "name"
    host_name = var.originHostname
  }
}
```

Seems like the tests of the provider are not really in Sync with API. Especially with the verizon API.

_Originally posted by @zekth in https://github.com/terraform-providers/terraform-provider-azurerm/issues/1109#issuecomment-726872100_

### PR DESCRIPTION
**Pull request by AliAllomani**
* Added test for "Premium_Verizon" SKU for azurerm_cdn_profile
* Assigning the parameters `EndpointProperties.ContentTypesToCompress`, `EndpointProperties.GeoFilters` only when values are set for `content_types_to_compress`, `geo_filter`.
* Assigning the parameter `EndpointProperties.DeliveryPolicy` only when SKU set to `Microsoft_Standard`.

 Fixes #9895

### CODE REVIEW

File: azurerm/internal/services/cdn/cdn_endpoint_resource.go [hunk 1]
```diff
@@ -453,14 +469,18 @@ func resourceCdnEndpointRead(d *schema.ResourceData, meta interface{}) error {
 			}
 		}
 
-		contentTypes := flattenAzureRMCdnEndpointContentTypes(props.ContentTypesToCompress)
-		if err := d.Set("content_types_to_compress", contentTypes); err != nil {
-			return fmt.Errorf("Error setting `content_types_to_compress`: %+v", err)
+		if _, ok := d.GetOk("content_types_to_compress"); ok {
```
Comment (katbyte) [inline azurerm/internal/services/cdn/cdn_endpoint_resource.go:472]: I don't think we need this check? or does the API return a default value?

File: azurerm/internal/services/cdn/cdn_endpoint_resource.go [hunk 2]
```diff
@@ -453,14 +469,18 @@ func resourceCdnEndpointRead(d *schema.ResourceData, meta interface{}) error {
...
+			contentTypes := flattenAzureRMCdnEndpointContentTypes(props.ContentTypesToCompress)
+			if err := d.Set("content_types_to_compress", contentTypes); err != nil {
+				return fmt.Errorf("Error setting `content_types_to_compress`: %+v", err)
+			}
 		}
 
-		geoFilters := flattenCdnEndpointGeoFilters(props.GeoFilters)
-		if err := d.Set("geo_filter", geoFilters); err != nil {
-			return fmt.Errorf("Error setting `geo_filter`: %+v", err)
+		if _, ok := d.GetOk("geo_filter"); ok {
```
Comment (katbyte) [inline azurerm/internal/services/cdn/cdn_endpoint_resource.go:479]: I don't think we need this check? or does the API return a default value?

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks for the PR @AliAllomani - Aside from two questions i have left inline this looks good! Once those are addressed this should be good to merge

**Comment by katbyte** [comment]
Additionally these tests are failing:
```
TestAccCdnEndpoint_deliveryRule
TestAccCdnEndpoint_globalDeliveryRule
TestAccCdnEndpoint_withGeoFilters

```

**Comment by AliAllomani** [comment]
Updated and passed acceptance tests

```
--- PASS: TestAccCdnEndpoint_withGeoFilters (470.36s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cdn	472.676s

--- PASS: TestAccCdnEndpoint_deliveryRule (633.33s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cdn	635.827s

--- PASS: TestAccCdnEndpoint_PremiumVerizon (708.57s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cdn	710.972s

--- PASS: TestAccCdnEndpoint_globalDeliveryRule (581.30s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cdn	586.211s
```

**Review by katbyte — APPROVED** [review]
Thanks @AliAllomani! - this LGTM  now 👍

**Comment by GlenColby** [comment]
@katbyte @AliAllomani 

This still isnt fixed. in 2.42 of the azureRM provider, version 0.13.5 of Terraform

`resource "azurerm_cdn_profile" "CDN" {
  name                                = "${var.PREFIX}${var.ENVIRONMENT}cdn${var.LOCATION}"
  resource_group_name      = var.GLOBAL_NAMESPACE
  location                            = var.LOCATION
  sku                                  = "Premium_Verizon"

  tags = {
    environment   = var.ENVIRONMENT
  }
}

resource "azurerm_cdn_endpoint" "UserManagementWebAppProdEndpoint" {
  name                            = "${var.PREFIX}${var.ENVIRONMENT}cdn${var.LOCATION}p"
  profile_name                 = azurerm_cdn_profile.CDN.name
  location                        = var.LOCATION
  resource_group_name  = var.GLOBAL_NAMESPACE
  is_http_allowed            = false
  
  origin {
    name      = "UserManagementProdCDN"
    host_name = replace(var.USERS_PROD_STATIC_WEBSITE,"/\\//","")
  }

  querystring_caching_behaviour = "NotSet"

  optimization_type  = "GeneralWebDelivery"
  

  origin_host_header = replace(var.USERS_PROD_STATIC_WEBSITE,"/\\//","")

  tags = {
    environment   = var.ENVIRONMENT
  }

  depends_on = [azurerm_cdn_profile.CDN]
}`

The above still throws the following error

"cdn.EndpointsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="We couldn’t configure QueryStringCachingBehavior, IsCompressionEnabled, ContentTypesToCompress, GeoFilters and DeliveryPolicy for premium profile endpoints. You’ll need to manage these endpoints in the supplemental portal."

This worked back in azureRM < 2.6.

The issue was listed here https://github.com/terraform-providers/terraform-provider-azurerm/issues/1109 and closed while people were still reporting it not working.
