### PR TITLE
azurerm_api_management_diagnostic add additional options, fix log_client_ip

### LINKED ISSUE #10322: azurerm_api_management_api_diagnostic.log_client_ip cannot be set to false
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
$ terraform -v
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/azurerm v2.44.0
```

### Affected Resource(s)

* `azurerm_api_management_api_diagnostic`
   * `log_client_ip` property

### Terraform Configuration Files

This uses a slightly modified `*_complete` acceptance test template found [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/64fca165dcb77fc42bc37f01055397736e404486/azurerm/internal/services/apimanagement/api_management_api_diagnostic_resource_test.go#L214). The complete acceptance test sets only a `true` value though. I found this while working on the enhancement to #9196

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG"
  location = "eastus"
}

resource "azurerm_application_insights" "test" {
  name                = "acctestappinsights"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  application_type    = "web"
}

resource "azurerm_api_management" "test" {
  name                = "acctestAM-slynickel"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  publisher_name      = "pub1"
  publisher_email     = "pub1@email.com"
  sku_name            = "Developer_1"
}

resource "azurerm_api_management_logger" "test" {
  name                = "acctestapimnglogger"
  api_management_name = azurerm_api_management.test.name
  resource_group_name = azurerm_resource_group.test.name

  application_insights {
    instrumentation_key = azurerm_application_insights.test.instrumentation_key
  }
}

resource "azurerm_api_management_api" "test" {
  name                = "acctestAMA"
  resource_group_name = azurerm_resource_group.test.name
  api_management_name = azurerm_api_management.test.name
  revision            = "1"
  display_name        = "Test API"
  path                = "test"
  protocols           = ["https"]

  import {
    content_format = "swagger-link-json"
    content_value  = "http://conferenceapi.azurewebsites.net/?format=json"
  }
}

resource "azurerm_api_management_api_diagnostic" "test" {
  identifier                = "applicationinsights"
  resource_group_name       = azurerm_resource_group.test.name
  api_management_name       = azurerm_api_management.test.name
  api_name                  = azurerm_api_management_api.test.name
  api_management_logger_id  = azurerm_api_management_logger.test.id
  sampling_percentage       = 1.0
  always_log_errors         = true
  log_client_ip             = false # ERROR HERE. If set to false you will enter perpetual apply loop as the property can't be set to true
  http_correlation_protocol = "W3C"
  verbosity                 = "verbose"

  backend_request {
    body_bytes     = 1
    headers_to_log = ["Host"]
  }

  backend_response {
    body_bytes     = 2
    headers_to_log = ["Content-Type"]
  }

  frontend_request {
    body_bytes     = 3
    headers_to_log = ["Accept"]
  }

  frontend_response {
    body_bytes     = 4
    headers_to_log = ["Content-Length"]
  }
}
```

### Debug Output

https://gist.github.com/slynickel/3a83111ba2d7123f6d3ca428bc84c3be

### Expected Behaviour

The `log_client_ip` setting should be set to false and not be in a perpetual apply loop. 

### Actual Behaviour

_opposite of expected behavior_ 

```
  # azurerm_api_management_api_diagnostic.test will be updated in-place
  ~ resource "azurerm_api_management_api_diagnostic" "test" {
        id                        = "/subscriptions/c7b490b6-6b3d-43d4-accb-590e69fe797f/resourceGroups/acctestRG/providers/Microsoft.ApiManagement/service/acctestAM-alynickel/diagnostics/applicationinsights"
      ~ log_client_ip             = true -> false
        # (8 unchanged attributes hidden)
```

### Steps to Reproduce

1. `terraform apply` _that's it_

### Important Factoids / References
N/A

### PR DESCRIPTION
**Pull request by slynickel**
_This looks larger then it is._

Fixes the remaining request in #9196 by adding additional options to `azurerm_api_management_diagnostic`. The heavy lifting was done by recent PRs for `azure_api_management_api_diagnostic` as the Go SDK uses the same struct for both diagnostics [apimangement.DiagnosticContract](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/apimanagement/mgmt/2019-12-01/apimanagement?utm_source=gopls#DiagnosticContract). This allowed the code to be completely reused.

Fixes #10322 which was found while testing this PR. Update to only checking if the input variable is nil as the `ok` value from `GetOk` does a Zero check which fails to work correctly with a Boolean variable. There could be some other ramifications of this I'm not aware of but I couldn't find a test case for this resource that was an issue.

**question (non-blocking):** the new options to `azurerm_api_management_diagnostic` reuse the functions `expandApiManagementApiDiagnosticHTTPMessageDiagnostic` and `flattenApiManagementApiDiagnosticHTTPMessageDiagnostic` should I rename these? I didn't because I wasn't sure it mattered.

### CODE REVIEW

**Comment by slynickel** [comment]
New acceptance test pass (as first submitter to this repository the README is out of date with how to run the acceptance tests). The `_complete` acceptance test validates #10322 is fixed.
```bash
~/go/src/github.com/terraform-providers/terraform-provider-azurerm(fix-9196-api_management_diagnostic)
$ TF_ACC=1 go test -v -timeout 120m -run '^(TestAccApiManagementDiagnostic_basic|TestAccApiManagementDiagnostic_update|TestAccApiManagementDiagnostic_requiresImport|TestAccApiManagementDiagnostic_complete)$' github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/apimanagement  -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccApiManagementDiagnostic_basic
=== PAUSE TestAccApiManagementDiagnostic_basic
=== RUN   TestAccApiManagementDiagnostic_update
=== PAUSE TestAccApiManagementDiagnostic_update
=== RUN   TestAccApiManagementDiagnostic_requiresImport
=== PAUSE TestAccApiManagementDiagnostic_requiresImport
=== RUN   TestAccApiManagementDiagnostic_complete
=== PAUSE TestAccApiManagementDiagnostic_complete
=== CONT  TestAccApiManagementDiagnostic_basic
=== CONT  TestAccApiManagementDiagnostic_complete
=== CONT  TestAccApiManagementDiagnostic_requiresImport
=== CONT  TestAccApiManagementDiagnostic_update
--- PASS: TestAccApiManagementDiagnostic_requiresImport (2276.90s)
--- PASS: TestAccApiManagementDiagnostic_complete (2370.21s)
--- PASS: TestAccApiManagementDiagnostic_basic (2385.37s)
--- PASS: TestAccApiManagementDiagnostic_update (2403.43s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/apimanagement       2403.466s
```

File: azurerm/internal/services/apimanagement/api_management_diagnostic_resource.go [hunk 1]
```diff
@@ -95,6 +144,70 @@ func resourceApiManagementDiagnosticCreateUpdate(d *schema.ResourceData, meta in
...
+
+	if verbosity, ok := d.GetOk("verbosity"); ok {
+		switch verbosity.(string) {
+		case string(apimanagement.Verbose):
+			parameters.Verbosity = apimanagement.Verbose
+		case string(apimanagement.Information):
+			parameters.Verbosity = apimanagement.Information
+		case string(apimanagement.Error):
+			parameters.Verbosity = apimanagement.Error
+		}
```
Comment (katbyte) [inline azurerm/internal/services/apimanagement/api_management_diagnostic_resource.go:168]: I think we can change this to
```suggestion
		parameters.Verbosity = apimanagement.Verbosity(verbosity.(string)) 
```

File: azurerm/internal/services/apimanagement/api_management_diagnostic_resource.go [hunk 2]
```diff
@@ -95,6 +144,70 @@ func resourceApiManagementDiagnosticCreateUpdate(d *schema.ResourceData, meta in
...
+
+	if httpCorrelationProtocol, ok := d.GetOk("http_correlation_protocol"); ok {
+		switch httpCorrelationProtocol.(string) {
+		case string(apimanagement.HTTPCorrelationProtocolNone):
+			parameters.HTTPCorrelationProtocol = apimanagement.HTTPCorrelationProtocolNone
+		case string(apimanagement.HTTPCorrelationProtocolLegacy):
+			parameters.HTTPCorrelationProtocol = apimanagement.HTTPCorrelationProtocolLegacy
+		case string(apimanagement.HTTPCorrelationProtocolW3C):
+			parameters.HTTPCorrelationProtocol = apimanagement.HTTPCorrelationProtocolW3C
+		}
```
Comment (katbyte) [inline azurerm/internal/services/apimanagement/api_management_diagnostic_resource.go:184]: and do the same conversion here instead of a switch

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @slynickel - overall this looks good, i've left two small comments and once they are addressed this should be good to merge 🙂

File: azurerm/internal/services/apimanagement/api_management_diagnostic_resource.go (hunk 1 above)
Comment (slynickel) [reply azurerm/internal/services/apimanagement/api_management_diagnostic_resource.go]: I've made the update here as well as in `api_management_api_diagnostic_resource.go` where this code was originally copied from.

File: azurerm/internal/services/apimanagement/api_management_diagnostic_resource.go (hunk 2 above)
Comment (slynickel) [reply azurerm/internal/services/apimanagement/api_management_diagnostic_resource.go]: Updated, also updated `api_management_api_diagnostic.go`

**Comment by slynickel** [comment]
@katbyte back to you. Thanks for the quick response time.

File: azurerm/internal/services/apimanagement/api_management_api_diagnostic_resource.go [hunk 3]
```diff
@@ -182,29 +182,16 @@ func resourceApiManagementApiDiagnosticCreateUpdate(d *schema.ResourceData, meta
...
-			parameters.Verbosity = apimanagement.Error
-		}
+		parameters.Verbosity = apimanagement.Verbosity(verbosity.(string))
 	}
 
-	if logClientIP, ok := d.GetOk("log_client_ip"); ok {
+	logClientIP, _ := d.GetOk("log_client_ip")
+	if logClientIP != nil {
 		parameters.LogClientIP = utils.Bool(logClientIP.(bool))
 	}
```
Comment (manicminer) [inline azurerm/internal/services/apimanagement/api_management_api_diagnostic_resource.go:191]: Hi @slynickel, many thanks for the PR.

Because this attribute is optional+computed, it would be best to use `GetOkExists()` which tells you if the attribute is configured, but bypasses the zero value check so you can detect an explicit false value.

```suggestion
	if logClientIP, exists := d.GetOkExists("log_client_ip"); exists {
		parameters.LogClientIP = utils.Bool(logClientIP.(bool))
	}
```

Comment (slynickel) [reply azurerm/internal/services/apimanagement/api_management_api_diagnostic_resource.go:191]: @manicminer Isn't that function being deprecated though? [ResourceData.GetOkayExist()](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/helper/schema#ResourceData.GetOkExists)

>GetOkExists can check if TypeBool attributes that are Optional with no Default value have been set.
>
>Deprecated: usage is discouraged due to undefined behaviors and may be removed in a future version of the SDK

My light review of the terraform-plugin-sdk is that some sections are pretty old, though the deprecation warning is within the last year.

Comment (manicminer) [reply azurerm/internal/services/apimanagement/api_management_api_diagnostic_resource.go:191]: @slynickel I checked with the team and although it's marked as deprecated in the SDK, in a context like this there's little alternative and it's ok to use it.

Comment (slynickel) [reply azurerm/internal/services/apimanagement/api_management_api_diagnostic_resource.go]: Updated.

Make sense, thanks for context.

Comment (slynickel) [reply azurerm/internal/services/apimanagement/api_management_api_diagnostic_resource.go]: @manicminer I'm assuming the failed golint check as a result of GetOkExist can be ignored?

Comment (manicminer) [reply azurerm/internal/services/apimanagement/api_management_api_diagnostic_resource.go]: @slynickel we can add a nolint comment to suppress that, i've pushed that whilst I run the acceptance tests

**Review by manicminer — APPROVED** [review]

**Comment by manicminer** [comment]
Test results

Screenshot 2021-01-29 at 15 22 33

**Comment by manicminer** [comment]
@slynickel Thanks again for the contribution :)
