### PR TITLE
azurerm_sql_database: deprecate `use_server_default`

### LINKED ISSUE #7215: terraform plan show state change without code change
### Terraform (and AzureRM Provider) Version

Terraform v0.12.26
+ provider.azuread v0.8.0
+ provider.azurerm v2.8.0
+ provider.random v2.2.1

### Affected Resource(s)
azurerm_sql_database

* `azurerm_sql_database`

### Terraform Configuration Files

see code [here](https://github.com/CharmanderJieniJieni/Terraform) 

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output
- log {
          - category = "AutomaticTuning" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }
      + log {
          + category = "AutomaticTuning"
          + enabled  = true

          + retention_policy {
              + enabled = true
            }
        }
      - log {
          - category = "Blocks" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }
      + log {
          + category = "Blocks"
          + enabled  = true

          + retention_policy {
              + enabled = true
            }
        }
      - log {
          - category = "DatabaseWaitStatistics" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }
      + log {
          + category = "DatabaseWaitStatistics"
          + enabled  = true

          + retention_policy {
              + enabled = true
            }
        }
      - log {
          - category = "Deadlocks" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }
      + log {
          + category = "Deadlocks"
          + enabled  = true

          + retention_policy {
              + enabled = true
            }
        }
      - log {
          - category = "DevOpsOperationsAudit" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "Errors" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }
      + log {
          + category = "Errors"
          + enabled  = true

          + retention_policy {
              + enabled = true
            }
        }
      - log {
          - category = "QueryStoreRuntimeStatistics" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }
      + log {
          + category = "QueryStoreRuntimeStatistics"
          + enabled  = true

          + retention_policy {
              + enabled = true
            }
        }
      - log {
          - category = "QueryStoreWaitStatistics" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }
      + log {
          + category = "QueryStoreWaitStatistics"
          + enabled  = true

          + retention_policy {
              + enabled = true
            }
        }
      - log {
          - category = "SQLInsights" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }
      + log {
          + category = "SQLInsights"
          + enabled  = true

          + retention_policy {
              + enabled = true
            }
        }
      - log {
          - category = "SQLSecurityAuditEvents" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "Timeouts" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }
      + log {
          + category = "Timeouts"
          + enabled  = true

          + retention_policy {
              + enabled = true
            }
        }

### Expected Behavior

nothing should be changed
### Actual Behavior

everytime we trigger terraform plan, the output shows up which indicates there is going to be listed changes, even there is no code change at all

### Steps to Reproduce

terraform plan

### References

* #0000

### PR DESCRIPTION
**Pull request by magodo**
Per this [comment](https://github.com/Azure/azure-rest-api-specs/issues/9762#issuecomment-751857677), the `useServerDefault` in Swagger (i.e. `use_server_default` in TF) is now deprecated and should be ignored.

This further fixes #7215, #4556.

### CODE REVIEW

**Comment by manicminer** [comment]
Hi @magodo, thanks for continuing to follow this. I agree this resolves #7215 but does it definitely close #4556 (noting [this comment](https://github.com/terraform-providers/terraform-provider-azurerm/issues/4556#issuecomment-543160762) about inability to change DTUs)?

**Comment by magodo** [comment]
@manicminer I mean the original issue in #4556 is about `use_server_default` and should be fixed by this PR. Regarding the other problem, I assume it should open another issue to track with?

File: azurerm/internal/services/sql/sql_database_resource.go [hunk 1]
```diff
@@ -316,6 +317,7 @@ func resourceSqlDatabase() *schema.Resource {
 								string(sql.SecurityAlertPolicyUseServerDefaultDisabled),
 								string(sql.SecurityAlertPolicyUseServerDefaultEnabled),
 							}, true),
+							Deprecated: "This field is non-functional and will be removed in version 3.0 of the Azure Provider",
```
Comment (katbyte) [inline azurerm/internal/services/sql/sql_database_resource.go:320]:
```suggestion
							Deprecated: "This field is now non-functional and thus will be removed in version 3.0 of the Azure Provider",
```

**Review by katbyte — APPROVED** [review]
Thanks @magodo - aside from 1 comment this LGTM 👍
