### PR TITLE
azurerm_bot_channel_directline: export extension_key_1 and extension_key_2

### LINKED ISSUE #30229: azurerm_bot_channel_directline: Missing site secrets and extension keys
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.12.0

### AzureRM Provider Version

4.37.0

### Affected Resource(s)/Data Source(s)

azurerm_bot_channel_directline

### Terraform Configuration Files

```hcl
resource "azurerm_bot_channel_directline" "bot" {
  bot_name            = "my-bot"
  location            = "westus2"
  resource_group_name = "my-bot"

  site {
    name    = "default"
    enabled = true
  }
}
```

### Debug Output/Panic Output

```shell
Stripped the keys.

2025-07-24T15:20:13.107+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-bot/providers/Microsoft.BotService/botServices/my-bot/channels/DirectLineChannel/listChannelWithKeys?api-version=2021-05-01-preview: 
2025-07-24T15:20:13.108+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: HTTP/2.0 200 OK
2025-07-24T15:20:13.108+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: Content-Length: 4212
2025-07-24T15:20:13.108+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: Cache-Control: no-cache
2025-07-24T15:20:13.109+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: Content-Type: application/json; charset=utf-8
2025-07-24T15:20:13.109+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: Date: Thu, 24 Jul 2025 12:20:12 GMT
2025-07-24T15:20:13.109+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: Etag: W/"3323e7efa5bdccc01c48f62872c048897/24/2025 12:20:12 PM"
2025-07-24T15:20:13.109+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: Expires: -1
2025-07-24T15:20:13.109+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: Pragma: no-cache
2025-07-24T15:20:13.109+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: Strict-Transport-Security: max-age=31536000; includeSubDomains
2025-07-24T15:20:13.109+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: Vary: Accept-Encoding
2025-07-24T15:20:13.109+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: X-Cache: CONFIG_NOCACHE
2025-07-24T15:20:13.109+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: X-Content-Type-Options: nosniff
2025-07-24T15:20:13.110+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: X-Ms-Correlation-Request-Id: 917a553d-d8a7-e56b-13a3-515e26c91a67
2025-07-24T15:20:13.110+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: X-Ms-Operation-Identifier: tenantId=1911c65c-893b-42f9-83fa-66c1b86fdf85,objectId=de877f58-f8b1-40bc-8eb7-58d868a38fae/israelcentral/ad69b35d-9504-420a-bfe3-69cd26063a78
2025-07-24T15:20:13.110+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: X-Ms-Ratelimit-Remaining-Subscription-Global-Writes: 2999
2025-07-24T15:20:13.110+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: X-Ms-Ratelimit-Remaining-Subscription-Writes: 199
2025-07-24T15:20:13.110+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: X-Ms-Request-Id: 9e28a457-0865-4cf0-a9fd-5190e9ae815d
2025-07-24T15:20:13.110+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: X-Ms-Routing-Request-Id: ISRAELCENTRAL:20250724T122012Z:37764a9f-78e1-4a83-895e-3bbc321a17a8
2025-07-24T15:20:13.110+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: X-Msedge-Ref: Ref A: DF1D0EAC9A6849D492465058570EB036 Ref B: TLV231050412034 Ref C: 2025-07-24T12:20:12Z
2025-07-24T15:20:13.111+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe
2025-07-24T15:20:13.111+0300 [DEBUG] provider.terraform-provider-azurerm_v4.37.0_x5.exe: {"resource":{"properties":{"sites":[{"siteId":"<site-id>","siteName":"default","key":"<site-id>.<key-1>","key2":"<site-id>.<key-2>","isEnabled":true,"isV1Enabled":true,"isV3Enabled":true,"isSecureSiteEnabled":false,"isBlockUserUploadEnabled":false,"trustedOrigins":[],"isTokenEnabled":false}],"extensionKey1":"<ext-id>.<ext-key-1>","extensionKey2":"<ext-id>.<ext-key-2>","isEnabled":true},"etag":"W/\"3323e7efa5bdccc01c48f62872c048897/24/2025 12:20:12 PM\"","channelName":"DirectLineChannel","location":"global"},"setting":{"extensionKey1":"<ext-id>.<ext-key-1>","extensionKey2":"<ext-id>.<ext-key-2>","sites":[{"siteId":"<site-id>","siteName":"default","key":"<site-id>.<key-1>","key2":"<site-id>.<key-2>","isEnabled":true,"isV1Enabled":true,"isV3Enabled":true,"isWebchatPreviewEnabled":false,"isSecureSiteEnabled":false,"isBlockUserUploadEnabled":false,"trustedOrigins":[],"isTokenEnabled":false,"eTag":"\"de00c501-0000-0d00-0000-6880f8aa0000\""}],"channelId":"directline","channelDisplayName":"Direct Line","botId":"my-bot","botIconUrl":"https://docs.botframework.com/static/devportal/client/images/bot-framework-default.png","isEnabled":true,"disableLocalAuth":false},"id":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-bot/providers/Microsoft.BotService/botServices/my-bot/channels/DirectLineChannel","location":"global","properties":{"properties":{"DirectLineEmbedCode":null,"sites":[{"siteId":"<site-id>","siteName":"default","key":"<site-id>.<key-1>","key2":"<site-id>.<key-2>","isEnabled":true,"isV1Enabled":true,"isV3Enabled":true,"isDetailedLoggingEnabled":null,"isNoStorageEnabled":null,"isEndpointParametersEnabled":null,"isSecureSiteEnabled":false,"isBlockUserUploadEnabled":false,"trustedOrigins":[],"appId":null,"tenantId":null,"isTokenEnabled":false}],"extensionKey1":"<ext-id>.<ext-key-1>","extensionKey2":"<ext-id>.<ext-key-2>","isEnabled":true},"etag":"W/\"3323e7efa5bdccc01c48f62872c048897/24/2025 12:20:12 PM\"","channelName":"DirectLineChannel","location":"global"},"provisioningState":"Accepted","entityTag":"W/\"3323e7efa5bdccc01c48f62872c048897/24/2025 12:20:12 PM\"","changedTime":"0001-01-01T00:00:00Z","zones":[]}
```

### Expected Behaviour

Reboot of #8248. All the properties are available in the SDK, verified by enabling debug log. Please add site keys and extension keys.

Thanks!

### Actual Behaviour

_No response_

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by orgads**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Export Directline App Service Extension keys.

## PR Checklist

- [X] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [X] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [X] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [X] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [X] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [X] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [X] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [X] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [X] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [X] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #30229

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Comment by orgads** [comment]
ping @WodansSon @magodo @sreallymatt

**Comment by wyattfry** [comment]
Hi @orgads , thanks for the PR. Could you add the passing test results to the PR description?

**Comment by orgads** [comment]
I didn't run the acceptance tests. I don't want to pollute our corporate subscription. Don't they run in Github actions?

File: internal/services/bot/bot_channel_directline_resource.go [hunk 1]
```diff
@@ -133,6 +133,18 @@ func resourceBotChannelDirectline() *pluginsdk.Resource {
...
 				},
 			},
+
+			"extension_key1": {
+				Type:      pluginsdk.TypeString,
+				Computed:  true,
+				Sensitive: true,
+			},
+
+			"extension_key2": {
```
Comment (jackofallops) [inline internal/services/bot/bot_channel_directline_resource.go]: as a style, we use `_1` for property names:
```suggestion
			"extension_key_1": {
				Type:      pluginsdk.TypeString,
				Computed:  true,
				Sensitive: true,
			},

			"extension_key_2": {
```

File: internal/services/bot/bot_channel_directline_resource_test.go [hunk 2]
```diff
@@ -28,6 +28,8 @@ func TestAccBotChannelDirectline_basic(t *testing.T) {
 			Config: r.basicConfig(data),
 			Check: acceptance.ComposeTestCheckFunc(
 				check.That(data.ResourceName).ExistsInAzure(r),
+				check.That(data.ResourceName).Key("extension_key1").Exists(),
+				check.That(data.ResourceName).Key("extension_key2").Exists(),
```
Comment (jackofallops) [inline internal/services/bot/bot_channel_directline_resource_test.go]: Since this value is `Computed` it will always exist, even if it's empty.
```suggestion
```

File: internal/services/bot/bot_channel_directline_resource_test.go [hunk 3]
```diff
@@ -43,6 +45,8 @@ func TestAccBotChannelDirectline_complete(t *testing.T) {
 			Config: r.completeConfig(data),
 			Check: acceptance.ComposeTestCheckFunc(
 				check.That(data.ResourceName).ExistsInAzure(r),
+				check.That(data.ResourceName).Key("extension_key1").Exists(),
+				check.That(data.ResourceName).Key("extension_key2").Exists(),
```
Comment (jackofallops) [inline internal/services/bot/bot_channel_directline_resource_test.go]: As above
```suggestion
```

File: internal/services/bot/bot_channel_directline_resource_test.go [hunk 4]
```diff
@@ -58,20 +62,26 @@ func TestAccBotChannelDirectline_update(t *testing.T) {
 			Config: r.basicConfig(data),
 			Check: acceptance.ComposeTestCheckFunc(
 				check.That(data.ResourceName).ExistsInAzure(r),
+				check.That(data.ResourceName).Key("extension_key1").Exists(),
+				check.That(data.ResourceName).Key("extension_key2").Exists(),
```
Comment (jackofallops) [inline internal/services/bot/bot_channel_directline_resource_test.go]: As above
```suggestion
```

File: internal/services/bot/bot_channel_directline_resource_test.go [hunk 5]
```diff
@@ -58,20 +62,26 @@ func TestAccBotChannelDirectline_update(t *testing.T) {
...
 			),
 		},
 		data.ImportStep(),
 		{
 			Config: r.completeConfig(data),
 			Check: acceptance.ComposeTestCheckFunc(
 				check.That(data.ResourceName).ExistsInAzure(r),
+				check.That(data.ResourceName).Key("extension_key1").Exists(),
+				check.That(data.ResourceName).Key("extension_key2").Exists(),
```
Comment (jackofallops) [inline internal/services/bot/bot_channel_directline_resource_test.go]: As above
```suggestion
```

File: internal/services/bot/bot_channel_directline_resource_test.go [hunk 6]
```diff
@@ -58,20 +62,26 @@ func TestAccBotChannelDirectline_update(t *testing.T) {
...
 			),
 		},
 		data.ImportStep(),
 		{
 			Config: r.basicUpdate(data),
 			Check: acceptance.ComposeTestCheckFunc(
 				check.That(data.ResourceName).ExistsInAzure(r),
+				check.That(data.ResourceName).Key("extension_key1").Exists(),
+				check.That(data.ResourceName).Key("extension_key2").Exists(),
```
Comment (jackofallops) [inline internal/services/bot/bot_channel_directline_resource_test.go]: As above
```suggestion
```

File: website/docs/r/bot_channel_directline.html.markdown [hunk 7]
```diff
@@ -80,6 +80,10 @@ In addition to the Arguments listed above - the following Attributes are exporte
 
 * `id` - The Bot Channel ID.
 
+* `extension_key1` - (Optional) The first key for Directline App Service Extension.
+
+* `extension_key2` - (Optional) The second key for Directline App Service Extension.
```
Comment (jackofallops) [inline website/docs/r/bot_channel_directline.html.markdown]:
```suggestion
* `extension_key_1` - (Optional) The first key for Directline App Service Extension.

* `extension_key_2` - (Optional) The second key for Directline App Service Extension.
```

**Review by jackofallops — DISMISSED** [review]
Thanks @orgads - Just a few comments to take a look at if you could please, then we can get the tests run on our CI.

Thanks!

File: internal/services/bot/bot_channel_directline_resource.go (hunk 1 above)
Comment (orgads) [reply internal/services/bot/bot_channel_directline_resource.go]: Thank you. Done.

File: internal/services/bot/bot_channel_directline_resource_test.go (hunk 2 above)
Comment (orgads) [reply internal/services/bot/bot_channel_directline_resource_test.go]: Done

**Comment by orgads** [comment]
I ran the acceptance tests. All pass.
```
=== RUN   TestAccBotChannelDirectline_basic
=== PAUSE TestAccBotChannelDirectline_basic
=== RUN   TestAccBotChannelDirectline_complete
=== PAUSE TestAccBotChannelDirectline_complete
=== RUN   TestAccBotChannelDirectline_update
=== PAUSE TestAccBotChannelDirectline_update
=== CONT  TestAccBotChannelDirectline_basic
=== CONT  TestAccBotChannelDirectline_update
=== CONT  TestAccBotChannelDirectline_complete
--- PASS: TestAccBotChannelDirectline_complete (145.63s)
--- PASS: TestAccBotChannelDirectline_basic (150.41s)
--- PASS: TestAccBotChannelDirectline_update (298.96s)
PASS
```

**Comment by orgads** [comment]
@jackofallops Can you please review this?

**Comment by orgads** [comment]
Rebased. Can anyone PLEASE review this?

@jackofallops @sreallymatt @mbfrahry

**Comment by orgads** [comment]
@jackofallops @sreallymatt @mbfrahry @catriona-m

This is a tiny change, and I really need it to avoid ugly hacks. Please review it.

**Comment by orgads** [comment]
This is really frustrating. I spent hours fixing this and it has been ignored for nearly 3 months!

**Comment by orgads** [comment]
@jackofallops

**Comment by orgads** [comment]
@wyattfry @jackofallops anybody?

**Comment by orgads** [comment]
@catriona-m maybe?

**Comment by orgads** [comment]
@katbyte Can you maybe approve this? It's been hanging here for 6 months 😞

File: website/docs/r/bot_channel_directline.html.markdown [hunk 8]
```diff
@@ -80,6 +80,10 @@ In addition to the Arguments listed above - the following Attributes are exporte
 
 * `id` - The Bot Channel ID.
 
+* `extension_key_1` - (Optional) The first key for Directline App Service Extension.
+
+* `extension_key_2` - (Optional) The second key for Directline App Service Extension.
```
Comment (sreallymatt) [inline website/docs/r/bot_channel_directline.html.markdown]: Since these are computed values, `(Optional)` should be omitted

```suggestion
* `extension_key_1` - The first key for Directline App Service Extension.

* `extension_key_2` - The second key for Directline App Service Extension.
```

**Review by sreallymatt — CHANGES_REQUESTED** [review]
Apologies for the delay in reviewing this @orgads - I've left one minor comment on the documentation, once that's resolved this is good to go

File: website/docs/r/bot_channel_directline.html.markdown (hunk 8 above)
Comment (orgads) [reply website/docs/r/bot_channel_directline.html.markdown]: Done

**Review by sreallymatt — APPROVED** [review]
Thanks @orgads - LGTM ✅
