### PR TITLE
`postgresql_server`: `public_network_access_enabled` fixed on createReplica

### LINKED ISSUE #11346: azurerm_postgresql_server public_network_access_enabled setting on replica not respected on create
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/azurerm v2.55.0

Your version of Terraform is out of date! The latest version
is 0.14.10. You can update by downloading from https://www.terraform.io/downloads.html
```
### Affected Resource(s)

* `azurerm_postgresql_server`

### Terraform Configuration Files

Two files:

**postgres.tf**
```hcl
resource "azurerm_resource_group" "rg" {
  name     = var.resource_group
  location = var.main_location
}


resource "azurerm_postgresql_server" "postgres_master" {
  name                             = var.main_db_name
  location                         = var.main_location
  resource_group_name              = azurerm_resource_group.rg.name
  sku_name                         = var.sku_name
  administrator_login              = var.administrator_login
  administrator_login_password     = var.administrator_login_password
  version                          = var.postgres_version
  ssl_enforcement_enabled          = true
  ssl_minimal_tls_version_enforced = "TLS1_2"
  backup_retention_days            = var.retention_days
  geo_redundant_backup_enabled     = var.replicas_count != 0 ? true : false
  storage_mb                       = var.storage_mb
  public_network_access_enabled    = var.public_access_enabled
  auto_grow_enabled                = true

  lifecycle {
    ignore_changes = [
      # Autogrow is enabled
      storage_mb,
    ]
  }

}

resource "azurerm_postgresql_server" "postgres_standby" {
  count                            = var.replicas_count
  name                             = "${azurerm_postgresql_server.postgres_master.name}-r-${var.replicas_count}"
  location                         = var.replicas_location
  resource_group_name              = var.resource_group
  sku_name                         = var.sku_name
  version                          = var.postgres_version
  ssl_enforcement_enabled          = true
  ssl_minimal_tls_version_enforced = "TLS1_2"
  storage_mb                       = var.storage_mb
  public_network_access_enabled    = var.public_access_enabled
  create_mode                      = "Replica"
  creation_source_server_id        = azurerm_postgresql_server.postgres_master.id
  auto_grow_enabled                = true

  lifecycle {
    ignore_changes = [
      # Autogrow is enabled
      storage_mb,
    ]
  }

}
```
**var.tf**
```hcl
provider "azurerm" {
  features {}
}

variable "main_db_name" {
    default = "nfpgtst"
}

variable "main_location" {
    default = "westus2"
}
variable "resource_group" {
    default = "pg-test-diff-reg"
}
variable "sku_name" {
    default = "GP_Gen5_4"
}
variable "administrator_login" {
    default = "nilfranadmin"
}
variable "administrator_login_password" {
    default = "superSecure123$"
}
variable "postgres_version" {
    default = 9.6
}
variable "retention_days" {
    default = 7
}
variable "replicas_count" {
    default = 1
}
variable "storage_mb" {
    default = 5120
}
variable "replicas_location" {
    default = "eastus2"
}
variable "public_access_enabled" {
    default = false
    }

```
### Debug Output
https://gist.github.com/NillsF/be2b1d564fa20844f7e59a98c8dc8379

### Expected Behaviour
- Replica's `public_network_access_enabled` should be kept false when creating.
### Actual Behaviour
When creating a postgresSQL replica, the `public_network_access_enabled` setting is set to true. In the master, it is kept the right way.

However, the `terraform plan` shows TF trying to set it to false:
```
# azurerm_postgresql_server.postgres_standby[0] will be created
  + resource "azurerm_postgresql_server" "postgres_standby" {
      + administrator_login              = (known after apply)
      + auto_grow_enabled                = true
      + backup_retention_days            = (known after apply)
      + create_mode                      = "Replica"
      + creation_source_server_id        = (known after apply)
      + fqdn                             = (known after apply)
      + geo_redundant_backup_enabled     = (known after apply)
      + id                               = (known after apply)
      + location                         = "westus2"
      + name                             = "nfpgsame-r-1"
      + public_network_access_enabled    = false
      + resource_group_name              = "pg-test-same-reg"
      + sku_name                         = "GP_Gen5_2"
      + ssl_enforcement                  = (known after apply)
      + ssl_enforcement_enabled          = true
      + ssl_minimal_tls_version_enforced = "TLS1_2"
      + storage_mb                       = 5120
      + version                          = "9.6"

      + storage_profile {
          + auto_grow             = (known after apply)
          + backup_retention_days = (known after apply)
          + geo_redundant_backup  = (known after apply)
          + storage_mb            = (known after apply)
        }
    }

```

This can be resolved by running `terraform plan` and `terraform apply` a second time.

### Steps to Reproduce

1. Run `terraform plan` and `terraform apply` using the files provided above. This will result in the bad config
2. Running `terraform plan` and `terraform apply` again will update the configuration correctly.

### References

@aristosvo did some great work implementing locking in the following issue/PR:
* #11318
* #11330

### PR DESCRIPTION
**Pull request by aristosvo**
Fixes #11346

Upstream issue tracked here: https://github.com/Azure/azure-rest-api-specs/issues/14117

### CODE REVIEW

File: azurerm/internal/services/postgres/postgresql_server_resource.go [hunk 1]
```diff
@@ -609,6 +609,25 @@ func resourcePostgreSQLServerCreate(d *schema.ResourceData, meta interface{}) er
 		}
 	}
 
+	// Issue tracking REST API update: https://github.com/Azure/azure-rest-api-specs/issues/14117
```
Comment (katbyte) [inline azurerm/internal/services/postgres/postgresql_server_resource.go:612]: random commit to trigger CI
```suggestion
	// Issue tracking the REST API update failure: https://github.com/Azure/azure-rest-api-specs/issues/14117
```

**Review by katbyte — APPROVED** [review]
Thanks @aristosvo - this LGTM 🥳
