### PR TITLE
azurerm_firewall: supports `dns_setting`

### LINKED ISSUE #7743: FQDN for azurerm_firewall_network_rule_collection
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Firewall now supports setting FQDN rules (rules based on domain names) directly under the Network Rules. This is in addition to IP address rules and Service Tags.

It would be great to be able to set FQDN rules via Terraform.

For context, Network Security Groups accept strings like service tags in the destination address fields.

### New or Affected Resource(s)

- `azurerm_firewall_network_rule_collection`

### LINKED ISSUE #8312: Azure Firewall Network Rule collection Compatibility
https://www.terraform.io/docs/providers/azurerm/r/firewall_network_rule_collection.html

Whilst adhering to the requirements, I note that destination addresses in the rule block can be: "(Required) A list of destination IP addresses, IP ranges, or **FQDNs**."

When creating a rule with FQDN (so it can both utilise Firewall DNS (something I cant see how to configure in Terraform so had to do otherwise) and as a bi-product DNS Proxy) I get the error on compile:

image

`network.AzureFirewallsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="AzureFirewallRuleInvalidIpAddressOrRangeFormat" Message="AzureFirewallRule RULENAME001: Invalid IP address value or range or Service Tag destination.subdomain.com.`

Code being attempted to run:

`  rule {
    name = "RULENAME001"

    source_addresses = [
      "192.168.0.1",
      "192.168.0.2",
    ]

    destination_addresses = [
      "destination.subdomain.com",
    ]

    destination_ports = [
      "22",
    ]

    protocols = [
      "TCP"
    ]
  }`

Can I confirm that terraform does support Network Rules by FQDN and perhaps be given a steer on how best to get a rule with the below logic implemented in the AzFirewall as a rule, as well as how best to implement turning on DNS Settings (pointed to Azure) and using DNS proxy:

Source IP1 -> Outbound -> destination.subdomain.com -> port random such as 64721

image

### PR DESCRIPTION
**Pull request by magodo**
`azurerm_firewall` supports `dns_setting` and `azurerm_firewall_network_rule_collection` supports `destination_fqdns`.

## Test Result

```bash
💢 make testacc TEST=./azurerm/internal/services/network/tests TESTARGS='-run "TestAccAzureRMFirewallNetworkRuleCollection_fqdns|TestAccAzureRMFirewallNetworkRuleCollection_noDestination|TestAccAzureRMFirewall_enableDNS"'

==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test ./azurerm/internal/services/network/tests -v -run "TestAccAzureRMFirewallNetworkRuleCollection_fqdns|TestAccAzureRMFirewallNetworkRuleCollection_noDestination|TestAccAzureRMFirewall_enableDNS" -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccAzureRMFirewallNetworkRuleCollection_fqdns
=== PAUSE TestAccAzureRMFirewallNetworkRuleCollection_fqdns
=== RUN   TestAccAzureRMFirewallNetworkRuleCollection_noDestination
=== PAUSE TestAccAzureRMFirewallNetworkRuleCollection_noDestination
=== RUN   TestAccAzureRMFirewall_enableDNS
=== PAUSE TestAccAzureRMFirewall_enableDNS
=== CONT  TestAccAzureRMFirewallNetworkRuleCollection_fqdns
=== CONT  TestAccAzureRMFirewall_enableDNS
=== CONT  TestAccAzureRMFirewallNetworkRuleCollection_noDestination
--- PASS: TestAccAzureRMFirewallNetworkRuleCollection_fqdns (2213.69s)
--- PASS: TestAccAzureRMFirewall_enableDNS (2222.99s)
--- PASS: TestAccAzureRMFirewallNetworkRuleCollection_noDestination (2234.54s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/network/tests       2234.580s
```

Fixes #8312, fixes #7743.

### CODE REVIEW

File: azurerm/internal/services/network/firewall_network_rule_collection_resource.go [hunk 1]
```diff
@@ -473,6 +485,9 @@ func flattenFirewallNetworkRuleCollectionRules(rules *[]network.AzureFirewallNet
 		if rule.DestinationPorts != nil {
 			output["destination_ports"] = set.FromStringSlice(*rule.DestinationPorts)
 		}
+		if rule.DestinationFqdns != nil {
+			output["destination_fqdns"] = set.FromStringSlice(*rule.DestinationFqdns)
+		}
```
Comment (tombuildsstuff) [inline azurerm/internal/services/network/firewall_network_rule_collection_resource.go:490]: this (and the other blocks) need to be output as an empty list in the case they're not returned from the API to be able to correctly map the diff, so could we make this:

```suggestion
		destinationFQDNs := make([]string, 0)
		if rule.DestinationFqdns != nil {
			destinationFQDNs = set.FromStringSlice(*rule.DestinationFqdns)
		}
		output["destination_fqdns"] = destinationFQDNs
```

File: azurerm/internal/services/network/firewall_resource.go [hunk 2]
```diff
@@ -467,6 +497,47 @@ func flattenArmFirewallIPConfigurations(input *[]network.AzureFirewallIPConfigur
...
+	v := input[0].(map[string]interface{})
+
+	var servers []string
+	for _, server := range v["servers"].([]interface{}) {
+		servers = append(servers, server.(string))
+	}
+
+	return map[string]*string{
+		"Network.DNS.EnableProxy": utils.String(fmt.Sprintf("%t", v["enabled"].(bool))),
+		"Network.DNS.Servers":     utils.String(strings.Join(servers, ",")),
```
Comment (tombuildsstuff) [inline azurerm/internal/services/network/firewall_resource.go:514]: Can we file a Swagger bug about these? Since this is a dictionary there's no guarantees there won't be breaking changes here

File: azurerm/internal/services/network/firewall_resource.go [hunk 3]
```diff
@@ -467,6 +497,47 @@ func flattenArmFirewallIPConfigurations(input *[]network.AzureFirewallIPConfigur
...
+
+	v := input[0].(map[string]interface{})
+
+	var servers []string
+	for _, server := range v["servers"].([]interface{}) {
+		servers = append(servers, server.(string))
+	}
+
+	return map[string]*string{
+		"Network.DNS.EnableProxy": utils.String(fmt.Sprintf("%t", v["enabled"].(bool))),
```
Comment (tombuildsstuff) [inline azurerm/internal/services/network/firewall_resource.go:513]: presumably this is a String to handle the Tri-state (True, False, Unset) here - is this defaulted/planned to be defaulted going forward? In general we're removing "enabled" fields and using the presence/omission of the block to infer that - but that won't work for tri-state fields, can we reach out to the service team and confirm the intention here?

**Review by tombuildsstuff — COMMENTED** [review]
hey @magodo 

Thanks for this PR - I've taken a look through and left a few comments inline but if we can fix those up then this is otherwise looking good 👍 

Thanks!

File: azurerm/internal/services/network/firewall_resource.go (hunk 2 above)
Comment (magodo) [reply azurerm/internal/services/network/firewall_resource.go:514]: Sure, Azure/azure-rest-api-specs#11278

File: azurerm/internal/services/network/firewall_resource.go (hunk 3 above)
Comment (magodo) [reply azurerm/internal/services/network/firewall_resource.go:513]: I will reply here later once I got the update from service team.

File: azurerm/internal/services/network/firewall_resource.go (hunk 2 above)
Comment (katbyte) [reply azurerm/internal/services/network/firewall_resource.go:515]: could we link to this in the code?

File: azurerm/internal/services/network/firewall_resource.go (hunk 3 above)
Comment (katbyte) [reply azurerm/internal/services/network/firewall_resource.go:514]: any update @magodo ?

Comment (magodo) [reply azurerm/internal/services/network/firewall_resource.go:514]: @katbyte Unfortunately no update yet, I'll let you know once I got any news.

File: azurerm/internal/services/network/firewall_resource.go (hunk 2 above)
Comment (magodo) [reply azurerm/internal/services/network/firewall_resource.go:515]: Yes, I have added them [in my last commit](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8878/commits/de7d098fb7c8b2548e59622356f927a6f5456224#diff-dff86c50f3e4bb4e7322805d8cf371d2fbd7e58d00444af8e33a4a34e0ec9d01R512).

File: azurerm/internal/services/network/firewall_resource.go (hunk 3 above)
Comment (magodo) [reply azurerm/internal/services/network/firewall_resource.go:514]: Got the updates that `false` here is identical to absent. So I guess we shall remove the `Network.DNS.EnableProxy` and regard the precense of `Network.DNS.Servers` as an indication to whether enable this or not.

**Comment by magodo** [comment]
@katbyte I have updated the `dns_settings` to be simply a `dns_servers` list. Please take another look. Thanks!

**Review by manicminer — APPROVED** [review]

**Comment by manicminer** [comment]
Test results:

Screenshot 2020-11-05 at 06 59 28

File: azurerm/internal/services/network/firewall_resource.go (hunk 3 above)
Comment (hazzik) [reply azurerm/internal/services/network/firewall_resource.go]: @magodo no, it is not. Firewall supports DNS Proxy to "nowhere" aka Azure default dns.
