### PR TITLE
postgres - add server name validation

### LINKED ISSUE #4813: Error: Provider produced inconsistent final plan in azurerm_postgresql_server
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```shell
😀 abest@BARMIX2:~/xxxxxx/cptTerraformEnterprise/terraform-private/examples/bootstrap-azure (develop-andrewb) $ terraform -v
Terraform v0.12.13
+ provider.azurerm v1.36.1
+ provider.random v2.2.1
```

### Affected Resource(s)

* `azurerm_postgresql_server`

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_server" "new" {
    name                = "${local.prefix}"
    location            = "${var.location}"
    resource_group_name = "${azurerm_resource_group.new.name}"

    sku {
        name     = "B_Gen5_2"
        capacity = 2
        tier     = "Basic"
        family   = "Gen5"
    }

    storage_profile {
        storage_mb            = 5120
        backup_retention_days = 30
        geo_redundant_backup  = "Disabled"
        auto_grow             = "Enabled"
    }

    administrator_login          = "psqladminun"
    administrator_login_password = "${random_string.dbserver.result}"
    version                      = "9.6"
    ssl_enforcement              = "Enabled"
    tags                         = "${var.additional_tags}"
}
```

### Debug Output

See the Gist here https://gist.github.com/ausfestivus/e66a004bcf1cf1c0fc4be8af735ee683

### Panic Output

nil

### Expected Behavior

apply should not have ended with an error.

### Actual Behavior

The following error is displayed at the end of the `apply` run:

```shell
2019/11/05 22:25:48 [ERROR] <root>: eval: *terraform.EvalCheckPlannedChange, err: Provider produced inconsistent final plan: When expanding the plan for azurerm_postgresql_database.new to include new values learned so far during apply, provider "azurerm" produced an invalid new value for .server_name: was cty.StringVal("cptTFE"), but now cty.StringVal("cpttfe").

This is a bug in the provider, which should be reported in the provider's own issue tracker.
2019/11/05 22:25:48 [ERROR] <root>: eval: *terraform.EvalSequence, err: Provider produced inconsistent final plan: When expanding the plan for azurerm_postgresql_database.new to include new values learned so far during apply, provider "azurerm" produced an invalid new value for .server_name: was cty.StringVal("cptTFE"), but now cty.StringVal("cpttfe").

This is a bug in the provider, which should be reported in the provider's own issue tracker.

```

### Steps to Reproduce

With the above HCL run `terraform apply -var-file ../AFILE.tfvars -input false -auto-approv`

### Important Factoids

nil

### References

* [azurerm_postgresql_server documentation](https://www.terraform.io/docs/providers/azurerm/r/postgresql_server.html)
* [the gist](https://gist.github.com/ausfestivus/e66a004bcf1cf1c0fc4be8af735ee683)

* #0000

### PR DESCRIPTION
**Pull request by katbyte**
fixes #4813

related: https://github.com/Azure/azure-sdk-for-go/issues/6305

### CODE REVIEW

File: azurerm/internal/services/postgres/resource_arm_postgresql_server.go [hunk 1]
```diff
@@ -22,6 +22,14 @@ import (
 	"github.com/terraform-providers/terraform-provider-azurerm/azurerm/utils"
 )
 
+func ValidatePSQLServerName(i interface{}, k string) (_ []string, errors []error) {
+	if m, regexErrs := validate.RegExHelper(i, k, `^[a-z][0-9a-z][-0-9a-z]{0,60}[0-9a-z]$`); !m {
```
Comment (jackofallops) [inline azurerm/internal/services/postgres/resource_arm_postgresql_server.go]: I think this may be too restrictive, `0-b` is a valid (albeit unlikely) name, which this regex prevents.
I think this maybe : `^[a-z0-9][-0-9a-z]{0,61}[0-9a-z]$`

Comment (katbyte) [reply azurerm/internal/services/postgres/resource_arm_postgresql_server.go]: I tried it with a 0 in front and the portal forbids it =/ the api might not... but then the api allows any character and just hangs when its invalid

Comment (katbyte) [reply azurerm/internal/services/postgres/resource_arm_postgresql_server.go]: Looks like the portal is wrong, API works just fine with a number! good spot :) updated!

Comment (katbyte) [reply azurerm/internal/services/postgres/resource_arm_postgresql_server.go]: Looks like the portal is wrong, API works just fine with a number! good spot :) updated!
