### PR TITLE
azurerm_public_ip: fixed domain name label validation

### LINKED ISSUE #2085: azurerm_public_ip domain_name_label incorrectly limited to 61 chars
azurerm_public_ip domain_name_label incorrectly limited to 61 chars

Azure provider limits domain name labels to <= 61 chars
The RFC1035 says domain name labels must be <= 63 chars
Azure is allowing domain name labels of at least 64 chars

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.11.8
provider.azurerm v1.16.0
```

### Affected Resource(s)

azurerm_public_ip

### Terraform Configuration Files

```hcl
resource "azurerm_public_ip" "rg-prod-cus-compute__aadds-f7ecdfea993c43bf9d2136af0a67a8d2-pip" {
   name = "aadds-f7ecdfea993c43bf9d2136af0a67a8d2-pip"
   location = "centralus"
   resource_group_name = "rg-prod-cus-compute"
   public_ip_address_allocation = "Dynamic" 
   sku = "Basic" 
   domain_name_label = "cust-c-u-s-0-x-x-x-x-x-x-x-f7ecdfea-993c-43bf-9d21-36af0a67a8d2"
   tags { 
    showback = "Compute" 
  }
}
```
*note*, replaced company name with x's above to protect privacy

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

terraform plan should be successful

### Actual Behavior
```
terraform plan

Error: azurerm_public_ip.rg-prod-cus-compute__aadds-f7ecdfea993c43bf9d2136af0a67a8d2-pip: "domain_name_label" cannot be longer than 61 characters: "cust-c-u-s-0-x-x-x-x-x-x-x-f7ecdfea-993c-43bf-9d21-36af0a67a8d2"
```
### Steps to Reproduce

Create a public IP resource with domain_name_label that is 62-63 chars long and run `terraform plan`

### Important Factoids

- Azure provider limits domain name labels to <= 61 chars
- The RFC1035 says domain name labels must be <= 63 chars
- Azure is allowing domain name labels of at least 64 chars

### References

[RFC1035 section 2.3.1](https://tools.ietf.org/html/rfc1035) says "Labels must be 63 characters or less."

[resource_arm_public_ip.go](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_public_ip.go) line 289 limits label name to 61 chars
```go
	if len(value) > 61 {
		errors = append(errors, fmt.Errorf(
			"%q cannot be longer than 61 characters: %q", k, value))
	}
```

Azure is allowing domain_name_labels with 64 chars: 
```bash
$ az network public-ip list -g rg-prod-cus-compute | jq .[].dnsSettings.domainNameLabel | sed s/\"//g 
cust-c-u-s-0-x-x-x-x-x-x-x-f7ecdfea-993c-43bf-9d21-36af0a67a8d2

$ az network public-ip list -g rg-prod-cus-compute | jq .[].dnsSettings.domainNameLabel | sed s/\"//g | wc -c
64
```

### PR DESCRIPTION
**Pull request by katbyte**
fixes #2085

### CODE REVIEW

File: azurerm/helpers/validate/public_ip.go [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+
+import (
+	"fmt"
+	"regexp"
+)
+
+func PublicIpDomainNameLabel(v interface{}, k string) (ws []string, errors []error) {
+	value := v.(string)
+	if !regexp.MustCompile(`^[a-z][a-z0-9-]{1,61}[a-z0-9]$`).MatchString(value) {
+		errors = append(errors, fmt.Errorf("Domain must contain only lowercase alphanumeric characters, numbers and hyphens. It must start with a letter and end only with a number or letter"))
```
Comment (tombuildsstuff) [inline azurerm/helpers/validate/public_ip.go]: the argument `k` here is the name of the field name being validated - so we could make this:

```suggestion
		errors = append(errors, fmt.Errorf("%s must contain only lowercase alphanumeric characters, numbers and hyphens. It must start with a letter and end only with a number or letter", k))
```
