### PR TITLE
Container Registry forced new resource on SKU change

### LINKED ISSUE #1256: Container registry change of SKU destroys and recreates
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
# terraform -v
Terraform v0.11.7
+ provider.azurerm v1.5.0
```

### Affected Resource(s)

* azurerm_container_registry

### Terraform Configuration Files

Create as SKU standard
```hcl
resource "azurerm_resource_group" "acr-rg" {
  name      = "${var.registry_name}-acr-rg"
  location  = "${var.location}"
}

resource "azurerm_container_registry" "acr" {
  name                = "${var.registry_name}acr"
  resource_group_name = "${azurerm_resource_group.acr-rg.name}"
  location            = "${azurerm_resource_group.acr-rg.location}"
  admin_enabled       = "false"
  sku                 = "Standard"
}
```
Update to SKU Premium
```hcl
resource "azurerm_resource_group" "acr-rg" {
  name      = "${var.registry_name}-acr-rg"
  location  = "${var.location}"
}

resource "azurerm_container_registry" "acr" {
  name                = "${var.registry_name}acr"
  resource_group_name = "${azurerm_resource_group.acr-rg.name}"
  location            = "${azurerm_resource_group.acr-rg.location}"
  admin_enabled       = "false"
  sku                 = "Premium"
}
```

### Debug Output

```

Terraform will perform the following actions:

-/+ azurerm_container_registry.acr (new resource required)
      id:                  "/subscriptions/xxxxx/resourceGroups/xxx-acr-rg/providers/Microsoft.ContainerRegistry/registries/xxxxacr" => <computed> (forces new resource)
      admin_enabled:       "false" => "false"
      admin_password:      "" => <computed>
      admin_username:      "" => <computed>
      location:            "uksouth" => "uksouth"
      login_server:        "xxxxacr.azurecr.io" => <computed>
      name:                "xxxxacr" => "xxxxacr"
      resource_group_name: "xxx-acr-rg" => "xxx-acr-rg"
      sku:                 "Standard" => "Premium" (forces new resource)
      tags.%:              "0" => <computed>


Plan: 1 to add, 0 to change, 1 to destroy.

```
### Expected Behavior

Update SKU from Standard to Premium
You are able to change up and down SKU's via the Azure portal

### Actual Behavior

Destroys the standard registry and creates a new premium registry.

### Steps to Reproduce

1. `terraform apply`
1. Update confirm from standard to premium
1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by jeffreyCline**
This PR fixes issue #1256 

(fixes #1256)

### CODE REVIEW

**Comment by jeffreyCline** [comment]
[Test Pass Results](https://gist.github.com/jeffreyCline/3cbf42d301bb0f3b834aa8535455534f)

**Comment by jeffreyCline** [comment]
New test case [TestAccAzureRMContainerRegistry_basicBasicUpgradePremium result](https://gist.github.com/jeffreyCline/2e447c8bbc494b8995b4c1b51b9ecd11).

File: azurerm/resource_arm_container_registry_test.go [hunk 1]
```diff
@@ -144,6 +144,32 @@ func TestAccAzureRMContainerRegistry_basicPremium(t *testing.T) {
...
+
+	resource.Test(t, resource.TestCase{
+		PreCheck:     func() { testAccPreCheck(t) },
+		Providers:    testAccProviders,
+		CheckDestroy: testCheckAzureRMContainerRegistryDestroy,
+		Steps: []resource.TestStep{
+			{
+				Config: config,
+				Check: resource.ComposeTestCheckFunc(
+					testCheckAzureRMContainerRegistryExistsValidateSkuValue("azurerm_container_registry.test", "Basic"),
```
Comment (tombuildsstuff) [inline azurerm/resource_arm_container_registry_test.go]: we want to be checking the value in the state rather than in the Remote API - as such can we remove this function and check this in the state instead via:

```
resource.TestCheckAttribbute(resourceName, "sku", "Basic"),
```

(same for below):
```
resource.TestCheckAttribbute(resourceName, "sku", "Premium"),
```

(we only tend to check the Remote API when the API is known to be eventually consistent, hence it's overkill checking the API here since the values will be pulled into the state either way)

File: website/docs/r/container_registry.html.markdown [hunk 2]
```diff
@@ -55,7 +55,7 @@ The following arguments are supported:
 
 * `storage_account_id` - (Required for `Classic` Sku - Optional otherwise) The ID of a Storage Account which must be located in the same Azure Region as the Container Registry.
 
-* `sku` - (Optional) The SKU name of the the container registry. Possible values are `Classic` (which was previously `Basic`), `Basic`, `Standard` and `Premium`.
+* `sku` - (Optional) The SKU name of the the container registry. Possible values are `Classic` (which was previously `Basic`), `Basic`, `Standard` and `Premium`. Once provisioned changing the SKU will not force a new resource.
```
Comment (tombuildsstuff) [inline website/docs/r/container_registry.html.markdown]: _minor_ I'd missed we didn't previously have `Changing this forces a new resource to be created.` at the end of this line (which I'd meant we can remove) - I'll push a commit to remove this and make it consistent :)
