### PR TITLE
azurerm_iothub - add default value for min_tls_version to prevent force replacement

### LINKED ISSUE #32087: azurerm_iothub: min_tls_version causes unexpected force replacement due to missing Computed or Default in schema
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.14.0

### AzureRM Provider Version

4.60.0

### Affected Resource(s)/Data Source(s)

azurerm_iothub

### Terraform Configuration Files

```hcl
resource "azurerm_iothub" "example" {
  name                = "example-iothub"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  sku {
    name     = "S1"
    capacity = 1
  }
}
```

### Debug Output/Panic Output

```shell
# azurerm_iothub.example must be replaced
-/+ resource "azurerm_iothub" "example" {
      - min_tls_version = "1.2" -> null # forces replacement
      ...
    }
```

### Expected Behaviour

When `min_tls_version` is not set in the configuration, Terraform should not plan a force replacement of the IoT Hub. The resource should remain stable since Azure defaults to TLS 1.2 and the effective configuration has not changed.

Either:
- The field should have `Default: "1.2"` in the schema (consistent with the v3.0 upgrade guide which stated all resources would default `min_tls_version` to 1.2), or
- The field should be` Computed: true` so the value read back from the Azure API is reconciled with state without triggering a diff

### Actual Behaviour

After a state refresh, the Azure API returns "1.2" for min_tls_version, which gets written into state. On the next plan, Terraform sees "1.2" (state) → null (config) and because the field is ForceNew: true, it plans a full destruction and recreation of the IoT Hub.

This is destructive and cascading — it destroys dependent resources (EventGrid system topics, event subscriptions, role assignments) and can leave the environment in a broken state.

The schema definition for this field is:
```
"min_tls_version": {
    Type:         pluginsdk.TypeString,
    Optional:     true,
    ForceNew:     true,
    ValidateFunc: validation.StringInSlice([]string{"1.2"}, false),
}
```
It has no `Default` and is not `Computed`. The v3.0 upgrade guide `([#14193](https://github.com/hashicorp/terraform-provider-azurerm/issues/14193))` stated that `min_tls_version` would default to `"1.2"` across all resources, but this was never implemented for `azurerm_iothub`. Other resources like `azurerm_storage_account` and `azurerm_redis_cache` received `Default: "1.2"` in their schemas.

### Steps to Reproduce

1. Create an `azurerm_iothub` without setting `min_tls_version`
2. Apply successfully
3. Run `terraform plan` — at some point after Azure's API starts returning `"1.2"` for the field, the state refresh writes `"1.2"` into state
4. Subsequent `terraform plan` shows `min_tls_version: "1.2" -> null # forces replacement`

### Important Factoids

_No response_

### References

- https://github.com/hashicorp/terraform-provider-azurerm/pull/9670
- https://github.com/hashicorp/terraform-provider-azurerm/issues/14193

### PR DESCRIPTION
**Pull request by robinabganpat**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

The `min_tls_version` field on `azurerm_iothub` is `Optional` and `ForceNew` but has no `Default` and is not `Computed`. When the Azure API returns `"1.2"` during a state refresh and the field is omitted from config, Terraform sees `"1.2" -> null` and plans a destructive force replacement of the entire IoT Hub, cascading into destruction of dependent resources (EventGrid system topics, event subscriptions, role assignments).

This PR adds `Default: "1.2"` to the schema, which:
- Prevents unintended force replacement when the field is omitted
- Is consistent with how other resources (`azurerm_storage_account`, `azurerm_redis_cache`) handle `min_tls_version`
- Is consistent with the v3.0 upgrade guide which stated all resources would default `min_tls_version` to `"1.2"`
- Is safe since `"1.2"` is already the only valid value (enforced by `ValidateFunc`)

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work.

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them.
- [ ] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.

## Testing

No new tests added. The change adds a schema default that matches the only valid value allowed by `ValidateFunc`. Existing tests should continue to pass as behavior is unchanged for configs that already set `min_tls_version = "1.2"`.

## Change Log

* `azurerm_iothub` - add `Default: "1.2"` for `min_tls_version` to prevent unintended force replacement when the field is omitted from config

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)

Fixes #32087

## AI Assistance Disclosure

- [x] AI Assisted - This contribution was made with the assistance of AI/LLMs (Claude) for research, root cause analysis, and drafting the PR description.

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

No changes to security controls.

### CODE REVIEW

File: internal/services/iothub/iothub_resource.go [hunk 1]
```diff
@@ -594,6 +594,7 @@ func resourceIotHub() *pluginsdk.Resource {
 				Type:     pluginsdk.TypeString,
 				Optional: true,
 				ForceNew: true,
+				Default:  "1.2",
```
Comment (sreallymatt) [inline internal/services/iothub/iothub_resource.go:597]: This will need adding to the resource doc as well

([contributing guide ref](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/reference-documentation-standards.md?plain=1#L48))

**Review by sreallymatt — CHANGES_REQUESTED** [review]
Thanks @robinabganpat - I've left a comment inline

**Review by sreallymatt — APPROVED** [review]

**Review by mbfrahry — APPROVED** [review]
LGTM!
