### PR TITLE
azurerm_eventhub_consumer_group - allow the name property to be set to $Default 

### LINKED ISSUE #7720: azurerm_eventhub_consumer_group doesn't support '$Default' consumer group name
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

+ Terraform v0.12.28
+ provider.azurerm v2.1.0

### Affected Resource(s)

* `azurerm_eventhub_consumer_group`

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub_consumer_group" "example" {
  name                = "$Default"
  namespace_name      = azurerm_eventhub_namespace.example.name
  eventhub_name       = azurerm_eventhub.example.name
  resource_group_name = azurerm_resource_group.example.name
  user_metadata       = "some-meta-data"
}
```

### Expected Behavior

Should have accepted the name `$Default` as this is the name that the azure portal assigns by default if one is not specified, when using the `Basic` Tier Event Hub Namespace.

### Actual Behavior

`Error: invalid value for name (The consumer group name can contain only letters, numbers, periods (.), hyphens (-),and underscores (_), up to 50 characters, and it must begin and end with a letter or number.)`

### Steps to Reproduce

As per example above

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by favoretti**
Fixes #7720

### CODE REVIEW

**Comment by favoretti** [comment]
@jackofallops would something like this work? Had to split validation for datasource and resource, to make sure people won't mangle `$Default` in resource definition.

File: azurerm/internal/services/eventhub/eventhub_consumer_group_data_source.go [hunk 1]
```diff
@@ -23,7 +23,7 @@ func dataSourceEventHubConsumerGroup() *schema.Resource {
 			"name": {
 				Type:         schema.TypeString,
 				Required:     true,
-				ValidateFunc: azure.ValidateEventHubConsumerName(),
+				ValidateFunc: azure.ValidateEventHubConsumerDataSourceName(),
```
Comment (jackofallops) [inline azurerm/internal/services/eventhub/eventhub_consumer_group_data_source.go:26]: Since we're catering for one specific string case, it might be better to do:
```suggestion
				ValidateFunc: validation.Any(
					azure.ValidateEventHubConsumerName(),
					validation.StringInSlice([]string{"$Default"},
					)
```
Or modify your new validation function to do similar?

**Review by jackofallops — CHANGES_REQUESTED** [review]
Hi @favoretti 
Thanks for this PR, I've had a quick look over and left one comment to look at initially since the new validation method regex would inadvertently allow invalid strings and not match `$Default` as intended.

Thanks!

File: azurerm/internal/services/eventhub/eventhub_consumer_group_data_source.go (hunk 1 above)
Comment (favoretti) [reply azurerm/internal/services/eventhub/eventhub_consumer_group_data_source.go:26]: Ah, didn't know it existed. This is indeed much better. I'll commit your suggestion and remove the rest.

**Comment by neil-yechenwei** [comment]
> Address #7720

Please update the comment from "Address #7720" to "fixes https://github.com/terraform-providers/terraform-provider-azurerm/issues/7720"

File: azurerm/internal/services/eventhub/eventhub_consumer_group_data_source.go [hunk 2]
```diff
@@ -2,6 +2,7 @@ package eventhub
 
 import (
 	"fmt"
+	"github.com/hashicorp/terraform-plugin-sdk/helper/validation"
```
Comment (neil-yechenwei) [inline azurerm/internal/services/eventhub/eventhub_consumer_group_data_source.go:5]: Move this line to line 9

**Comment by favoretti** [comment]
@neil-yechenwei @jackofallops Feedback addressed.

**Review by katbyte — APPROVED** [review]
Thanks @favoretti - LGTM now! 🚀
