### PR TITLE
Fix to not drop MySQL and PostgreSQL DB when storage_mb value is changed

### LINKED ISSUE #1522: MySQL and PG should be inplace update when updating storage etc.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* azurerm_mysql_server
* azurerm_postgresql_server

### Description

Current Terraform version, if any of the following parameters updated: server Tier, Family, Admin Login, Storage_mb, it resulted in deleting and recreating the server. This causes data lose. 

The expected behavior is to call the backend as stated in this doc: https://docs.microsoft.com/en-us/rest/api/mysql/servers/update. Backend will perform correct in-place updates.

### PR DESCRIPTION
**Pull request by jeffreyCline**
Fixes issue #1522
[Test Results](https://gist.github.com/jeffreyCline/706f3d3a59b27abf28142e17006c2e54)

(fixes #1522 )

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
@jeffreyCline can you run all of the Postgres/MySQL tests for this?

File: azurerm/resource_arm_postgresql_server.go [hunk 1]
```diff
@@ -138,7 +138,6 @@ func resourceArmPostgreSQLServer() *schema.Resource {
 						"storage_mb": {
 							Type:         schema.TypeInt,
 							Required:     true,
-							ForceNew:     true,
```
Comment (tombuildsstuff) [inline azurerm/resource_arm_postgresql_server.go]: Can we update the docs to mention that this is no longer ForceNew? (And above)

**Comment by katbyte** [comment]
@tombuildsstuff I am running them now

File: azurerm/resource_arm_postgresql_server.go (hunk 1 above)
Comment (jeffreyCline) [reply azurerm/resource_arm_postgresql_server.go]: Yeah, I thought about that after I did the initial push. I'll update those now.

Comment (jeffreyCline) [reply azurerm/resource_arm_postgresql_server.go]: I just looked at the documentation and the original text does not mention that it will ForceNew so I believe this is a no op:

```Markdown
* `storage_mb` - (Required) Max storage allowed for a server. Possible values are between `5120` MB(5GB) and `1048576` MB(1TB) for the Basic SKU and between `5120` MB(5GB) and `4194304` MB(4TB) for General Purpose/Memory Optimized SKUs. For more information see the [product documentation](https://docs.microsoft.com/en-us/rest/api/mysql/servers/create#StorageProfile).
```
