### PR TITLE
Validate policy mode value

### LINKED ISSUE #8748: azurerm_policy_definition mode is case sensitive
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_policy_definition `

### Terraform Configuration Files

```hcl
resource "azurerm_policy_definition" "key_vault_soft_delete" {
  name                  = "Key-Vault-Soft-Delete"
  policy_type           = "Custom"
  mode                  = "indexed"
  display_name          = "Key-Vault-Soft-Delete"
  management_group_name = var.definition_management_group
  policy_rule           = file("${path.module}/policies/keyVaultSoftDelete/policyRule.json")
}
```

### Expected Behavior

When this snippet is applied, a policy definition is created as one would expect. A "terraform plan" after apply should yield that no changes are required.  

### Actual Behavior

However, a "terraform plan" after "terraform apply" yields the need to update the resource.  

The problem is a case sensitive comparison on the 'mode' property and that mode "indexed" is stored as "Indexed" during apply. 

### Steps to Reproduce

1. `terraform apply` with the snippet
2. `terraform plan`

### References

* #0000

### PR DESCRIPTION
**Pull request by beandrad**
Policy creation succeeds even if the policy mode in the request is
not capitalized, however, when fetching the policy mode value from
Azure, the correct capitalized version is returned, which causes
the Terraform state and configuration to be different.

Ideally, there should be an enum with a set of allowed values, but
thi is not the case in the latest version of the Azure Rest API specs.
However, the supported mode values are returned in the create error
response when an invalid mode is requested.

Fixes #8748

### CODE REVIEW

**Comment by beandrad** [comment]
Screenshot 2020-10-08 at 12 11 25

File: azurerm/internal/services/policy/policy_definition_resource.go [hunk 1]
```diff
@@ -63,6 +63,20 @@ func resourceArmPolicyDefinition() *schema.Resource {
...
+						"Indexed",
+						"Microsoft.ContainerService.Data",
+						"Microsoft.CustomerLockbox.Data",
+						"Microsoft.DataCatalog.Data",
+						"Microsoft.KeyVault.Data",
+						"Microsoft.Kubernetes.Data",
+						"Microsoft.MachineLearningServices.Data",
+						"Microsoft.Network.Data",
+						"Microsoft.Synapse.Data",
+					}, false,
```
Comment (tombuildsstuff) [inline azurerm/internal/services/policy/policy_definition_resource.go:78]: could we also update the values used in the docs here: https://github.com/terraform-providers/terraform-provider-azurerm/blame/master/website/docs/r/policy_definition.html.markdown#L72-L74

```
* `mode` - (Required) The policy mode that allows you to specify which resource types will be evaluated. Possible values are `All`, `Indexed`, `Microsoft.ContainerService.Data`, `Microsoft.CustomerLockbox.Data`, `Microsoft.DataCatalog.Data`, `Microsoft.KeyVault.Data`, `Microsoft.Kubernetes.Data`, `Microsoft.MachineLearningServices.Data`, `Microsoft.Network.Data` and `Microsoft.Synapse.Data`.
```

**Review by tombuildsstuff — APPROVED** [review]
hey @beandrad 

Thanks for this PR - if we can also update the docs then this otherwise LGTM 👍 

Thanks!

**Comment by Nepomuceno** [comment]
I do think that a DiffSupress Would be better for this them forcing the values.
