### PR TITLE
azurerm_eventhub_namespace: allow maximum_throughput_units to be zero

### LINKED ISSUE #2083: Cannot set maximum_throughput_units when auto_inflate_enabled is false
Hi,
we are running Terraform with Azure provider module:
```
Terraform v0.11.8
+ provider.azurerm v1.16.0
```

We have a general module containing Event Hub Namespace resource
```
resource "azurerm_eventhub_namespace" "default" {
  name                     = "${var.event_hub_namespace_name}"
  location                 = "${var.location}"
  resource_group_name      = "${var.resource_group_name}"
  auto_inflate_enabled     = "${var.autoscaling["enabled"]}"
  maximum_throughput_units = "${var.autoscaling["max_units"]}"

  sku      = "${var.sku}"
  capacity = "${var.capacity}"
}
```
From the module, we are trying to set **auto_inflate_enabled** and **maximum_throughput_units** parameters. The **maximum_throughput_units** parameter is dependent on **auto_inflate_enabled** parameters. It means, we can set **maximum_throughput_units** only when **auto_inflate_enabled** is enabled.

Is it possible to use one **azurerm_eventhub_namespace** resource for the following two scenarios?
1. **auto_inflate_enabled** is disabled and we don't care about **maximum_throughput_units**
2. **auto_inflate_enabled** is enabled and **maximum_throughput_units** is set to e.g. 20

We tried the following solutions:
1. By default set **auto_inflate_enabled** to false and **maximum_throughput_units** to 0. Following error occured: `Error: module.event_hub.azurerm_eventhub_namespace.default: expected maximum_throughput_units to be in the range (1 - 20), got 0`
2. By default set **auto_inflate_enabled** to false and **maximum_throughput_units** to 1. Following error occured: `eventhub.NamespacesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Cannot set MaximumThroughputUnits property if AutoInflate is not enabled.`

### PR DESCRIPTION
**Pull request by katbyte**
also removed separate import tests

fixes #2083

### CODE REVIEW

**Comment by katbyte** [comment]
tests pass:
screen shot 2018-10-20 at 20 49 52

File: azurerm/resource_arm_eventgrid_topic_test.go [hunk 1]
```diff
@@ -14,38 +14,41 @@ import (
...
 				Check: resource.ComposeTestCheckFunc(
 					testCheckAzureRMEventGridTopicExists(resourceName),
 					resource.TestCheckResourceAttrSet(resourceName, "endpoint"),
 					resource.TestCheckResourceAttrSet(resourceName, "primary_access_key"),
 					resource.TestCheckResourceAttrSet(resourceName, "secondary_access_key"),
 				),
 			},
+			{
+				ResourceName:      resourceName,
+				ImportState:       true,
```
Comment (metacpp) [inline azurerm/resource_arm_eventgrid_topic_test.go]: Are we merging the import test into regular resource test ?
