### PR TITLE
P vmss image

### LINKED ISSUE #425: Creating a  image data source and using it in VMSS crashes
I am trying to create a data source for azurerm_image and use it in VMSS. I can successfully directly use my resource id for my custom vm image in storage_profile_image_reference and this works as expected.  Now I want to create a data source and use this in storage_profile_image_reference and this crashes. 
@
[crash.log](https://github.com/terraform-providers/terraform-provider-azurerm/files/1380872/crash.log)

Terraform Version : Terraform v0.10.8-dev (5fb1fe9de8ca3c4655ddd25098c7e486caae9a2a) (Latest source code. 

Affected Resource :  azurerm_image data source used in VMSS 

HCL file : main.tf 
```HCL
resource "azurerm_resource_group" "vmss" {
  name     = "${var.resource_group_name}"
  location = "${var.location}"

  tags {
    environment = "codelab"
  }
}

resource "azurerm_virtual_network" "vmss" {
  name                = "vmss-vnet"
  address_space       = ["10.0.0.0/16"]
  location            = "${var.location}"
  resource_group_name = "${azurerm_resource_group.vmss.name}"

  tags {
    environment = "codelab"
  }
}

resource "azurerm_subnet" "vmss" {
  name                 = "vmss-subnet"
  resource_group_name  = "${azurerm_resource_group.vmss.name}"
  virtual_network_name = "${azurerm_virtual_network.vmss.name}"
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_public_ip" "vmss" {
  name                         = "vmss-public-ip"
  location                     = "${var.location}"
  resource_group_name          = "${azurerm_resource_group.vmss.name}"
  public_ip_address_allocation = "static"
  domain_name_label            = "${azurerm_resource_group.vmss.name}"

  tags {
    environment = "codelab"
  }
}

resource "azurerm_lb" "vmss" {
  name                = "vmss-lb"
  location            = "${var.location}"
  resource_group_name = "${azurerm_resource_group.vmss.name}"

  frontend_ip_configuration {
    name                 = "PublicIPAddress"
    public_ip_address_id = "${azurerm_public_ip.vmss.id}"
  }

  tags {
    environment = "codelab"
  }
}

resource "azurerm_lb_backend_address_pool" "bpepool" {
  resource_group_name = "${azurerm_resource_group.vmss.name}"
  loadbalancer_id     = "${azurerm_lb.vmss.id}"
  name                = "BackEndAddressPool"
}

resource "azurerm_lb_probe" "test" {
  resource_group_name = "${azurerm_resource_group.vmss.name}"
  loadbalancer_id     = "${azurerm_lb.vmss.id}"
  name                = "ssh-running-probe"
  port                = "${var.application_port}"
}

resource "azurerm_lb_rule" "lbnatrule" {
    resource_group_name            = "${azurerm_resource_group.vmss.name}"
    loadbalancer_id                = "${azurerm_lb.vmss.id}"
    name                           = "ssh"
    protocol                       = "Tcp"
    frontend_port                  = "${var.application_port}"
    backend_port                   = "${var.application_port}"
    backend_address_pool_id        = "${azurerm_lb_backend_address_pool.bpepool.id}"
    frontend_ip_configuration_name = "PublicIPAddress"
    probe_id                       = "${azurerm_lb_probe.test.id}"
}

data "azurerm_image" "dataimage" {
  name = "myPackerImage"
  resource_group_name = "myResourceGroupW2"

}



resource "azurerm_virtual_machine_scale_set" "vmss" {
  name                = "vmscaleset"
  location            = "${var.location}"
  resource_group_name = "${azurerm_resource_group.vmss.name}"
  upgrade_policy_mode = "Manual"

  sku {
    name     = "Standard_DS1_v2"
    tier     = "Standard"
    capacity = 2
  }


  storage_profile_image_reference {
   id = "${data.azurerm_image.dataimage.id}"
}



  storage_profile_os_disk {
    name              = ""
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }

  storage_profile_data_disk {
    lun          = 0
    caching        = "ReadWrite"
    create_option  = "Empty"
    disk_size_gb   = 10
  }

  os_profile {
    computer_name_prefix = "vmlab"
    admin_username       = "azureuser"
    admin_password       = "Passwword1234"
  }

  os_profile_linux_config {
    disable_password_authentication = true

    ssh_keys {
      path     = "/home/azureuser/.ssh/authorized_keys"
      key_data = "${file("/root/.ssh/id_rsa.pub")}"
    }
  }

  network_profile {
    name    = "terraformnetworkprofile"
    primary = true

    ip_configuration {
      name                                   = "IPConfiguration"
      subnet_id                              = "${azurerm_subnet.vmss.id}"
      load_balancer_backend_address_pool_ids = ["${azurerm_lb_backend_address_pool.bpepool.id}"]
    }
  }

  tags {
    environment = "codelab"
  }
}
```
### Steps to reproduce 
terraform plan

### PR DESCRIPTION
**Pull request by mbfrahry**
This PR fixes #425. Adds a nil check and a test for custom images in vmss

```
make testacc TEST=./azurerm TESTARGS="-run=TestAccAzureRMVirtualMachineScaleSet_customImage"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./azurerm -v -run=TestAccAzureRMVirtualMachineScaleSet_customImage -timeout 180m
=== RUN   TestAccAzureRMVirtualMachineScaleSet_customImage
--- PASS: TestAccAzureRMVirtualMachineScaleSet_customImage (820.55s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	820.578s
```

### CODE REVIEW

File: azurerm/resource_arm_virtual_machine_scale_set_test.go [hunk 1]
```diff
@@ -298,6 +298,41 @@ func TestAccAzureRMVirtualMachineScaleSet_planManagedDisk(t *testing.T) {
 	})
 }
 
+func TestAccAzureRMVirtualMachineScaleSet_customImage(t *testing.T) {
+	ri := acctest.RandInt()
+	resourceGroup := fmt.Sprintf("acctestRG-%d", ri)
+	userName := "testadmin"
+	password := "Password1234!"
```
Comment (vancluever) [inline azurerm/resource_arm_virtual_machine_scale_set_test.go]: I guess one question about these kinds of test credentials being in the clear. I understand that the resources are ephemeral and more than likely this is low risk, but is there any way that maybe we could randomize this? That way, if by any chance the test instances/VMSS ends up available on the internet anywhere, at least the credentials are't predictable. Thoughts?

Comment (mbfrahry) [reply azurerm/resource_arm_virtual_machine_scale_set_test.go]: Sounds sane sane to me!

File: azurerm/resource_arm_virtual_machine_scale_set_test.go [hunk 2]
```diff
@@ -301,8 +301,8 @@ func TestAccAzureRMVirtualMachineScaleSet_planManagedDisk(t *testing.T) {
 func TestAccAzureRMVirtualMachineScaleSet_customImage(t *testing.T) {
 	ri := acctest.RandInt()
 	resourceGroup := fmt.Sprintf("acctestRG-%d", ri)
-	userName := "testadmin"
-	password := "Password1234!"
+	userName := fmt.Sprintf("testadmin%d", ri)
+	password := fmt.Sprintf("Password1234!", ri)
```
Comment (vancluever) [inline azurerm/resource_arm_virtual_machine_scale_set_test.go]: Is this gaining the desired effect? Just noticed there's no verbs in this format string.
