### PR TITLE
Switching `azurerm_storage_blob` over to the new Storage SDK

### LINKED ISSUE #2245: azurerm_storage_blob - error when storage account/RG have been deleted
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.9
+ provider.azurerm v1.18.0

### Affected Resource(s)

* azurerm_storage_blob

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "resources" {
  name     = "test-rg"
  location = "westeurope"
}
resource "azurerm_storage_account" "teststoreaccount" {
  name                     = "teststoreaccount124"
  resource_group_name      = "${azurerm_resource_group.resources.name}"
  location                 = "${azurerm_resource_group.resources.location}"
  account_tier             = "Standard"
  account_replication_type = "GRS"
}
resource "azurerm_storage_container" "storecontainer" {
  name                  = "storecontainer124"
  storage_account_name  = "${azurerm_storage_account.teststoreaccount.name}"
  resource_group_name   = "${azurerm_resource_group.resources.name}"
  container_access_type = "private"
}
resource "azurerm_storage_blob" "blob-copy" {
  name                   = "blob-copy.image"
  storage_account_name   = "${azurerm_storage_account.teststoreaccount.name}"
  storage_container_name = "${azurerm_storage_container.storecontainer.name}"
  resource_group_name    = "${azurerm_resource_group.resources.name}"
  source_uri             = "https://www.terraform.io/favicon.ico"
}
```

### Steps to reproduce:
1. Apply the terraform file above (works well)
2. delete the resource group in the azure portal (without terraform)
3. Apply the terraform file above (causes error message)

### Error-message: 
`azurerm_storage_blob.blob-copy: azurerm_storage_blob.blob-copy: Unable to determine Resource Group for Storage Account "teststoreaccount124"`

### Workaround
`terraform state rm azurerm_storage_blob.blob-copy`

### Important Factoids
I remember older versions were less picky about disappearing resources.
I'm not aware of other resources causing similar problems. Only storage_blob.

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Since this is quite a complex resource (in that there's different kinds of blobs) we're going to do this migration to the new SDK in phases. This first PR switches the SDK over to using the new Giovanni Storage SDK but doesn't add support for the new features - nor does it address the open TODO's/add validation/switch the test suite over - which will come in a subsequent PR.

This PR fixes #2245

### CODE REVIEW

File: azurerm/resource_arm_storage_blob.go [hunk 1]
```diff
@@ -101,686 +91,228 @@ func resourceArmStorageBlob() *schema.Resource {
...
-		if err != nil {
-			ctx.errors <- fmt.Errorf("Error uploading block %q for source file %q: %s", block.id, ctx.source, err)
-			ctx.wg.Done()
-			continue
-		}
+	d.SetId(id)
 
-		ctx.wg.Done()
-	}
+	return resourceArmStorageBlobUpdate(d, meta)
```
Comment (tombuildsstuff) [inline azurerm/resource_arm_storage_blob.go]: (for info) this now calls into Update because the Access Tier might as well be set there, since it needs to be configured after creation anyway

File: azurerm/internal/services/storage/blobs.go [hunk 2]
```diff
@@ -0,0 +1,306 @@
...
+		start := page.offset
+		end := page.offset + page.section.Size() - 1
+		if end > uploadCtx.blobSize-1 {
+			end = uploadCtx.blobSize - 1
+		}
+		size := end - start + 1
+
+		chunk := make([]byte, size)
+		_, err := page.section.Read(chunk)
+		if err != nil && err != io.EOF {
```
Comment (katbyte) [inline azurerm/internal/services/storage/blobs.go]: These lines could be merged:
```suggestion
		if _, err := page.section.Read(chunk) != nil && err != io.EOF {
```

**Comment by tombuildsstuff** [comment]
I've done some manual testing with large files and this seems fine 👍

**Comment by tombuildsstuff** [comment]
Travis is failing because a downstream dependency is offline: `	fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection timed out` but it's fine in TeamCity so this is fine 👍
