### PR TITLE
`azurerm_mssql_database` create mode read during import

### LINKED ISSUE #11024: Importing mssql failover group secondary database is destructive
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform 0.12.26
AzureRM provider 2.51.0

### Affected Resource(s)

* `azurerm_mssql_database`
* `azurerm_sql_failover_group`

#### Example Failover Group to reproduce problem:
For reproduction purposes, this terraform will create a failover group that will illustrate the problem:
```hcl
variable instance_name { 
    type = string
    default = "test-mssql-db" 
}
variable resource_group { 
    type = string
    default = "test-mssql-db-rg" 
}
variable db_name { 
    type = string
    default = "test-db"
}
variable location { 
    type = string 
    default = "eastus2"
}
variable labels { 
    type = map
    default = {} 
}
variable sku_name { 
    type = string 
    default = "GP_Gen5_2"
}
variable max_storage_gb { 
    type = number 
    default = 10
}

provider "azurerm" {
  version = "~> 2.51.0"
  features {}
}

resource "azurerm_resource_group" "azure-sql-fog" {
  name     = var.resource_group
  location = var.location
  tags     = var.labels
}

resource "random_string" "username" {
  length = 16
  special = false
  number = false
}

resource "random_password" "password" {
  length = 64
  override_special = "~_-."
  min_upper = 2
  min_lower = 2
  min_special = 2
}

resource "azurerm_sql_server" "primary_azure_sql_db_server" {
  depends_on = [ azurerm_resource_group.azure-sql-fog ]
  name                         = format("%s-primary", var.instance_name)
  resource_group_name          = var.resource_group
  location                     = var.location
  version                      = "12.0"
  administrator_login          = random_string.username.result
  administrator_login_password = random_password.password.result
  tags = var.labels
}

locals {
  default_pair = {
    // https://docs.microsoft.com/en-us/azure/best-practices-availability-paired-regions
    "eastasia" = "southeastasia"
    "southeastasia" = "eastasia"
    "centralus" = "eastus2"
    "eastus" = "westus"
    "eastus2" = "centralus"
    "westus" = "eastus"
    "northcentralus" = "southcentralus"
    "southcentralus" = "northcentralus"
    "northeurope" = "westeurope"
    "westeurope" = "northeurope"
    "japanwest" = "japaneast"
    "japaneast" = "japanwest"
    "brazilsouth" = "southcentralus"
    "australiaeast" = "australiasoutheast"
    "australiasoutheast" = "australiaeast"
    "australiacentral" = "australiacentral2"
    "australiacentral2" = "australiacentral"
    "southindia" = "centralindia"
    "centralindia" = "southindia"
    "westindia" = "southindia"
    "canadacentral" = "canadaeast"
    "canadaeast" = "canadacentral"
    "uksouth" = "ukwest"
    "ukwest" = "uksouth"
    "westcentralus" = "westus2"
    "westus2" = "westcentralus"
    "koreacentral" = "koreasouth"
    "koreasouth" = "koreacentral"
    "francecentral" = "francesouth"
    "francesouth" = "francecentral"
    "uaenorth" = "uaecentral"
    "uaecentral" = "uaenorth"
    "southafricanorth" = "southafricawest" 
    "southafricawest" = "southafricanorth"
    "germanycentral" = "germanynortheast"
    "germanynortheast" = "germanycentral"
  }   
}

resource "azurerm_sql_server" "secondary_sql_db_server" {
  depends_on = [ azurerm_resource_group.azure-sql-fog ]
  name                         = format("%s-secondary", var.instance_name)
  resource_group_name          = var.resource_group
  location                     = local.default_pair[var.location]
  version                      = "12.0"
  administrator_login          = random_string.username.result
  administrator_login_password = random_password.password.result
  tags                         = var.labels
}

resource "azurerm_mssql_database" "azure_sql_db" {
  name                = var.db_name
  server_id           = azurerm_sql_server.primary_azure_sql_db_server.id
  sku_name            = var.sku_name
  max_size_gb         = var.max_storage_gb
  tags                = var.labels
}

resource "azurerm_sql_failover_group" "failover_group" {
  depends_on = [ azurerm_resource_group.azure-sql-fog ]
  name                = var.instance_name
  resource_group_name = var.resource_group
  server_name         = azurerm_sql_server.primary_azure_sql_db_server.name
  databases           = [azurerm_mssql_database.azure_sql_db.id]
  partner_servers {
    id = azurerm_sql_server.secondary_sql_db_server.id
  }

  read_write_endpoint_failover_policy {
    mode          = "Automatic"
    grace_minutes = 5
  }
}

output primary_server_name { value = azurerm_sql_server.primary_azure_sql_db_server.name }
output secondary_server_name { value = azurerm_sql_server.secondary_sql_db_server.name }
output failover_group_name { value = azurerm_sql_failover_group.failover_group.name }
output resource_group { value = var.resource_group }
output db_name { value = azurerm_mssql_database.azure_sql_db.name }
```
#### Terraform to import resulting failover group
*provider.tf*
```hcl
provider "azurerm" {
  version = "~> 2.51.0"
  features {}
}
```
*main.tf*
```hcl
resource "azurerm_mssql_database" "primary_db" {
}

resource "azurerm_mssql_database" "secondary_db" {
}

resource "azurerm_sql_failover_group" "failover_group" {
}
```
### Expected Behaviour

Once `terraform import` for the three resources is complete and the resulting terraform is cleaned `terraform apply` (with an update to the tags) should result in 0 to add, 1 to change, 0 to destroy

### Actual Behaviour

If the secondary db has a `create_mode` of *Secondary*, the db is destroyed and recreated.

if the secondary db does not have a `create_mode` of *Secondary*, the apply fails with 

```
Error: failure in issuing create/update request for SQL Database "test-db" Blob Auditing Policies(SQL Server "test-mssql-db-secondary"/ Resource Group "test-mssql-db-rg"): sql.ExtendedDatabaseBlobAuditingPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BlobAuditingIsNotSupportedOnGeoDr" Message="Blob auditing can be configured on primary databases only."bash
```

#### Create an example failover group

Use the *Example Failover Group to reproduce problem* segment above to create a failover group and get the Azure ID's for the resources
```bash
terraform init
terraform apply
export PRIMARY_DB_ID=$(az sql failover-group show --name $(terraform output failover_group_name | tr -d '\n\r') --server $(terraform output primary_server_name | tr -d '\n\r') --resource-group $(terraform output resource_group | tr -d '\n\r') --query databases[0] -o tsv)
export SECONDARY_DB_ID=$(az sql failover-group show --name $(terraform output failover_group_name | tr -d '\n\r') --server $(terraform output secondary_server_name | tr -d '\n\r') --resource-group $(terraform output resource_group | tr -d '\n\r') --query databases[0] -o tsv)
export FOG_ID=$(az sql failover-group show --name $(terraform output failover_group_name | tr -d '\n\r') --server $(terraform output primary_server_name | tr -d '\n\r') --resource-group $(terraform output resource_group | tr -d '\n\r') --query id -o tsv)
```

#### Import the failover group and db's

In a new directory, put *provider.tf* and *main.tf* files from above, import the db's and failover group, and use show to get the updated *main.tf*

```bash
terraform init
terraform import azurerm_mssql_database.primary_db ${PRIMARY_DB_ID}
terraform import azurerm_mssql_database.secondary_db ${SECONDARY_DB_ID}
terraform import azurerm_sql_failover_group.failover_group ${FOG_ID}
mv main.tf main.tf.orig
terraform show -no-color > main.tf
```

#### Clean out the new main.tf
Some values are readonly and can't be applied.

Remove or comment out the following from *main.tf*
* azurerm_mssql_database.primary_db.id
* azurerm_mssql_database.primary_db.long_term_retention_policy
* azurerm_mssql_database.secondary_db.id
* azurerm_mssql_database.secondary_db.long_term_retention_policy
* azurerm_sql_failover_group.failover_group.id
* azurerm_sql_failover_group.failover_group.location
* azurerm_sql_failover_group.failover_group.role
* azurerm_sql_failover_group.failover_group.partner_servers.location
* azurerm_sql_failover_group.failover_group.partner_servers.role

#### Attempt to apply
```bash
terraform apply
```

Should fail with 
```bash
Error: failure in issuing create/update request for SQL Database "test-db" Blob Auditing Policies(SQL Server "test-mssql-db-secondary"/ Resource Group "test-mssql-db-rg"): sql.ExtendedDatabaseBlobAuditingPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BlobAuditingIsNotSupportedOnGeoDr" Message="Blob auditing can be configured on primary databases only."
```

#### Change `create_mode` to *Secondary*
Add the following to `azurerm_mssql_database.secondary_db`:
```
    create_mode = "Secondary"
```

Run `terraform plan` and it'll want to destroy and recreate the db, which is very unwanted.

```bash
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

azurerm_sql_failover_group.failover_group: Refreshing state... [id=/subscriptions/899bf076-632b-4143-b015-43da8179e53f/resourceGroups/test-mssql-db-rg/providers/Microsoft.Sql/servers/test-mssql-db-primary/failoverGroups/test-mssql-db]
azurerm_mssql_database.primary_db: Refreshing state... [id=/subscriptions/899bf076-632b-4143-b015-43da8179e53f/resourceGroups/test-mssql-db-rg/providers/Microsoft.Sql/servers/test-mssql-db-primary/databases/test-db]
azurerm_mssql_database.secondary_db: Refreshing state... [id=/subscriptions/899bf076-632b-4143-b015-43da8179e53f/resourceGroups/test-mssql-db-rg/providers/Microsoft.Sql/servers/test-mssql-db-secondary/databases/test-db]

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # azurerm_mssql_database.secondary_db must be replaced
-/+ resource "azurerm_mssql_database" "secondary_db" {
        auto_pause_delay_in_minutes = 0
        collation                   = "SQL_Latin1_General_CP1_CI_AS"
      + create_mode                 = "Secondary" # forces replacement
      + creation_source_database_id = (known after apply)
        extended_auditing_policy    = []
      ~ id                          = "/subscriptions/899bf076-632b-4143-b015-43da8179e53f/resourceGroups/test-mssql-db-rg/providers/Microsoft.Sql/servers/test-mssql-db-secondary/databases/test-db" -> (known after apply)
        license_type                = "LicenseIncluded"
        max_size_gb                 = 10
        min_capacity                = 0
        name                        = "test-db"
        read_replica_count          = 0
        read_scale                  = false
      + restore_point_in_time       = (known after apply)
      + sample_name                 = (known after apply)
        server_id                   = "/subscriptions/899bf076-632b-4143-b015-43da8179e53f/resourceGroups/test-mssql-db-rg/providers/Microsoft.Sql/servers/test-mssql-db-secondary"
        sku_name                    = "GP_Gen5_2"
        storage_account_type        = "GRS"
        tags                        = {
            "creator" = "eb"
        }
        zone_redundant              = false

      ~ long_term_retention_policy {
          ~ monthly_retention = "PT0S" -> (known after apply)
          ~ week_of_year      = 0 -> (known after apply)
          ~ weekly_retention  = "PT0S" -> (known after apply)
          ~ yearly_retention  = "PT0S" -> (known after apply)
        }

        short_term_retention_policy {
            retention_days = 7
        }

      ~ threat_detection_policy {
          - disabled_alerts      = [] -> null
            email_account_admins = "Disabled"
          - email_addresses      = [] -> null
            retention_days       = 0
            state                = "Disabled"
          + use_server_default   = "Disabled"
        }

        timeouts {}
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Warning: "extended_auditing_policy": [DEPRECATED] the `extended_auditing_policy` block has been moved to `azurerm_mssql_server_extended_auditing_policy` and `azurerm_mssql_database_extended_auditing_policy`. This block will be removed in version 3.0 of the provider.

  on main.tf line 2, in resource "azurerm_mssql_database" "primary_db":
   2: resource "azurerm_mssql_database" "primary_db" {

(and one more similar warning elsewhere)


------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

### Important Factoids

We have a few customers with many failover groups they would like to assume control over and this behavior is preventing the secondary db from being cleanly imported.

### References

Thought the `create_mode = "Secondary"` was a fix, but since it results in a re-creation of the secondary db, its not.

* https://github.com/terraform-providers/terraform-provider-azurerm/issues/8892

### PR DESCRIPTION
**Pull request by aristosvo**
Fixes #11024

### CODE REVIEW

File: azurerm/internal/services/mssql/mssql_database_resource.go [hunk 1]
```diff
@@ -558,6 +558,9 @@ func resourceMsSqlDatabaseRead(d *schema.ResourceData, meta interface{}) error {
 		d.Set("sku_name", props.CurrentServiceObjectiveName)
 		d.Set("storage_account_type", props.StorageAccountType)
 		d.Set("zone_redundant", props.ZoneRedundant)
+		if props.CreateMode != "" {
+			d.Set("create_mode", props.CreateMode)
+		}
```
Comment (tombuildsstuff) [inline azurerm/internal/services/mssql/mssql_database_resource.go:563]: rather than doing this, can we instead put this in the Import function above, making that:

```go
		Importer: azSchema.ValidateResourceIDPriorToImportThen(func(id string) error {
			_, err := parse.DatabaseID(id)
			return err
		}, func(d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
			d.Set("create_mode", "Default")
			if v, ok := d.GetOk("create_mode"); ok && v.(string) != "" {
				d.Set("create_mode", v)
			}
			
			return []*schema.ResourceData{d}, nil
		}),
```

which means this'll only be set at Import time

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
hey @aristosvo 

Thanks for this PR - taking a look through this looks pretty good to me, but if we can move this to the Import function rather than the Read (since this is an import-specific fix) then this should otherwise be good to go 👍 

Thanks!

File: azurerm/internal/services/mssql/mssql_database_resource.go (hunk 1 above)
Comment (aristosvo) [reply azurerm/internal/services/mssql/mssql_database_resource.go]: Thanks, done! Normally I would also run the AccTests myself to validate, but I ran out of credits in my personal account, so that's up to you 😊

**Comment by tombuildsstuff** [comment]
@aristosvo I've tested this locally and realised there's some further changes needed here, so I hope you don't mind but I'm going to push a couple of commits to fix this, namely it appears we also need to change the Computed value out for a Default (since the API doesn't return one) and add a state migration here to ensure that's set for older resources - will confirm the upgrade path in a while.

**Comment by aristosvo** [comment]
No problem! Thanks for taking over!

**Comment by aristosvo** [comment]
@tombuildsstuff Just curious, the state migration is just adding the previous schema and a migration function to a migration package? Are there specific tricks to take into account?

Looks a bit less complicated than it sounded 👍🏽

**Comment by tombuildsstuff** [comment]
@aristosvo pretty much, the complexity there is more in terms of testing than the code itself - also de-duping references to the schema, since it's a point-in-time reference to the schema at the time the migration should occur

From a testing perspective it's then confirming the upgrade path - but this is a one-way upgrade so it's a little bit of a pain to test, all in all it's not that involved it's just painful copying/making the point in time reference of the schema :)

**Comment by tombuildsstuff** [comment]
State migration runs clean:

```
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

**Comment by aristosvo** [comment]
@tombuildsstuff Although the code works fine, the initial problem is not solved.

This is the setup:
```hcl
variable instance_name { 
    type = string
    default = "test-mssql-db-2191" 
}
variable resource_group { 
    type = string
    default = "test-mssql-db-rg" 
}
variable db_name { 
    type = string
    default = "test-db"
}
variable location { 
    type = string 
    default = "westeurope"
}
variable labels { 
    type = map
    default = {} 
}
variable sku_name { 
    type = string 
    default = "GP_Gen5_2"
}
variable max_storage_gb { 
    type = number 
    default = 10
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "azure-sql-fog" {
  name     = var.resource_group
  location = var.location
  tags     = var.labels
}

resource "random_string" "username" {
  length = 16
  special = false
  number = false
}

resource "random_password" "password" {
  length = 64
  override_special = "~_-."
  min_upper = 2
  min_lower = 2
  min_special = 2
}

resource "azurerm_sql_server" "primary_azure_sql_db_server" {
  depends_on = [ azurerm_resource_group.azure-sql-fog ]
  name                         = format("%s-primary", var.instance_name)
  resource_group_name          = var.resource_group
  location                     = var.location
  version                      = "12.0"
  administrator_login          = random_string.username.result
  administrator_login_password = random_password.password.result
  tags = var.labels
}

locals {
  default_pair = {
    // https://docs.microsoft.com/en-us/azure/best-practices-availability-paired-regions
    "eastasia" = "southeastasia"
    "southeastasia" = "eastasia"
    "centralus" = "eastus2"
    "eastus" = "westus"
    "eastus2" = "centralus"
    "westus" = "eastus"
    "northcentralus" = "southcentralus"
    "southcentralus" = "northcentralus"
    "northeurope" = "westeurope"
    "westeurope" = "northeurope"
    "japanwest" = "japaneast"
    "japaneast" = "japanwest"
    "brazilsouth" = "southcentralus"
    "australiaeast" = "australiasoutheast"
    "australiasoutheast" = "australiaeast"
    "australiacentral" = "australiacentral2"
    "australiacentral2" = "australiacentral"
    "southindia" = "centralindia"
    "centralindia" = "southindia"
    "westindia" = "southindia"
    "canadacentral" = "canadaeast"
    "canadaeast" = "canadacentral"
    "uksouth" = "ukwest"
    "ukwest" = "uksouth"
    "westcentralus" = "westus2"
    "westus2" = "westcentralus"
    "koreacentral" = "koreasouth"
    "koreasouth" = "koreacentral"
    "francecentral" = "francesouth"
    "francesouth" = "francecentral"
    "uaenorth" = "uaecentral"
    "uaecentral" = "uaenorth"
    "southafricanorth" = "southafricawest" 
    "southafricawest" = "southafricanorth"
    "germanycentral" = "germanynortheast"
    "germanynortheast" = "germanycentral"
  }   
}

resource "azurerm_sql_server" "secondary_sql_db_server" {
  depends_on = [ azurerm_resource_group.azure-sql-fog ]
  name                         = format("%s-secondary", var.instance_name)
  resource_group_name          = var.resource_group
  location                     = local.default_pair[var.location]
  version                      = "12.0"
  administrator_login          = random_string.username.result
  administrator_login_password = random_password.password.result
  tags                         = var.labels
}

resource "azurerm_mssql_database" "azure_sql_db" {
  name                = var.db_name
  server_id           = azurerm_sql_server.primary_azure_sql_db_server.id
  sku_name            = var.sku_name
  max_size_gb         = var.max_storage_gb
  tags                = var.labels
}

resource "azurerm_sql_failover_group" "failover_group" {
  depends_on = [ azurerm_resource_group.azure-sql-fog ]
  name                = var.instance_name
  resource_group_name = var.resource_group
  server_name         = azurerm_sql_server.primary_azure_sql_db_server.name
  databases           = [azurerm_mssql_database.azure_sql_db.id]
  partner_servers {
    id = azurerm_sql_server.secondary_sql_db_server.id
  }

  read_write_endpoint_failover_policy {
    mode          = "Automatic"
    grace_minutes = 5
  }
}

# resource "azurerm_mssql_database" "secondary_db" {
#   name                = var.db_name
#   server_id           = azurerm_sql_server.secondary_sql_db_server.id
#   sku_name            = var.sku_name
#   max_size_gb         = var.max_storage_gb
#   tags                = var.labels
#   create_mode         = "Secondary"
# }

```

After the `terraform apply`, an import (of the uncommented `secondary_db`) creates a` secondary_db` in state with `create_mode = "Default"`. During import, when calling `value, ok := d.GetOk` to get the configuration, `ok = false` and `value = nil`.

**Comment by aristosvo** [comment]
@tombuildsstuff Ping! Is it possible to validate the `Possible solutions` [here](https://github.com/terraform-providers/terraform-provider-azurerm/pull/11026#issuecomment-803154168), so I can implement one of them?

**Comment by katbyte** [comment]
@aristosvo - this is similar to what you did with postgres? sounds like a good solution to me 🙂

**Comment by aristosvo** [comment]
@katbyte Thanks! I've submitted an improved version of my proposal, haven't tested it yet but the foundations is the same/better. Will rebase in a few minutes.

**Comment by aristosvo** [comment]
Against `master`:
```
❯ make acctests SERVICE='mssql' TESTARGS='-run=TestAccMsSqlDatabase_createSecondaryMode\|TestAccMsSqlDatabase_scaleReplicaSetWithFailovergroup'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./azurerm/internal/services/mssql -run=TestAccMsSqlDatabase_createSecondaryMode\|TestAccMsSqlDatabase_scaleReplicaSetWithFailovergroup -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
2021/04/28 15:41:41 [DEBUG] not using binary driver name, it's no longer needed
2021/04/28 15:41:42 [DEBUG] not using binary driver name, it's no longer needed
=== RUN   TestAccMsSqlDatabase_createSecondaryMode
=== PAUSE TestAccMsSqlDatabase_createSecondaryMode
=== RUN   TestAccMsSqlDatabase_scaleReplicaSetWithFailovergroup
=== PAUSE TestAccMsSqlDatabase_scaleReplicaSetWithFailovergroup
=== CONT  TestAccMsSqlDatabase_createSecondaryMode
=== CONT  TestAccMsSqlDatabase_scaleReplicaSetWithFailovergroup
    testing_new_import_state.go:249: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
        
        (map[string]string) {
        }
        
        
        (map[string]string) (len=1) {
         (string) (len=11) "create_mode": (string) (len=9) "Secondary"
        }
=== CONT  TestAccMsSqlDatabase_createSecondaryMode
    testing_new_import_state.go:249: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
        
        (map[string]string) {
        }
        
        
        (map[string]string) (len=1) {
         (string) (len=11) "create_mode": (string) (len=9) "Secondary"
        }
--- FAIL: TestAccMsSqlDatabase_scaleReplicaSetWithFailovergroup (437.81s)
--- FAIL: TestAccMsSqlDatabase_createSecondaryMode (459.95s)
FAIL
FAIL    github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/mssql       463.287s
FAIL
make: *** [acctests] Error 1
```

Against PR branch:
```
❯ make acctests SERVICE='mssql' TESTARGS='-run=TestAccMsSqlDatabase_createSecondaryMode\|TestAccMsSqlDatabase_scaleReplicaSetWithFailovergroup'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./azurerm/internal/services/mssql -run=TestAccMsSqlDatabase_createSecondaryMode\|TestAccMsSqlDatabase_scaleReplicaSetWithFailovergroup -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
2021/04/28 16:24:14 [DEBUG] not using binary driver name, it's no longer needed
2021/04/28 16:24:15 [DEBUG] not using binary driver name, it's no longer needed
=== RUN   TestAccMsSqlDatabase_createSecondaryMode
=== PAUSE TestAccMsSqlDatabase_createSecondaryMode
=== RUN   TestAccMsSqlDatabase_scaleReplicaSetWithFailovergroup
=== PAUSE TestAccMsSqlDatabase_scaleReplicaSetWithFailovergroup
=== CONT  TestAccMsSqlDatabase_createSecondaryMode
=== CONT  TestAccMsSqlDatabase_scaleReplicaSetWithFailovergroup
--- PASS: TestAccMsSqlDatabase_createSecondaryMode (429.97s)
=== CONT  TestAccMsSqlDatabase_scaleReplicaSetWithFailovergroup
--- PASS: TestAccMsSqlDatabase_scaleReplicaSetWithFailovergroup (971.87s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/mssql        975.440s
```

**Review by katbyte — APPROVED** [review]
Thanks @aristosvo - LGTM 👍
