### PR TITLE
azurerm_api_management_logger:  add resource_id attribute

### LINKED ISSUE #10548: api management logger doesn't set the application insights resource id
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform version: 0.14.5
AzureRM version : 2.46.1

### Affected Resource(s)

* `azurerm_api_management_logger`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_application_insights" "example" {
  name                = "example-appinsights"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  application_type    = "other"
}

resource "azurerm_api_management" "example" {
  name                = "example-apim-test"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  publisher_name      = "My Company"
  publisher_email     = "company@terraform.io"

  sku_name = "Developer_1"
}

resource "azurerm_api_management_logger" "example" {
  name                = "example-appinsights"
  api_management_name = azurerm_api_management.example.name
  resource_group_name = azurerm_resource_group.example.name

  application_insights {
    instrumentation_key = azurerm_application_insights.example.instrumentation_key
  }
}
```

### Expected Behaviour

{
  "value": [
    {
      "id": "/subscriptions/XXX/resourceGroups/example-resources/providers/Microsoft.ApiManagement/service/example-apim-test/diagnostics/applicationinsights/loggers/example-appinsights",
      "type": "Microsoft.ApiManagement/service/diagnostics/loggers",
      "name": "example-appinsights",
      "properties": {
        "loggerType": "applicationInsights",
        "description": "",
        "credentials": {
          "instrumentationKey": "{{Logger-Credentials--12345}}"
        },
        "isBuffered": true,
        **"resourceId": "/subscriptions/XXX/resourceGroups/example-resources/providers/microsoft.insights/components/example-appinsights"**
      }
    }
  ],
  "count": 1
}

### Actual Behaviour
{
  "value": [
    {
      "id": "/subscriptions/XXX/resourceGroups/example-resources/providers/Microsoft.ApiManagement/service/example-apim-test/diagnostics/applicationinsights/loggers/example-appinsights",
      "type": "Microsoft.ApiManagement/service/diagnostics/loggers",
      "name": "example-appinsights",
      "properties": {
        "loggerType": "applicationInsights",
        "description": "",
        "credentials": {
          "instrumentationKey": "{{Logger-Credentials--12345}}"
        },
        "isBuffered": true,
        **"resourceId": null**
      }
    }
  ],
  "count": 1
}

If the resource id is not set you can't jump from api management to app insights. The goto button has grey color.

### Steps to Reproduce

1. `terraform apply`

### PR DESCRIPTION
**Pull request by patst**
This adds the link to a resource to the logger configuration (https://github.com/terraform-providers/terraform-provider-azurerm/issues/10548). This way you can jump in the Azure Portal to the configured logger.

I wasn't sure about the naming (`resource_id`), maybe it could be more prescriptive.

The test case passed:

```
make testacc TEST='./azurerm/internal/services/apimanagement/api_management_logger_resource_test.go' TESTARGS='-run=TestAccApiManagementLogger_complete' TESTTIMEOUT='120m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test ./azurerm/internal/services/apimanagement/api_management_logger_resource_test.go -v -run=TestAccApiManagementLogger_complete -timeout 120m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccApiManagementLogger_complete
=== PAUSE TestAccApiManagementLogger_complete
=== CONT  TestAccApiManagementLogger_complete
--- PASS: TestAccApiManagementLogger_complete (2757.20s)
PASS
ok      command-line-arguments  2759.035s
```

Fixes #10548

### CODE REVIEW

File: azurerm/internal/services/apimanagement/api_management_logger_resource.go [hunk 1]
```diff
@@ -142,6 +148,9 @@ func resourceApiManagementLoggerCreate(d *schema.ResourceData, meta interface{})
 		parameters.Credentials = expandApiManagementLoggerApplicationInsights(appInsightsRaw)
 	}
 
+	resourceId := utils.String(d.Get("resource_id").(string))
+	parameters.ResourceID = resourceId
```
Comment (tombuildsstuff) [inline azurerm/internal/services/apimanagement/api_management_logger_resource.go:152]: since this is optional we may need to make this conditional:

```suggestion
	if resourceId := d.Get("resource_id").(string); resourceId != "" {
		parameters.ResourceID = utils.String(resourceId)
	}
```

File: website/docs/r/api_management_logger.html.markdown [hunk 2]
```diff
@@ -66,6 +67,7 @@ The following arguments are supported:
 
 * `eventhub` - (Optional) An `eventhub` block as documented below.
 
+* `resource_id` - (Optional) The target resource id which will be linked in the API-Management portal page.
```
Comment (tombuildsstuff) [inline website/docs/r/api_management_logger.html.markdown:70]: we need to add a divider here, else this is rendered as a title (`h1`)

```suggestion
* `resource_id` - (Optional) The target resource id which will be linked in the API-Management portal page.

```

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
hey @patst 

Thanks for this PR - I've taken a look through and left some comments inline, but this is otherwise looking good - if we can fix those up then this should be good to go 👍 

Thanks!

**Review by jackofallops — APPROVED** [review]
Thanks @patst for the changes. This LGTM now 👍
