### PR TITLE
`azurerm_frontdoor_custom_https_configuration` - add support for import

### LINKED ISSUE #11623: Front Door: Upgrade 2.57 -> 2.58 breaks on existing FD instances with inline HTTPS configuration
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

AzureRM: 2.57 & 2.58
Terraform: 0.14.11

### Affected Resource(s)

* `azurerm_frontdoor`
* `azurerm_frontdoor_custom_https_configuration`

### Terraform Configuration Files

For 2.57

```hcl
resource "azurerm_frontdoor" "fd" {
  name                                         = "sample-frontdoor-brc"
  resource_group_name                          = azurerm_resource_group.rg.name
  enforce_backend_pools_certificate_name_check = true
  tags = {
    "Version" = "4.0.2"
  }

  backend_pool {
    health_probe_name   = "health-probe"
    load_balancing_name = "backend-lb"
    name                = "backend"
    backend {
      address     = "www.bing.com"
      host_header = "www.bing.com"
      http_port   = 80
      https_port  = 443
    }
  }

  backend_pool_load_balancing {
    name = "backend-lb"
  }

  backend_pool_health_probe {
    <snipped for brevity>
  }

  frontend_endpoint {
    name      = "default"
    host_name = "sample-frontdoor-brc.azurefd.net"
  }

  frontend_endpoint {
    name      = "custom"
    host_name = "sample-frontdoor-brc.sandbox.provider.engineering"

    custom_https_provisioning_enabled = true
    custom_https_configuration {
      certificate_source = "FrontDoor"
    }
  }

  routing_rule {
     <snipped for brevity>
  }
}
```

For 2.58

```hcl
resource "azurerm_frontdoor" "fd" {
  name                                         = "sample-frontdoor-brc"
  resource_group_name                          = azurerm_resource_group.rg.name
  enforce_backend_pools_certificate_name_check = true
  tags = {
    "Version" = "4.0.2"
  }

  backend_pool {
    <snipped for brevity>
  }

  backend_pool_load_balancing {
    name = "backend-lb"
  }

  backend_pool_health_probe {
    <snipped for brevity>
  }

  frontend_endpoint {
    name      = "default"
    host_name = "sample-frontdoor-brc.azurefd.net"
  }

  frontend_endpoint {
    name      = "custom"
    host_name = "sample-frontdoor-brc.sandbox.provider.engineering"
  }

  routing_rule {
     <snipped for brevity>
  }
}

resource "azurerm_frontdoor_custom_https_configuration" "fd_custom_url" {
  frontend_endpoint_id              = azurerm_frontdoor.fd.frontend_endpoint[1].id
  custom_https_provisioning_enabled = true

  custom_https_configuration {
    certificate_source = "FrontDoor"
  }
}
```

### Debug Output

Post a comment below if it is needed. I have to make sure that the debug output does not contain any sensitive info before I put it here in the issue or in a paste bin.

### Panic Output

N/A

### Expected Behaviour

Unsure really. Are we supposed to delete the Front Door first before going from 2.57 to 2.58? Or is it supposed to just ignore the existing certificate on the Front Door.

### Actual Behaviour

First error when running `terraform apply`:

```text
azurerm_frontdoor.fd: Modifying... [id=/subscriptions/[redacted]/resourceGroups/frontdoor-issue-brc/providers/Microsoft.Network/frontDoors/sample-frontdoor-brc]
azurerm_frontdoor.fd: Modifications complete after 3s [id=/subscriptions/[redacted]/resourceGroups/frontdoor-issue-brc/providers/Microsoft.Network/frontDoors/sample-frontdoor-brc]
azurerm_frontdoor_custom_https_configuration.fd_custom_url: Creating...

Error: updating Custom HTTPS configuration for Frontend Endpoint "custom"
(Front Door "sample-frontdoor-brc" / Resource Group "frontdoor-issue-brc"): unable to enable/update Custom Domain HTTPS for Frontend Endpoint "custom" (Resource Group "frontdoor-issue-brc"): enabling Custom Domain HTTPS for Frontend Endpoint: frontdoor.FrontendEndpointsClient#EnableHTTPS: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="That action isn’t allowed in this profile."
```

Second error when running `terraform apply`:

```text
azurerm_frontdoor_custom_https_configuration.fd_custom_url: Creating...

Error: updating Custom HTTPS configuration for Frontend Endpoint "custom" (Front Door "sample-frontdoor-brc" / Resource Group "frontdoor-issue-brc"): unable to enable/update Custom Domain HTTPS for Frontend Endpoint "custom"
(Resource Group "frontdoor-issue-brc"): enabling Custom Domain HTTPS for Frontend Endpoint:
frontdoor.FrontendEndpointsClient#EnableHTTPS: Failure sending request: StatusCode=0 -- Original Error:
Code="OperationNotAllowed" Message="Frontend endpoint custom is already secured with a managed certificate.
Only the Minimum TLS Version property for a managed certificate configuration can be updated. All other updates are not suppored."
```

### Steps to Reproduce

1. Pin your configuration to AzureRM 2.57 (or earlier)
2. Create a Front Door resource using the custom HTTPS configuration inline resource
3. `terraform apply`
4. DO NOT DESTROY!
5. Remove the pinned version so that AzureRM 2.58 can be downloaded
    1. You may have to run `terraform init -upgrade` because of the lock file
6. Remove the inline configuration in `azurerm_frontdoor`.
7. Add the custom HTTPS configuration through `azurerm_frontdoor_custom_https_configuration`
8. `terraform apply`
9. Change **nothing** and run `terraform apply` for the second error

### Important Factoids

N/A

### References

* #11456

### PR DESCRIPTION
**Pull request by WodansSon**
Add support for `azurerm_frontdoor_custom_https_configuration` resource import.

(fixes #11623)

### CODE REVIEW

File: azurerm/internal/services/frontdoor/frontdoor_custom_https_configuration_resource.go [hunk 1]
```diff
@@ -26,10 +26,34 @@ func resourceFrontDoorCustomHttpsConfiguration() *schema.Resource {
...
+				if err != nil {
+					return []*schema.ResourceData{d}, fmt.Errorf("parsing Custom HTTPS Configuration ID %q for import: %v", d.Id(), err)
+				}
+
+				// convert the passed custom HTTPS configuration ID to a frontend endpoint ID
+				frontend := parse.NewFrontendEndpointID(custom.SubscriptionId, custom.ResourceGroup, custom.FrontDoorName, custom.CustomHttpsConfigurationName)
+
+				// validate that the frontend endpoint ID exists in the Frontdoor resource
+				_, err = client.Get(ctx, custom.ResourceGroup, custom.FrontDoorName, custom.CustomHttpsConfigurationName)
+				if err != nil {
```
Comment (katbyte) [inline azurerm/internal/services/frontdoor/frontdoor_custom_https_configuration_resource.go:46]: these lines can be merged

**Review by katbyte — APPROVED** [review]
Thanks @WodansSon - LGTM 👍

File: website/docs/r/frontdoor_custom_https_configuration.html.markdown [hunk 2]
```diff
@@ -10,8 +10,6 @@ description: |-
 
 Manages the Custom Https Configuration for an Azure Front Door Frontend Endpoint..
 
-~> **NOTE:** Custom https configurations for a Front Door Frontend Endpoint can be defined both within [the `azurerm_frontdoor` resource](frontdoor.html) via the `custom_https_configuration` block and by using a separate resource, as described in the following sections.
```
Comment (katbyte) [inline website/docs/r/frontdoor_custom_https_configuration.html.markdown:13]: should we link to the new guide on this page?

File: website/docs/guides/2.58.0-frontdoor-upgrade-guide.html.markdown [hunk 3]
```diff
@@ -0,0 +1,451 @@
...
+
+## Breaking Changes
+
+* `azurerm_frontdoor` - The `custom_https_provisioning_enabled` field and the `custom_https_configuration` block have been removed from the `azurerm_frontdoor` resource due to changes made by the service team. What this means is you have a `azurerm_frontdoor` configuration file with a `custom_https_configuration` block currently defined, once you upgrade to v2.58.0 you will need to remove that code from the configuration file and define a separate `azurerm_frontdoor_custom_https_configuration` block in your configuration file for each frontend endpoint reguardless if it had a `custom_https_configuration` block or not. If you do not remove these configuration file values after you upgrade you will receive a `An argument named "custom_https_provisioning_enabled" is not expected here.` or `An argument named "custom_https_configuration" is not expected here.` error.
```
Comment (katbyte) [inline website/docs/guides/2.58.0-frontdoor-upgrade-guide.html.markdown:17]:
```suggestion
* `azurerm_frontdoor` - The `custom_https_provisioning_enabled` field and the `custom_https_configuration` block have been removed from the `azurerm_frontdoor` resource due to changes made by the service team. What this means is you have a `azurerm_frontdoor` configuration file with a `custom_https_configuration` block currently defined, once you upgrade to `v2.58.0` you will need to remove that code from the configuration file and define a separate `azurerm_frontdoor_custom_https_configuration` block in your configuration file for each frontend endpoint regardless if it had a `custom_https_configuration` block or not. If you do not remove these configuration file values after you upgrade you will receive a `An argument named "custom_https_provisioning_enabled" is not expected here.` or `An argument named "custom_https_configuration" is not expected here.` error.
```

File: website/docs/guides/2.58.0-frontdoor-upgrade-guide.html.markdown [hunk 4]
```diff
@@ -0,0 +1,451 @@
...
+
+* `azurerm_frontdoor_custom_https_configuration` - The `resource_group_name` field has been removed from the `azurerm_frontdoor_custom_https_configuration` resource. If the `resource_group_name` field has been defined in your current `azurerm_frontdoor_custom_https_configuration` resource configuration file please remove it else you will receive a `An argument named "resource_group_name" is not expected here.` error.
+
+
+# How to Migrate Your Current Front Door Configuration to Azure Resource Manager: v2.58.0
+
+For this upgrade guide we are going to assume that your configuration file looks something like the below example before you upgraded to v2.58.0 of the Azure provider. For this upgrade guide we are also assuming that the Front Door resource already exists in Azure and that it is curretnly being managed by Terraform.
```
Comment (katbyte) [inline website/docs/guides/2.58.0-frontdoor-upgrade-guide.html.markdown:24]:
```suggestion
For this upgrade guide we are going to assume that your configuration file looks something like the below example before you upgraded to `v2.58.0` of the Azure provider. For this upgrade guide we are also assuming that the Front Door resource already exists in Azure and that it is curretnly being managed by Terraform.
```

File: website/docs/guides/2.58.0-frontdoor-upgrade-guide.html.markdown [hunk 5]
```diff
@@ -0,0 +1,451 @@
...
+  }
+
+  backend_pool_health_probe {
+    name     = "example-AFD-google-HP"
+    protocol = "Https"
+  }
+}
+```
+
+Firstly, you will need to upgrade your provider to v2.58.0 or later in the way you normally would upgrade your provider, for more information about how to upgrade your provider please see the [product documentation](https://learn.hashicorp.com/tutorials/terraform/provider-versioning). For this upgrade guide I am going to force the upgrade via the configuration files `provider` block like this:
```
Comment (katbyte) [inline website/docs/guides/2.58.0-frontdoor-upgrade-guide.html.markdown:177]:
```suggestion
Firstly, you will need to upgrade your provider to `v2.58.0` or later in the way you normally would upgrade your provider, for more information about how to upgrade your provider please see the [product documentation](https://learn.hashicorp.com/tutorials/terraform/provider-versioning). For this upgrade guide I am going to force the upgrade via the configuration files `provider` block like this:
```

**Review by katbyte — APPROVED** [review]
Aside from a couple comments LGTM
