### PR TITLE
azurerm_hdinsights_*_cluster: loosen work node count validation

### LINKED ISSUE #7342: azurerm_hdinsight_hbase_cluster has incorrect worker node target_instance_count limit
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.12.6
+ provider.azurerm v1.44.0
```

### Affected Resource(s)

* `azurerm_hdinsight_hbase_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "mystorage" {
  // [...]
}

resource "azurerm_storage_container" "my-hdinsight" {
  // [...]
}

#
# Hbase cluster
#
resource "azurerm_hdinsight_hbase_cluster" "my-hdinsight" {
  name                = var.cluster_name
  resource_group_name = data.azurerm_resource_group.my_rg.name
  location            = var.location
  cluster_version     = "3.6"
  tier                = "Standard"

  component_version {
    hbase = "1.1"
  }

  gateway {
    enabled  = true
    username = var.gateway_username
    password = var.gateway_password
  }

  storage_account {
    storage_container_id = azurerm_storage_container.my-hdinsight.id
    storage_account_key  = azurerm_storage_account.mystorage.primary_access_key
    is_default           = true
  }

  roles {
    head_node {
      vm_size             = var.head_node_vm_size
      username            = var.username
      ssh_keys            = [var.ssh_key]
      subnet_id           = data.azurerm_subnet.subnet_selected.id
      virtual_network_id  = data.azurerm_virtual_network.selected.id
    }

    worker_node {
      vm_size                  = var.worker_node_vm_size
      username                 = var.username
      ssh_keys                 = [var.ssh_key]
      subnet_id                = data.azurerm_subnet.subnet_selected.id
      virtual_network_id       = data.azurerm_virtual_network.selected.id
      target_instance_count    = 27
    }

    zookeeper_node {
      vm_size            = var.zk_node_vm_size
      username           = var.username
      ssh_keys           = [var.ssh_key]
      subnet_id          = data.azurerm_subnet.subnet_selected.id
      virtual_network_id = data.azurerm_virtual_network.selected.id
    }
  }
}

```

### Debug Output

```
Error: expected roles.0.worker_node.0.target_instance_count to be in the range (1 - 23), got 27
```

### Panic Output
n/a

### Expected Behavior
An HDInsight HBase cluster should be created with 27 worker nodes.

### Actual Behavior
There is a limit of 23 worker nodes that does not match Azure documentation.
It seems likely that 23 is a typo that should be 32.

Additionally, if the head nodes are of sufficient size, there should not be a limit of 32 worker nodes
(Azure Documentation attached in references)

### Steps to Reproduce

1. `terraform plan`

### References

* Here is the line in the provider code:
https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/hdinsight/hdinsight_hbase_cluster_resource.go#L32

* Here is the Azure HDInsight Documentation suggesting the limit should be 32 if the head nodes are smaller than 8 cores with 14GB of memory
https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-supported-node-configuration
```
If you need more than 32 worker nodes in a cluster, select a head node size with at least 8 cores and 14 GB of RAM.
```

### PR DESCRIPTION
**Pull request by magodo**
The limitation should be loosened for work nodes (there already exists this case in the current [code base](https://github.com/terraform-providers/terraform-provider-azurerm/blob/5e66b05b25c3d78a55d14ccbd544a58f089776b3/azurerm/internal/services/hdinsight/hdinsight_storm_cluster_resource.go#L32)), and I can't find the source for current hard limits.

From the document: https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-supported-node-configuration

> If you need more than 32 worker nodes in a cluster, select a head node size with at least 8 cores and 14 GB of RAM.

And this is the exact behavior in Portal.

So I would suggest loosening the constraints for work node count.

(this fix #7342 )

### CODE REVIEW

File: azurerm/internal/services/hdinsight/hdinsight_hadoop_cluster_resource.go [hunk 1]
```diff
@@ -34,14 +34,13 @@ var hdInsightHadoopClusterHeadNodeDefinition = azure.HDInsightNodeDefinition{
...
 	MinInstanceCount:        1,
-	MaxInstanceCount:        25,
 	CanSpecifyDisks:         false,
 }
 
 var hdInsightHadoopClusterZookeeperNodeDefinition = azure.HDInsightNodeDefinition{
 	CanSpecifyInstanceCount:  false,
 	MinInstanceCount:         3,
-	MaxInstanceCount:         3,
+	MaxInstanceCount:         utils.Int(2),
```
Comment (jackofallops) [inline azurerm/internal/services/hdinsight/hdinsight_hadoop_cluster_resource.go:43]: Was this intended to be changed from 3 -> 2 ?

Comment (magodo) [reply azurerm/internal/services/hdinsight/hdinsight_hadoop_cluster_resource.go:43]: This is by mistake, thank you for pointing this!

**Comment by magodo** [comment]
@jackofallops I have updated the typo, please take a look :)

**Comment by jackofallops** [comment]
Tests looking good:
image
(Failures are unrelated / transient)
