### PR TITLE
`azurerm_subscription` - fix ability to specify `DevTest` as `workload`

### LINKED ISSUE #11232: azurerm_subscription workload parameter 'does not match config value'
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.9

- provider registry.terraform.io/hashicorp/azurerm v2.54.0

### Affected Resource(s)

* `azurerm_subscription` - workload

### Terraform Configuration Files

```hcl
resource "azurerm_subscription" "azureSubscription" {
  subscription_name = "testsub"
  billing_scope_id  = "/providers/Microsoft.Billing/billingAccounts/<BILLING_ACCOUNT_ID>/enrollmentAccounts/<ENROLLMENT_ACCOUNT_ID>"
  workload          = "DevTest"
}
```

### Expected Behaviour
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription#workload

Terraform plan shows the provided workload parameter.
Subscription will be created using the provided (in this case "DevTest") workload.

### Actual Behaviour

Subscription is created using the "Production" workload.

Terraform plan does not display the workload parameter at all:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.components.azurerm_subscription.azureSubscription will be created
  + resource "azurerm_subscription" "azureSubscription" {
      + alias             = (known after apply)
      + billing_scope_id  = "/providers/Microsoft.Billing/billingAccounts/<BILLING_ACCOUNT_ID>/enrollmentAccounts/<ENROLLMENT_ACCOUNT_ID>"
      + id                = (known after apply)
      + subscription_id   = (known after apply)
      + subscription_name = "testsub"
      + tags              = (known after apply)
      + tenant_id         = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

Terraform plan using the trace parameter gives the following output:
```
...
2021/04/07 07:50:53 [WARN] Provider "registry.terraform.io/hashicorp/azurerm" produced an invalid plan for module.components.azurerm_subscription.azureSubscription, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .workload: planned value cty.NullVal(cty.String) does not match config value cty.StringVal("DevTest")
...
```

We tested the workload parameter with "Production" aswell with the same behaviour in the plan and debug output.

### Steps to Reproduce

1. `terraform plan/apply`

### PR DESCRIPTION
**Pull request by jackofallops**
fixes #11232

### CODE REVIEW

File: azurerm/internal/services/subscription/subscription_resource.go [hunk 1]
```diff
@@ -86,7 +86,10 @@ func resourceSubscription() *pluginsdk.Resource {
 				}, false),
 				// Workload is not exposed in any way, so must be ignored if the resource is imported.
 				DiffSuppressFunc: func(k, old, new string, d *pluginsdk.ResourceData) bool {
-					return old == ""
+					if new != "" {
+						return false
+					}
+					return true
```
Comment (manicminer) [inline azurerm/internal/services/subscription/subscription_resource.go:92]: Maybe
```suggestion
					return new == ""
```
?

**Review by manicminer — APPROVED** [review]
Just a minor suggestion but otherwise LGTM 👍
