### PR TITLE
`azurerm_federated_identity_credential` - Deprecate the `resource_group_name`

### LINKED ISSUE #30825: azurerm_federated_identity_credential plan does not match apply - parent_id resource group name is lost
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.8

### AzureRM Provider Version

~>4 (exact version obscured by TF cloud)

### Affected Resource(s)/Data Source(s)

azurerm_federated_identity_credential (associated with parent azurerm_user_assigned_identity)

### Terraform Configuration Files

```hcl
Working in a constrained environment so unable to pull this together now, but refer to repro steps.
```

### Debug Output/Panic Output

```shell
Error: creating Federated Identity Credential (Subscription: "----" Resource Group Name: "rg-storm-simulation-lab-support-dev" User Assigned Identity Name: "mi-storm-simulation-lab-test-operator-dev" Federated Identity Credential Name: "storm-sim-lab-dev-e2-github-credential-storm-testing-app"): unexpected status 404 (404 Not Found) with error: ParentResourceNotFound: Failed to perform 'write' on resource(s) of type 'userAssignedIdentities/federatedIdentityCredentials', because the parent resource '/subscriptions/----/resourceGroups/rg-storm-simulation-lab-support-dev/providers/Microsoft.ManagedIdentity/userAssignedIdentities/mi-storm-simulation-lab-test-operator-dev' could not be found.
```

### Expected Behaviour

Here's the generated plan:
Image

* The `mi-storm-simulation-lab-test-operator-dev` User Assigned Identity should have been found in resource group `rg-storm-simulation-lab-dev`. This resource group is managed by separate TF configuration and credentials. 
* The Federated Identity Credentials should have been created in resource group `rg-storm-simulation-lab-support-dev`, where my team and our TF configuration exists.

I can find no documentation indicating that the Federated Identity Credentials *must* be created in the same resource group as the User Assigned Identity. If such a constraint is required, the plan should have failed (and likely `parent_id` should be a `user_assigned_identity_name` property instead, since the whole ID is clearly discarded and just the name used if such a constraint is required).

### Actual Behaviour

The plan clearly knows the parent User Assigned Identity the Federated Identity Credentials should be created for is in resource group `rg-storm-simulation-lab-dev` (see `parent_id` property); however, when apply the plan it tries to find the parent User Assigned Identity in resource group `rg-storm-simulation-lab-support-dev`. 

**Conclusion**: The `parent_id` value was not taken in its entirety. Instead, only the resource name portion of the resource ID was used, and it assumed that the parent is in the same resource group as the Federated Identity Credentials being created. The apply failed, indicating that the state from the plan was not used.

### Steps to Reproduce

1. Create a `azurerm_user_assigned_identity` in Resource Group `rg-storm-simulation-lab-dev`
2. Create a `azurerm_federated_identity_credential` in Resource Group `rg-storm-simulation-lab-support-dev`, with the `parent_id` referring to the User Assigned Identity's ID.

### Important Factoids

Terraform plan shows the state I want, but the apply tries to do something different. The plan and apply do not match. The apply is not respecting the generated plan. Via Terraform Cloud's workflow, the generated plan should have been utilized for the apply (I can't apply locally in the restricted environment).

### References

I know nothing about authoring low-level TF modules, but we can see here that the arguments to `NewFederatedIdentityCredentialID` just takes the `parentId.UserAssignedIdentityName`. And the parentId is parsed as the `config.ResourceName`:

```
			parentId, err := commonids.ParseUserAssignedIdentityID(config.ResourceName)
			if err != nil {
				return fmt.Errorf("parsing parent resource ID: %+v", err)
			}

			locks.ByID(parentId.ID())
			defer locks.UnlockByID(parentId.ID())

			id := managedidentities.NewFederatedIdentityCredentialID(subscriptionId, config.ResourceGroupName, parentId.UserAssignedIdentityName, config.Name)
```
[Source](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/managedidentity/federated_identity_credential_resource.go#L98-L106)

### PR DESCRIPTION
**Pull request by magodo**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Deprecate the `resource_group_name` for `azurerm_federated_identity_credential`, since it is already coded in the `parent_id` field. A `azurerm_federated_identity_credential` is a child resource of a `azurerm_user_assigned_identity`. E.g. the following is a sample HTTP request that one creates a FIC via Portal:

```
PUT 
https://management.azure.com//subscriptions/xxxx/resourceGroups/magodo-uai/providers/Microsoft.ManagedIdentity/userAssignedIdentities/test/federatedIdentityCredentials/my-cred?api-version=2023-01-31
```

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)
```shell
💢 ARM_FIVEPOINTZERO_BETA=true TF_ACC=1 go test -v -timeout=20h -run='TestAccFederatedIdentityCredential_' ./internal/services/managedidentity
=== RUN   TestAccFederatedIdentityCredential_basic
=== PAUSE TestAccFederatedIdentityCredential_basic
=== RUN   TestAccFederatedIdentityCredential_requiresImport
=== PAUSE TestAccFederatedIdentityCredential_requiresImport
=== CONT  TestAccFederatedIdentityCredential_basic
=== CONT  TestAccFederatedIdentityCredential_requiresImport
--- PASS: TestAccFederatedIdentityCredential_requiresImport (57.78s)
--- PASS: TestAccFederatedIdentityCredential_basic (76.15s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/managedidentity     76.175s

💤 TF_ACC=1 go test -v -timeout=20h -run='TestAccFederatedIdentityCredential_' ./internal/services/managedidentity
=== RUN   TestAccFederatedIdentityCredential_basic
=== PAUSE TestAccFederatedIdentityCredential_basic
=== RUN   TestAccFederatedIdentityCredential_requiresImport
=== PAUSE TestAccFederatedIdentityCredential_requiresImport
=== CONT  TestAccFederatedIdentityCredential_basic
=== CONT  TestAccFederatedIdentityCredential_requiresImport
--- PASS: TestAccFederatedIdentityCredential_requiresImport (61.14s)
--- PASS: TestAccFederatedIdentityCredential_basic (80.41s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/managedidentity      80.439s

```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-merging.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)

Fixes #30825

## AI Assistance Disclosure

- [ ] AI Assisted - This contribution was made by, or with the assistance of, AI/LLMs

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/managedidentity/federated_identity_credential_resource.go [hunk 1]
```diff
@@ -63,9 +67,8 @@ func (r FederatedIdentityCredentialResource) Arguments() map[string]*pluginsdk.S
 			Required: true,
 			Type:     pluginsdk.TypeString,
 		},
-		"resource_group_name": commonschema.ResourceGroupName(),
 		"parent_id": {
-			// TODO: this wants renaming to `user_assigned_identity_id` (and `resource_group_name` removing in 4.0)
+			// TODO: this wants renaming to `user_assigned_identity_id`
```
Comment (sreallymatt) [inline internal/services/managedidentity/federated_identity_credential_resource.go]: Could you leave the `4.0` bit in place (or change to 5.0)

We have an internal issue that we'll work on before the major release to find all `TODO 4.*` and `TODO 5.*` comments and implement them

**Review by sreallymatt — CHANGES_REQUESTED** [review]
Thanks @magodo - 1 minor comment, and could you rebase this on main to resolve the conflict?

File: internal/services/managedidentity/federated_identity_credential_resource.go (hunk 1 above)
Comment (magodo) [reply internal/services/managedidentity/federated_identity_credential_resource.go]: Done.

```shell
💤 TF_ACC=1 go test -v -run='TestAccFederatedIdentityCredential_' ./internal/services/managedidentity
=== RUN   TestAccFederatedIdentityCredential_basic
=== PAUSE TestAccFederatedIdentityCredential_basic
=== RUN   TestAccFederatedIdentityCredential_requiresImport
=== PAUSE TestAccFederatedIdentityCredential_requiresImport
=== CONT  TestAccFederatedIdentityCredential_basic
=== CONT  TestAccFederatedIdentityCredential_requiresImport
--- PASS: TestAccFederatedIdentityCredential_requiresImport (71.51s)
--- PASS: TestAccFederatedIdentityCredential_basic (95.02s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/managedidentity       95.157s
```

**Review by sreallymatt — APPROVED** [review]
Thanks @magodo  - LGTM ✅
