### PR TITLE
desktopvirtualization: adding a state migration for the new ID format

### LINKED ISSUE #9491: virtual_desktop_workspace_application_group_association: Force VM replacement since v2.35 (maybe change #9057)?
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: 0.13.5
Provider AzureRM: v0.35+ (including latest v0.37)

### Affected Resource(s)

virtual_desktop_workspace_application_group_association

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_desktop_workspace_application_group_association" "workspaceremoteapp" {
  workspace_id         = azurerm_virtual_desktop_workspace.workspace.id
  application_group_id = azurerm_virtual_desktop_application_group.appgroup.id
}
```

### Expected Behaviour

No modification on the existing azurerm_virtual_desktop_workspace_application_group_association

### Actual Behaviour

terraform apply cause virtual machine replacement but no modification in tf file. This problem appear in 0.35 and is still present in 0.37. When reverting to 0.34 no modification found when terraform plan/apply
Here is the plan output with 0.35+:

```hcl
Terraform will perform the following actions:

  # module.azurerm_virtual_desktop_test.azurerm_virtual_desktop_application_group.appgroup will be updated in-place
  ~ resource "azurerm_virtual_desktop_application_group" "appgroup" {
      ~ host_pool_id        = "/subscriptions/XXXXXXXXX-XXXX-XXXX-XXXX/resourceGroups/TEST-rg/providers/Microsoft.DesktopVirtualization/hostpools/SRVTEST-hp" -> "/subscriptions/XXXXXXXXX-XXXX-XXXX-XXXX/resourcegroups/TEST-rg/providers/Microsoft.DesktopVirtualization/hostpools/SRVTEST-hp"
        id                  = "/subscriptions/XXXXXXXXX-XXXX-XXXX-XXXX/resourcegroups/TEST-rg/providers/Microsoft.DesktopVirtualization/applicationgroups/SRVTEST-appgroup"
        location            = "eastus"
        name                = "SRVTEST-appgroup"
        resource_group_name = "TEST-rg"
        tags                = {}
        type                = "Desktop"
    }

  # module.azurerm_virtual_desktop_test.azurerm_virtual_desktop_workspace_application_group_association.workspaceremoteapp must be replaced
-/+ resource "azurerm_virtual_desktop_workspace_application_group_association" "workspaceremoteapp" {
      ~ application_group_id = "/subscriptions/XXXXXXXXX-XXXX-XXXX-XXXX/resourceGroups/TEST-rg/providers/Microsoft.DesktopVirtualization/applicationgroups/SRVTEST-appgroup" -> "/subscriptions/XXXXXXXXX-XXXX-XXXX-XXXX/resourcegroups/TEST-rg/providers/Microsoft.DesktopVirtualization/applicationgroups/SRVTEST-appgroup" # forces replacement
      ~ id                   = "/subscriptions/XXXXXXXXX-XXXX-XXXX-XXXX/resourcegroups/TEST-rg/providers/Microsoft.DesktopVirtualization/workspaces/SRVTEST-ws|/subscriptions/XXXXXXXXX-XXXX-XXXX-XXXX/resourcegroups/TEST-rg/providers/Microsoft.DesktopVirtualization/applicationgroups/SRVTEST-appgroup" -> (known after apply)
      ~ workspace_id         = "/subscriptions/XXXXXXXXX-XXXX-XXXX-XXXX/resourceGroups/TEST-rg/providers/Microsoft.DesktopVirtualization/workspaces/SRVTEST-ws" -> "/subscriptions/XXXXXXXXX-XXXX-XXXX-XXXX/resourcegroups/TEST-rg/providers/Microsoft.DesktopVirtualization/workspaces/SRVTEST-ws" # forces replacement
    }
```

### Steps to Reproduce

1. Implement VDI hostpool and virtual machine. Use azurerm_virtual_desktop_workspace_application_group_association and update module to 035+
2. `terraform plan`

### References

It seems there is pull request #9057 has been done on azurerm_virtual_desktop_workspace_application_group_association that can cause this issue

### PR DESCRIPTION
**Pull request by tombuildsstuff**
This PR introduces a state migration for each of the Desktop Virtualization resources - allowing these to be parsed insensitively and then patched up to match the apply.

This adds support for a conditional "insensitive" option within the Resource ID generator - intentionally named `rewrite`, since that's what it's intended to do - which is intentionally disabled by default, since this should be a last-resort to work around a broken API response prior to patching it.

You'll want to review this commit by commit, since the last one is a regeneration of all the parse functions to add some documentation to account for the optional `{Insensitive}` parser

Ultimately this issue fixes #9491

### CODE REVIEW

File: azurerm/internal/services/desktopvirtualization/parse/application_group_test.go [hunk 1]
```diff
@@ -110,3 +110,120 @@ func TestApplicationGroupID(t *testing.T) {
...
+			Expected: &ApplicationGroupId{
+				SubscriptionId: "12345678-1234-9876-4563-123456789012",
+				ResourceGroup:  "resGroup1",
+				Name:           "applicationGroup1",
+			},
+		},
+
+		{
+			// mixed-cased segment names
+			Input: "/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/resGroup1/providers/Microsoft.DesktopVirtualization/ApPlIcAtIoNgRoUpS/applicationGroup1",
```
Comment (manicminer) [inline azurerm/internal/services/desktopvirtualization/parse/application_group_test.go:195]: 😄

**Review by manicminer — APPROVED** [review]
LGTM 🚀

**Comment by tombuildsstuff** [comment]
Tests pass:

Screenshot 2020-11-26 at 16 44 44
