### PR TITLE
azurerm_databricks - add 100% coverage for 2018-04-01 API

### LINKED ISSUE #9785: azurerm_databricks_workspace support DBFS CMK  prepare_encryption and encryption in custom_parameters
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.28
+ provider.azurerm v2.39.0
+ provider.databricks v0.2.9
```
### Affected Resource(s)

* `azurerm_databricks_workspace`

### Terraform Configuration Files

```hcl
resource "azurerm_databricks_workspace" "main" {
  location            = var.azurerm_location_long
  name                = local.full_name
  resource_group_name = data.azurerm_resource_group.rg.name
  sku                 = var.databricks_sku

  custom_parameters {

    prepare_encryption     = true

    encryption {
        key_source = "Microsoft.Keyvault"
        keyvaulturi = azurerm_key_vault.dbfs.vault_uri
        key_name = "dbfs"
        keyversion = "00000000000000000000000000000000"
    }
  }

}
```

### Expected Behaviour

Workspace is prepared for encryption and configured with CMK via Azure Key Vault.

As Described in Azure API Reference: https://docs.microsoft.com/en-us/rest/api/databricks/workspaces/createorupdate#create-a-workspace-which-is-ready-for-customer-managed-key-(cmk)-encryption

### Actual Behaviour

```
$ terraform apply

Error: Unsupported argument

  on az_databricks.tf line 12, in resource "azurerm_databricks_workspace" "main":
  12:     prepare_encryption   = true

An argument named "prepare_encryption" is not expected here.


Error: Unsupported block type

  on az_databricks.tf line 14, in resource "azurerm_databricks_workspace" "main":
  14:     encryption {

Blocks of type "encryption" are not expected here.
```

### Steps to Reproduce

1. Define Terraform resource - as per above example above, passing custom_parameters specified in Azure API Reference 
2. `terraform apply`

### Important Factoids

None

### PR DESCRIPTION
**Pull request by WodansSon**
**New Resource:** `azurerm_databricks_workspace_customer_managed_key`

### New Fields Added:
* `machine_learning_workspace_id`
* `customer_managed_key_enabled`
* `infrastructure_encryption_enabled`
* `storage_account_identity`
     * `principal_id`
     * `tenant_id`
     * `type`

fixes #9785

### CODE REVIEW

**Comment by WodansSon** [comment]
image

File: azurerm/internal/services/databricks/databricks_workspace_resource.go [hunk 1]
```diff
@@ -79,46 +79,98 @@ func resourceDatabricksWorkspace() *pluginsdk.Resource {
...
+						},
+
+						"enable_cmk_encryption": {
+							Type:         pluginsdk.TypeBool,
+							Optional:     true,
+							Default:      false,
+							AtLeastOneOf: workspaceCustomParametersString(),
+						},
+
+						"enable_infrastructure_encryption": {
```
Comment (katbyte) [inline azurerm/internal/services/databricks/databricks_workspace_resource.go:161]: could we change this to match the rest of the provideR?
```suggestion
						"infrastructure_encryption_enabled": {
```

File: azurerm/internal/services/databricks/databricks_workspace_resource.go [hunk 2]
```diff
@@ -79,46 +79,98 @@ func resourceDatabricksWorkspace() *pluginsdk.Resource {
...
 							ForceNew:     true,
 							Optional:     true,
 							ValidateFunc: azure.ValidateResourceIDOrEmpty,
-							AtLeastOneOf: []string{"custom_parameters.0.no_public_ip", "custom_parameters.0.public_subnet_name",
-								"custom_parameters.0.private_subnet_name", "custom_parameters.0.virtual_network_id",
-							},
+							AtLeastOneOf: workspaceCustomParametersString(),
+						},
+
+						"enable_cmk_encryption": {
```
Comment (katbyte) [inline azurerm/internal/services/databricks/databricks_workspace_resource.go:154]:
```suggestion
						"customer_managed_key_enabled": {
```

File: azurerm/internal/services/databricks/databricks_workspace_resource.go [hunk 3]
```diff
@@ -79,46 +79,98 @@ func resourceDatabricksWorkspace() *pluginsdk.Resource {
...
+									"key_vault_uri": {
+										Type:     pluginsdk.TypeString,
+										Optional: true,
+									},
+								},
 							},
+							AtLeastOneOf: workspaceCustomParametersString(),
+						},
+
+						"no_public_ip": {
```
Comment (katbyte) [inline azurerm/internal/services/databricks/databricks_workspace_resource.go:124]:
```suggestion
						"public_ip_disabled": {
```

File: azurerm/internal/services/databricks/databricks_workspace_resource.go [hunk 4]
```diff
@@ -79,46 +79,98 @@ func resourceDatabricksWorkspace() *pluginsdk.Resource {
 				MaxItems: 1,
 				Elem: &pluginsdk.Resource{
 					Schema: map[string]*pluginsdk.Schema{
-						"no_public_ip": {
-							Type:     pluginsdk.TypeBool,
-							ForceNew: true,
+						"aml_workspace_id": {
```
Comment (katbyte) [inline azurerm/internal/services/databricks/databricks_workspace_resource.go:82]: could we expand aml and no use an abbreviation?

File: azurerm/internal/services/databricks/databricks_workspace_resource.go [hunk 5]
```diff
@@ -79,46 +79,98 @@ func resourceDatabricksWorkspace() *pluginsdk.Resource {
...
+						"customer_managed_key": {
+							Type:     pluginsdk.TypeList,
 							Optional: true,
-							AtLeastOneOf: []string{"custom_parameters.0.no_public_ip", "custom_parameters.0.public_subnet_name",
-								"custom_parameters.0.private_subnet_name", "custom_parameters.0.virtual_network_id",
+							Computed: true,
+							MaxItems: 1,
+							Elem: &pluginsdk.Resource{
+								Schema: map[string]*pluginsdk.Schema{
+									"key_source": {
```
Comment (katbyte) [inline azurerm/internal/services/databricks/databricks_workspace_resource.go:97]: key is in the block name already
```suggestion
									"source": {
```

File: azurerm/internal/services/databricks/databricks_workspace_resource.go [hunk 6]
```diff
@@ -79,46 +79,98 @@ func resourceDatabricksWorkspace() *pluginsdk.Resource {
...
+							ForceNew:     true,
+							Optional:     true,
+							Default:      false,
+							AtLeastOneOf: workspaceCustomParametersString(),
 						},
 					},
 				},
 			},
 
+			"tags": tags.Schema(),
```
Comment (katbyte) [inline azurerm/internal/services/databricks/databricks_workspace_resource.go:172]: this should be at the bottom of the resource schema

File: azurerm/internal/services/databricks/databricks_workspace_resource_test.go [hunk 7]
```diff
@@ -50,6 +46,84 @@ func TestAccDatabricksWorkspace_requiresImport(t *testing.T) {
...
+
+// This is currently untestable due to https://github.com/Azure/azure-rest-api-specs/issues/8075
+// Per jlichwa: It is as designed, purge protection is irreversible. Otherwise hacker would be able
+// to delete your key vault without option to recover. #please-close
+// Unable to delete key vault since purge protection is required by the resource:
+// Code="StorageAccountOperationFailed" Message="Unable to update storage account 'dbstoragel2bko37m6ebog': 'Keyvault policy recoverable is not set'."
+// If I Add Purge Protection to be true the clean up gets the below error:
+// keyvault.BaseClient#PurgeDeletedKey: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error.
+// Status=403 Code="Forbidden" Message="The user, group or application 'appid=XXXX;oid=XXXX;iss=https://sts.windows.net/XXXX/' does not have keys
+// purge permission on key vault 'acctest-kv-rczeo;location=westeurope'. InnerError={"code":"ForbiddenByPolicy"}
```
Comment (katbyte) [inline azurerm/internal/services/databricks/databricks_workspace_resource_test.go:72]: we need to test this resource so can we please see about the service removing this restriction? it doesn't make sense to enforce this

File: azurerm/internal/services/databricks/databricks_workspace_resource_test.go [hunk 8]
```diff
@@ -50,6 +46,84 @@ func TestAccDatabricksWorkspace_requiresImport(t *testing.T) {
...
+// 		data.ImportStep(),
+// 		{
+// 			Config: r.customerManagedKeysStepTwo(data, "premium"),
+// 			Check: acceptance.ComposeTestCheckFunc(
+// 				check.That(data.ResourceName).ExistsInAzure(r),
+// 			),
+// 		},
+// 		data.ImportStep(),
+// 		{
+// 			Config: r.customerManagedKeysStepThree(data, "premium"),
```
Comment (katbyte) [inline azurerm/internal/services/databricks/databricks_workspace_resource_test.go:96]: how come this is three steps?

File: azurerm/internal/services/databricks/databricks_workspace_resource_test.go [hunk 9]
```diff
@@ -279,31 +349,558 @@ resource "azurerm_databricks_workspace" "test" {
...
+//   sku                 = "%[3]s"
+
+//   custom_parameters {
+//     enable_cmk_encryption = true
+
+//     customer_managed_key {
+//       key_source    = "Microsoft.KeyVault"
+//       key_name      = azurerm_key_vault_key.test.name
+//       key_version   = azurerm_key_vault_key.test.version
+//       key_vault_uri = azurerm_key_vault.test.vault_uri
```
Comment (katbyte) [inline azurerm/internal/services/databricks/databricks_workspace_resource_test.go:758]: could we not all get these from the key_vault_key id?

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @WodansSon - left some comments inline

File: azurerm/internal/services/databricks/databricks_workspace_resource_test.go (hunk 8 above)
Comment (WodansSon) [reply azurerm/internal/services/databricks/databricks_workspace_resource_test.go:96]: That is the way the API configured to work:
1) Enable CMK (this creates the MSI identity for the workspace)
2) Actually pass the BYOK key info so the DBFS can be encrypted by the workspace worker
3) Verify we can disable BYOK and revert to Microsoft Managed encryption

File: azurerm/internal/services/databricks/databricks_workspace_resource_test.go (hunk 9 above)
Comment (WodansSon) [reply azurerm/internal/services/databricks/databricks_workspace_resource_test.go:758]: Not sure, this might be one of those chicken or the egg scenarios... I will investigate if this is possible.

File: azurerm/internal/services/databricks/databricks_workspace_resource.go (hunk 3 above)
Comment (WodansSon) [reply azurerm/internal/services/databricks/databricks_workspace_resource.go:124]: I can't change this as it has already shipped as [no_public_ip](https://github.com/terraform-providers/terraform-provider-azurerm/blob/2b36b7bfb90cd04c135cd76ef7631b15fd5921f4/azurerm/internal/services/databricks/databricks_workspace_resource.go#L82). I can add a TODO to remove this and rename it in 3.0 if you'd like?

File: azurerm/internal/services/databricks/databricks_workspace_resource.go (hunk 4 above)
Comment (WodansSon) [reply azurerm/internal/services/databricks/databricks_workspace_resource.go:82]: Fixed

File: azurerm/internal/services/databricks/databricks_workspace_resource.go (hunk 6 above)
Comment (WodansSon) [reply azurerm/internal/services/databricks/databricks_workspace_resource.go:172]: Fixed

File: azurerm/internal/services/databricks/databricks_workspace_resource_test.go (hunk 7 above)
Comment (WodansSon) [reply azurerm/internal/services/databricks/databricks_workspace_resource_test.go:72]: We have tried, it is a hard no from the service team so I am really stuck.

**Comment by WodansSon** [comment]
image

**Comment by WodansSon** [comment]
image

File: azurerm/internal/services/databricks/databricks_customer_managed_key_resource.go [hunk 10]
```diff
@@ -0,0 +1,314 @@
...
+	if d.IsNewResource() {
+		if workspace.Parameters.Encryption != nil {
+			return tf.ImportAsExistsError("azurerm_databricks_workspace_customer_managed_key", resourceID.ID())
+		}
+	}
+
+	keySource := databricks.MicrosoftKeyvault
+	keyName := key.Name
+	keyVersion := key.Version
+	keyVaultBaseURI := key.KeyVaultBaseUrl
```
Comment (katbyte) [inline azurerm/internal/services/databricks/databricks_customer_managed_key_resource.go:145]: i don't think theres any point in creating new local variables ?

File: azurerm/internal/services/databricks/databricks_workspace_resource_test.go [hunk 11]
```diff
@@ -59,15 +85,15 @@ func TestAccDatabricksWorkspace_complete(t *testing.T) {
...
-				check.That(data.ResourceName).Key("tags.Pricing").HasValue("Standard"),
 			),
 		},
 		data.ImportStep(),
+		{
+			Config: r.cleanupSubnetDelegation(data),
+		},
+		{
+			Config: r.cleanupNsgAssociation(data),
+		},
```
Comment (katbyte) [inline azurerm/internal/services/databricks/databricks_workspace_resource_test.go:96]: we should not be doing a multi step cleanup.. how come this is required?

File: website/docs/r/databricks_workspace.html.markdown [hunk 12]
```diff
@@ -42,29 +42,36 @@ The following arguments are supported:
...
 * `sku` - (Required) The `sku` to use for the Databricks Workspace. Possible values are `standard`, `premium`, or `trial`. Changing this can force a new resource to be created in some circumstances.
 
-~> **NOTE** While downgrading to `trial`, the Databricks Workspace resource would be recreated.
+~> **NOTE** Downgrading to a `trial sku` from a `standard` or `premium sku` will force a new resource to be created.
 
 * `managed_resource_group_name` - (Optional) The name of the resource group where Azure should place the managed Databricks resources. Changing this forces a new resource to be created.
 
 ~> **NOTE** Azure requires that this Resource Group does not exist in this Subscription (and that the Azure API creates it) - otherwise the deployment will fail.
 
+* `customer_managed_key_enabled` - (Optional) Is the workspace enabled for customer managed key encryption? If `true` this enables the Managed Identity for the managed storage account. Possible values are `true` or `false`. Defaults to `false`. This field is only valid if the Databricks Workspace `sku` is set to `premium`. Changing this forces a new resource to be created.
```
Comment (katbyte) [inline website/docs/r/databricks_workspace.html.markdown:51]: is there any point of this being on the resource when there is a seperate one to manage it? that cloud.. should toggle it?

File: website/docs/r/databricks_workspace.html.markdown [hunk 13]
```diff
@@ -42,29 +42,36 @@ The following arguments are supported:
...
+
+* `infrastructure_encryption_enabled`- (Optional) Is the DBFS root file system enabled with a secondary layer of encryption with platform managed keys? Possible values are `true` or `false`. Defaults to `false`. This field is only valid if the Databricks Workspace `sku` is set to `premium`. Changing this forces a new resource to be created.
```
Comment (katbyte) [inline website/docs/r/databricks_workspace.html.markdown:53]: could we not have the DBFS as an acronym?

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @WodansSon - see my comments inline

File: website/docs/r/databricks_workspace.html.markdown (hunk 12 above)
Comment (WodansSon) [reply website/docs/r/databricks_workspace.html.markdown:51]: Yes, while we abstract this in being able to this functionality is a single apply via Terraform. It actually really is still a two step operation to actually implement the CMK in Databricks. This flag on the main resource tells the Databricks to create a system assigned identity behind the scenes which we will then later use to apply the key vault key access policies so the Databricks can use the key vault key to encrypt the DBFS storage.

File: website/docs/r/databricks_workspace.html.markdown (hunk 13 above)
Comment (WodansSon) [reply website/docs/r/databricks_workspace.html.markdown:53]: Yep... I'll fix that...

File: azurerm/internal/services/databricks/databricks_workspace_resource_test.go (hunk 11 above)
Comment (WodansSon) [reply azurerm/internal/services/databricks/databricks_workspace_resource_test.go:96]: This is required because when you configure a Databricks resource to with `no_public_ip` azure proper will automatically create and attach a network policy to your subnets. The subnets cannot be deleted if there is a network policy attached to them, plus the subnets have a service delegation assigned to them as well which means we cannot delete the subnets or the VNet until the network policy and the service delegation association with the Databricks workspace has been broken.

File: azurerm/internal/services/databricks/databricks_customer_managed_key_resource.go (hunk 10 above)
Comment (WodansSon) [reply azurerm/internal/services/databricks/databricks_customer_managed_key_resource.go:145]: Agreed... fixed...

**Comment by WodansSon** [comment]
image

**Comment by WodansSon** [comment]
The 2 tests that have historically failed before this PR are now failing in the same way once I reverted my test fix, all net new tests `pass`...
image

**Comment by WodansSon** [comment]
image

**Review by katbyte — APPROVED** [review]
LGTM 🙌

**Comment by alexott** [comment]
The issue #12302 isn't really covered by this PR because it requires a new API
