### PR TITLE
r/kubernetes_cluster: making the `aci_connector_linux` & `http_application_routing` blocks cloud specific

### LINKED ISSUE #5510: azurerm_kubernetes_cluster: "addon is not supported" error in Azure China with provider version >= 1.37.0
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform version -v
Terraform v0.12.19
+ provider.azurerm v1.41.0
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  environment = "china"
}

resource "azurerm_kubernetes_cluster" "cluster" {
  name                = ""aks-cluster"
  location            = "chinaeast2"
  resource_group_name = "RESOURCE_GROUP_NAME"
  kubernetes_version  = "1.15.7"
  dns_prefix          = "DNS_PREFIX"
  node_resource_group = "NODE_RESOURCE_GROUP"

  agent_pool_profile {
    name = "agent-pool"

    type            = "VirtualMachineScaleSets"
    vm_size         = "Standard_E8s_v3"
    os_disk_size_gb = 64
    vnet_subnet_id  = "VNET_SUBNET_ID"
    max_pods        = 30
    node_taints     = []

    count = "NODE_COUNT"
  }

  service_principal {
    client_id     = "SERVICE_PRINCIPAL_ID"
    client_secret = "SERVICE_PRINCIPAL_SECRET"
  }

  linux_profile {
    admin_username = "ADMIN_USERNAME"
    ssh_key {
      key_data = "SSH_KEY_DATA"
    }
  }

  network_profile {
    network_plugin     = "azure"
    network_policy     = "azure"
    dns_service_ip     = "DNS_SERVICE_IP"
    service_cidr       = "SERVICE_CIDR"
    docker_bridge_cidr = "172.17.0.1/16"
    load_balancer_sku  = "basic"
  }

  role_based_access_control {
    enabled = true
  }
}
```

(note: this has been downgraded to `agent_pool_profile` because the last working version is 1.36.0, but `default_node_pool` has been tested as well)

### Debug Output

This thing is embedded in a larger Terraform module, so I'm hesitant to share the whole debug log. Please let me know if the debug output here is really required since we're getting a relatively clear error from the Azure China API.

### Expected Behavior

A AKS cluster should be created in Azure China.

### Actual Behavior

Starting with the AzureRM provider version 1.37.0 (up to the current version 1.41.0), creating the cluster fails on Azure China with this error message:

```
Error: Error creating Managed Kubernetes Cluster "REDACTED" (Resource Group "REDACTED""): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="OperationNotAllowed" Message="Addon 'aciConnectorLinux' is not supported in this cloud environment."

  on .REDACTED/main.tf line 1, in resource "azurerm_kubernetes_cluster" "cluster":
   1: resource "azurerm_kubernetes_cluster" "cluster" {
```

With no changes to the resource, 1.36.0 successfully deploys the cluster.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

- This only affects Azure China
- probably caused by the changes to the resource in 1.37.0 (mentioned [in the release notes](https://github.com/terraform-providers/terraform-provider-azurerm/releases/tag/v1.37.0))
- verified 1.36.0 as the last working version, both 1.37.0 and 1.41.0 are affected (did not check the versions in between)

### References

* #0000

### LINKED ISSUE #5960: AKS setup failing in Government Cloud
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "k8s_cluster" {
  resource_group_name = "${local.resource_group_name}"
  location            = "${var.resource_group_location}"
  name                = "${var.cluster_name}"
  dns_prefix          = "${local.unique_resource_name}"
  kubernetes_version  = "${var.cluster_version}"

  default_node_pool {
    max_count           = "${var.cluster_pool_vm_max_count}"
    min_count           = "${var.cluster_pool_vm_min_count}"
    node_count          = "${var.cluster_pool_vm_count}"
    name                = "${var.cluster_pool_name}"
    vm_size             = "${var.cluster_pool_vm_size}"
    os_disk_size_gb     = "${var.cluster_pool_vm_disk}"
    enable_auto_scaling = "${var.cluster_pool_enable_auto_scaling}"
    type                = "${var.cluster_pool_enable_auto_scaling ? "VirtualMachineScaleSets" : "AvailabilitySet" }"
  }

  lifecycle {
    ignore_changes = [
      "default_node_pool.0.node_count"
    ]
  }

  role_based_access_control {
    enabled = true
  }

  # https://github.com/terraform-providers/terraform-provider-azurerm/issues/2510
  service_principal {
    client_id     = "${azurerm_azuread_application.aks_app.application_id}"
    client_secret = "${azurerm_azuread_service_principal_password.aks_sp_password.value}"
  }
}
```

### Expected Behavior

It should create the AKS cluster as configured (without any addons).

### Actual Behavior

The request to create the cluster failed with a 400 status.

```
azurerm_kubernetes_cluster.k8s_cluster: Error creating Managed Kubernetes Cluster "logrocket" (Resource Group "logrocketiew0s2"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="OperationNotAllowed" Message="Addon 'httpApplicationRouting' is not supported in this cloud environment.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This is a Government Cloud customer; we do not have access to our own Government Cloud account to test with.

### References

* #0000

### PR DESCRIPTION
**Pull request by tombuildsstuff**
The blocks `aci_connector_linux` and `http_application_routing` are not supported in Azure China or Azure US Government Clouds. As such this commit filters them out if they're disabled (since the API does not allow them to exist in the payload, even if disabled) and returns an error if attempting to use these add-ons in this region.

Fixes #5960
Fixes #5510

### CODE REVIEW

File: azurerm/internal/services/containers/kubernetes_addons.go [hunk 1]
```diff
@@ -1,24 +1,42 @@
...
+// the list of unsupported addons in the defined region - e.g. by being
+// omited from this list an addon/environment combination will be supported
+var unsupportedAddonsForEnvironment = map[string][]string{
+	azure.ChinaCloud.Name: {
+		aciConnectorKey,           // https://github.com/terraform-providers/terraform-provider-azurerm/issues/5510
+		httpApplicationRoutingKey, // https://github.com/terraform-providers/terraform-provider-azurerm/issues/5960
+	},
+	azure.USGovernmentCloud.Name: {
+		httpApplicationRoutingKey, // https://github.com/terraform-providers/terraform-provider-azurerm/issues/5960
+	},
```
Comment (tombuildsstuff) [inline azurerm/internal/services/containers/kubernetes_addons.go:36]: I went digging through the Docs & AKS Engine to try and find a definitive list of which add-ons - but ended up with this based on then open issues

@jluk do you know if there's a document stating which add-ons are supported in which cloud environments?

Comment (jluk) [reply azurerm/internal/services/containers/kubernetes_addons.go:36]: Unfortunately not today.

@feiskeyer to confirm the 2 missing addons in Azure China/Gov.

Comment (feiskyer) [reply azurerm/internal/services/containers/kubernetes_addons.go:36]: there're some list under https://github.com/Azure/AKS/projects/1

**Comment by tombuildsstuff** [comment]
Ignoring some known/expected test failures on AKS's end the tests look good:

Screenshot 2020-04-07 at 12 20 05
