### PR TITLE
`azurerm_purview_account` - use correct values for identity type to match API 

### LINKED ISSUE #20043: Terraform Purview resource 'azurerm_purview_account' erroring out adding type = "UserAssigned"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

User Terraform resource as below

resource "azurerm_purview_account" "catalog" {
  name                        = "Sample"
  resource_group_name         = "rg
  location                    = "eastus"
  public_network_enabled      = true
  managed_resource_group_name = "managed-rg"

  identity {
    type = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.cat.id]
  }
}

When trying add Managed Identity providing the id; Terraform is failing with error below

### Terraform Version

1.3.7

### AzureRM Provider Version

3.38.0

### Affected Resource(s)/Data Source(s)

azurerm_purview_account

### Terraform Configuration Files

```hcl
resource "azurerm_purview_account" "catalog" {
  name                        = "Sample"
  resource_group_name         = "rg
  location                    = "eastus"
  public_network_enabled      = true
  managed_resource_group_name = "managed-rg"

  identity {
    type = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.cat.id]
  }
}
```

### Debug Output/Panic Output

```shell
Error:
**performing CreateOrUpdate: account.AccountClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="1001" Message="PrincipalId is required" Target="PrincipalId" Details=[]**
```

### Expected Behaviour

Purview created with Managed Identity attached

### Actual Behaviour

Error:
**performing CreateOrUpdate: account.AccountClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="1001" Message="PrincipalId is required" Target="PrincipalId" Details=[]**

### Steps to Reproduce

resource "azurerm_purview_account" "catalog" {
  name                        = "Sample"
  resource_group_name         = "rg
  location                    = "eastus"
  public_network_enabled      = true
  managed_resource_group_name = "managed-rg"

  identity {
    type = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.cat.id]
  }
}

### Important Factoids

No

### References

_No response_

### PR DESCRIPTION
**Pull request by toddgiguere**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

This fix, which comprises both an SDK/API workaround and a change to allowed values for the provider, will allow a user to specify user identities to the Purview configuration by using the correct identity type of `SystemAssigned, UserAssigned`.

The Azure API currently accepts the following values for `identity.type`:
- `SystemAssigned`
- `SystemAssigned, UserAssigned`
(`UserAssigned` on its own is NOT accepted)

The current swagger spec for the Purview API is still reporting allowed values of `SystemAssigned` and `UserAssigned`, but the API itself does not allow `UserAssigned` on its own. This issue was [reported but is still open](https://github.com/Azure/azure-rest-api-specs/issues/22257). We have taken care of this discrepency with a [workaround to the API spec ](https://github.com/hashicorp/pandora/pull/5241) to create our SDK with the correct values.

This PR has the following changes to the provider:
- Uses new `go-azure-sdk` built with workaround mentioned above
- Reworking of identity model to accept the valid `type` values
- Fix for another Azure API inconsistency with returned `identity_ids` that cause an unintended drift
- Documentation change to point out the valid values allowed for Identity `type`
- Small changes to `azurerm_netapp_volume` resources that were also needed for new `go-azure-sdk` version

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-merging.md).

* [BUG] * `azurerm_purview_account` - use correct API values for identity type  [GH-00000]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)

Fixes #20043

## AI Assistance Disclosure

- [ ] AI Assisted - This contribution was made by, or with the assistance of, AI/LLMs

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/purview/purview_account_resource.go [hunk 1]
```diff
@@ -350,3 +354,29 @@ func flattenPurviewAccountManagedResources(managedResources *account.ManagedReso
 		},
 	}
 }
+
+// resourcePurviewAccountIdentitySchema will take the common `SystemAssignedUserAssignedIdentityRequired` schema and make
+// small changes to match this purview resource schemas with what is supported by API.
```
Comment (sreallymatt) [inline internal/services/purview/purview_account_resource.go:359]: Could you add a link to the Azure REST API specs issue here for future reference?

File: website/docs/r/purview_account.html.markdown [hunk 2]
```diff
@@ -59,11 +59,13 @@ The following arguments are supported:
 
 The `identity` block supports the following:
 
-* `type` - (Required) Specifies the type of Managed Service Identity that should be configured on this Purview Account. Possible values are `UserAssigned` and `SystemAssigned`.
+* `type` - (Required) Specifies the type of Managed Service Identity that should be configured on this Purview Account. Possible values are `SystemAssigned` and `SystemAssigned, UserAssigned`.
+
+~> **Note:** `UserAssigned` on its own is not a valid value, if you need to assign identities please use `SystemAssigned, UserAssigned`.
```
Comment (sreallymatt) [inline website/docs/r/purview_account.html.markdown]: Note not needed here as this is covered by the schema ValidateFunc + the `Possible values are ...` bit above

```suggestion
```

File: internal/services/purview/purview_account_resource_test.go [hunk 3]
```diff
@@ -31,6 +31,44 @@ func TestAccPurviewAccountSequential(t *testing.T) {
 	})
 }
 
+func TestAccPurviewAccount_updateWithUserIdentity(t *testing.T) {
```
Comment (sreallymatt) [inline internal/services/purview/purview_account_resource_test.go]: Given the other tests are run sequentially (due to quota limitations) we should lowercase this one as well and add it to `TestAccPurviewAccountSequential` above

```suggestion
func testAccPurviewAccount_updateWithUserIdentity(t *testing.T) {
```

**Review by sreallymatt — COMMENTED** [review]
Thanks @toddgiguere - just a couple minor comments but otherwise this looks good!

**Comment by toddgiguere** [comment]
TeamCity tests are passing for Purview package, including new test.
https://hashicorp.teamcity.com/buildConfiguration/TF_AzureRM_AZURERM_SERVICE_PUBLIC_PURVIEW/626575
