### PR TITLE
azurerm_public_ip_resource - Added sku_tier property

### LINKED ISSUE #12335: Support for Public IP SKU Tier
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Public IP has an option to set up Tier (Global or Regional). Unfortunately, Terraform AzureRM provider does not support Tier parameter under SKU as it accepts SKU string values only.
```
Error: Incorrect attribute value type

  on ..\main.tf line 29, in resource "azurerm_public_ip" "main":
  29:   sku               =  {
  30:     name = "Standard"
  31:     tier = "Regional"
  32:   }
```
 Therefore, a request is to implement SKU block support in AzureRM provider to accept Tier property (Global or Regional).

When listing SKU property using PowerShell, we can see Tier property:
```
$publicip.sku | Get-Member 

   TypeName: Microsoft.Azure.Commands.Network.Models.PSPublicIpAddressSku

Name        MemberType Definition
----        ---------- ----------
Equals      Method     bool Equals(System.Object obj)
GetHashCode Method     int GetHashCode()
GetType     Method     type GetType()
ToString    Method     string ToString()
Name        Property   string Name {get;set;}
Tier        Property   string Tier {get;set;}
```
### New or Affected Resource(s)

* azurerm_public_ip

### Potential Terraform Configuration

```hcl
resource "azurerm_public_ip" "main" {
  name                = "test-publicip"
  resource_group_name = "resouce-group-1"
  location            = "West Europe"
  sku                 =  {
    name = "Standard"
    tier = "Global"
  }
}
```

### References

N/A

### PR DESCRIPTION
**Pull request by catriona-m**
fixes #12335

### CODE REVIEW

File: azurerm/internal/services/network/public_ip_resource.go [hunk 1]
```diff
@@ -103,6 +103,18 @@ func resourcePublicIp() *pluginsdk.Resource {
...
+			"sku_tier": {
+				Type:             pluginsdk.TypeString,
+				Optional:         true,
+				Default:          string(network.PublicIPAddressSkuTierRegional),
+				ForceNew:         true,
+				DiffSuppressFunc: suppress.CaseDifference,
+				ValidateFunc: validation.StringInSlice([]string{
+					string(network.PublicIPAddressSkuTierGlobal),
+					string(network.PublicIPAddressSkuTierRegional),
+				}, true),
```
Comment (tombuildsstuff) [inline azurerm/internal/services/network/public_ip_resource.go:115]: all new properties should be case-sensitive here, so can we make this:

```suggestion
				ValidateFunc: validation.StringInSlice([]string{
					string(network.PublicIPAddressSkuTierGlobal),
					string(network.PublicIPAddressSkuTierRegional),
				}, false),
```

File: azurerm/internal/services/network/public_ip_resource_test.go [hunk 2]
```diff
@@ -677,6 +679,8 @@ resource "azurerm_public_ip" "test" {
   resource_group_name = azurerm_resource_group.test.name
   allocation_method   = "Static"
   domain_name_label   = "acctest-%d"
+  sku                 = "Standard"
+  sku_tier            = "Regional"
```
Comment (tombuildsstuff) [inline azurerm/internal/services/network/public_ip_resource_test.go:683]: since this is ForceNew, this'll recreate the resource when it changes - as such it can't go in the Update test (since whilst it'll work provisioning wise, it'll recreate the resource when doing so) - instead could we add two new tests (removing this from both the Basic/Update tests) for Global/Regional SKU Tiers?

File: azurerm/internal/services/network/public_ip_resource.go [hunk 3]
```diff
@@ -103,6 +103,18 @@ func resourcePublicIp() *pluginsdk.Resource {
 				}, true),
 			},
 
+			"sku_tier": {
```
Comment (tombuildsstuff) [inline azurerm/internal/services/network/public_ip_resource.go:106]: can we add this new property [to the documentation too](https://github.com/terraform-providers/terraform-provider-azurerm/blame/master/website/docs/r/public_ip.html.markdown#L49-L73)?

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
hey @catriona-m 

Thanks for this PR.

I've taken a look through and left a few comments inline but if we can fix those up this should be good to go 👍 

Thanks!

File: azurerm/internal/services/network/public_ip_resource.go [hunk 4]
```diff
@@ -103,6 +103,18 @@ func resourcePublicIp() *pluginsdk.Resource {
...
+				Type:             pluginsdk.TypeString,
+				Optional:         true,
+				Default:          string(network.PublicIPAddressSkuTierRegional),
+				ForceNew:         true,
+				DiffSuppressFunc: suppress.CaseDifference,
```
Comment (tombuildsstuff) [inline azurerm/internal/services/network/public_ip_resource.go:111]: can we remove this:

```suggestion
```

File: website/docs/r/public_ip.html.markdown [hunk 5]
```diff
@@ -46,6 +46,10 @@ The following arguments are supported:
 
 -> **Note** Public IP Standard SKUs require `allocation_method` to be set to `Static`.
 
+* `sku_tier` - (Optional) The SKU Tier that should be used for the Public IP. Possible values are `Regional` and `Global`. Defaults to `Regional`.
+
+-> **Note** Public IP Global SKU Tier requires `sku` to be set to `Standard`.
```
Comment (tombuildsstuff) [inline website/docs/r/public_ip.html.markdown:51]: is it worth making this:

```suggestion
-> **Note** When `sku_tier` is set to `Global`, `sku` must be set to `Standard`.
```

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
hey @catriona-m 

Thanks for pushing those changes - I've left a couple of minor comments inline but this otherwise LGTM 👍 

Thanks!

**Review by katbyte — APPROVED** [review]
Thanks @catriona-m - LGTM 🚀
