### PR TITLE
`azurerm_databricks_workspace_root_dbfs_customer_managed_key` - fix panics, allow managed hsm, and allow versionless keys

### LINKED ISSUE #25896: azurerm_databricks_workspace_root_dbfs_customer_managed_key doesn't support versionless_id of CMK key
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.2

### AzureRM Provider Version

3.102.0

### Affected Resource(s)/Data Source(s)

azurerm_databricks_workspace_root_dbfs_customer_managed_key

### Terraform Configuration Files

```hcl
resource "azurerm_databricks_workspace_root_dbfs_customer_managed_key" "cmk" {
  workspace_id     = azurerm_databricks_workspace.this.id
  key_vault_key_id = azurerm_key_vault_key.cmk_test.versionless_id
}
```

### Debug Output/Panic Output

```shell
Error: can not parse "key_vault_key_id" as a Key Vault Child resource id: expected a key vault versioned ID but no version information was found in: "https://cmk-kv.vault.azure.net/keys/cmk-test"

  with azurerm_databricks_workspace_root_dbfs_customer_managed_key.cmk,
  on databricks.tf line 49, in resource "azurerm_databricks_workspace_root_dbfs_customer_managed_key" "cmk":
  49:   key_vault_key_id = azurerm_key_vault_key.cmk_test_environment.versionless_id
```

### Expected Behaviour

Azure Databricks resource allows using versionless key to auto rotate keys when new key version is available. However, Terraform doesn't allows to do so.

### Actual Behaviour

Terraform plans fail with error.

### Steps to Reproduce

1.) Use `versionless_id` attribute of Key vault key in resource `azurerm_databricks_workspace_root_dbfs_customer_managed_key`.
2.) Run `Terraform plan`

### Important Factoids

_No response_

### References

https://learn.microsoft.com/en-us/azure/storage/common/customer-managed-keys-overview#automatically-update-the-key-version

### LINKED ISSUE #27739: azurerm_databricks_root_dbfs_customer_managed_key - missing support for keys from a Managed HSM Key Vault
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.1

### AzureRM Provider Version

3.116.0

### Affected Resource(s)/Data Source(s)

azurerm_databricks_root_dbfs_customer_managed_key

### Terraform Configuration Files

```hcl
resource "azurerm_databricks_workspace_root_dbfs_customer_managed_key" "example" {
  workspace_id     = azurerm_databricks_workspace.example.id
  key_vault_key_id = "https://<hsm_id>.managedhsm.azure.net/keys/<key_name>/<key_version>"
}
```

### Debug Output/Panic Output

```shell
Error: parsing "https://XXX.managedhsm.azure.net/keys/KEY_NAME/KEY_VERSION": internal-error: Managed HSM IDs are not supported as Key Vault Nested Items
```

### Expected Behaviour

The parameter `key_vault_key_id` should accept a value with `.managedhsm.`. Alternatively a new field should be added specifically for managed HSM KVs (e.g. `managed_hsm_key_vault_key_id`).

### Actual Behaviour

The error in Debug Output is thrown

In the `azurerm_databricks_root_dbfs_customer_managed_key` resource, the key vault id is passed to a [keyvaultParser](https://github.com/hashicorp/terraform-provider-azurerm/blob/5a772a728bc92e13e1e608602cae114c7f168dd6/internal/services/databricks/databricks_root_dbfs_customer_managed_key_resource.go#L64)
→ the [parser](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/keyvault/parse/nested_item.go#L120-#L122) explicitly checks for `.managedhsm.` in the id . If it exists, the error experienced is thrown.

### Steps to Reproduce

Run a terraform plan

### Important Factoids

_No response_

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/21470
https://github.com/hashicorp/terraform-provider-azurerm/issues/22977
https://github.com/hashicorp/terraform-provider-azurerm/issues/26392
https://github.com/hashicorp/terraform-provider-azurerm/issues/26357
https://github.com/hashicorp/terraform-provider-azurerm/issues/26338
https://github.com/hashicorp/terraform-provider-azurerm/issues/27436
https://github.com/hashicorp/terraform-provider-azurerm/issues/27738

### PR DESCRIPTION
**Pull request by sreallymatt**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

PR resolves some bugs and adds additional functionality:
- resolves panics in the event the CMK is removed from the `azurerm_databricks_workspace`
- fixes the delete timeout (it was using the read timeout value, which is too short in many cases)
- adds support for keys from a managed HSM vault
- adds support for versionless keys

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

2 failures:
image

`basicAltSubscription` was ignoring the wrong field during the ImportStep, fixed and reran:
```
--- PASS: TestAccDatabricksWorkspaceRootDbfsCustomerManagedKey_basicAltSubscription (1127.01s)
```

`basicManagedHSM` seems to have failed due to a timing issue regarding the permissions allocated to the SP running Terraform. Transient error, succeeded on rerun:

```
--- PASS: TestAccDatabricksWorkspaceRootDbfsCustomerManagedKey_basicManagedHSM (3352.33s)
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-merging.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)

Fixes #25896
Fixes #27739

## AI Assistance Disclosure

- [ ] AI Assisted - This contribution was made by, or with the assistance of, AI/LLMs

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/databricks/databricks_workspace_root_dbfs_customer_managed_key_resource.go [hunk 1]
```diff
@@ -87,102 +86,73 @@ func databricksWorkspaceRootDbfsCustomerManagedKeyCreate(d *pluginsdk.ResourceDa
...
 	// make sure the key vault exists
-	keyVaultIdRaw, err := keyVaultsClient.KeyVaultIDFromBaseUrl(ctx, dbfsSubscriptionId, key.KeyVaultBaseUrl)
-	if err != nil || keyVaultIdRaw == nil {
-		return fmt.Errorf("retrieving the Resource ID for the Key Vault at URL %q: %+v", key.KeyVaultBaseUrl, err)
-	}
-
-	// Only throw the import error if the keysource value has been set to something other than default...
-	if params.Encryption != nil && params.Encryption.Value != nil && keySource != workspaces.KeySourceDefault {
-		return tf.ImportAsExistsError("azurerm_databricks_workspace_root_dbfs_customer_managed_key", id.ID())
+	// TODO: consider removing this check and deprecating the `key_vault_id` property.
```
Comment (catriona-m) [inline internal/services/databricks/databricks_workspace_root_dbfs_customer_managed_key_resource.go:136]: I agree that we should probably remove these checks from the create/update. We don't typically check this in other customer_managed_key resources and there doesn't seem to be any particular reason it was added in this one in the first place?

**Review by catriona-m — APPROVED** [review]
Thanks @sreallymatt LGTM! Left one comment on your //todo but we don't necessarily have to fix that in this pr.

File: internal/services/databricks/databricks_workspace_root_dbfs_customer_managed_key_resource.go (hunk 1 above)
Comment (sreallymatt) [reply internal/services/databricks/databricks_workspace_root_dbfs_customer_managed_key_resource.go:136]: No particular reason I was able to find, I'll add an issue internally to resolve this TODO
