### PR TITLE
`azurerm_postgres_flexible_server` - change validation for the `customer_managed_key.[geo_backup_]key_vault_key_id` properties to allow managed hsm keys

### LINKED ISSUE #26338: azurerm_postgresql_flexible_server: support for Key Vault Keys from a Managed HSM
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.2.6

### AzureRM Provider Version

3.107

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server" "example" {
  name                          = "example-psqlflexibleserver"
  resource_group_name           = "resource-group"
  location                      = "location"
  version                       = "12"
  public_network_access_enabled = true
  administrator_login           = "psqladmin"
  administrator_password        = "***********"
  zone                          = "1"

  storage_mb   = 32768
  storage_tier = "P30"

  sku_name   = "GP_Standard_D4s_v3"

  identity {
    type         = "UserAssigned"
    identity_ids = ["USER_ASSIGNED_IDENTITY_ID"]
  }

  customer_managed_key {
      key_vault_key_id = "https://XXX.managedhsm.azure.net/keys/KEY_NAME/KEY_VERSION"
      primary_user_assigned_identity_id = "USER_ASSIGNED_IDENTITY_ID"
  }
}
```

### Debug Output/Panic Output

```shell
Error: parsing "https://XXX.managedhsm.azure.net/keys/KEY_NAME/KEY_VERSION": internal-error: Managed HSM IDs are not supported as Key Vault Nested Items
```

### Expected Behaviour

- The parameter **key_vault_key_id** should accept a value with ".managedhsm."
or
- The parameter **managed_hsm_key_id** should be added

### Actual Behaviour

Terraform throw an error:
`Error: parsing "https://XXX.managedhsm.azure.net/keys/KEY_NAME/KEY_VERSION": internal-error: Managed HSM IDs are not supported as Key Vault Nested Items`

### Steps to Reproduce

1. terraform plan

### Important Factoids

_No response_

### References

- Same issue here with azurerm_mssqlèserver : https://github.com/hashicorp/terraform-provider-azurerm/issues/22977
- Same issue here with disk_encryption_set : https://github.com/hashicorp/terraform-provider-azurerm/issues/21470
 
I found this error message in this function : https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/keyvault/parse/nested_item.go#L121

### PR DESCRIPTION
**Pull request by sreallymatt**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Changes validation to the new go-azure-helpers function, also allowing managed hsm keys

Note: I've left out a test specifically for managed HSM keys due to the cost associated with running these tests and the fact that the functionality (from a provider perspective) doesn't change between key vault and managed HSM key vaults.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

New failure due to a transient error

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-merging.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)

Fixes #26338

## AI Assistance Disclosure

- [ ] AI Assisted - This contribution was made by, or with the assistance of, AI/LLMs

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/postgres/postgresql_flexible_server_resource.go [hunk 1]
```diff
@@ -469,6 +470,30 @@ func resourcePostgresqlFlexibleServer() *pluginsdk.Resource {
 		},
 		),
 	}
+
+	if !features.FivePointOh() {
```
Comment (mbfrahry) [inline internal/services/postgres/postgresql_flexible_server_resource.go:474]: I may be reading this wrong but to me, this looks the same in v4 as is it does in v5? In case I'm missing something, can you confirm that there is a difference between v4 and v5 that warrants putting this in a 5.0 block?

Comment (sreallymatt) [reply internal/services/postgres/postgresql_flexible_server_resource.go:474]: In 4.0 it validates this as any nested item type input, for 5.0 it validates it expecting a `keys` sub type. (`keyvault.NestedItemTypeAny` vs `keyvault.NestedItemTypeKey`)

Comment (mbfrahry) [reply internal/services/postgres/postgresql_flexible_server_resource.go:474]: Ohhh, understood. Thank you thank you

**Review by mbfrahry — APPROVED** [review]
LGTM
