### PR TITLE
Various improvements to automation account & schedule (interval property for recurring)

### LINKED ISSUE #463: azurerm_automation_schedule fails when recurring. Interval options missing/non-importable
### Terraform Version
0.10.8

### Affected Resource(s)
- azurerm_automation_schedule

### Terraform Configuration Files
```hcl
resource "azurerm_automation_schedule" "schedule_prd_tas_admin_sync" {
  name                = "ProductionTOPdeskAdministratorsSync"
  resource_group_name = "${azurerm_automation_account.automation.resource_group_name}"
  account_name        = "${azurerm_automation_account.automation.name}"
  frequency           = "Hour"
  timezone            = "W. Europe Standard Time"
  start_time          = "2017-10-28T02:07:00+01:00"
  description         = "Automation schedule to start the synchronization of admin accounts to TAS servers."
}
```

### Debug Output
https://gist.github.com/draggeta/8af664cd5858f5093c982763e4f2bd27

### Expected Behavior
When reading/creating a recurring schedule , this should not fail. Also there are missing options such as days of week, weeks of months etc.

### Actual Behavior
Any time you try to perform a CRUD operation on a recurring schedule, you get an error regarding the frequency interval. This seems to be caused by the fact that it is an integer and json cannot unmarshal it to a string. Sadly, that is as far as my Go knowledge goes.

### Steps to Reproduce
Happens on the following:
1. `terraform apply`
2. `terraform plan`
3. `terraform import`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### LINKED ISSUE #1127: azurerm_automation_schedule failed with frequency Day, Week or Monthly
_This issue was originally opened by @petit-lu as hashicorp/terraform#17858. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version

```
Terraform v0.11.7
+ provider.azurerm v1.3.2
```
### Crash Output

```
Error: Error applying plan:

1 error(s) occurred:

* azurerm_automation_schedule.example: 1 error(s) occurred:

* azurerm_automation_schedule.example: automation.ScheduleClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Argument requestScheduleData with value Orchestrator.Schedules.DataAccess.Models.ScheduleAllData is not valid. Error message: Intervalmust greater than zero"
```

### Steps to Reproduce

When you want create an Automation Schedule, with frequence type (Day, Week, Monthly). Azure reply with errorStatus=400

But frequency =  "OneTime" works fine. 

```
resource "azurerm_resource_group" "example" {
  name     = "resourceGroup1"
  location = "West Europe"
}


resource "azurerm_automation_account" "example" {
  name                = "account1"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"


  sku {
    name = "Basic"
  }
}


resource "azurerm_automation_schedule" "example" {
  name                = "schedule1"
  resource_group_name = "${azurerm_resource_group.example.name}"
  account_name        = "${azurerm_automation_account.example.name}"
  frequency           = "Day"
  timezone            = "Central Europe Standard Time"
  start_time          = "2018-04-15T18:00:15+02:00"
  description         = "This is an example schedule"
}
```

### PR DESCRIPTION
**Pull request by katbyte**
This adds an example and improves validation for automation accounts and schedules. This also adds the `interval` property to `azurerm_automation_schedule` allowing for recurring automation.

Fixes #463 
Fixes #1127

### CODE REVIEW

**Comment by katbyte** [comment]
Tests pass: 
screen shot 2018-06-15 at 00 27 42

File: azurerm/helpers/suppress/string.go [hunk 1]
```diff
@@ -0,0 +1,10 @@
+package suppress
+
+import (
+	"github.com/hashicorp/terraform/helper/schema"
+	"strings"
+)
+
+func CaseDifference(_, old, new string, _ *schema.ResourceData) bool {
```
Comment (bflad) [inline azurerm/helpers/suppress/string.go]: We should get this added into helper/schema 😄

File: azurerm/helpers/suppress/time.go [hunk 2]
```diff
@@ -0,0 +1,18 @@
+package suppress
+
+import (
+	"time"
+
+	"github.com/hashicorp/terraform/helper/schema"
+)
+
+func Rfc3339Time(_, old, new string, _ *schema.ResourceData) bool {
```
Comment (bflad) [inline azurerm/helpers/suppress/time.go]: Ohhh this too! 👍

File: azurerm/helpers/validate/time.go [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+
+import (
+	"fmt"
+	"time"
+
+	"github.com/Azure/go-autorest/autorest/date"
+	"github.com/hashicorp/terraform/helper/schema"
+)
+
+//todo, now in terraform helper, switch over once vended,
```
Comment (bflad) [inline azurerm/helpers/validate/time.go]: Might be worth noting exactly what the helper is: https://godoc.org/github.com/hashicorp/terraform/helper/validation#ValidateRFC3339TimeString

File: azurerm/resource_arm_automation_account.go [hunk 4]
```diff
@@ -25,6 +27,11 @@ func resourceArmAutomationAccount() *schema.Resource {
 				Type:     schema.TypeString,
 				Required: true,
 				ForceNew: true,
+				ValidateFunc: validation.StringMatch(
+					//todo this will not allow single character names, even thou they are valid
```
Comment (bflad) [inline azurerm/resource_arm_automation_account.go]: Can we just wrap the part after the first character with `(...)?`

```go
regexp.MustCompile(`^[0-9a-zA-Z]([-0-9a-zA-Z]{0,48}[0-9a-zA-Z])?$`),
```

File: azurerm/resource_arm_automation_schedule_test.go [hunk 5]
```diff
@@ -2,30 +2,173 @@ package azurerm
...
+			},
+		},
+	})
+}
+
+func TestAccAzureRMAutomationSchedule_oneTime_complete(t *testing.T) {
+	resourceName := "azurerm_automation_schedule.test"
+	ri := acctest.RandInt()
+
+	//the API returns the time in the timezone we pass in
```
Comment (bflad) [inline azurerm/resource_arm_automation_schedule_test.go]: Thank you for these comments!

File: website/docs/r/automation_schedule.html.markdown [hunk 6]
```diff
@@ -46,17 +47,19 @@ The following arguments are supported:
 
 * `resource_group_name` - (Required) The name of the resource group in which the Schedule is created. Changing this forces a new resource to be created.
 
-* `account_name` - (Required) The name of the automation account in which the Schedule is created. Changing this forces a new resource to be created.
```
Comment (bflad) [inline website/docs/r/automation_schedule.html.markdown]: Since we do not have versioned documentation at the moment, not sure if we should leave the old argument documented with **deprecated** and noting the new name to reduce any confusion
