### PR TITLE
re-opening #2806 (adjust autoscale limit validation)

### LINKED ISSUE #2136: Cannot increase maximum size of Azure VMSS
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

---

I can't increase the size of an existing VMSS within Azure.  It was created via terraform originally.  I am using the latest version of terraform.  I tried the latest version of provider.azurerm (v1.17.0) with the same behavior.  

```
$ terraform plan

Error: module.ourmodule.azurerm_autoscale_setting.vmss-autoscale-cpu: expected profile.0.capacity.0.maximum to be in the range (1 - 40), got 1000

$ terraform -version
Terraform v0.11.9
+ provider.azurerm v1.16.0
+ provider.random v2.0.0


$ git diff
diff --git a/avmss.tf
index 152733e..de42594 100644
--- a/vmss.tf
+++ b/vmss.tf
@@ -91,7 +91,7 @@ resource "azurerm_autoscale_setting" "vmss-autoscale-cpu" {
     capacity {
       default = 10
       minimum = 10
-      maximum = 40
+      maximum = 1000
     }
 
$ cat vmss.tf 

.......

### Configuration for Service azurerm_autoscale_setting ###
##
##
resource "azurerm_autoscale_setting" "prod-autoscale-cpu" {
  name                = "Percentage CPU"
  resource_group_name = "${var.resource_group_name}"
  location            = "${var.location}"
  target_resource_id  = "${azurerm_virtual_machine_scale_set.prod-ss.id}"

  profile {
    name = "Percentage CPU"
    capacity {
      default = 10
      minimum = 10
      maximum = 1000
    }

.........

```

To reproduce, create an Azure VMSS with terraform with set minimum/maximum/default values.  Then increase the maximum setting.  It should fail as this does.

### LINKED ISSUE #2624: Unable to set autoscaling setting for vmss to 0 min/default, also max too low
In the console, I can apply an autoscaling rule to a VMSS and set it to 0 for min/default:  https://imgur.com/a/B5WE7i3

Checking resouces.azure.com, this is confirmed:

    "properties": {
      "profiles": [
        {
          "name": "Auto created scale condition",
          "capacity": {
            "minimum": "0",
            "maximum": "300",
            "default": "0"
          },

However, trying to do so via Terraform I hit a limit of 1-40, apparently controlled here:
https://github.com/terraform-providers/terraform-provider-azurerm/blob/47a920a9fdd0e8b82d7d7c568caee6b9fb6db410/azurerm/resource_arm_autoscale_setting.go#L74

    azure:autoscale:Setting (Stage-Eus2-Scale-Config):
      error: azure:autoscale/setting:Setting resource 'Stage-Eus2-Scale-Config' has a problem: expected profile.0.capacity.0.default to be in the range (1 - 40), got 0                                                                                            
      error: azure:autoscale/setting:Setting resource 'Stage-Eus2-Scale-Config' has a problem: expected profile.0.capacity.0.minimum to be in the range (1 - 40), got 0 

Also, the max is 40.. why on earth?  We can have somewhere upwards of 1000 for a vmss.. please fix this!

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Including the changes from @georgespatton in #2806 - pushing to that fork broken the PR 🤷‍♂️

Original PR:

---

This should fix #2136 as well as #2624 to follow the Azure documentation here: https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/overview

Fixes #2136
Fixes #2624

### CODE REVIEW

File: azurerm/resource_arm_autoscale_setting_test.go [hunk 1]
```diff
@@ -100,10 +96,56 @@ func TestAccAzureRMAutoScaleSetting_multipleProfiles(t *testing.T) {
...
+	ri := tf.AccRandTimeInt()
+	location := testLocation()
+
+	resource.ParallelTest(t, resource.TestCase{
+		PreCheck:     func() { testAccPreCheck(t) },
+		Providers:    testAccProviders,
+		CheckDestroy: testCheckAzureRMAutoScaleSettingDestroy,
+		Steps: []resource.TestStep{
+			{
+				Config: testAccAzureRMAutoScaleSetting_capacity(ri, location, 1, 3, 2),
```
Comment (katbyte) [inline azurerm/resource_arm_autoscale_setting_test.go]: We should maybe pass in 0s here to ensure its a valid minimum?

File: azurerm/resource_arm_autoscale_setting_test.go [hunk 2]
```diff
@@ -819,35 +902,17 @@ resource "azurerm_subnet" "test" {
...
+  resource_group_name    = "${azurerm_resource_group.test.name}"
+  upgrade_policy_mode    = "Automatic"
+  single_placement_group = "false"
 
   sku {
-    name     = "Standard_F2"
+    name     = "Standard_DS1_v2"
     tier     = "Standard"
-    capacity = 2
+    capacity = 30
```
Comment (tombuildsstuff) [inline azurerm/resource_arm_autoscale_setting_test.go]: needs confirmation, but I believe this can go down to 1

Comment (georgespatton) [reply azurerm/resource_arm_autoscale_setting_test.go]: It should also be able to goto 0 as well.
