### PR TITLE
`azurerm_managed_redis` - support to update `sku_name`

### LINKED ISSUE #31188: Changing Azure Managed Redis SKU recreates the whole resource
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

Changing the `sku_name` on `azurerm_managed_redis` recreates the whole resource, this destroys the database and all data is lost even when using persistence redis database. Alongside it it removes all private links and connectionstrings that is used to the by the resource.

When doing the scale operation in the portal the whole resource is not recreated and there is no data loss.

### Terraform Version

1.9.6

### AzureRM Provider Version

4.54.0

### Affected Resource(s)/Data Source(s)

azurerm_managed_redis

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      version = ">=4.54.0"
    }
  }
}

provider "azurerm" {
  features {}
  subscription_id = "XXXXXXXXXXXXXXXXXXXXXXXXXX"
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "core" {
  name     = "rg-AMR-test-dev"
  location = "Sweden Central"
}

resource "azurerm_managed_redis" "core" {
  name                = "amr-skuchange-test-dev"
  resource_group_name = azurerm_resource_group.core.name
  location            = azurerm_resource_group.core.location
  #sku_name            = "Balanced_B1"
  sku_name            = "Balanced_B0"

  high_availability_enabled = true
  public_network_access     = "Disabled"

  default_database {
    persistence_redis_database_backup_frequency = "1h"
    clustering_policy                           = "EnterpriseCluster"
    eviction_policy                             = "NoEviction"
  }
}
```

### Debug Output/Panic Output

```shell
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # azurerm_managed_redis.core must be replaced
-/+ resource "azurerm_managed_redis" "core" {
      ~ hostname                  = "amr-skuchange-test-dev.swedencentral.redis.azure.net" -> (known after apply)
      ~ id                        = "/subscriptions/XXXXXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/rg-AMR-test-dev/providers/Microsoft.Cache/redisEnterprise/amr-skuchange-test-dev" -> (known after apply)
        name                      = "amr-skuchange-test-dev"
      ~ sku_name                  = "Balanced_B1" -> "Balanced_B0" # forces replacement
      - tags                      = {} -> null
        # (4 unchanged attributes hidden)

      ~ default_database {
          ~ id                                            = "/subscriptions/XXXXXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/rg-AMR-test-dev/providers/Microsoft.Cache/redisEnterprise/amr-skuchange-test-dev/databases/default" -> (known after apply)
          ~ port                                          = 10000 -> (known after apply)
          + primary_access_key                            = (sensitive value)
          + secondary_access_key                          = (sensitive value)
            # (7 unchanged attributes hidden)
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Expected Behaviour

The resource should not be replaced and the database data should not be lost.

### Actual Behaviour

`sku_name` change forces replacment of the resource, the resource is destroyed and created again resulting in data loss.

### Steps to Reproduce

1. terraform apply
2. change the `sku_name` to another value.
3. terraform apply

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by CorrenSoft**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

**Changes**
- Changes schema to set `ForceNew: false`.
- Adds a helper function (isSkuAllowedForScaling) which calls ListSkusForScaling to know if the transition is allowed.
  - If any error occurs when validating, a warning is logged and it will continue trying to apply the change.
- Updates `Update()` method to detect and apply changes to sku_name during update.
- Updates `CustomizeDiff()` to validate that the requested SKU is allowed for scaling from the current cluster state (only when sku_name changes).
- Adds a new test case for the Update Sku scenario.

**Notes**
- Due to the restrictions that Azure has on scaling the cluster (especially when scaling down) and its complexity to determine if the change is going to be allowed just based on the Sku name, decided to use Azure as the source of true by calling a method that return the list of allowed targets.
Perhaps is cleaner and/or more efficient to add that step into the Read stage but it would imply deeper changes (it could be easily done afterwards).

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

```
TF_ACC=1 go test -v ./internal/services/managedredis -run=TestAccManagedRedis_ -timeout 180m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccManagedRedis_basic
=== PAUSE TestAccManagedRedis_basic
=== RUN   TestAccManagedRedis_withDefaultDb
=== PAUSE TestAccManagedRedis_withDefaultDb
=== RUN   TestAccManagedRedis_requiresImport
=== PAUSE TestAccManagedRedis_requiresImport
=== RUN   TestAccManagedRedis_complete
=== PAUSE TestAccManagedRedis_complete
=== RUN   TestAccManagedRedis_update
=== PAUSE TestAccManagedRedis_update
=== RUN   TestAccManagedRedis_updateSku
=== PAUSE TestAccManagedRedis_updateSku
=== RUN   TestAccManagedRedis_withPrivateEndpoint
=== PAUSE TestAccManagedRedis_withPrivateEndpoint
=== RUN   TestAccManagedRedis_withModuleArgs
=== PAUSE TestAccManagedRedis_withModuleArgs
=== RUN   TestAccManagedRedis_skuDoesNotSupportGeoReplication
=== PAUSE TestAccManagedRedis_skuDoesNotSupportGeoReplication
=== RUN   TestAccManagedRedis_moduleDoesNotSupportGeoReplication
=== PAUSE TestAccManagedRedis_moduleDoesNotSupportGeoReplication
=== RUN   TestAccManagedRedis_hasToUseNoEvictionWithRediSearch
=== PAUSE TestAccManagedRedis_hasToUseNoEvictionWithRediSearch
=== RUN   TestAccManagedRedis_hasToUseEnterpriseClusteringWithRediSearch
=== PAUSE TestAccManagedRedis_hasToUseEnterpriseClusteringWithRediSearch
=== RUN   TestAccManagedRedis_publicNetworkAccess
=== PAUSE TestAccManagedRedis_publicNetworkAccess
=== RUN   TestAccManagedRedis_dbPersistence
=== PAUSE TestAccManagedRedis_dbPersistence
=== RUN   TestAccManagedRedis_dbPersistenceCannotEnableBothRDBAndAOF
=== PAUSE TestAccManagedRedis_dbPersistenceCannotEnableBothRDBAndAOF
=== RUN   TestAccManagedRedis_dbPersistenceConflictsWithGeoReplication
=== PAUSE TestAccManagedRedis_dbPersistenceConflictsWithGeoReplication
=== CONT  TestAccManagedRedis_dbPersistence
=== CONT  TestAccManagedRedis_basic
=== CONT  TestAccManagedRedis_publicNetworkAccess
=== CONT  TestAccManagedRedis_hasToUseEnterpriseClusteringWithRediSearch
=== CONT  TestAccManagedRedis_hasToUseNoEvictionWithRediSearch
=== CONT  TestAccManagedRedis_moduleDoesNotSupportGeoReplication
=== CONT  TestAccManagedRedis_skuDoesNotSupportGeoReplication
=== CONT  TestAccManagedRedis_withModuleArgs
=== CONT  TestAccManagedRedis_withPrivateEndpoint
--- PASS: TestAccManagedRedis_moduleDoesNotSupportGeoReplication (26.38s)
--- PASS: TestAccManagedRedis_skuDoesNotSupportGeoReplication (42.20s)
=== CONT  TestAccManagedRedis_updateSku
--- PASS: TestAccManagedRedis_hasToUseNoEvictionWithRediSearch (50.77s)
=== CONT  TestAccManagedRedis_update
--- PASS: TestAccManagedRedis_hasToUseEnterpriseClusteringWithRediSearch (81.84s)
=== CONT  TestAccManagedRedis_complete
--- PASS: TestAccManagedRedis_basic (1045.82s)
=== CONT  TestAccManagedRedis_requiresImport
--- PASS: TestAccManagedRedis_withModuleArgs (1135.10s)
=== CONT  TestAccManagedRedis_withDefaultDb
--- PASS: TestAccManagedRedis_publicNetworkAccess (1186.94s)
=== CONT  TestAccManagedRedis_dbPersistenceConflictsWithGeoReplication
--- PASS: TestAccManagedRedis_dbPersistenceConflictsWithGeoReplication (14.31s)
=== CONT  TestAccManagedRedis_dbPersistenceCannotEnableBothRDBAndAOF
--- PASS: TestAccManagedRedis_dbPersistenceCannotEnableBothRDBAndAOF (10.72s)
--- PASS: TestAccManagedRedis_dbPersistence (1380.88s)
--- PASS: TestAccManagedRedis_complete (1364.69s)
--- PASS: TestAccManagedRedis_withPrivateEndpoint (1456.03s)
--- PASS: TestAccManagedRedis_requiresImport (1041.19s)
--- PASS: TestAccManagedRedis_updateSku (2053.89s)
--- PASS: TestAccManagedRedis_withDefaultDb (1046.18s)
--- PASS: TestAccManagedRedis_update (2436.92s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/managedredis  2488.047s
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-merging.md).

* `azurerm_managed_redis` - support to update property `sku_name` [GH-31203]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)

Fixes #31188

## AI Assistance Disclosure

- [ ] AI Assisted - This contribution was made by, or with the assistance of, AI/LLMs

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/managedredis/managed_redis_resource.go [hunk 1]
```diff
@@ -859,3 +877,25 @@ func flattenPersistenceRDB(input *databases.Persistence) string {
...
+
+	validSku := false
+	for _, sku := range *skusForScaling.Model.Skus {
+		if *sku.Name == targetSkuName {
+			validSku = true
+			break
+		}
+	}
+	if !validSku {
+		return fmt.Errorf("%s is not valid for scaling from the current SKU and resource configuration", targetSkuName)
```
Comment (gerrytan) [inline internal/services/managedredis/managed_redis_resource.go]: The accepted pattern is to conditionally ForceNew rather than throwing error for situations like this. Do a codebase search for `metadata.ResourceDiff.ForceNew`, you will see lots of examples.

User can use the `prevent_destroy` lifecycle arg if they want to block such replacement from taking place.

File: internal/services/managedredis/managed_redis_resource.go [hunk 2]
```diff
@@ -859,3 +877,25 @@ func flattenPersistenceRDB(input *databases.Persistence) string {
...
 }
+
+func isSkuAllowedForScaling(ctx context.Context, clusterClient *redisenterprise.RedisEnterpriseClient, clusterId *redisenterprise.RedisEnterpriseId, targetSkuName string) error {
+	skusForScaling, err := clusterClient.ListSkusForScaling(ctx, *clusterId)
+	if err != nil {
+		return fmt.Errorf("retrieving skus for scaling: %+v", err)
+	}
+	if skusForScaling.Model.Skus == nil {
+		return fmt.Errorf("no valid scaling SKUs returned by Azure for current cluster state")
+	}
```
Comment (gerrytan) [inline internal/services/managedredis/managed_redis_resource.go:893]: I think we should be more lenient in error handling here. Could user encounter permission problem when calling POST ../listSkusForScaling ?

My suggestion is to do the SKU checking on a best effort basis, and log this warning if it cannot be done: `SKU scaling cannot be validated due to ... The deployment might fail, check ... for more information`.

File: website/docs/r/managed_redis.html.markdown [hunk 3]
```diff
@@ -126,10 +126,12 @@ The following arguments are supported:
...
 
 ~> **Note:** `Enterprise_` and `EnterpriseFlash_` prefixed SKUs were previously used by Redis Enterprise, and [not supported by Managed Redis](https://learn.microsoft.com/azure/redis/migrate/migrate-overview).
 
+~> **Note:** Changing `sku_name` to a lower tier is restricted by Azure under certains conditions. Please refer to the [Azure documentation](https://learn.microsoft.com/en-us/azure/redis/how-to-scale) for more information.
+
```
Comment (gerrytan) [inline website/docs/r/managed_redis.html.markdown:134]: Please update the wording once the validation logic is amended

**Review by gerrytan — CHANGES_REQUESTED** [review]
Thank you @CorrenSoft for submitting the PR. Sorry for the delay, we are currently facing a severe shortage of reviewers.

I like the idea of dynamic validation using POST /listSkusForScaling but I have some concern around error handling and permission. Also as I recommended in the issue comment, the pattern is to conditionally ForceNew the field rather than throwing error.

File: internal/services/managedredis/managed_redis_resource.go (hunk 2 above)
Comment (CorrenSoft) [reply internal/services/managedredis/managed_redis_resource.go:893]: Well... is not impossible... if using a custom role that for some reason does not include ".../listSkusForScaling/action" could have a 403 error, which should be captured and displayed by the first evaluation (`if err != nil `). I can make it, if you think is worthy.

File: internal/services/managedredis/managed_redis_resource.go (hunk 1 above)
Comment (CorrenSoft) [reply internal/services/managedredis/managed_redis_resource.go]: Oh, i thought it was or the other option, and as i usually rather to have the error instead of a not informed loss of data, i went for that for that one. 
Let me try that option then...

Comment (gerrytan) [reply internal/services/managedredis/managed_redis_resource.go]: > not informed loss of data

If a plan result in replacement, it is clearly informed to user in the plan output. As stated above you can use 'prevent_destroy', or add a custom validation to your pipeline that inspects the plan output and fail if an accidental replacement would be made.

Comment (CorrenSoft) [reply internal/services/managedredis/managed_redis_resource.go]: That is the piece of information that i did not had, that it will reported in the plan as usual. Already updated.

File: internal/services/managedredis/managed_redis_resource.go (hunk 2 above)
Comment (CorrenSoft) [reply internal/services/managedredis/managed_redis_resource.go:893]: Updated to print a warning when the API call fails for whenever reason.

File: internal/services/managedredis/managed_redis_resource.go [hunk 4]
```diff
@@ -105,7 +105,7 @@ func (r ManagedRedisResource) Arguments() map[string]*pluginsdk.Schema {
 		"sku_name": {
 			Type:         pluginsdk.TypeString,
 			Required:     true,
-			ForceNew:     true,
+			ForceNew:     false,
```
Comment (gerrytan) [inline internal/services/managedredis/managed_redis_resource.go]: (minor) please omit property entirely rather than specifying false. If you observe other schema design, vast majority omit these rather than specifying false.

```suggestion
```

File: internal/services/managedredis/managed_redis_resource.go [hunk 5]
```diff
@@ -680,6 +685,22 @@ func (r ManagedRedisResource) CustomizeDiff() sdk.ResourceFunc {
...
+					if err != nil {
+						return err
+					}
+					clusterClient := metadata.Client.ManagedRedis.Client
+					warning, err := isSkuAllowedForScaling(ctx, clusterClient, clusterId, model.SkuName)
+					if err != nil {
+						metadata.ResourceDiff.ForceNew("sku_name")
+					} else if warning != "" {
+						metadata.Logger.Warnf(warning)
+					}
```
Comment (gerrytan) [inline internal/services/managedredis/managed_redis_resource.go]: Please keep the error / warning handling internal to isSkuAllowedForScaling function, this logic should be simplified like this:

```suggestion
					if !isSkuAllowedForScaling(ctx, clusterClient, clusterId, model.SkuName) {
						metadata.ResourceDiff.ForceNew("sku_name")
					}
```

File: internal/services/managedredis/managed_redis_resource.go [hunk 6]
```diff
@@ -859,3 +880,25 @@ func flattenPersistenceRDB(input *databases.Persistence) string {
 
 	return ""
 }
+
+func isSkuAllowedForScaling(ctx context.Context, clusterClient *redisenterprise.RedisEnterpriseClient, clusterId *redisenterprise.RedisEnterpriseId, targetSkuName string) (warning string, err error) {
```
Comment (gerrytan) [inline internal/services/managedredis/managed_redis_resource.go]:
```suggestion
func isSkuAllowedForScaling(ctx context.Context, clusterClient *redisenterprise.RedisEnterpriseClient, clusterId *redisenterprise.RedisEnterpriseId, targetSkuName string) bool {
```

File: internal/services/managedredis/managed_redis_resource.go [hunk 7]
```diff
@@ -859,3 +880,25 @@ func flattenPersistenceRDB(input *databases.Persistence) string {
...
+	for _, sku := range *skusForScaling.Model.Skus {
+		if *sku.Name == targetSkuName {
+			validSku = true
+			break
+		}
+	}
+	if !validSku {
+		return "", fmt.Errorf("%s is not valid for scaling from the current SKU and resource configuration", targetSkuName)
+	}
+	return "", nil
```
Comment (gerrytan) [inline internal/services/managedredis/managed_redis_resource.go]: This logic can now be simplified

```suggestion
	return slices.ContainsFunc(pointer.From(skusForScaling.Model.Skus), func(sku redisenterprise.SkuDetails) bool {
		return pointer.From(sku.Name) == targetSkuName
	})
```

File: internal/services/managedredis/managed_redis_resource.go [hunk 8]
```diff
@@ -859,3 +880,25 @@ func flattenPersistenceRDB(input *databases.Persistence) string {
...
 }
+
+func isSkuAllowedForScaling(ctx context.Context, clusterClient *redisenterprise.RedisEnterpriseClient, clusterId *redisenterprise.RedisEnterpriseId, targetSkuName string) (warning string, err error) {
+	skusForScaling, err := clusterClient.ListSkusForScaling(ctx, *clusterId)
+	if err != nil {
+		return fmt.Sprintf("SKU scaling cannot be validated due to an error whilst retrieving the list: %+v. The deployment might fail, check resource documentation for more information", err), nil
+	}
+	if skusForScaling.Model.Skus == nil {
+		return "SKU scaling cannot be validated due to Azure returning no information. The deployment might fail", nil
+	}
```
Comment (gerrytan) [inline internal/services/managedredis/managed_redis_resource.go:893]: Should print a warning and allow the scaling to proceed in here. In this scenario user might not have permission to query valid SKU, or the API has bugs.

```suggestion
	if err != nil {
		log.Printf("[WARN] SKU scaling cannot be validated due to an error whilst retrieving the list. The deployment might fail, check resource documentation for more information: https://learn.microsoft.com/azure/redis/how-to-scale: %+v", err)
		return true
	}
	if skusForScaling.Model.Skus == nil {
		log.Printf("[WARN] SKU scaling cannot be validated due to Azure returning no information. The deployment might fail, check resource documentation for more information: https://learn.microsoft.com/azure/redis/how-to-scale.")
		return true
	}
```

**Review by gerrytan — CHANGES_REQUESTED** [review]
Thank you @CorrenSoft , I left some more feedback to address.

Also would appreciate if you can use the "re-request review" button once it's ready for the reviewer to take another look so it's easier for us to sort and filter among many other PRs.

File: internal/services/managedredis/managed_redis_resource.go (hunk 4 above)
Comment (CorrenSoft) [reply internal/services/managedredis/managed_redis_resource.go]: Done!

File: internal/services/managedredis/managed_redis_resource.go (hunk 5 above)
Comment (CorrenSoft) [reply internal/services/managedredis/managed_redis_resource.go]: My first impulse was to keep only the decision on the function, but since that is only used once i guess that makes no difference. Is Done.

File: internal/services/managedredis/managed_redis_resource.go (hunk 8 above)
Comment (CorrenSoft) [reply internal/services/managedredis/managed_redis_resource.go:893]: Not sure if this kind of warning will be displayed in the same way, but is done.

File: internal/services/managedredis/managed_redis_resource.go [hunk 9]
```diff
@@ -859,3 +876,19 @@ func flattenPersistenceRDB(input *databases.Persistence) string {
...
 	return ""
 }
+
+func isSkuAllowedForScaling(ctx context.Context, clusterClient *redisenterprise.RedisEnterpriseClient, clusterId *redisenterprise.RedisEnterpriseId, targetSkuName string) bool {
+	skusForScaling, err := clusterClient.ListSkusForScaling(ctx, *clusterId)
+	if err != nil {
+		log.Printf("[WARN] SKU scaling cannot be validated due to an error whilst retrieving the list. The deployment might fail, check resource documentation for more information: https://learn.microsoft.com/azure/redis/how-to-scale: %+v", err)
+		return true
+	}
+	if skusForScaling.Model.Skus == nil {
```
Comment (catriona-m) [inline internal/services/managedredis/managed_redis_resource.go]: should we nil check `Model` first?

File: internal/services/managedredis/managed_redis_resource.go [hunk 10]
```diff
@@ -680,6 +684,19 @@ func (r ManagedRedisResource) CustomizeDiff() sdk.ResourceFunc {
...
+			if metadata.ResourceDiff.HasChanges("sku_name") {
+				if resId := metadata.ResourceDiff.Id(); resId != "" {
+					clusterId, err := redisenterprise.ParseRedisEnterpriseID(resId)
+					if err != nil {
+						return err
+					}
+					clusterClient := metadata.Client.ManagedRedis.Client
+					if !isSkuAllowedForScaling(ctx, clusterClient, clusterId, model.SkuName) {
+						metadata.ResourceDiff.ForceNew("sku_name")
+					}
```
Comment (catriona-m) [inline internal/services/managedredis/managed_redis_resource.go:700]: could we add a test step to confirm the property becomes ForceNew when attempting to downgrade?

**Review by catriona-m — CHANGES_REQUESTED** [review]
Thanks for working on this @CorrenSoft - this looks good to me, I just left a couple of suggestions inline. Thanks!

File: internal/services/managedredis/managed_redis_resource.go (hunk 10 above)
Comment (sreallymatt) [reply internal/services/managedredis/managed_redis_resource.go:700]: This is difficult to reliably test as it's not necessarily SKU based, it depends on other factors, e.g. memory usage at the time of the downgrade and the available memory on the requested SKU

**Comment by Garderoben** [comment]
@CorrenSoft Epic! Thanks!
