### PR TITLE
`azurerm_postgresql_flexible_server_virtual_endpoint`: add support for cross subscription flexible servers

### LINKED ISSUE #29141: [azurerm_postgresql_flexible_server] Getting “could not locate postgres replica server with name" for a replica that was successfully created
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

User is trying to create a cross subscription+ cross region read replica and then create virtual endpoints for PGFS server. The script tries to create a read replica in another region first and then create virtual endpoints from the replica server. 

While the script runs fine on Azure RM version 4.5.0, the deployment fails on the latest Azure RM versions with “could not locate postgres replica server with name" and ''Server 'postgres-rr-omga1-om-ger01' is busy with another operation. Please try again later.''

For “could not locate postgres replica server with name" is not coming from our RP.  We are unsure as to why this error is being thrown from the SDK since the replica was created. Can we please be helped to understand this bug?

Need determined what caused script to start failing after Azure RM version 4.5.0

### Terraform Version

n/a

### AzureRM Provider Version

v4.20.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
n/a
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

Should not say that replica could not be located.

### Actual Behaviour

**14:21:23  [0;90m08:51:21.919 [0m[0;37mSTDOUT [0m[0;38;5;139m[ms360-azr-postgres-ga-rr-tf-module] [0m[0;36mtfwrapper: [0m[Error][ms360-azr-postgres-ga-rr-tf-module] {'name':'52e6d1c5-9125-4c59-9ead-680977307982','status':'Failed','startTime':'2025-02-18T08:49:41.62Z','error':{'code':'ServerBusy','message':'Server 'postgres-rr-omga1-om-ger01' is busy with another operation. Please try again later.'}}**
14:21:23  [0;90m08:51:21.919 [0m[0;37mSTDOUT [0m[0;38;5;139m[ms360-azr-postgres-ga-rr-tf-module] [0m[0;36mtfwrapper: [0m[Error][ms360-azr-postgres-ga-rr-tf-module] -----[end]-----
14:21:23  [0;90m08:51:21.919 [0m[0;37mSTDOUT [0m[0;38;5;139m[ms360-azr-postgres-ga-rr-tf-module] [0m[0;36mtfwrapper: [0m[Error][ms360-azr-postgres-ga-rr-tf-module]
14:21:23  [0;90m08:51:21.919 [0m[0;37mSTDOUT [0m[0;38;5;139m[ms360-azr-postgres-ga-rr-tf-module] [0m[0;36mtfwrapper: [0m[Error][ms360-azr-postgres-ga-rr-tf-module]
14:21:23  [0;90m08:51:21.919 [0m[0;37mSTDOUT [0m[0;38;5;139m[ms360-azr-postgres-ga-rr-tf-module] [0m[0;36mtfwrapper: [0m[Error][ms360-azr-postgres-ga-rr-tf-module]   with azurerm_postgresql_flexible_server_configuration.postgres_server_parameters['max_worker_processes'],
14:21:23  [0;90m08:51:21.920 [0m[0;37mSTDOUT [0m[0;38;5;139m[ms360-azr-postgres-ga-rr-tf-module] [0m[0;36mtfwrapper: [0m[Error][ms360-azr-postgres-ga-rr-tf-module]   on main.tf line 108, in resource 'azurerm_postgresql_flexible_server_configuration' 'postgres_server_parameters':
14:21:23  [0;90m08:51:21.920 [0m[0;37mSTDOUT [0m[0;38;5;139m[ms360-azr-postgres-ga-rr-tf-module] [0m[0;36mtfwrapper: [0m[Error][ms360-azr-postgres-ga-rr-tf-module]  108: resource 'azurerm_postgresql_flexible_server_configuration' 'postgres_server_parameters' {
14:21:23  [0;90m08:51:21.920 [0m[0;37mSTDOUT [0m[0;38;5;139m[ms360-azr-postgres-ga-rr-tf-module] [0m[0;36mtfwrapper: [0m[Error][ms360-azr-postgres-ga-rr-tf-module]
14:21:23  [0;90m08:51:21.922 [0m[0;37mSTDOUT [0m[0;38;5;139m[ms360-azr-postgres-ga-rr-tf-module] [0m[0;36mtfwrapper: [0m[Error][ms360-azr-postgres-ga-rr-tf-module]
14:21:23  [0;90m08:51:21.922 [0m[0;37mSTDOUT [0m[0;38;5;139m[ms360-azr-postgres-ga-rr-tf-module] **[0m[0;36mtfwrapper: [0m[Error][ms360-azr-postgres-ga-rr-tf-module] Error: could not locate postgres replica server with name postgres-rr-omga1-om-ger01**

### Steps to Reproduce

Create replica in another region to primary server.
Then create virtual endpoint from the replica.

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by wuxu92**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

From V4.7.0 `azurerm_postgresql_flexible_server_virtual_endpoint` resource of difference subscription servers wil encounter the error, because we can only list servers by subscription, although before v.4.70 the cross subscription support is actually not 100% correct. This PR is to set the replica server back to state if it canoot be listed in the same subscription.

https://github.com/hashicorp/terraform-provider-azurerm/blob/4f8e3abe72dc419d47bd005508b62fb361cdb610/internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource.go#L282

Note: cross subscription replication needs to be enabled by service team non-standard operation. waiting service team to enable it for our test subs.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

```
--- PASS: TestAccPostgresqlFlexibleServerVirtualEndpoint_crossSubscription (1076.64s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/postgres      1076.673s
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_postgresql_flexible_server_virtual_endpoint` - support replica server of crossing subscriptions [GH-29141 ]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #29141 

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]

File: internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource.go [hunk 1]
```diff
@@ -184,6 +184,9 @@ func (r PostgresqlFlexibleServerVirtualEndpointResource) Read() sdk.ResourceFunc
 							}
 
 							replicaServerId = replicaId.ID()
+						} else {
+							// if the replica server is not found, it may exists in different subscription, read from the metadata
+							replicaServerId = metadata.ResourceData.Get("replica_server_id").(string)
```
[the remark this answers is not in the document]
Comment (omerfeldman22) [reply internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource.go:230]: Hi Guys - @wuxu92, @katbyte, Any update on this enhancment?

[the remark this answers is not in the document]
Comment (gkasar) [reply internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource.go:230]: Hi @katbyte - Can you please help us update on the review?

[the remark this answers is not in the document]
Comment (gkasar) [reply internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource.go:230]: Hi @katbyte - Can you please help us with this PR review?

**Comment by magodo** [comment]
The failure that users encountered was introduced in #27509. The complete evolving of this resource is like below:

- Before #27509: Assume the source and replica servers are under the same subscription, same resource group (same as this virtual endpoint), all constructed manually.
- In #27509: Source server is constructed manually, by assuming it is under the same subscription & resource group as this virtual endpoint. The replica server is precisely looked up by a ListBySubscription on its name (with the assumption that it's under the same subscription as the virtual endpoint).

This user has a replica server from another subscription, which can't be looked up by the List call (actually list by subscription), results into an error.

The root cause of all above less ideal implementation is the GET API on this resource only returns the names of the source and replica servers. Since the PG team supports cross subscription of servers, making it even possible that both the source and replica servers are not in the subscription of this virtual endpoint, breaks all the assumptions above.

Based on the current buggy implementation, most users are using `ignore_changes` for the source and replica server ids, especially when a fail over can happen. This PR looks like a quick fix to unblock the current user (and others have similar cross subscriptions setup), without causing another issue, assuming the users are ignoring the changes (as otherwise non of the pre-existing implementation will work without a plan diff).

With above, I think we can merge it for now and ask the service team to improve the API, hopefully return a new `member_ids` to return the full ids instead of just names. Cc @gkasar

File: internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource_test.go [hunk 2]
```diff
@@ -80,6 +81,28 @@ func TestAccPostgresqlFlexibleServerVirtualEndpoint_crossRegion(t *testing.T) {
 	})
 }
 
+func TestAccPostgresqlFlexibleServerVirtualEndpoint_crossSubscription(t *testing.T) {
+	t.Skip("Skipping: cross subscription replication is non-standard operation and need to add the subscriptions to a service whitelist")
```
Comment (catriona-m) [inline internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource_test.go]: could you clarify what is needed to get this test running? is there a reason why we should not add the subscription to the service list rather than just skipping this test?

File: internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource_test.go [hunk 3]
```diff
@@ -463,6 +486,91 @@ resource "azurerm_postgresql_flexible_server" "west" {
...
+
+  tenant_id       = "%[2]s"
+  subscription_id = "%[3]s"
+}
+
+data "azurerm_client_config" "current" {}
+
+resource "azurerm_resource_group" "test" {
+  name     = "acctestRG-%[1]d"
+  location = "westus2" // force region due to service whitelisting
```
Comment (catriona-m) [inline internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource_test.go]:
```suggestion
  location = "westus2" // force region due to service allow list
```

File: internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource_test.go [hunk 4]
```diff
@@ -463,6 +486,91 @@ resource "azurerm_postgresql_flexible_server" "west" {
...
+}
+
+resource "azurerm_resource_group" "alt" {
+  provider = azurerm-alt
+
+  name     = "acctestRG-alt-%[1]d"
+  location = "eastus2" // force region due to service whitelisting
```
Comment (catriona-m) [inline internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource_test.go]:
```suggestion
  location = "eastus2" // force region due to service allow list
```

File: internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource_test.go (hunk 2 above)
Comment (wuxu92) [reply internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource_test.go]: By default, cross-subscription read replicas are not permitted. To enable them, it is necessary to file a support ticket, providing the subscription and region details. The PostgreSQL service team will then add these to an allow list. However, as this is not a fully supported feature and the resource in question is somewhat imperfect, I suggest skipping this test.

File: internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource_test.go (hunk 3 above)
Comment (wuxu92) [reply internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource_test.go]: updated.

File: internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource_test.go (hunk 4 above)
Comment (wuxu92) [reply internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource_test.go]: updated.

Comment (gkasar) [reply internal/services/postgres/postgresql_flexible_server_virtual_endpoint_resource_test.go]: Hi @catriona-m  - Can you please help us update/review the PR? Thanks!

**Comment by gkasar** [comment]
Thank you @catriona-m for the help!
