### PR TITLE
`log_analytics_workspace` - exclude `Free` from `daily_quota_gb` settings

### LINKED ISSUE #9150: azurerm_log_analytics_workspace creation fails on Bad Request when selecting Free tier
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azurerm v2.34.0

### Affected Resource(s)

* `azurerm_log_analytics_workspace`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "= 2.34.0"
  features {}
}

resource "azurerm_resource_group" "resource_group" {
  location = "West Europe"
  name     = "log-analytics-rg"
}

resource "azurerm_log_analytics_workspace" "log_analytics" {
  name                = "log-analytics-test"
  resource_group_name = azurerm_resource_group.resource_group.name
  location            = "West Europe"
  sku                 = "free"
}
```

The result is the same if daily quota and retention are specified explicitly:
```hcl
provider "azurerm" {
  version = "= 2.34.0"
  features {}
}

resource "azurerm_resource_group" "resource_group" {
  location = "West Europe"
  name     = "log-analytics-rg"
}

resource "azurerm_log_analytics_workspace" "log_analytics" {
  name                = "log-analytics-test"
  resource_group_name = azurerm_resource_group.resource_group.name
  location            = "West Europe"
  sku                 = "free"
  retention_in_days   = 7
  daily_quota_gb      = 0.5
}

```

### Debug Output
- The first configuration without specifying quotas: https://gist.github.com/salatamartin/01e3644ed665fe8050363acd0730c141
- The second one with quotas: https://gist.github.com/salatamartin/5236c779da390a1e64e330b41c748d75

### Expected Behavior

Terraform creates `azurerm_log_analytics_workspace` without failing.

### Actual Behavior
Terraform run fails on "Bad Request". 
1. Terraform sends to Azure this object `{"location":"westeurope","properties":{"retentionInDays":0,"sku":{"name":"free"},"workspaceCapping":{"dailyQuotaGb":-1}},"tags":{}}`
2. Azure responds with bad request `{"error":{"code":"BadRequest","message":"The object supplied in the request is invalid","target":"WorkspaceCapping"}}`

If the proper quotas acceptable by Free tier are specified:
1. Terraform sends `{"location":"westeurope","properties":{"retentionInDays":7,"sku":{"name":"free"},"workspaceCapping":{"dailyQuotaGb":0.5}},"tags":{}}`
2. Azure responds with the same message `{"error":{"code":"BadRequest","message":"The object supplied in the request is invalid","target":"WorkspaceCapping"}}`

Note: Tier `PerGB2018` seems to be working fine.

### Steps to Reproduce

1. Have azurerm provider in version at least `v2.34.0`  (the daily quota was introduced here)
1. `terraform apply` on the provided configuration above

### References
Probably something to do with #3288

### PR DESCRIPTION
**Pull request by jackofallops**
The `Free` tier SKU does not accept changes for the Quota value, and is always set to `0.5` GB.

Upgrade Notes:
Previously the `daily_quota_gb` argument on the `log_analytics_workspace` resource required setting to `-1` to disable. This is no longer a valid value and the argument should be removed to set to the default of `Unlimited`.

fixes #9150

### CODE REVIEW

File: azurerm/internal/services/loganalytics/log_analytics_workspace_resource.go [hunk 1]
```diff
@@ -148,12 +149,18 @@ func resourceArmLogAnalyticsWorkspaceCreateUpdate(d *schema.ResourceData, meta i
...
-			WorkspaceCapping: &operationalinsights.WorkspaceCapping{
-				DailyQuotaGb: &dailyQuotaGb,
-			},
 		},
 	}
 
+	dailyQuotaGb, ok := d.GetOk("daily_quota_gb")
+	if ok && skuName == "Free" {
+		return fmt.Errorf("`Free` tier SKU quota is not configurable and is hard set to 0.5GB")
+	} else if skuName != "Free" {
```
Comment (manicminer) [inline azurerm/internal/services/loganalytics/log_analytics_workspace_resource.go:158]:
```suggestion
	if ok && strings.EqualFold(skuName, operationalinsights.WorkspaceSkuNameEnumFree) {
		return fmt.Errorf("`Free` tier SKU quota is not configurable and is hard set to 0.5GB")
	} else if !strings.EqualFold(skuName, operationalinsights.WorkspaceSkuNameEnumFree) {
```

File: azurerm/internal/services/loganalytics/log_analytics_workspace_resource.go [hunk 2]
```diff
@@ -208,7 +215,10 @@ func resourceArmLogAnalyticsWorkspaceRead(d *schema.ResourceData, meta interface
 		d.Set("sku", sku.Name)
 	}
 	d.Set("retention_in_days", resp.RetentionInDays)
-	if workspaceCapping := resp.WorkspaceCapping; workspaceCapping != nil {
+	if resp.WorkspaceProperties != nil && resp.WorkspaceProperties.Sku != nil && strings.EqualFold(string(resp.WorkspaceProperties.Sku.Name), "free") {
```
Comment (manicminer) [inline azurerm/internal/services/loganalytics/log_analytics_workspace_resource.go:218]:
```suggestion
	if resp.WorkspaceProperties != nil && resp.WorkspaceProperties.Sku != nil && strings.EqualFold(string(resp.WorkspaceProperties.Sku.Name), operationalinsights.WorkspaceSkuNameEnumFree) {
```

File: azurerm/internal/services/loganalytics/log_analytics_workspace_resource.go [hunk 3]
```diff
@@ -263,3 +273,12 @@ func ValidateAzureRmLogAnalyticsWorkspaceName(v interface{}, _ string) (warnings
 
 	return warnings, errors
 }
+
+func dailyQuotaGbDiffSuppressFunc(_, _, _ string, d *schema.ResourceData) bool {
+	// (@jackofallops) - 'free' is a legacy special case that is always set to 0.5GB
+	if skuName := d.Get("sku").(string); strings.EqualFold(skuName, "free") {
```
Comment (manicminer) [inline azurerm/internal/services/loganalytics/log_analytics_workspace_resource.go:279]:
```suggestion
	if skuName := d.Get("sku").(string); strings.EqualFold(skuName, operationalinsights.WorkspaceSkuNameEnumFree) {
```

**Review by manicminer — CHANGES_REQUESTED** [review]
@jackofallops LGTM, just a couple suggestions to account for case insensitivity

**Review by manicminer — APPROVED** [review]

File: website/docs/r/log_analytics_workspace.html.markdown [hunk 4]
```diff
@@ -43,7 +43,9 @@ The following arguments are supported:
 
 * `retention_in_days` - (Optional) The workspace data retention in days. Possible values are either 7 (Free Tier only) or range between 30 and 730.
 
-* `daily_quota_gb` - (Optional) The workspace daily quota for ingestion in GB.  Defaults to -1 (unlimited).
+* `daily_quota_gb` - (Optional) The workspace daily quota for ingestion in GB.  Defaults to -1 (unlimited) if omitted.
+
+~> **NOTE:** The `Free` tier SKU does not accept any value for this argument, and is always configured as `0.5` GB.
```
Comment (tombuildsstuff) [inline website/docs/r/log_analytics_workspace.html.markdown:48]:
```suggestion
-> **Note:** When `sku_name` is set to `Free` this field must be set to `0.5` (GB) - as Azure does not allow any other value.
```

Comment (tombuildsstuff) [reply website/docs/r/log_analytics_workspace.html.markdown:48]: probably also wants a note under SKU tbh

**Review by tombuildsstuff — APPROVED** [review]
otherwise LGTM 👍
