### PR TITLE
cosmos db account - fixes for #1525

### LINKED ISSUE #1525: CosmosDB polling/set fixes
Opening this issue to ensure it's tracked for the release. The following CosmosDB tests need fixing before we release 1.9.0:

```
------- Stdout: -------
=== RUN   TestAccAzureRMCosmosDBAccount_failover_boundedStaleness
--- FAIL: TestAccAzureRMCosmosDBAccount_failover_boundedStaleness (930.25s)
	testing.go:573: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.
		
		Error: Error applying: 1 error(s) occurred:
		
		* azurerm_resource_group.test (destroy): 1 error(s) occurred:
		
		* azurerm_resource_group.test: Error deleting Resource Group "acctestRG-3021637299523799643": pollingTrackerBase#updatePollingState: the response from the async operation has an invalid status code: StatusCode=0
		
		State: azurerm_resource_group.test:
		  ID = /subscriptions/*******/resourceGroups/acctestRG-3021637299523799643
		  provider = provider.azurerm
		  location = westeurope
		  name = acctestRG-3021637299523799643
		  tags.% = 0
FAIL
```

```
------- Stdout: -------
=== RUN   TestAccDataSourceAzureRMCosmosDBAccount_complete
--- FAIL: TestAccDataSourceAzureRMCosmosDBAccount_complete (607.20s)
	testing.go:513: Step 0 error: Error applying: 1 error(s) occurred:
		
		* data.azurerm_cosmosdb_account.test: data.azurerm_cosmosdb_account.test: Error setting `capabilities`: capabilities: '': source data must be an array or slice, got struct
	testing.go:573: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.
		
		Error: Error refreshing: 1 error(s) occurred:
		
		* data.azurerm_cosmosdb_account.test: 1 error(s) occurred:
		
		* data.azurerm_cosmosdb_account.test: data.azurerm_cosmosdb_account.test: Error setting `capabilities`: capabilities: '': source data must be an array or slice, got struct
		
		State: <nil>
FAIL
```

### PR DESCRIPTION
**Pull request by katbyte**
fixes #1525

### CODE REVIEW

File: azurerm/resource_arm_cosmos_db_account.go [hunk 1]
```diff
@@ -573,24 +573,48 @@ func resourceArmCosmosDBAccountDelete(d *schema.ResourceData, meta interface{})
...
-	err = future.WaitForCompletion(ctx, client.Client)
+	err = future.WaitForCompletionRef(ctx, client.Client)
 	if err != nil {
-		if response.WasNotFound(future.Response()) {
-			return nil
+		if !response.WasNotFound(future.Response()) {
+			return fmt.Errorf("Error issuing AzureRM delete request for CosmosDB Account '%s': %+v", name, err)
 		}
-		return fmt.Errorf("Error issuing AzureRM delete request for CosmosDB Account '%s': %+v", name, err)
 	}
```
Comment (tombuildsstuff) [inline azurerm/resource_arm_cosmos_db_account.go]: TBH we could probably remove polling via this future for the moment given the custom waiter?
