### PR TITLE
`azurerm_api_management_certificate` - allow key vault certificates

### LINKED ISSUE #10138: azurerm_api_management_certificate missing azure keyvault certificate input
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Actual Behaviour

 The azurerm_api_management_certificate is missing a way to input Keyvault certificate, whereas this is feasible through Azure API : https://docs.microsoft.com/en-us/rest/api/apimanagement/2020-06-01-preview/certificate/createorupdate#apimanagementcreatecertificatewithkeyvault.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by MattiasAng**
Dependency on #11146

Fixes #10138

Creating this pull request even though dependency is not merged yet since I want feedback on if implementation is OK. Unfortunately Microsoft is not so consistent with which ID of User Assigned Managed Identity they want on resources.

### CODE REVIEW

File: azurerm/internal/services/apimanagement/api_management_certificate_resource.go [hunk 1]
```diff
@@ -44,15 +46,30 @@ func resourceApiManagementCertificate() *schema.Resource {
 
 			"data": {
 				Type:         schema.TypeString,
-				Required:     true,
+				Optional:     true,
 				Sensitive:    true,
 				ValidateFunc: validation.StringIsBase64,
 			},
```
Comment (katbyte) [inline azurerm/internal/services/apimanagement/api_management_certificate_resource.go:52]: could we add the RequiredWith & conflicts with property here too? it needs to be on both properties it applies to

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks for the pr @MattiasAng - overall looks good but i've left a couple comments inline to address

File: azurerm/internal/services/apimanagement/api_management_certificate_resource.go (hunk 1 above)
Comment (MattiasAng) [reply azurerm/internal/services/apimanagement/api_management_certificate_resource.go:53]: Added conflicts with on data. Both key_vault_secret_id and data can be set by themselves so shouldn't need a RequiredWith on them.

**Comment by MattiasAng** [comment]
@manicminer @katbyte This should be good now that API management version is updated.

File: azurerm/internal/services/apimanagement/api_management_certificate_resource.go [hunk 2]
```diff
@@ -43,16 +45,32 @@ func resourceApiManagementCertificate() *schema.Resource {
...
-				Optional:  true,
-				Sensitive: true,
+			"key_vault_secret_id": {
+				Type:          schema.TypeString,
+				Optional:      true,
+				ValidateFunc:  keyVaultValidate.NestedItemIdWithOptionalVersion,
+				ConflictsWith: []string{"data", "password"},
+			},
+
+			"key_vault_identity_client_id": {
```
Comment (katbyte) [inline azurerm/internal/services/apimanagement/api_management_certificate_resource.go:69]: doses it make sense to put these into a `key_vault` block?

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @MattiasAng  - looks like we have a crash during the tests thou

**Comment by katbyte** [comment]
```
Test ended in panic.

------- Stdout: -------
=== RUN   TestAccApiManagementBackend_allProperties
=== PAUSE TestAccApiManagementBackend_allProperties
=== CONT  TestAccApiManagementBackend_allProperties

------- Stderr: -------
2021/04/29 19:53:14 [DEBUG] not using binary driver name, it's no longer needed
2021/04/29 19:53:15 [DEBUG] not using binary driver name, it's no longer needed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4447195]

goroutine 765 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/apimanagement.resourceApiManagementCertificateRead(0xc0020bde30, 0x55fe540, 0xc00028a300, 0x0, 0x0)
	/opt/teamcity-agent/work/a73be106926a7472/azurerm/internal/services/apimanagement/api_management_certificate_resource.go:200 +0x755
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/apimanagement.resourceApiManagementCertificateCreateUpdate(0xc0020bde30, 0x55fe540, 0xc00028a300, 0x0, 0x0)
	/opt/teamcity-agent/work/a73be106926a7472/azurerm/internal/services/apimanagement/api_management_certificate_resource.go:161 +0x836
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00147c320, 0xc0012a4190, 0xc002164c20, 0x55fe540, 0xc00028a300, 0x562db01, 0xc002418c38, 0xc001572180)
	/opt/teamcity-agent/work/a73be106926a7472/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:320 +0x375
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000b93800, 0xc00134ba38, 0xc0012a4190, 0xc002164c20, 0xc0021dcbc8, 0xc0014eed70, 0x5630de0)
	/opt/teamcity-agent/work/a73be106926a7472/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc001a94700, 0x65875d0, 0xc002530e40, 0xc0020bd960, 0xc001a94700, 0xc002530e40, 0xc002804ba0)
	/opt/teamcity-agent/work/a73be106926a7472/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:895 +0x8a5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x5b09400, 0xc001a94700, 0x65875d0, 0xc002530e40, 0xc0033bc960, 0x0, 0x65875d0, 0xc002530e40, 0xc0021ee000, 0x1f0e)
	/opt/teamcity-agent/work/a73be106926a7472/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001c72700, 0x65ce0b8, 0xc0030b8180, 0xc00139da00, 0xc003299f20, 0x99c76e0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/a73be106926a7472/vendor/google.golang.org/grpc/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc001c72700, 0x65ce0b8, 0xc0030b8180, 0xc00139da00, 0x0)
	/opt/teamcity-agent/work/a73be106926a7472/vendor/google.golang.org/grpc/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0011a6040, 0xc001c72700, 0x65ce0b8, 0xc0030b8180, 0xc00139da00)
	/opt/teamcity-agent/work/a73be106926a7472/vendor/google.golang.org/grpc/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
```

File: azurerm/internal/services/apimanagement/api_management_certificate_resource.go (hunk 2 above)
Comment (MattiasAng) [reply azurerm/internal/services/apimanagement/api_management_certificate_resource.go:69]: It makes sense, especially since that is how the request to API is done, but in my opinion for small resources like this it reduces the complexity if all properties are on top-level and we can handle conflicts between properties.
I don't see a lot of changes coming to this resource in the future after this is implemented.

Let me know if you want it changed.

**Comment by MattiasAng** [comment]
Certificate tests are succeeding locally now (bad rebase) but looking in to the panic for backend, possibly an issue from API update.

**Comment by MattiasAng** [comment]
Certificate tests are working locally now (bad rebase). The backend panic is probably an issue from API update but I am working on it.

**Comment by MattiasAng** [comment]
Sorry, only ran keyvault tests, should be good now. See reply on your question inline.

````
--- PASS: TestAccApiManagementCertificate_basic (2846.87s)
--- PASS: TestAccApiManagementCertificate_basicKeyVaultUserIdentity (3032.96s)
--- PASS: TestAccApiManagementCertificate_basicKeyVaultUpdate (3074.11s)
--- PASS: TestAccApiManagementCertificate_basicKeyVaultSystemIdentity (3205.09s)
--- PASS: TestAccApiManagementCertificate_requiresImport (3391.28s)
````

**Review by katbyte — APPROVED** [review]
Thanks @MattiasAng - LGTM 👍
