### PR TITLE
`azurerm_network_security_perimeter` - Create new resources

### LINKED ISSUE #28698: Add Support for Azure Network Security Perimeter
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Azure has introduced Network Security Perimeter (NSP), a new networking feature designed to provide a logical isolation boundary for Platform-as-a-Service (PaaS) resources such as Azure Storage, CosmosDB, and Azure SQL Database. This feature offers an alternative to Private Endpoints by restricting public access while allowing controlled exceptions via access rules.

Currently, Terraform users must rely on the AzAPI provider to provision and manage NSP resources. This approach is cumbersome due to the lack of native data sources and resources in the azurerm provider. Adding native support for NSP in azurerm would streamline deployment, improve usability, and align with other networking features already supported.

### Why This Is Needed

Reduce Complexity: The current approach using AzAPI is cumbersome and requires manual data retrieval for referencing existing NSP resources.

Standardization: Align with existing azurerm networking resources like Virtual WAN and Private Endpoints.

Improved Terraform Support: Enhance usability and automation of NSP deployments within Terraform-managed environments.

### References

[Azure Network Security Perimeter Documentation](https://learn.microsoft.com/en-us/azure/networking)

[Azure Resource Manager API for NSP](https://learn.microsoft.com/en-us/azure/networking/nsp-api)

### Conclusion

Native support for Azure Network Security Perimeter in the azurerm provider would greatly simplify infrastructure management for users looking to secure Azure PaaS resources. By introducing these Terraform resources and data sources, we can improve automation, reduce reliance on AzAPI, and bring feature parity with existing networking solutions.

Would love to hear thoughts from the community and maintainers on the feasibility of implementing this!

### New or Affected Resource(s)/Data Source(s)

azurerm_network_security_perimeter

### Potential Terraform Configuration

```hcl
### Proposed Resources

Network Security Perimeter


resource "azurerm_network_security_perimeter" "main" {
  name                = "nsp-foo"
  location            = "westus"
  resource_group_name = "rg-foo"
}


Network Security Perimeter Profile


resource "azurerm_network_security_perimeter_profile" "profile1" {
  name                = "nsp-foo-profile1"
  location            = "westus"
  resource_group_name = "rg-foo"
  perimeter_id        = azurerm_network_security_perimeter.main.id
}


Network Security Perimeter Access Rule


resource "azurerm_network_security_perimeter_profile_access_rule" "rule1" {
  name                = "nsp-foo-rule1"
  location            = "westus"
  resource_group_name = "rg-foo"
  profile_id          = azurerm_network_security_perimeter_profile.profile1.id
  direction           = "Inbound"
  address_prefixes    = ["10.45.0.0/16"]
}


Resource Association


resource "azurerm_network_security_perimeter_resource_association" "cosmosdb_association" {
  name                 = "cosmosdb-nsp-link"
  resource_group_name  = "rg-foo"
  perimeter_id         = azurerm_network_security_perimeter.main.id
  resource_id          = azurerm_cosmosdb_account.main.id
  access_mode          = "Learning"
  profile_id           = azurerm_network_security_perimeter_profile.profile1.id
}


### Proposed Data Sources

Network Security Perimeter


data "azurerm_network_security_perimeter" "main" {
  name                = "nsp-foo"
  resource_group_name = "rg-foo"
}


Network Security Perimeter Profile


data "azurerm_network_security_perimeter_profile" "profile1" {
  perimeter_name      = "nsp-foo"
  name                = "nsp-foo-profile1"
  resource_group_name = "rg-foo"
}
```

### References

_No response_

### PR DESCRIPTION
**Pull request by zachrousseau**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Creates [Network Security Perimeter](https://learn.microsoft.com/en-us/azure/private-link/network-security-perimeter-concepts) resources and data resources.

## PR Checklist

- [X] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [X] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [X] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [X] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [X] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [X] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [X] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [X] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-merging.md).

* **New Data Source** `azurerm_network_security_perimeter`  [GH-XXXX]
* **New Data Source** `azurerm_network_security_perimeter_profile` [GH-XXXX]
* **New Resource**: `azurerm_network_security_perimeter` [GH-XXXX]
* **New Resource**: `azurerm_network_security_perimeter_profile` [GH-XXXX]
* **New Resource**: `azurerm_network_security_perimeter_access_rule` [GH-XXXX]
* **New Resource**: `azurerm_network_security_perimeter_association` [GH-XXXX]

This is a (please select all that apply):

- [ ] Bug Fix
- [X] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)

Closes #28698 

## AI Assistance Disclosure

- [X] AI Assisted - This contribution was made by, or with the assistance of, AI/LLMs

ChatGPT assistance for code generation and documentation. 

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Comment by pregress** [comment]
@jackofallops could you review?

File: internal/services/network/network_security_perimeter_access_rule.go [hunk 1]
```diff
@@ -0,0 +1,319 @@
+// Copyright (c) HashiCorp, Inc.
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule.go]: Could you rename this file to `network_security_perimeter_access_rule_resource.go`

File: internal/services/network/network_security_perimeter_access_rule.go [hunk 2]
```diff
@@ -0,0 +1,319 @@
...
+	FullyQualifiedDomainNames []string `tfschema:"fqdns"`
+	Subscriptions             []string `tfschema:"subscription_ids"`
+}
+
+func (NetworkSecurityPerimeterAccessRuleResource) Arguments() map[string]*pluginsdk.Schema {
+	return map[string]*pluginsdk.Schema{
+		"name": {
+			Type:         pluginsdk.TypeString,
+			Required:     true,
+			ValidateFunc: validation.StringIsNotEmpty,
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule.go]: The API spec documents a specific pattern that is allowed for the `name` field, could you look at adding it? ([ref](https://learn.microsoft.com/en-us/rest/api/network-security-perimeter/network-security-perimeter-profiles/create-or-update?view=rest-network-security-perimeter-2025-03-01&tabs=HTTP#uri-parameters))

`validation.StringMatch` should work for this

File: internal/services/network/network_security_perimeter_access_rule.go [hunk 3]
```diff
@@ -0,0 +1,319 @@
...
+			ForceNew:     true,
+		},
+
+		"profile_id": {
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule.go]: Generally when referencing a parent resource's ID we name the property after the parent resource, could you change this to:

```suggestion
		"network_security_perimeter_profile_id": {
```

File: internal/services/network/network_security_perimeter_access_rule.go [hunk 4]
```diff
@@ -0,0 +1,319 @@
...
+	return sdk.ResourceFunc{
+		Func: func(ctx context.Context, metadata sdk.ResourceMetaData) error {
+			rd := metadata.ResourceDiff
+			direction := rd.Get("direction").(string)
+
+			if direction == string(networksecurityperimeteraccessrules.AccessRuleDirectionOutbound) && rd.HasChange("address_prefixes") {
+				return fmt.Errorf("`address_prefixes` can only be set when `direction` is Inbound")
+			}
+
+			if direction == string(networksecurityperimeteraccessrules.AccessRuleDirectionOutbound) && rd.HasChange("subscription_id") {
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule.go]: typo
```suggestion
			if direction == string(networksecurityperimeteraccessrules.AccessRuleDirectionOutbound) && rd.HasChange("subscription_ids") {
```

File: internal/services/network/network_security_perimeter_access_rule_resource.go [hunk 5]
```diff
@@ -0,0 +1,319 @@
...
+				return fmt.Errorf("`address_prefixes` can only be set when `direction` is Inbound")
+			}
+
+			if direction == string(networksecurityperimeteraccessrules.AccessRuleDirectionOutbound) && rd.HasChange("subscription_id") {
+				return fmt.Errorf("`subscription_ids` can only be set when `direction` is Inbound")
+			}
+
+			if direction == string(networksecurityperimeteraccessrules.AccessRuleDirectionInbound) && rd.HasChange("fqdns") {
+				return fmt.Errorf("`fqdns` cannot be specified when `direction` is Outbound")
+			}
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule_resource.go]: This logic will need to be updated as it returns errors in certain cases where an error is not expected, e.g.

Create a rule with this config:
```
resource "azurerm_network_security_perimeter_access_rule" "test" {
  name = "test"
  profile_id = azurerm_network_security_perimeter_profile.test.id

  direction = "Inbound"
  subscription_ids = [
     data.azurerm_subscription.test.id
  ]
}
```

Then change this rule from inbound -> outbound, and replace `subscription_ids` with `fqdns`:

```
resource "azurerm_network_security_perimeter_access_rule" "test" {
  name = "test"
  profile_id = azurerm_network_security_perimeter_profile.test.id

  direction = "Outbound"
  fqdns = ["google.com"]
}
```

The subsequent plan will then fail with `` "`subscription_ids` can only be set when `direction` is Inbound"` `` even though that field wasn't set, when the expected behaviour (based on the schema) should be a resource recreation

A simple length check should work here to resolve this issue.

File: internal/services/network/network_security_perimeter_access_rule.go [hunk 6]
```diff
@@ -0,0 +1,319 @@
...
+			subscriptionId := metadata.Client.Account.SubscriptionId
+
+			var config NetworkSecurityPerimeterAccessRuleResourceModel
+			if err := metadata.Decode(&config); err != nil {
+				return fmt.Errorf("decoding: %+v", err)
+			}
+
+			profileId, err := networksecurityperimeterprofiles.ParseProfileID(config.ProfileId)
+			if err != nil {
+				return fmt.Errorf("parsing profile ID: %+v", err)
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule.go]: when parsing resource IDs the returned error is sufficient by itself and doesn't need wrapping ([ref](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/reference-errors.md?plain=1#L49-L56))

```suggestion
				return err
```

File: internal/services/network/network_security_perimeter_access_rule.go [hunk 7]
```diff
@@ -0,0 +1,319 @@
...
+			}
+			nspId := networksecurityperimeters.NewNetworkSecurityPerimeterID(profileId.SubscriptionId, profileId.ResourceGroupName, profileId.NetworkSecurityPerimeterName)
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule.go]: the profile ID already contains all the relevant fields, so we can remove this and directly reference `profileId.{field}` below (ln152)
```suggestion
```

File: internal/services/network/network_security_perimeter_access_rule.go [hunk 8]
```diff
@@ -0,0 +1,319 @@
...
+
+			id := networksecurityperimeteraccessrules.NewAccessRuleID(subscriptionId, nspId.ResourceGroupName, nspId.NetworkSecurityPerimeterName, profileId.ProfileName, config.Name)
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule.go]:
```suggestion
			id := networksecurityperimeteraccessrules.NewAccessRuleID(subscriptionId, profileId.ResourceGroupName, profileId.NetworkSecurityPerimeterName, profileId.ProfileName, config.Name)
```

File: internal/services/network/network_security_perimeter_access_rule_resource.go [hunk 9]
```diff
@@ -0,0 +1,319 @@
...
+
+			direction := networksecurityperimeteraccessrules.AccessRuleDirection(config.Direction)
+
+			subscriptions := make([]networksecurityperimeteraccessrules.SubscriptionId, len(config.Subscriptions))
+			for i, s := range config.Subscriptions {
+				subscriptions[i] = networksecurityperimeteraccessrules.SubscriptionId{
+					Id: pointer.To(s),
+				}
+			}
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule_resource.go]: Could you put this logic into an `expand{Thing}` function? e.g. `expandAccessRuleSubscriptionIDs`. This can then be reused for both the `Create` and `Update` methods ([example](https://github.com/hashicorp/terraform-provider-azurerm/blob/6eb8629fe81cf699bc64e9c3d1b74ca2fce95990/internal/services/managedredis/managed_redis_geo_replication_resource.go#L326-L338))

File: internal/services/network/network_security_perimeter_access_rule.go [hunk 10]
```diff
@@ -0,0 +1,319 @@
...
+
+			subscriptions := make([]networksecurityperimeteraccessrules.SubscriptionId, len(config.Subscriptions))
+			for i, s := range config.Subscriptions {
+				subscriptions[i] = networksecurityperimeteraccessrules.SubscriptionId{
+					Id: pointer.To(s),
+				}
+			}
+			param := networksecurityperimeteraccessrules.NspAccessRule{
+				Properties: &networksecurityperimeteraccessrules.NspAccessRuleProperties{
+					Direction:                 &direction,
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule.go]: We could use `pointer.ToEnum` here and skip the `direction` var instantiation, since the `direction` variable isn't used elsewhere

```suggestion
					Direction:                 pointer.ToEnum[networksecurityperimeteraccessrules.AccessRuleDirection](config.Direction),
```

File: internal/services/network/network_security_perimeter_access_rule.go [hunk 11]
```diff
@@ -0,0 +1,319 @@
...
+
+			existing, err := client.Get(ctx, id)
+			if err != nil && !response.WasNotFound(existing.HttpResponse) {
+				return fmt.Errorf("checking for presence of existing %s: %+v", id, err)
+			}
+			if !response.WasNotFound(existing.HttpResponse) {
+				return metadata.ResourceRequiresImport(r.ResourceType(), id)
+			}
+
+			direction := networksecurityperimeteraccessrules.AccessRuleDirection(config.Direction)
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule.go]:
```suggestion
```

File: internal/services/network/network_security_perimeter_access_rule_resource.go [hunk 12]
```diff
@@ -0,0 +1,319 @@
...
+			param := networksecurityperimeteraccessrules.NspAccessRule{
+				Properties: &networksecurityperimeteraccessrules.NspAccessRuleProperties{
+					Direction:                 &direction,
+					AddressPrefixes:           pointer.To(config.AddressPrefixes),
+					FullyQualifiedDomainNames: pointer.To(config.FullyQualifiedDomainNames),
+					Subscriptions:             &subscriptions,
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule_resource.go]: Once an expand function is added, this can then directly call `expand{Thing}`

File: internal/services/network/network_security_perimeter_access_rule.go [hunk 13]
```diff
@@ -0,0 +1,319 @@
...
+				return fmt.Errorf("retrieving %s: `properties` was nil", id)
+			}
+
+			if metadata.ResourceData.HasChange("address_prefixes") {
+				existing.Model.Properties.AddressPrefixes = pointer.To(config.AddressPrefixes)
+			}
+			if metadata.ResourceData.HasChange("fqdns") {
+				existing.Model.Properties.FullyQualifiedDomainNames = pointer.To(config.FullyQualifiedDomainNames)
+			}
+			if metadata.ResourceData.HasChange("direction") {
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule.go]: `direction` is marked as ForceNew so it shouldn't be included in the Update func

File: internal/services/network/network_security_perimeter_access_rule_resource.go [hunk 14]
```diff
@@ -0,0 +1,319 @@
...
+			}
+			if metadata.ResourceData.HasChange("fqdns") {
+				existing.Model.Properties.FullyQualifiedDomainNames = pointer.To(config.FullyQualifiedDomainNames)
+			}
+			if metadata.ResourceData.HasChange("direction") {
+				direction := networksecurityperimeteraccessrules.AccessRuleDirection(config.Direction)
+				existing.Model.Properties.Direction = &direction
+			}
+			if metadata.ResourceData.HasChange("subscription_ids") {
+				subs := make([]networksecurityperimeteraccessrules.SubscriptionId, len(config.Subscriptions))
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule_resource.go]: Can be replaced with expand function as mentioned in my previous comment

File: internal/services/network/network_security_perimeter_access_rule.go [hunk 15]
```diff
@@ -0,0 +1,319 @@
...
+						Id: pointer.To(s),
+					}
+				}
+				existing.Model.Properties.Subscriptions = &subs
+			}
+
+			param := networksecurityperimeteraccessrules.NspAccessRule{
+				Properties: existing.Model.Properties,
+			}
+			if _, err := client.CreateOrUpdate(ctx, *id, param); err != nil {
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule.go]: minor nit: since we're working with pointers here, we don't need to instantiate a new `NspAccessRule` object and can directly pass the modified `existing.Model` object

```suggestion
			if _, err := client.CreateOrUpdate(ctx, *id, *existing.Model); err != nil {
```

File: internal/services/network/network_security_perimeter_access_rule_resource.go [hunk 16]
```diff
@@ -0,0 +1,319 @@
...
+			if err != nil {
+				if response.WasNotFound(resp.HttpResponse) {
+					return metadata.MarkAsGone(id)
+				}
+
+				return fmt.Errorf("retrieving %s: %+v", id, err)
+			}
+
+			var subscriptions []string
+			if resp.Model.Properties.Subscriptions != nil {
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule_resource.go]: While these _should_ never be nil, to be extra safe and avoid any chance of a panic we should nil check `Model` and `Properties` fields before accessing other nested fields. ([ref](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/guide-new-resource.md?plain=1#L347-L352))

It would generally look something like:

```go
state := NetworkSecurityPerimeterAccessRuleResourceModel{
    // Set items that we know the value of, e.g. any properties that we can set the value for based on the parsed resource ID
}

if model := resp.Model; model != nil {
    if props := model.Properties; props != nil {
        state.AddressPrefixes = pointer.From(props.AddressPrefixes)
        // Set remaining fields
    }
}
```

File: internal/services/network/network_security_perimeter_access_rule_resource.go [hunk 17]
```diff
@@ -0,0 +1,319 @@
...
+				subscriptions = make([]string, len(*resp.Model.Properties.Subscriptions))
+				for i, s := range *resp.Model.Properties.Subscriptions {
+					if s.Id != nil {
+						subscriptions[i] = *s.Id
+					}
+				}
+			}
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule_resource.go]: Similar to my comment regarding an `expand{Thing}` function for create/update, for `Read` we generally use `flatten{Thing}` functions, could you add one for this bit of code? ([example](https://github.com/hashicorp/terraform-provider-azurerm/blob/6eb8629fe81cf699bc64e9c3d1b74ca2fce95990/internal/services/managedredis/managed_redis_geo_replication_resource.go#L312-L324))

File: internal/services/network/network_security_perimeter_access_rule_test.go [hunk 18]
```diff
@@ -0,0 +1,289 @@
...
+%s
+
+resource "azurerm_network_security_perimeter_access_rule" "import" {
+	name = azurerm_network_security_perimeter_access_rule.test.name
+	profile_id =azurerm_network_security_perimeter_access_rule.test.profile_id
+
+	direction = "Inbound"
+	address_prefixes = [
+		"8.8.8.8/32"
+	]
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule_test.go]: Could you update these fields to reference the basic tests' resource's values? (since they're expected to be identical) 

This will prevent any future import test failures in case someone updates the `basic` test and not the `requiresImport` test

```suggestion
	direction = azurerm_network_security_perimeter_access_rule.test.direction
	address_prefixes = azurerm_network_security_perimeter_access_rule.test.address_prefixes
```

File: internal/services/network/network_security_perimeter_association.go [hunk 19]
```diff
@@ -0,0 +1,274 @@
...
+	ResourceId string `tfschema:"resource_id"`
+	AccessMode string `tfschema:"access_mode"`
+}
+
+func (NetworkSecurityPerimeterAssociationResource) Arguments() map[string]*pluginsdk.Schema {
+	return map[string]*pluginsdk.Schema{
+		"name": {
+			Type:         pluginsdk.TypeString,
+			Required:     true,
+			ValidateFunc: validation.StringIsNotEmpty,
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_association.go]: The API spec lists a regex that the name must match, could you implement validation for that here as well?

File: internal/services/network/network_security_perimeter_association.go [hunk 20]
```diff
@@ -0,0 +1,274 @@
...
+		},
+
+		"resource_id": {
+			Type:         pluginsdk.TypeString,
+			Required:     true,
+			ValidateFunc: azure.ValidateResourceID,
+			ForceNew:     true,
+		},
+
+		"profile_id": {
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_association.go]: Same as my comment on the previous resource, could you change this to `network_security_perimeter_profile_id`?

File: internal/services/network/network_security_perimeter_association.go [hunk 21]
```diff
@@ -0,0 +1,274 @@
...
+			if err := metadata.Decode(&config); err != nil {
+				return fmt.Errorf("decoding: %+v", err)
+			}
+
+			profileId, err := networksecurityperimeterprofiles.ParseProfileID(config.ProfileId)
+			if err != nil {
+				return err
+			}
+
+			nspId := networksecurityperimeters.NewNetworkSecurityPerimeterID(profileId.SubscriptionId, profileId.ResourceGroupName, profileId.NetworkSecurityPerimeterName)
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_association.go]: Like the previous resource, this can be removed and we can just use the `profileId` below

File: internal/services/network/network_security_perimeter_association.go [hunk 22]
```diff
@@ -0,0 +1,274 @@
...
+			}
+			if existing.Model.Properties == nil {
+				return fmt.Errorf("retrieving %s: `properties` was nil", id)
+			}
+
+			if metadata.ResourceData.HasChange("profile_id") {
+				existing.Model.Properties.Profile = &networksecurityperimeterassociations.SubResource{
+					Id: pointer.To(config.ProfileId),
+				}
+			}
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_association.go]: `profile_id` is marked as ForceNew so it shouldn't be included in the update func

File: internal/services/network/network_security_perimeter_association.go [hunk 23]
```diff
@@ -0,0 +1,274 @@
...
+			if metadata.ResourceData.HasChange("resource_id") {
+
+				existing.Model.Properties.PrivateLinkResource = &networksecurityperimeterassociations.SubResource{
+					Id: pointer.To(config.ResourceId),
+				}
+
+			}
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_association.go]: `resource_id` is also marked as ForceNew

File: internal/services/network/network_security_perimeter_association.go [hunk 24]
```diff
@@ -0,0 +1,274 @@
...
+			if metadata.ResourceData.HasChange("access_mode") {
+				existing.Model.Properties.AccessMode = pointer.To(networksecurityperimeterassociations.AssociationAccessMode(config.AccessMode))
+
+			}
+
+			param := networksecurityperimeterassociations.NspAssociation{
+				Properties: existing.Model.Properties,
+			}
+			if _, err := client.CreateOrUpdate(ctx, *id, param); err != nil {
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_association.go]: similar to my comment on the previous resource, we can skip this and pass `*existing.Model` directly to the `CreateOrUpdate` func

```suggestion
			if _, err := client.CreateOrUpdate(ctx, *id, *existing.Model); err != nil {
```

File: internal/services/network/network_security_perimeter_association_resource.go [hunk 25]
```diff
@@ -0,0 +1,274 @@
...
+
+				return fmt.Errorf("retrieving %s: %+v", id, err)
+			}
+
+			state := NetworkSecurityPerimeterAssociationResourceModel{
+				Name:       id.ResourceAssociationName,
+				ProfileId:  pointer.From(resp.Model.Properties.Profile.Id),
+				ResourceId: pointer.From(resp.Model.Properties.PrivateLinkResource.Id),
+				AccessMode: string(pointer.From(resp.Model.Properties.AccessMode)),
+			}
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_association_resource.go:212]: Please add nil checks before accessing any nested fields within a pointer.

File: internal/services/network/network_security_perimeter_association.go [hunk 26]
```diff
@@ -0,0 +1,274 @@
...
+
+		Func: func(ctx context.Context, metadata sdk.ResourceMetaData) error {
+			client := metadata.Client.Network.NetworkSecurityPerimeterAssociationsClient
+
+			id, err := networksecurityperimeterassociations.ParseResourceAssociationID(metadata.ResourceData.Id())
+			if err != nil {
+				return err
+			}
+
+			if _, err := client.Delete(ctx, *id); err != nil {
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_association.go]: The SDK has a `DeleteThenPoll` method available, indicating that this operation is asynchronous, could you use it here instead of the base `Delete` method?

File: internal/services/network/network_security_perimeter_association.go [hunk 27]
```diff
@@ -0,0 +1,274 @@
...
+			// 	},
+
+			// 	Timeout:    15 * time.Minute,
+			// 	MinTimeout: 15 * time.Second,
+			// }
+
+			// _, err = stateConf.WaitForStateContext(ctx)
+			// if err != nil {
+			// 	return fmt.Errorf("waiting for %s to be deleted: %+v", *id, err)
+			// }
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_association.go]: Please remove

File: internal/services/network/network_security_perimeter_association_test.go [hunk 28]
```diff
@@ -0,0 +1,187 @@
...
+	data.ResourceTest(t, r, []acceptance.TestStep{
+		{
+			Config: r.complete(data),
+			Check: acceptance.ComposeTestCheckFunc(
+				check.That(data.ResourceName).ExistsInAzure(r),
+			),
+		},
+		data.ImportStep(),
+	})
+}
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_association_test.go]: Since all properties in this resource are required, the complete test can be omitted

File: internal/services/network/network_security_perimeter_association_resource_test.go [hunk 29]
```diff
@@ -0,0 +1,187 @@
...
+			Config: r.complete(data),
+			Check: acceptance.ComposeTestCheckFunc(
+				check.That(data.ResourceName).ExistsInAzure(r),
+			),
+		},
+		data.ImportStep(),
+	})
+}
+
+func TestAccNetworkSecurityPerimeterAssociation_update(t *testing.T) {
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_association_resource_test.go:48]: The basic and complete configs look identical, could you update one of them to change the `access_mode` property (since that's the only non-forcenew field)

File: internal/services/network/network_security_perimeter_association_test.go [hunk 30]
```diff
@@ -0,0 +1,187 @@
...
+  location = "%s"
+}
+
+resource "azurerm_network_security_perimeter_profile" "test" {
+	name = "acctestProfile-%d"
+	perimeter_id = azurerm_network_security_perimeter.test.id
+}
+
+resource "azurerm_log_analytics_workspace" "test" {
+  name                = "example"
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_association_test.go]: please prefix test resource names with `acctest`

```suggestion
  name                = "acctestLAW"
```

File: internal/services/network/network_security_perimeter_association_test.go [hunk 31]
```diff
@@ -0,0 +1,187 @@
...
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_association_test.go]:
```suggestion
  name                = "acctestLAW"
```

File: internal/services/network/network_security_perimeter_data_source.go [hunk 32]
```diff
@@ -0,0 +1,94 @@
...
+	Location          string            `tfschema:"location"`
+	Tags              map[string]string `tfschema:"tags"`
+}
+
+func (NetworkSecurityPerimeterDataSource) Arguments() map[string]*pluginsdk.Schema {
+	return map[string]*pluginsdk.Schema{
+		"name": {
+			Type:         pluginsdk.TypeString,
+			Required:     true,
+			ValidateFunc: validation.StringIsNotEmpty,
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_data_source.go]: Please update validation to match API spec's documented regex

File: internal/services/network/network_security_perimeter_data_source.go [hunk 33]
```diff
@@ -0,0 +1,94 @@
...
+					return fmt.Errorf("%s was not found", id)
+				}
+
+				return fmt.Errorf("retrieving %s: %+v", id, err)
+			}
+
+			metadata.SetID(id)
+
+			if model := resp.Model; model != nil {
+				state.Location = location.NormalizeNilable(pointer.To(model.Location))
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_data_source.go]: Since `model.Location` isn't a pointer, we can just use `location.Normalize` rather than passing the address of it to `NormalizeNilable`

```suggestion
				state.Location = location.Normalize(model.Location)
```

File: internal/services/network/network_security_perimeter_data_source.go [hunk 34]
```diff
@@ -0,0 +1,94 @@
...
+				state.Tags = pointer.ToMapOfStringStrings(model.Tags)
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_data_source.go]: Please use the generic `pointer.From`

```suggestion
				state.Tags = pointer.From(model.Tags)
```

File: internal/services/network/network_security_perimeter_profile_data_source.go [hunk 35]
```diff
@@ -0,0 +1,91 @@
+// Copyright (c) HashiCorp, Inc.
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_profile_data_source.go]: I'm not sure I see the value of this data source, there are no additional exported attributes. Could you clarify why you've included it?

File: internal/services/network/network_security_perimeter_profile_resource.go [hunk 36]
```diff
@@ -0,0 +1,155 @@
...
+	Name        string `tfschema:"name"`
+	PerimeterId string `tfschema:"perimeter_id"`
+}
+
+func (NetworkSecurityPerimeterProfileResource) Arguments() map[string]*pluginsdk.Schema {
+	return map[string]*pluginsdk.Schema{
+		"name": {
+			Type:         pluginsdk.TypeString,
+			Required:     true,
+			ValidateFunc: validation.StringIsNotEmpty,
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_profile_resource.go]: Please update the validation to match the regex documented in the API spec

File: internal/services/network/network_security_perimeter_profile_resource.go [hunk 37]
```diff
@@ -0,0 +1,155 @@
...
+			ForceNew:     true,
+		},
+
+		"perimeter_id": {
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_profile_resource.go]:
```suggestion
		"network_security_perimeter_id": {
```

File: internal/services/network/network_security_perimeter_profile_resource.go [hunk 38]
```diff
@@ -0,0 +1,155 @@
...
+			if err != nil && !response.WasNotFound(existing.HttpResponse) {
+				return fmt.Errorf("checking for presence of existing %s: %+v", id, err)
+			}
+			if !response.WasNotFound(existing.HttpResponse) {
+				return metadata.ResourceRequiresImport(r.ResourceType(), id)
+			}
+
+			param := networksecurityperimeterprofiles.NspProfile{}
+
+			if _, err := client.CreateOrUpdate(ctx, id, param); err != nil {
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_profile_resource.go]: minor nit: since we're not adding any other fields in the NspProfile object, we can pass it directly

```suggestion
			if _, err := client.CreateOrUpdate(ctx, id, networksecurityperimeterprofiles.NspProfile{}); err != nil {
```

File: internal/services/network/network_security_perimeter_profile_resource_test.go [hunk 39]
```diff
@@ -0,0 +1,156 @@
...
+	data.ResourceTest(t, r, []acceptance.TestStep{
+		{
+			Config: r.complete(data),
+			Check: acceptance.ComposeTestCheckFunc(
+				check.That(data.ResourceName).ExistsInAzure(r),
+			),
+		},
+		data.ImportStep(),
+	})
+}
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_profile_resource_test.go]: complete test can be omitted since there are only required properties in this resource

File: internal/services/network/network_security_perimeter_profile_resource_test.go [hunk 40]
```diff
@@ -0,0 +1,156 @@
...
+		data.ImportStep(),
+		{
+			Config: r.complete(data),
+			Check: acceptance.ComposeTestCheckFunc(
+				check.That(data.ResourceName).ExistsInAzure(r),
+			),
+		},
+		data.ImportStep(),
+	})
+}
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_profile_resource_test.go]: update test can be deleted, there is nothing to update as both properties in this resource are ForceNew

File: internal/services/network/network_security_perimeter_resource.go [hunk 41]
```diff
@@ -0,0 +1,193 @@
...
+	Location          string            `tfschema:"location"`
+	Tags              map[string]string `tfschema:"tags"`
+}
+
+func (NetworkSecurityPerimeterResource) Arguments() map[string]*pluginsdk.Schema {
+	return map[string]*pluginsdk.Schema{
+		"name": {
+			Type:         pluginsdk.TypeString,
+			Required:     true,
+			ValidateFunc: validation.StringIsNotEmpty,
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_resource.go]: Please add validation matching the regex in API spec

File: internal/services/network/network_security_perimeter_resource.go [hunk 42]
```diff
@@ -0,0 +1,193 @@
...
+			ForceNew:     true,
+		},
+
+		"resource_group_name": commonschema.ResourceGroupNameForDataSource(),
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_resource.go]: Generally `resource_group_name` fields on resources are ForceNew

```suggestion
		"resource_group_name": commonschema.ResourceGroupName(),
```

File: internal/services/network/network_security_perimeter_resource.go [hunk 43]
```diff
@@ -0,0 +1,193 @@
...
+
+		"location": {
+			Type:         pluginsdk.TypeString,
+			Required:     true,
+			ValidateFunc: validation.StringIsNotEmpty,
+			ForceNew:     true,
+		},
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_resource.go]: we have a helper for `location` properties

```suggestion
		"location": commonschema.Location(),
```

File: internal/services/network/network_security_perimeter_access_rule_resource_test.go [hunk 44]
```diff
@@ -0,0 +1,289 @@
+package network_test
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule_resource_test.go:1]: Could you rename this file to `network_security_perimeter_access_rule_resource_test.go`

File: internal/services/network/network_security_perimeter_association.go [hunk 45]
```diff
@@ -0,0 +1,274 @@
+// Copyright (c) HashiCorp, Inc.
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_association.go]: Could you rename this file to `network_security_perimeter_association_resource.go`

File: internal/services/network/network_security_perimeter_association_resource_test.go [hunk 46]
```diff
@@ -0,0 +1,187 @@
+package network_test
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_association_resource_test.go:1]: Could you rename this file to `network_security_perimeter_association_resource_test.go`

**Review by sreallymatt — CHANGES_REQUESTED** [review]
Thanks for getting this started @zachrousseau, I've reviewed the new resources and data sources, and left some comments inline.

I've not yet reviewed the documentation, as it will likely have to be updated as a result of this review.

Please @ me if you have any questions!

File: internal/services/network/network_security_perimeter_association.go (hunk 27 above)
Comment (zachrousseau) [reply internal/services/network/network_security_perimeter_association.go]: Removed the comments. The reason why the sleep is in there is to resolve this issue:

```
=== NAME TestAccNetworkSecurityPerimeterAssociation_basic testcase.go:173: Error running post-test destroy, there may be dangling resources: exit status 1 Error: waiting for Resource Association (Subscription: "XXXXXXXXXXXXXX" Resource Group Name: "acctestRG-250917135824223676" Network Security Perimeter Name: "acctestNsp-250917135824223676" Resource Association Name: "acctestassoc-250917135824223676") to be deleted: couldn't find resource (21 retries) waiting for Resource Association (Subscription: "XXXXXXXXXXXXXXX" Resource Group Name: "acctestRG-250917135824223676" Network Security Perimeter Name: "acctestNsp-250917135824223676" Resource Association Name: "acctestassoc-250917135824223676") to be deleted: couldn't find resource (21 retries)
```

File: internal/services/network/network_security_perimeter_profile_data_source.go (hunk 35 above)
Comment (zachrousseau) [reply internal/services/network/network_security_perimeter_profile_data_source.go]: I've commonly see data sources used in practice as a way to ensure consistency in Terraform. 

An example would be if you're creating NSP access rules and need to reference the NSP profile id you could use the data source to reference that id. At the same time the data source validate that the NSP profile exists, which you lose if you're just using a local/var/something else to ensure the same value of the NSP id across the access rules.

File: internal/services/network/network_security_perimeter_association.go (hunk 27 above)
Comment (zachrousseau) [reply internal/services/network/network_security_perimeter_association.go]: Ah I see the comment above. DeleteThenPoll method. Will remove the sleep.

File: internal/services/network/network_security_perimeter_access_rule.go (hunk 2 above)
Comment (zachrousseau) [reply internal/services/network/network_security_perimeter_access_rule.go]: Added for all resources.

**Comment by zachrousseau** [comment]
@sreallymatt, I've resolved all comments. I have also added support for a `service_tags` attribute for the NSP access rules which was Microsoft did not support when I first wrote this code. 

Can I get another review?

File: internal/services/network/network_security_perimeter_access_rule_resource.go [hunk 47]
```diff
@@ -0,0 +1,358 @@
...
+
+			var subscriptions []string
+			if model := resp.Model; model != nil {
+				if props := model.Properties; props != nil {
+					if props.Subscriptions != nil {
+						subscriptions = flattenAccessRuleSubscriptionIDs(*props.Subscriptions)
+					}
+				}
+			}
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule_resource.go]: So we don't have to repeat these nil checks on `Model` and `Properties`, could you remove this snippet and move the call to `flattenAccessRuleSubscriptionIDs` to ln297?

The function signature of `flattenAccessRuleSubscriptionIDs` can be modified to accept a pointer, and a nil check can be added on ln346 (I'll leave a suggestion inline there as well)

```suggestion
```

File: internal/services/network/network_security_perimeter_access_rule_resource.go [hunk 48]
```diff
@@ -0,0 +1,358 @@
...
+				ProfileId: profileId.ID(),
+			}
+
+			if model := resp.Model; model != nil {
+				if props := model.Properties; props != nil {
+					state.AddressPrefixes = pointer.From(props.AddressPrefixes)
+					state.Direction = string(pointer.From(props.Direction))
+					state.FullyQualifiedDomainNames = pointer.From(props.FullyQualifiedDomainNames)
+					state.ServiceTags = pointer.From(props.ServiceTags)
+					state.Subscriptions = subscriptions
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule_resource.go]:
```suggestion
					state.Subscriptions = flattenAccessRuleSubscriptionIDs(props.Subscriptions)
```

File: internal/services/network/network_security_perimeter_access_rule_resource.go [hunk 49]
```diff
@@ -0,0 +1,358 @@
...
+	return &result
+}
+
+func flattenAccessRuleSubscriptionIDs(subscriptions []networksecurityperimeteraccessrules.SubscriptionId) []string {
+	if len(subscriptions) == 0 {
+		return nil
+	}
+
+	result := make([]string, 0, len(subscriptions))
+	for _, s := range subscriptions {
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_access_rule_resource.go]:
```suggestion
func flattenAccessRuleSubscriptionIDs(subscriptions *[]networksecurityperimeteraccessrules.SubscriptionId) []string {
	if subscriptions == nil || len(*subscriptions) == 0 {
		return nil
	}

	result := make([]string, 0, len(*subscriptions))
	for _, s := range *subscriptions {
```

File: internal/services/network/network_security_perimeter_association_resource.go [hunk 50]
```diff
@@ -0,0 +1,247 @@
...
+			id, err := networksecurityperimeterassociations.ParseResourceAssociationID(metadata.ResourceData.Id())
+			if err != nil {
+				return err
+			}
+
+			if err := client.DeleteThenPoll(ctx, *id); err != nil {
+				return fmt.Errorf("deleting %s: %+v", *id, err)
+			}
+
+			time.Sleep(5 * time.Second)
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_association_resource.go]: This should no longer be required with the `DeleteThenPoll` above, we generally avoid arbitrary `time.Sleep` calls in the provider

```suggestion
```

File: internal/services/network/network_security_perimeter_profile_resource_test.go [hunk 51]
```diff
@@ -0,0 +1,119 @@
...
+%s
+
+resource "azurerm_network_security_perimeter_profile" "import" {
+  name                          = azurerm_network_security_perimeter_profile.test.name
+  network_security_perimeter_id = azurerm_network_security_perimeter_profile.test.network_security_perimeter_id
+}
+`, r.basic(data))
+}
+
+func (NetworkSecurityPerimeterProfileTestResource) complete(data acceptance.TestData) string {
```
Comment (sreallymatt) [inline internal/services/network/network_security_perimeter_profile_resource_test.go]: this function is unused so it should be removed (required to resolve linter error)

File: website/docs/r/network_security_perimeter.html.markdown [hunk 52]
```diff
@@ -0,0 +1,63 @@
...
+
+## Arguments Reference
+
+The following arguments are supported:
+
+* `location` - (Required) The Azure Region where the Network Security Perimeter should exist. Changing this forces a new Network Security Perimeter to be created.
+
+* `name` - (Required) The name which should be used for this Network Security Perimeter. Changing this forces a new Network Security Perimeter to be created.
+
+* `resource_group_name` - (Required) The name of the Resource Group where the Network Security Perimeter should exist.
```
Comment (sreallymatt) [inline website/docs/r/network_security_perimeter.html.markdown]: Could you reorder these following our [contributing guides](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/reference-documentation-standards.md#ordering) for consistency

File: website/docs/r/network_security_perimeter_access_rule.html.markdown [hunk 53]
```diff
@@ -0,0 +1,85 @@
...
+
+## Arguments Reference
+
+The following arguments are supported:
+
+* `direction` - (Required) The direction of the rule. Possible values are `Inbound` and `Outbound`. Changing this forces a new Network Security Perimeter Access Rule to be created.
+
+* `name` - (Required) The name which should be used for this Network Security Perimeter Access Rule. Changing this forces a new Network Security Perimeter Access Rule to be created.
+
+* `network_security_perimeter_profile_id` - (Required) The ID of the Network Security Perimeter Profile within which this Access Rule is created. Changing this forces a new Network Security Perimeter Access Rule to be created.
```
Comment (sreallymatt) [inline website/docs/r/network_security_perimeter_access_rule.html.markdown]: Could you reorder these following our [contributing guides](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/reference-documentation-standards.md#ordering) for consistency

File: website/docs/r/network_security_perimeter_access_rule.html.markdown [hunk 54]
```diff
@@ -0,0 +1,85 @@
...
+
+---
+
+* `address_prefixes` - (Optional) Specifies a list of CIDRs. Can only be specified when direction is set to `Inbound`. Conflicts with `fqdns`, `service_tags`, `subscription_ids`. 
+
+* `fqdns` - (Optional) Specifies a list of fully qualified domain names. Can only be specified when direction is set to `Outbound`. Conflicts with `fqdns`, `service_tags`, and `subscription_ids`.
```
Comment (sreallymatt) [inline website/docs/r/network_security_perimeter_access_rule.html.markdown]:
```suggestion
* `fqdns` - (Optional) Specifies a list of fully qualified domain names. Can only be specified when direction is set to `Outbound`. Conflicts with `address_prefixes`, `service_tags`, and `subscription_ids`.
```

File: website/docs/r/network_security_perimeter_access_rule.html.markdown [hunk 55]
```diff
@@ -0,0 +1,85 @@
...
+
+* `service_tags` - (Optional) Specifies a list of service tags. Can only be specified when direction is set to `Inbound`. Conflicts with `fqdns`, `service_tags`, and `subscription_ids`.
```
Comment (sreallymatt) [inline website/docs/r/network_security_perimeter_access_rule.html.markdown]:
```suggestion
* `service_tags` - (Optional) Specifies a list of service tags. Can only be specified when direction is set to `Inbound`. Conflicts with `address_prefixes`, `fqdns`, and `subscription_ids`.
```

File: website/docs/r/network_security_perimeter_access_rule.html.markdown [hunk 56]
```diff
@@ -0,0 +1,85 @@
...
+
+* `subscription_ids` - (Optional) Specifies a list of subscription IDs this rule applies to. Can only be specified when direction is set to `Inbound`. Conflicts with `fqdns`, `service_tags`, and `subscription_ids`.
```
Comment (sreallymatt) [inline website/docs/r/network_security_perimeter_access_rule.html.markdown]:
```suggestion
* `subscription_ids` - (Optional) Specifies a list of subscription IDs this rule applies to. Can only be specified when direction is set to `Inbound`. Conflicts with `address_prefixes`, `fqdns`, and `service_tags`.
```

File: website/docs/r/network_security_perimeter_association.html.markdown [hunk 57]
```diff
@@ -0,0 +1,83 @@
...
+
+The following arguments are supported:
+
+* `name` - (Required) The name which should be used for this Network Security Perimeter Association. Changing this forces a new Network Security Perimeter Association to be created.
+
+* `access_mode` - (Required) Access mode for the associated resource on the Network Security Perimeter. Possible values are `Audit`, `Enforced`, and `Learning`.
+
+* `network_security_perimeter_profile_id` - (Required) The ID of the Network Security Perimeter Profile. Changing this forces a new Network Security Perimeter Association to be created.
+
+* `resource_id` - (Required) The ID of the associated resource. Changing this forces a new Network Security Perimeter Association to be created.
```
Comment (sreallymatt) [inline website/docs/r/network_security_perimeter_association.html.markdown:57]: Could you reorder these following our [contributing guides](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/reference-documentation-standards.md#ordering) for consistency

File: internal/services/network/network_security_perimeter_association_resource.go (hunk 50 above)
Comment (zachrousseau) [reply internal/services/network/network_security_perimeter_association_resource.go]: Thought I deleted this one. Apologies.

**Comment by zachrousseau** [comment]
Thanks for the additional review @sreallymatt. All requested changes should be made.

**Comment by sreallymatt** [comment]
image
