### PR TITLE
Added domain_name_label to read to fix import. (#784)

### LINKED ISSUE #784: domain_name_label not imported for azurerm_public_ip
### Terraform Version
```
Terraform v0.11.2
+ provider.azurerm v1.1.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
`- azurerm_public_ip`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Description
When importing public ip `terraform import azurerm_public_ip.name {ID}` the `domain_name_label` is ignored and not imported into state

### PR DESCRIPTION
**Pull request by shanepoint**
Fixes #784

### CODE REVIEW

File: azurerm/resource_arm_public_ip.go [hunk 1]
```diff
@@ -46,6 +46,7 @@ func resourceArmPublicIp() *schema.Resource {
 
 			"zones": singleZonesSchema(),
 
+			//should this perhaps be allocation_method?
```
Comment (katbyte) [inline azurerm/resource_arm_public_ip.go]: Probably.

File: azurerm/resource_arm_public_ip_test.go [hunk 2]
```diff
@@ -64,6 +64,29 @@ func TestAccAzureRMPublicIpStatic_basic(t *testing.T) {
...
+		Providers:    testAccProviders,
+		CheckDestroy: testCheckAzureRMPublicIpDestroy,
+		Steps: []resource.TestStep{
+			{
+				Config: config,
+				Check: resource.ComposeTestCheckFunc(
+					testCheckAzureRMPublicIpExists(resourceName),
+					resource.TestCheckResourceAttrSet(resourceName, "ip_address"),
+					resource.TestCheckResourceAttr(resourceName, "public_ip_address_allocation", "static"),
+					resource.TestCheckResourceAttr(resourceName, "domain_name_label", "dnstestlabel"),
```
Comment (katbyte) [inline azurerm/resource_arm_public_ip_test.go]: Could we please make this random to prevent conflicts?

**Comment by katbyte** [comment]
Tests pass:
screen shot 2018-05-24 at 20 28 08
