### PR TITLE
azurerm_automation_schedule - fix time in future validation

### LINKED ISSUE #5726: azurerm_automation_schedule is not usable for subsequent terraform runs without updating its start_time to a future time
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.20
+ provider.azurerm v1.44.0
### Affected Resource(s)

* `azurerm_automation_schedule`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "tfex-automation-account"
  location = "West Europe"
}

resource "azurerm_automation_account" "example" {
  name                = "tfex-automation-account"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku_name            = "Basic"
}

resource "azurerm_automation_schedule" "example" {
  name                    = "tfex-automation-schedule"
  resource_group_name     = azurerm_resource_group.example.name
  automation_account_name = azurerm_automation_account.example.name
  frequency               = "Week"
  interval                = 1
  timezone                = "Central Europe Standard Time"
  start_time              = "2020-02-13T11:15:00+02:00"
  description             = "This is an example schedule"
  week_days               = ["Friday"]
}

```

### Expected Behavior
Plan or apply should complete successfully subsequently after initial resource provisioning as _start_time_ is a fixed value and it wasn't changed.

```hcl

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```
### Actual Behavior
```hcl
Error: "start_time" is "2020-02-13T11:15:00+02:00" and should be at least "5m0s" in the future

  on main.tf line 13, in resource "azurerm_automation_schedule" "example":
  13: resource "azurerm_automation_schedule" "example" {
```

### Steps to Reproduce

1. `terraform init`
2. Change _start_time_ to +7-8 minutes from your current time
3. `terraform apply`
4. Wait for 3+ minutes to get into 5min barrier between specified _start_time_ and your current time or wait for current time to get past _start_time_
5. `terraform plan`

### References

* #0000

### PR DESCRIPTION
**Pull request by njuCZ**
fix #5726 

terraform will always invoke validation function, we could not make terraform execute validation function only when field changes.

I think the best way for now to solve this problem is to remove the validation.

### CODE REVIEW

File: azurerm/internal/services/automation/resource_arm_automation_schedule.go [hunk 1]
```diff
@@ -82,7 +82,7 @@ func resourceArmAutomationSchedule() *schema.Resource {
 				Optional:         true,
 				Computed:         true,
 				DiffSuppressFunc: suppress.RFC3339Time,
-				ValidateFunc:     validate.RFC3339DateInFutureBy(time.Duration(5) * time.Minute),
+				ValidateFunc:     validate.RFC3339Time,
```
Comment (katbyte) [inline azurerm/internal/services/automation/resource_arm_automation_schedule.go]: Since we are removing this constraint, could we add the constraint/check into the create/update function?

Comment (njuCZ) [reply azurerm/internal/services/automation/resource_arm_automation_schedule.go]: Thanks for the suggestion. I have added the check into create/update function.

**Comment by njuCZ** [comment]
@katbyte  Thanks for the suggestion. I have added the check into create/update function
