### PR TITLE
`azurerm_app_service` && `azurerm_function_app` - don't try to manage source_control when scm_type is `VSTSRM`

### LINKED ISSUE #8171: azurerm_app_service transient error - "RepoUrl VSTSRM is not supported"
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ /c/tools/Terraform/terraform0_12_29.exe -v
Terraform v0.12.29
+ provider.azuread v0.11.0
+ provider.azurerm v2.23.0
+ provider.local v1.4.0
+ provider.random v2.3.0
```

### Affected Resource(s)

* `azurerm_function_app`, `azurerm_app_service`

### Terraform Configuration Files

```hcl

resource "azurerm_function_app" "mgmtportal_fa" {
  name                      = "${local.resourceNamePrefix}${local.nameschemeAffixes.azureFunction}${var.functionAppName}"
  location                  = "${azurerm_resource_group.rg.location}"
  resource_group_name       = "${azurerm_resource_group.rg.name}"
  app_service_plan_id       = "${azurerm_app_service_plan.mgmtportal_asp.id}"
  storage_connection_string = "${azurerm_storage_account.mgmtportal_sa.primary_connection_string}"
  version                   = "~3"
  app_settings = {
     // ...
  }
  site_config {
    always_on = true
  }
  
  identity {
    type = "SystemAssigned"
  }
}

```

### Debug Output

<details>
 <summary>Error Message</summary>
  
  ```
  Error: failed to create App Service Source Control for "aitifdevaffunctions" (Resource Group "aitdevelopment"): web.AppsClient#CreateOrUpdateSourceControl: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Operation not supported: RepoUrl VSTSRM is not supported." Details=[{"Message":"Operation not supported: RepoUrl VSTSRM is not supported."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"51024","Message":"Operation not supported: RepoUrl VSTSRM is not supported.","MessageTemplate":"Operation not supported: {0}","Parameters":["RepoUrl VSTSRM is not supported."]}}]

  on main.tf line 369, in resource "azurerm_function_app" "mgmtportal_fa":
 369: resource "azurerm_function_app" "mgmtportal_fa" {

  ```

</details>

<details>
  <summary>Failing Request</summary>
 
  ```
  2020-08-19T10:03:49.1545190Z 2020-08-19T12:03:49.151+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: PUT /subscriptions/99e0a02c-f0ab-41ad-8de7-d621ce36a09e/resourceGroups/aitdevelopment/providers/Microsoft.Web/sites/aitifdevaffunctions/sourcecontrols/web?api-version=2019-08-01 HTTP/1.1
  2020-08-19T10:03:49.1545852Z 2020-08-19T12:03:49.151+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Host: management.azure.com
  2020-08-19T10:03:49.1546672Z 2020-08-19T12:03:49.151+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: User-Agent: Go/go1.14.5 (amd64-windows) go-autorest/v14.0.0 Azure-SDK-For-Go/v44.2.0 web/2019-08-01 HashiCorp Terraform/0.12.29 (+https://www.terraform.io) Terraform Plugin SDK/1.13.1 terraform-provider-azurerm/2.23.0 VSTS_3a20467b-7171-4b7e-a40b-19e133f2093a_build_354_0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
  2020-08-19T10:03:49.1547477Z 2020-08-19T12:03:49.151+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Content-Length: 135
  2020-08-19T10:03:49.1547949Z 2020-08-19T12:03:49.151+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Content-Type: application/json; charset=utf-8
  2020-08-19T10:03:49.1548480Z 2020-08-19T12:03:49.151+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Ms-Correlation-Request-Id: c1d1a14c-1989-abf4-4e88-a526f0abfa49
  2020-08-19T10:03:49.1548981Z 2020-08-19T12:03:49.151+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Accept-Encoding: gzip
  2020-08-19T10:03:49.1549387Z 2020-08-19T12:03:49.151+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: 
  2020-08-19T10:03:49.1549989Z 2020-08-19T12:03:49.151+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: {"properties":{"repoUrl":"VSTSRM","branch":"master","isManualIntegration":false,"deploymentRollbackEnabled":false,"isMercurial":false}}
  2020-08-19T10:03:49.3271152Z 2020/08/19 12:03:49 [TRACE] dag/walk: vertex "local_file.mgmt_sql_init_sql" is waiting for "azurerm_function_app.mgmtportal_fa"
  2020-08-19T10:03:49.6218201Z 2020-08-19T12:03:49.621+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/99e0a02c-f0ab-41ad-8de7-d621ce36a09e/resourceGroups/aitdevelopment/providers/Microsoft.Web/sites/aitifdevaffunctions/sourcecontrols/web?api-version=2019-08-01: 
  2020-08-19T10:03:49.6219247Z 2020-08-19T12:03:49.621+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: HTTP/2.0 400 Bad Request
  2020-08-19T10:03:49.6219696Z 2020-08-19T12:03:49.621+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Content-Length: 459
  2020-08-19T10:03:49.6220135Z 2020-08-19T12:03:49.621+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Cache-Control: no-cache
  2020-08-19T10:03:49.6220609Z 2020-08-19T12:03:49.621+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Content-Type: application/json; charset=utf-8
  2020-08-19T10:03:49.6221096Z 2020-08-19T12:03:49.621+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Date: Wed, 19 Aug 2020 10:03:49 GMT
  2020-08-19T10:03:49.6221550Z 2020-08-19T12:03:49.621+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Expires: -1
  2020-08-19T10:03:49.6221961Z 2020-08-19T12:03:49.621+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Pragma: no-cache
  2020-08-19T10:03:49.6222398Z 2020-08-19T12:03:49.621+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Server: Microsoft-IIS/10.0
  2020-08-19T10:03:49.6222891Z 2020-08-19T12:03:49.621+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Strict-Transport-Security: max-age=31536000; includeSubDomains
  2020-08-19T10:03:49.6223396Z 2020-08-19T12:03:49.621+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Aspnet-Version: 4.0.30319
  2020-08-19T10:03:49.6224054Z 2020-08-19T12:03:49.621+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Content-Type-Options: nosniff
  2020-08-19T10:03:49.6224588Z 2020-08-19T12:03:49.621+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Ms-Correlation-Request-Id: c1d1a14c-1989-abf4-4e88-a526f0abfa49
  2020-08-19T10:03:49.6225716Z 2020-08-19T12:03:49.621+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Ms-Ratelimit-Remaining-Subscription-Writes: 1195
  2020-08-19T10:03:49.6226250Z 2020-08-19T12:03:49.621+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Ms-Request-Id: e2b2adc5-b93e-4fd8-b715-0aec297c41cd
  2020-08-19T10:03:49.6226845Z 2020-08-19T12:03:49.621+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Ms-Routing-Request-Id: GERMANYWESTCENTRAL:20200819T100349Z:e2b2adc5-b93e-4fd8-b715-0aec297c41cd
  2020-08-19T10:03:49.6227761Z 2020-08-19T12:03:49.621+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Powered-By: ASP.NET
  2020-08-19T10:03:49.6228480Z 2020-08-19T12:03:49.621+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: 
  2020-08-19T10:03:49.6229625Z 2020-08-19T12:03:49.621+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: {"Code":"BadRequest","Message":"Operation not supported: RepoUrl VSTSRM is not supported.","Target":null,"Details":[{"Message":"Operation not supported: RepoUrl VSTSRM is not supported."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"51024","MessageTemplate":"Operation not supported: {0}","Parameters":["RepoUrl VSTSRM is not supported."],"Code":"BadRequest","Message":"Operation not supported: RepoUrl VSTSRM is not supported."}}],"Innererror":null}
  ```
  
</details>

<details>
  <summary>Likely problematic response (before the error happens)</summary>
  
  ```
  2020-08-19T10:02:11.7321231Z 2020-08-19T12:02:11.729+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: [DEBUG] AzureRM Request: 
  2020-08-19T10:02:11.7322258Z 2020-08-19T12:02:11.729+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: GET /subscriptions/99e0a02c-f0ab-41ad-8de7-d621ce36a09e/resourceGroups/aitdevelopment/providers/Microsoft.Web/sites/aitifdevaffunctions/config/web?api-version=2019-08-01 HTTP/1.1
  2020-08-19T10:02:11.7323280Z 2020-08-19T12:02:11.729+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Host: management.azure.com
  2020-08-19T10:02:11.7324605Z 2020-08-19T12:02:11.729+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: User-Agent: Go/go1.14.5 (amd64-windows) go-autorest/v14.0.0 Azure-SDK-For-Go/v44.2.0 web/2019-08-01 HashiCorp Terraform/0.12.29 (+https://www.terraform.io) Terraform Plugin SDK/1.13.1 terraform-provider-azurerm/2.23.0 VSTS_3a20467b-7171-4b7e-a40b-19e133f2093a_build_354_0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
  2020-08-19T10:02:11.7325998Z 2020-08-19T12:02:11.729+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Ms-Correlation-Request-Id: 51f9c150-2d49-80c3-8936-9a9e9470cf5b
  2020-08-19T10:02:11.7326770Z 2020-08-19T12:02:11.729+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Accept-Encoding: gzip
  2020-08-19T10:02:11.7327382Z 2020-08-19T12:02:11.729+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: 
  2020-08-19T10:02:11.7327947Z 2020-08-19T12:02:11.729+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: 
  2020-08-19T10:02:11.8261663Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/99e0a02c-f0ab-41ad-8de7-d621ce36a09e/resourceGroups/aitdevelopment/providers/Microsoft.Web/sites/aitifdevaffunctions/config/web?api-version=2019-08-01: 
  2020-08-19T10:02:11.8263146Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: HTTP/2.0 200 OK
  2020-08-19T10:02:11.8263968Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Cache-Control: no-cache
  2020-08-19T10:02:11.8264764Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Content-Type: application/json
  2020-08-19T10:02:11.8266111Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Date: Wed, 19 Aug 2020 10:02:08 GMT
  2020-08-19T10:02:11.8266953Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Expires: -1
  2020-08-19T10:02:11.8267411Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Pragma: no-cache
  2020-08-19T10:02:11.8267845Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Server: Microsoft-IIS/10.0
  2020-08-19T10:02:11.8268346Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Strict-Transport-Security: max-age=31536000; includeSubDomains
  2020-08-19T10:02:11.8268843Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Vary: Accept-Encoding
  2020-08-19T10:02:11.8269291Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Aspnet-Version: 4.0.30319
  2020-08-19T10:02:11.8269757Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Content-Type-Options: nosniff
  2020-08-19T10:02:11.8270269Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Ms-Correlation-Request-Id: 51f9c150-2d49-80c3-8936-9a9e9470cf5b
  2020-08-19T10:02:11.8271571Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Ms-Ratelimit-Remaining-Subscription-Reads: 11990
  2020-08-19T10:02:11.8272384Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Ms-Request-Id: 6f279179-6bcb-4308-8fb6-a2007b1fc03a
  2020-08-19T10:02:11.8273954Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Ms-Routing-Request-Id: GERMANYWESTCENTRAL:20200819T100209Z:02ad04d3-0df4-400e-a381-6fca02eefb8c
  2020-08-19T10:02:11.8275023Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Powered-By: ASP.NET
  2020-08-19T10:02:11.8275456Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: 
  2020-08-19T10:02:11.8282150Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: {"id":"/subscriptions/99e0a02c-f0ab-41ad-8de7-d621ce36a09e/resourceGroups/aitdevelopment/providers/Microsoft.Web/sites/aitifdevaffunctions/config/web","name":"aitifdevaffunctions","type":"Microsoft.Web/sites/config","location":"West Europe","tags":{},"properties":{"numberOfWorkers":1,"defaultDocuments":["Default.htm","Default.html","Default.asp","index.htm","index.html","iisstart.htm","default.aspx","index.php"],"netFrameworkVersion":"v4.0","phpVersion":"5.6","pythonVersion":"","nodeVersion":"","powerShellVersion":"","linuxFxVersion":"","windowsFxVersion":null,"requestTracingEnabled":false,"remoteDebuggingEnabled":false,"remoteDebuggingVersion":"VS2019","httpLoggingEnabled":false,"azureMonitorLogCategories":null,"acrUseManagedIdentityCreds":false,"acrUserManagedIdentityID":null,"logsDirectorySizeLimit":35,"detailedErrorLoggingEnabled":false,"publishingUsername":"$aitifdevaffunctions","publishingPassword":null,"appSettings":null,"azureStorageAccounts":{},"metadata":null,"connectionStrings":null,"machineKey":null,"handlerMappings":null,"documentRoot":null,"scmType":"VSTSRM","use32BitWorkerProcess":true,"webSocketsEnabled":false,"alwaysOn":true,"javaVersion":null,"javaContainer":null,"javaContainerVersion":null,"appCommandLine":"","managedPipelineMode":"Integrated","virtualApplications":[{"virtualPath":"/","physicalPath":"site\\wwwroot","preloadEnabled":true,"virtualDirectories":null}],"winAuthAdminState":0,"winAuthTenantState":0,"customAppPoolIdentityAdminState":false,"customAppPoolIdentityTenantState":false,"runtimeADUser":null,"runtimeADUserPassword":null,"loadBalancing":"LeastRequests","routingRules":[],"experiments":{"rampUpRules":[]},"limits":null,"autoHealEnabled":false,"autoHealRules":null,"tracingOptions":null,"vnetName":"","vnetRouteAllEnabled":false,"siteAuthEnabled":false,"siteAuthSettings":{"enabled":null,"unauthenticatedClientAction":null,"tokenStoreEnabled":null,"allowedExternalRedirectUrls":null,"defaultProvider":null,"clientId":null,"clientSecret":null,"clientSecretSettingName":null,"clientSecretCertificateThumbprint":null,"issuer":null,"allowedAudiences":null,"additionalLoginParams":null,"isAadAutoProvisioned":false,"aadClaimsAuthorization":null,"googleClientId":null,"googleClientSecret":null,"googleClientSecretSettingName":null,"googleOAuthScopes":null,"facebookAppId":null,"facebookAppSecret":null,"facebookAppSecretSettingName":null,"facebookOAuthScopes":null,"gitHubClientId":null,"gitHubClientSecret":null,"gitHubClientSecretSettingName":null,"gitHubOAuthScopes":null,"twitterConsumerKey":null,"twitterConsumerSecret":null,"twitterConsumerSecretSettingName":null,"microsoftAccountClientId":null,"microsoftAccountClientSecret":null,"microsoftAccountClientSecretSettingName":null,"microsoftAccountOAuthScopes":null},"cors":{"allowedOrigins":[],"supportCredentials":false},"push":null,"apiDefinition":null,"apiManagementConfig":null,"autoSwapSlotName":null,"localMySqlEnabled":false,"managedServiceIdentityId":18048,"xManagedServiceIdentityId":null,"ipSecurityRestrictions":[{"ipAddress":"Any","action":"Allow","priority":1,"name":"Allow all","description":"Allow all access"}],"scmIpSecurityRestrictions":[{"ipAddress":"Any","action":"Allow","priority":1,"name":"Allow all","description":"Allow all access"}],"scmIpSecurityRestrictionsUseMain":false,"http20Enabled":false,"minTlsVersion":"1.2","scmMinTlsVersion":"1.0","ftpsState":"AllAllowed","preWarmedInstanceCount":0,"functionAppScaleLimit":0,"healthCheckPath":null,"fileChangeAuditEnabled":false,"functionsRuntimeScaleMonitoringEnabled":false,"websiteTimeZone":null,"minimumElasticInstanceCount":0}}
  
  
  2020-08-19T10:02:11.8288880Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: [DEBUG] AzureRM Request: 
  2020-08-19T10:02:11.8289568Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: GET /subscriptions/99e0a02c-f0ab-41ad-8de7-d621ce36a09e/resourceGroups/aitdevelopment/providers/Microsoft.Web/sites/aitifdevaffunctions/sourcecontrols/web?api-version=2019-08-01 HTTP/1.1
  2020-08-19T10:02:11.8290242Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Host: management.azure.com
  2020-08-19T10:02:11.8291069Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: User-Agent: Go/go1.14.5 (amd64-windows) go-autorest/v14.0.0 Azure-SDK-For-Go/v44.2.0 web/2019-08-01 HashiCorp Terraform/0.12.29 (+https://www.terraform.io) Terraform Plugin SDK/1.13.1 terraform-provider-azurerm/2.23.0 VSTS_3a20467b-7171-4b7e-a40b-19e133f2093a_build_354_0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
  2020-08-19T10:02:11.8291936Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Ms-Correlation-Request-Id: 51f9c150-2d49-80c3-8936-9a9e9470cf5b
  2020-08-19T10:02:11.8292439Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Accept-Encoding: gzip
  2020-08-19T10:02:11.8292846Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: 
  2020-08-19T10:02:11.8293223Z 2020-08-19T12:02:11.825+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: 
  2020-08-19T10:02:12.0698984Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/99e0a02c-f0ab-41ad-8de7-d621ce36a09e/resourceGroups/aitdevelopment/providers/Microsoft.Web/sites/aitifdevaffunctions/sourcecontrols/web?api-version=2019-08-01: 
  2020-08-19T10:02:12.0700200Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: HTTP/2.0 200 OK
  2020-08-19T10:02:12.0700650Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Cache-Control: no-cache
  2020-08-19T10:02:12.0701303Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Content-Type: application/json
  2020-08-19T10:02:12.0702116Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Date: Wed, 19 Aug 2020 10:02:08 GMT
  2020-08-19T10:02:12.0702732Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Etag: "1D6760C83016480"
  2020-08-19T10:02:12.0703273Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Expires: -1
  2020-08-19T10:02:12.0703782Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Pragma: no-cache
  2020-08-19T10:02:12.0704297Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Server: Microsoft-IIS/10.0
  2020-08-19T10:02:12.0704926Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Strict-Transport-Security: max-age=31536000; includeSubDomains
  2020-08-19T10:02:12.0705541Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: Vary: Accept-Encoding
  2020-08-19T10:02:12.0706074Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Aspnet-Version: 4.0.30319
  2020-08-19T10:02:12.0706640Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Content-Type-Options: nosniff
  2020-08-19T10:02:12.0707522Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Ms-Correlation-Request-Id: 51f9c150-2d49-80c3-8936-9a9e9470cf5b
  2020-08-19T10:02:12.0708539Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Ms-Ratelimit-Remaining-Subscription-Reads: 11989
  2020-08-19T10:02:12.0709402Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Ms-Request-Id: d994b01a-c9d6-4290-9c66-169b9b0e4214
  2020-08-19T10:02:12.0710015Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Ms-Routing-Request-Id: GERMANYWESTCENTRAL:20200819T100209Z:fc3f0e7c-d8cc-4c54-a93d-f76d7a79757a
  2020-08-19T10:02:12.0710570Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: X-Powered-By: ASP.NET
  2020-08-19T10:02:12.0710978Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: 
  2020-08-19T10:02:12.0712046Z 2020-08-19T12:02:12.068+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5.exe: {"id":"/subscriptions/99e0a02c-f0ab-41ad-8de7-d621ce36a09e/resourceGroups/aitdevelopment/providers/Microsoft.Web/sites/aitifdevaffunctions/sourcecontrols/web","name":"aitifdevaffunctions","type":"Microsoft.Web/sites/sourcecontrols","location":"West Europe","tags":{},"properties":{"repoUrl":"VSTSRM","branch":null,"isManualIntegration":false,"isGitHubAction":false,"deploymentRollbackEnabled":false,"isMercurial":false,"provisioningState":"Succeeded"}}
  ```
  
</details>

### Expected Behavior

Deployment should work

### Actual Behavior

apply fails with error

### Steps to Reproduce

1. `terraform apply` in our CI pipeline

### Important Factoids

I feel like this has been introduced in #7945, as we don't even want to set/use these fields. My assumption is that when we deploy to the webapp via Azure DevOps (different pipeline) that the field is set with the `VSTSRM`-Value and then terraform somehow reads that and tries to change it (it shows in the diff, that it tries to change to `None`).

Interestingly, even when I set

```hcl
  lifecycle {
    ignore_changes = [
      site_config.0.scm_type,
      source_control
    ]
  }
```

the deployment fails. I'm not sure why the terraform provider should ever try to write this field, given the above configurations.

I'm still testing but I think downgrading to `2.22.0` should work.

We have a function app and a web app, and it seems like either both work or both fail in a single deployment. If my assumption is correct that this happens when the function or web app are deployed (or are being deployed) by the other pipeline this seems reasonable. This also explains why I cannot reproduce this with another infrastructure I have deployed myself, this only happens in our CI/CD pipeline.

### References

* #3696
* Probably the cause: #7945

### PR DESCRIPTION
**Pull request by jackofallops**
resolves #8171

This change will prevent Terraform from resetting the `site_config.scm_type` value and updating the `source_control` block for Apps and Function Apps that have been updated/deployed after creation by Azure Devops. 

!> Note: The side effect of this is that the resource cannot be used to create `VSTSRM` based apps directly.

### CODE REVIEW

File: azurerm/internal/services/web/resource_arm_app_service.go [hunk 1]
```diff
@@ -377,6 +377,8 @@ func resourceArmAppServiceUpdate(d *schema.ResourceData, meta interface{}) error
 	// If `source_control` is defined, we need to set site_config.0.scm_type to "None" or we cannot update it
 	_, hasSourceControl := d.GetOk("source_control.0.repo_url")
 
+	scmType := web.ScmType("None")
```
Comment (tombuildsstuff) [inline azurerm/internal/services/web/resource_arm_app_service.go:380]: is there a constant for this?

```suggestion
	scmType := web.ScmTypeNone
```

File: azurerm/internal/services/web/resource_arm_function_app.go [hunk 2]
```diff
@@ -458,6 +458,8 @@ func resourceArmFunctionAppUpdate(d *schema.ResourceData, meta interface{}) erro
 	// repo_url is required by the API
 	_, hasSourceControl := d.GetOk("source_control.0.repo_url")
 
+	scmType := web.ScmType("None")
```
Comment (tombuildsstuff) [inline azurerm/internal/services/web/resource_arm_function_app.go:461]: (same here)

**Review by tombuildsstuff — APPROVED** [review]
a couple of minor points but this otherwise LGTM 👍

**Comment by tombuildsstuff** [comment]
Tests look good 👍
