### PR TITLE
`azurerm_monitor_aad_diagnostic_setting` - add a custom poller for create to wait until the resource is fully created

### LINKED ISSUE #30808: azurerm_monitor_aad_diagnostic_setting is not always created successfully
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.13.3

### AzureRM Provider Version

4.47.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_aad_diagnostic_setting

### Terraform Configuration Files

```hcl
locals {
  location = "westus"
  tags     = {}
}

provider "azurerm" {
  subscription_id = "<subscription_id>"
  features {}
}

provider "azuread" {
}

data "azurerm_client_config" "this" {}

resource "random_string" "resource_group" {
  length = 13
  keepers = {
    tenant_id       = data.azurerm_client_config.this.tenant_id
    subscription_id = data.azurerm_client_config.this.subscription_id
    location        = local.location
  }
  special = false
}

resource "azurerm_resource_group" "this" {
  name     = "rg-entid-diag-test-${random_string.resource_group.id}"
  location = local.location
  tags     = local.tags
}

resource "random_string" "eventhub_namespace" {
  length = 13
  keepers = {
    tenant_id           = data.azurerm_client_config.this.tenant_id
    subscription_id     = data.azurerm_client_config.this.subscription_id
    resource_group_name = azurerm_resource_group.this.name
    location            = local.location
  }
  special = false
}

resource "azurerm_eventhub_namespace" "this" {
  name                          = "evhns-entid-diag-test-${random_string.eventhub_namespace.id}"
  location                      = azurerm_resource_group.this.location
  resource_group_name           = azurerm_resource_group.this.name
  sku                           = "Standard"
  capacity                      = 2
  auto_inflate_enabled          = true
  local_authentication_enabled  = true
  maximum_throughput_units      = 10
  minimum_tls_version           = "1.2"
  public_network_access_enabled = true
  network_rulesets {
    default_action                 = "Deny"
    public_network_access_enabled  = true
    trusted_service_access_enabled = true
    ip_rule = [{
      ip_mask = "10.1.1.1" // it doesn't matter
      action  = "Allow"
    }]
  }
  tags = local.tags

  depends_on = [
    azurerm_resource_group.this
  ]
}

resource "azurerm_eventhub" "entra_id_log" {
  name              = "evh-entid-diag-test"
  namespace_id      = azurerm_eventhub_namespace.this.id
  partition_count   = 16
  message_retention = 1

  depends_on = [
    azurerm_eventhub_namespace.this
  ]
}

resource "azurerm_eventhub_namespace_authorization_rule" "this" {
  name                = "rule-entid-diag-test"
  namespace_name      = azurerm_eventhub_namespace.this.name
  resource_group_name = azurerm_resource_group.this.name

  listen = false
  send   = true
  manage = false

  depends_on = [
    azurerm_eventhub_namespace.this
  ]
}


resource "random_string" "entid_diag" {
  length = 13
  keepers = {
    tenant_id          = data.azurerm_client_config.this.tenant_id
    subscription_id    = data.azurerm_client_config.this.subscription_id
    eventhub_namespace = azurerm_eventhub_namespace.this.id
    eventhub_id        = azurerm_eventhub.entra_id_log.id
    location           = local.location
  }
  special = false
}

resource "azurerm_monitor_aad_diagnostic_setting" "entra_id_log" {
  name                           = "evh-entid-diag-test-${random_string.entid_diag.id}"
  eventhub_name                  = azurerm_eventhub.entra_id_log.name
  eventhub_authorization_rule_id = azurerm_eventhub_namespace_authorization_rule.this.id
  enabled_log {
    category = "AuditLogs"
  }
  enabled_log {
    category = "SignInLogs"
  }
  enabled_log {
    category = "NonInteractiveUserSignInLogs"
  }
  enabled_log {
    category = "ServicePrincipalSignInLogs"
  }
  enabled_log {
    category = "ManagedIdentitySignInLogs"
  }
  enabled_log {
    category = "ADFSSignInLogs"
  }

  depends_on = [
    azurerm_eventhub_namespace.this,
    azurerm_eventhub_namespace_authorization_rule.this,
    azurerm_eventhub.entra_id_log
  ]
}
```

### Debug Output/Panic Output

```shell
azurerm_monitor_aad_diagnostic_setting.entra_id_log: Creating...
2025-10-08T16:17:05.304-0400 [INFO]  Starting apply for azurerm_monitor_aad_diagnostic_setting.entra_id_log
2025-10-08T16:17:05.304-0400 [DEBUG] azurerm_monitor_aad_diagnostic_setting.entra_id_log: applying the planned Create change
2025-10-08T16:17:05.306-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: [DEBUG] AzureRM Request: 
2025-10-08T16:17:05.306-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: GET /providers/Microsoft.AADIAM/diagnosticSettings/evh-entid-diag-test-pxRZb76eC6F3p?api-version=2017-04-01 HTTP/1.1
2025-10-08T16:17:05.306-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Host: management.azure.com
2025-10-08T16:17:05.306-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: User-Agent: HashiCorp/go-azure-sdk (Go-http-Client/1.1 diagnosticsettings/2017-04-01) HashiCorp Terraform/1.13.3 (+https://www.terraform.io) terraform-provider-azurerm/dev pid-222c6c49-1b0a-5959-a213-6608f9eb8820
2025-10-08T16:17:05.306-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Content-Type: application/json; charset=utf-8
2025-10-08T16:17:05.306-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Ms-Correlation-Request-Id: 240b74de-b10a-da4b-1eb1-cbfb2004121d
2025-10-08T16:17:05.306-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Accept-Encoding: gzip
2025-10-08T16:17:05.306-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5
2025-10-08T16:17:05.306-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5
2025-10-08T16:17:05.306-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: [DEBUG] GET https://management.azure.com/providers/Microsoft.AADIAM/diagnosticSettings/evh-entid-diag-test-pxRZb76eC6F3p?api-version=2017-04-01
2025-10-08T16:17:05.884-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: [DEBUG] AzureRM Response for https://management.azure.com/providers/Microsoft.AADIAM/diagnosticSettings/evh-entid-diag-test-pxRZb76eC6F3p?api-version=2017-04-01: 
2025-10-08T16:17:05.884-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: HTTP/2.0 404 Not Found
2025-10-08T16:17:05.884-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Content-Length: 113
2025-10-08T16:17:05.884-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Cache-Control: no-cache
2025-10-08T16:17:05.884-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Content-Type: application/json; charset=utf-8
2025-10-08T16:17:05.884-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Date: Wed, 08 Oct 2025 20:17:05 GMT
2025-10-08T16:17:05.884-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Expires: -1
2025-10-08T16:17:05.884-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Pragma: no-cache
2025-10-08T16:17:05.884-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Strict-Transport-Security: max-age=31536000; includeSubDomains
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Cache: CONFIG_NOCACHE
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Content-Type-Options: nosniff
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Ms-Correlation-Request-Id: 240b74de-b10a-da4b-1eb1-cbfb2004121d
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Ms-Operation-Identifier: 
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Ms-Ratelimit-Remaining-Tenant-Reads: 249
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Ms-Request-Id: 00000000-0000-0000-0000-000000000000
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Ms-Routing-Request-Id: WESTUS:20251008T201705Z:394134a6-74e4-4dec-95e0-9518af745a5f
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Msedge-Ref: Ref A: CCAF7F7DD7F84799A81A5462F31C25F1 Ref B: YQ1AA2090601023 Ref C: 2025-10-08T20:17:05Z
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: {"code":"ResourceNotFound","message":"The diagnostic setting 'evh-entid-diag-test-pxRZb76eC6F3p' doesn't exist."}
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: [DEBUG] AzureRM Request: 
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: PUT /providers/Microsoft.AADIAM/diagnosticSettings/evh-entid-diag-test-pxRZb76eC6F3p?api-version=2017-04-01 HTTP/1.1
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Host: management.azure.com
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: User-Agent: HashiCorp/go-azure-sdk (Go-http-Client/1.1 diagnosticsettings/2017-04-01) HashiCorp Terraform/1.13.3 (+https://www.terraform.io) terraform-provider-azurerm/dev pid-222c6c49-1b0a-5959-a213-6608f9eb8820
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Content-Length: 608
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Content-Type: application/json; charset=utf-8
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Ms-Correlation-Request-Id: 240b74de-b10a-da4b-1eb1-cbfb2004121d
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Accept-Encoding: gzip
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: {"properties":{"eventHubAuthorizationRuleId":"/subscriptions/3222feaf-8446-4fcc-8fa2-012655c9d454/resourceGroups/rg-entid-diag-test-hIj5h42etFhFa/providers/Microsoft.EventHub/namespaces/evhns-entid-diag-test-Uw9VqmJbj6nhP/authorizationRules/rule-entid-diag-test","eventHubName":"evh-entid-diag-test","logs":[{"category":"ServicePrincipalSignInLogs","enabled":true},{"category":"SignInLogs","enabled":true},{"category":"ADFSSignInLogs","enabled":true},{"category":"NonInteractiveUserSignInLogs","enabled":true},{"category":"ManagedIdentitySignInLogs","enabled":true},{"category":"AuditLogs","enabled":true}]}}
2025-10-08T16:17:05.885-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: [DEBUG] PUT https://management.azure.com/providers/Microsoft.AADIAM/diagnosticSettings/evh-entid-diag-test-pxRZb76eC6F3p?api-version=2017-04-01
2025-10-08T16:17:08.439-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: [DEBUG] AzureRM Response for https://management.azure.com/providers/Microsoft.AADIAM/diagnosticSettings/evh-entid-diag-test-pxRZb76eC6F3p?api-version=2017-04-01: 
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: HTTP/2.0 200 OK
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Content-Length: 1352
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Cache-Control: no-cache
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Content-Type: application/json; charset=utf-8
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Date: Wed, 08 Oct 2025 20:17:08 GMT
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Expires: -1
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Pragma: no-cache
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Strict-Transport-Security: max-age=31536000; includeSubDomains
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Cache: CONFIG_NOCACHE
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Content-Type-Options: nosniff
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Ms-Correlation-Request-Id: 240b74de-b10a-da4b-1eb1-cbfb2004121d
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Ms-Operation-Identifier: 
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Ms-Ratelimit-Remaining-Tenant-Writes: 199
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Ms-Request-Id: 52c3d754-52f8-4ddc-a032-197797c9aefc
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Ms-Routing-Request-Id: CANADACENTRAL:20251008T201708Z:96973875-e60f-451f-9cb9-521afeab48b4
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Msedge-Ref: Ref A: E796E36EE1044871BAB987325E89C004 Ref B: YQ1AA2090602062 Ref C: 2025-10-08T20:17:06Z
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: {"id":"providers/Microsoft.AADIAM/diagnosticSettings/evh-entid-diag-test-pxRZb76eC6F3p","type":"Microsoft.Insights/diagnosticSettings","name":"evh-entid-diag-test-pxRZb76eC6F3p","location":null,"kind":null,"tags":null,"properties":{"storageAccountId":null,"serviceBusRuleId":null,"workspaceId":null,"eventHubAuthorizationRuleId":"/subscriptions/3222feaf-8446-4fcc-8fa2-012655c9d454/resourceGroups/rg-entid-diag-test-hIj5h42etFhFa/providers/Microsoft.EventHub/namespaces/evhns-entid-diag-test-Uw9VqmJbj6nhP/authorizationRules/rule-entid-diag-test","eventHubName":"evh-entid-diag-test","metrics":[],"logs":[{"category":"ServicePrincipalSignInLogs","categoryGroup":null,"enabled":true,"retentionPolicy":{"enabled":false,"days":0}},{"category":"SignInLogs","categoryGroup":null,"enabled":true,"retentionPolicy":{"enabled":false,"days":0}},{"category":"ADFSSignInLogs","categoryGroup":null,"enabled":true,"retentionPolicy":{"enabled":false,"days":0}},{"category":"NonInteractiveUserSignInLogs","categoryGroup":null,"enabled":true,"retentionPolicy":{"enabled":false,"days":0}},{"category":"ManagedIdentitySignInLogs","categoryGroup":null,"enabled":true,"retentionPolicy":{"enabled":false,"days":0}},{"category":"AuditLogs","categoryGroup":null,"enabled":true,"retentionPolicy":{"enabled":false,"days":0}}],"logAnalyticsDestinationType":null},"identity":null}
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: [DEBUG] AzureRM Request: 
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: GET /providers/Microsoft.AADIAM/diagnosticSettings/evh-entid-diag-test-pxRZb76eC6F3p?api-version=2017-04-01 HTTP/1.1
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Host: management.azure.com
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: User-Agent: HashiCorp/go-azure-sdk (Go-http-Client/1.1 diagnosticsettings/2017-04-01) HashiCorp Terraform/1.13.3 (+https://www.terraform.io) terraform-provider-azurerm/dev pid-222c6c49-1b0a-5959-a213-6608f9eb8820
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Content-Type: application/json; charset=utf-8
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Ms-Correlation-Request-Id: 240b74de-b10a-da4b-1eb1-cbfb2004121d
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Accept-Encoding: gzip
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5
2025-10-08T16:17:08.440-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: [DEBUG] GET https://management.azure.com/providers/Microsoft.AADIAM/diagnosticSettings/evh-entid-diag-test-pxRZb76eC6F3p?api-version=2017-04-01
2025-10-08T16:17:08.851-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: [DEBUG] AzureRM Response for https://management.azure.com/providers/Microsoft.AADIAM/diagnosticSettings/evh-entid-diag-test-pxRZb76eC6F3p?api-version=2017-04-01: 
2025-10-08T16:17:08.851-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: HTTP/2.0 404 Not Found
2025-10-08T16:17:08.851-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Content-Length: 113
2025-10-08T16:17:08.851-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Cache-Control: no-cache
2025-10-08T16:17:08.851-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Content-Type: application/json; charset=utf-8
2025-10-08T16:17:08.851-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Date: Wed, 08 Oct 2025 20:17:08 GMT
2025-10-08T16:17:08.851-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Expires: -1
2025-10-08T16:17:08.851-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Pragma: no-cache
2025-10-08T16:17:08.851-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: Strict-Transport-Security: max-age=31536000; includeSubDomains
2025-10-08T16:17:08.851-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Cache: CONFIG_NOCACHE
2025-10-08T16:17:08.851-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Content-Type-Options: nosniff
2025-10-08T16:17:08.851-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Ms-Correlation-Request-Id: 240b74de-b10a-da4b-1eb1-cbfb2004121d
2025-10-08T16:17:08.851-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Ms-Operation-Identifier: 
2025-10-08T16:17:08.851-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Ms-Ratelimit-Remaining-Tenant-Reads: 249
2025-10-08T16:17:08.851-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Ms-Request-Id: 00000000-0000-0000-0000-000000000000
2025-10-08T16:17:08.851-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Ms-Routing-Request-Id: WESTUS:20251008T201708Z:71f40eca-6565-483d-bf60-af47efe42f96
2025-10-08T16:17:08.851-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: X-Msedge-Ref: Ref A: EF099FA3A55D4DCDAEA1101D4EC87C07 Ref B: YQ1AA2090602054 Ref C: 2025-10-08T20:17:08Z
2025-10-08T16:17:08.851-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5
2025-10-08T16:17:08.851-0400 [DEBUG] provider.terraform-provider-azurerm_v4.47.0_x5: {"code":"ResourceNotFound","message":"The diagnostic setting 'evh-entid-diag-test-pxRZb76eC6F3p' doesn't exist."}
2025-10-08T16:17:08.851-0400 [WARN]  provider.terraform-provider-azurerm_v4.47.0_x5: [WARN] Diagnostic Setting (Diagnostic Setting Name: "evh-entid-diag-test-pxRZb76eC6F3p") was not found - removing from state!
2025-10-08T16:17:08.858-0400 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2025-10-08T16:17:08.858-0400 [ERROR] vertex "azurerm_monitor_aad_diagnostic_setting.entra_id_log" error: Provider produced inconsistent result after apply
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to azurerm_monitor_aad_diagnostic_setting.entra_id_log, provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value: Root object was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
2025-10-08T16:17:08.866-0400 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2025-10-08T16:17:08.878-0400 [INFO]  provider: plugin process exited: plugin=.terraform/providers/registry.terraform.io/hashicorp/azurerm/4.47.0/darwin_arm64/terraform-provider-azurerm_v4.47.0_x5 id=58567
2025-10-08T16:17:08.878-0400 [DEBUG] provider: plugin exited
```

### Expected Behaviour

The `azurerm_monitor_aad_diagnostic_setting` should always be created successfully.

### Actual Behaviour

`azurerm_monitor_aad_diagnostic_setting` sometimes is failed to be created with the error:
```
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to azurerm_monitor_aad_diagnostic_setting.entra_id_log, provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value: Root object was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

As you can see in the debug log, the `PUT https://management.azure.com/providers/Microsoft.AADIAM/diagnosticSettings/evh-entid-diag-test-pxRZb76eC6F3p?api-version=2017-04-01` returned `200 OK`, but the following `GET https://management.azure.com/providers/Microsoft.AADIAM/diagnosticSettings/evh-entid-diag-test-pxRZb76eC6F3p?api-version=2017-04-01` call returned `404 Not found`, which shouldn't happen.

### Steps to Reproduce

1. `terraform plan -out=plan.out`
2. `terraform apply plan.out`

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by teowa**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

add custompoller for create to workaround https://github.com/Azure/azure-rest-api-specs/issues/38858

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-merging.md).

* `azurerm_monitor_aad_diagnostic_setting` - add a custom poller for create to wait until the resource is fully created [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)

Fixes #30808

## AI Assistance Disclosure

- [ ] AI Assisted - This contribution was made by, or with the assistance of, AI/LLMs

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/monitor/monitor_aad_diagnostic_setting_resource_test.go [hunk 1]
```diff
@@ -49,12 +53,45 @@ func TestAccMonitorAADDiagnosticSetting(t *testing.T) {
 	}
 }
 
+func deleteExistingAcctestAADDiagnosticSetting(t *testing.T) func() {
```
Comment (teowa) [inline internal/services/monitor/monitor_aad_diagnostic_setting_resource_test.go]: This is intended to remove the current test resources from the tenant, as they are not under a resource group and may not be automatically cleaned up by certain tools.

Image

**Comment by teowa** [comment]
image
