### PR TITLE
`azurerm_cdn_frontdoor_route` - make `cdn_frontdoor_origin_ids` field `optional`

### LINKED ISSUE #29063: azurerm_cdn_frontdoor_route import does not import cdn_frontdoor_origin_ids
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

Hi,

Create an import block or import resource manually,

You will have a diff on  cdn_frontdoor_origin_ids, it set to null on import

### Terraform Version

1.10

### AzureRM Provider Version

v4.22.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_route

### Terraform Configuration Files

```hcl
import {
    to = azurerm_cdn_frontdoor_route.adb2c_custom_domain
    id = format("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Cdn/profiles/%s-login-custom-domain/afdEndpoints/%s/routes/%s", local.azure_subscription_id, var.rg_name, local.adb2c_tenant_name, substr(format("%s-login-custom-domain", local.adb2c_tenant_name), 0, 46), "default-route")
  }
```

### Debug Output/Panic Output

```shell
~ resource "azurerm_cdn_frontdoor_route" "adb2c_custom_domain" {
+ cdn_frontdoor_origin_ids        = [
+ "/subscriptionsxxxxxxxxxxxxx/resourceGroups/production/providers/Microsoft.Cdn/profiles/xxxxx-login-custom-domain/originGroups/default-origin-group/origins/default-origin",
+ ]
}
```

### Expected Behaviour

_No response_

### Actual Behaviour

_No response_

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by WodansSon**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

In issue [#29063](https://github.com/hashicorp/terraform-provider-azurerm/issues/29063) a community member raised an issue that: 

* You will have a diff on `cdn_frontdoor_origin_ids`, it set to `null` on import

While this is by design, some community members stated that they would prefer that the `cdn_frontdoor_origin_ids` field be deprecated in favor of a `depends_on` argument. This PR addresses both issues allowing for both, with the caveat that this may cause more issues moving forward due to community members personal preference. In the design of this resource exposing the `cdn_frontdoor_origin_ids` field was intentional, showing the relationship between the resources and allowing the Terraform core runtime to provision and destroy the resources in the correct order to avoid errors. With this change, while it will work, it puts that duty on the end user to ensure the correct order/relationship of the resources based on their personal preference (e.g., `cdn_frontdoor_origin_ids` or a `depends_on` argument).

## PR Checklist

- [X] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [X] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [X] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [X] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [X] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [X] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [X] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [X] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [X] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_cdn_frontdoor_route` - make `cdn_frontdoor_origin_ids` field `optional` [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [X] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #29063

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/cdn/cdn_frontdoor_route_resource.go
Comment (wyattfry) [inline internal/services/cdn/cdn_frontdoor_route_resource.go:1]: Could you replace the `utils.String()` etc with `pointer.To()`?

File: website/docs/r/cdn_frontdoor_route.html.markdown [hunk 1]
```diff
@@ -10,6 +10,8 @@ description: |-
 
 Manages a Front Door (standard/premium) Route.
 
+!>**Note:** The `azurerm_cdn_frontdoor_route` resource must **explicitly** reference its associated `azurerm_cdn_frontdoor_origin` resource(s). This can be achieved either by using a `depends_on` meta-argument that points to the `azurerm_cdn_frontdoor_origin` resource(s), or by specifying the `azurerm_cdn_frontdoor_origin` IDs via the `cdn_frontdoor_origin_ids` field.
```
Comment (wyattfry) [inline website/docs/r/cdn_frontdoor_route.html.markdown]:
```suggestion
!> **Note:** The `azurerm_cdn_frontdoor_route` resource must **explicitly** reference its associated `azurerm_cdn_frontdoor_origin` resource(s). This can be achieved either by using a `depends_on` meta-argument that points to the `azurerm_cdn_frontdoor_origin` resource(s), or by specifying the `azurerm_cdn_frontdoor_origin` IDs via the `cdn_frontdoor_origin_ids` field.
```

File: internal/services/cdn/cdn_frontdoor_route_resource.go [hunk 2]
```diff
@@ -62,9 +62,10 @@ func resourceCdnFrontDoorRoute() *pluginsdk.Resource {
 
 			// NOTE: These are not sent to the API, they are only here so Terraform
 			// can provision/destroy the resources in the correct order.
+			// Made this field optional to address comments in Issue #29063
 			"cdn_frontdoor_origin_ids": {
 				Type:     pluginsdk.TypeList,
-				Required: true,
+				Optional: true,
 
 				Elem: &pluginsdk.Schema{
```
Comment (wyattfry) [inline internal/services/cdn/cdn_frontdoor_route_resource.go:70]: I've seen both ways in the code, but it seems most of the time there's no new line before `Elem:`

```suggestion
				Optional: true,
Elem: &pluginsdk.Schema{
```

**Review by wyattfry — CHANGES_REQUESTED** [review]
This may have already been considered, but I was thinking about how giving the route a property for origin IDs only reflects part of what's actually happening at the Azure API level. As it is probably known, routes don't depend on specific origins—they just need their associated origin group to have at least one enabled origin before creation of the route can succeed.

What if we handled the issue in the provider itself with a custom poller? It could catch the specific "origin group needs at least one enabled origin" error from Azure and retry route creation for a few minutes. The Portal does not allow for origin groups with zero enabled origins, but the REST API does, even though such groups are of no practical value. If an origin group exists, I believe it's safe to assume that soon it will have at least one enabled origin.

The poller approach would:
- be more semantically accurate
- remove the need for workarounds in user configurations
- handle the timing automatically

The downside is a potential added delay during apply if origins aren't ready immediately, but that seems like a reasonable trade-off for cleaner resource modeling. Curious what others think about this approach, or if there are better alternatives, or reasons why the custom poller one wouldn't work?

File: internal/services/cdn/cdn_frontdoor_route_resource.go
Comment (WodansSon) [reply internal/services/cdn/cdn_frontdoor_route_resource.go:1]: Fixed.

File: internal/services/cdn/cdn_frontdoor_route_resource.go (hunk 2 above)
Comment (WodansSon) [reply internal/services/cdn/cdn_frontdoor_route_resource.go:70]: Fixed.

File: website/docs/r/cdn_frontdoor_route.html.markdown (hunk 1 above)
Comment (WodansSon) [reply website/docs/r/cdn_frontdoor_route.html.markdown]: Fixed.

**Comment by WodansSon** [comment]
> This may have already been considered, but I was thinking about how giving the route a property for origin IDs only reflects part of what's actually happening at the Azure API level. As it is probably known, routes don't depend on specific origins—they just need their associated origin group to have at least one enabled origin before creation of the route can succeed.
> 
> What if we handled the issue in the provider itself with a custom poller? It could catch the specific "origin group needs at least one enabled origin" error from Azure and retry route creation for a few minutes. The Portal does not allow for origin groups with zero enabled origins, but the REST API does, even though such groups are of no practical value. If an origin group exists, I believe it's safe to assume that soon it will have at least one enabled origin.
> 
> The poller approach would:
> 
> * be more semantically accurate
> * remove the need for workarounds in user configurations
> * handle the timing automatically
> 
> The downside is a potential added delay during apply if origins aren't ready immediately, but that seems like a reasonable trade-off for cleaner resource modeling. Curious what others think about this approach, or if there are better alternatives, or reasons why the custom poller one wouldn't work?

That would likely be a more modern solution to the API’s provisioning order issue for this resource, as it would let Terraform handle the behavior more gracefully rather than relying on faux fields. However, the custom poller wasn’t really an option when this resource/PR was first created. I agree the custom poller approach is worth considering going forward, but for the scope of this PR, can we set that aside? I’m happy to open a follow-up PR to introduce the custom poller. For now, can we move this PR forward to address the current customer needs without that added functionality?

File: website/docs/r/cdn_frontdoor_route.html.markdown [hunk 3]
```diff
@@ -10,6 +10,8 @@ description: |-
 
 Manages a Front Door (standard/premium) Route.
 
+!> **Note:** The `azurerm_cdn_frontdoor_route` resource must **explicitly** reference its associated `azurerm_cdn_frontdoor_origin` resource(s). This can be achieved either by using a `depends_on` meta-argument that points to the `azurerm_cdn_frontdoor_origin` resource(s), or by specifying the `azurerm_cdn_frontdoor_origin` IDs via the `cdn_frontdoor_origin_ids` field.
```
Comment (wyattfry) [inline website/docs/r/cdn_frontdoor_route.html.markdown]: We'd like to save the "!>" notes for cases where costly or irreversible damage could occur. The "~>" is a good choice for advising users how to avoid minor errors.

```suggestion
~> **Note:** The `azurerm_cdn_frontdoor_route` resource must **explicitly** reference its associated `azurerm_cdn_frontdoor_origin` resource(s). This can be achieved either by using a `depends_on` meta-argument that points to the `azurerm_cdn_frontdoor_origin` resource(s), or by specifying the `azurerm_cdn_frontdoor_origin` IDs via the `cdn_frontdoor_origin_ids` field.
```

File: website/docs/r/cdn_frontdoor_route.html.markdown [hunk 4]
```diff
@@ -134,16 +136,20 @@ The following arguments are supported:
...
 
 ~> **Note:** If `https_redirect_enabled` is set to `true` the `supported_protocols` field must contain both `Http` and `Https` values.
 
+* `cdn_frontdoor_origin_ids` - (Optional) One or more Front Door Origin resource IDs for this Front Door Route.
+
+~> **Note:** The `cdn_frontdoor_origin_ids` field is not sent to the Azure API, it exists solely to ensure Terraform can manage the correct `provisioning` and `destruction` order of related resources. When importing an existing `azurerm_cdn_frontdoor_route` resource, you will need to manually add the `cdn_frontdoor_origin_ids` field to your configuration after the resource has been successfully imported.
+
+~> **Note:** If the `cdn_frontdoor_origin_ids` field is not defined in the configuration, you **must** use a `depends_on` meta-argument that references the corresponding `azurerm_cdn_frontdoor_origin` resource(s) for the route. When importing an existing `azurerm_cdn_frontdoor_route` resource from Azure, you will need to manually add the `depends_on` meta-argument to your configuration after the resource has been successfully imported.
```
Comment (wyattfry) [inline website/docs/r/cdn_frontdoor_route.html.markdown]: Could these two notes be condensed and combined?

**Comment by wyattfry** [comment]
> > This may have already been considered, but I was thinking about how giving the route a property for origin IDs only reflects part of what's actually happening at the Azure API level. As it is probably known, routes don't depend on specific origins—they just need their associated origin group to have at least one enabled origin before creation of the route can succeed.
> > What if we handled the issue in the provider itself with a custom poller? It could catch the specific "origin group needs at least one enabled origin" error from Azure and retry route creation for a few minutes. The Portal does not allow for origin groups with zero enabled origins, but the REST API does, even though such groups are of no practical value. If an origin group exists, I believe it's safe to assume that soon it will have at least one enabled origin.
> > The poller approach would:
> > 
> > * be more semantically accurate
> > * remove the need for workarounds in user configurations
> > * handle the timing automatically
> > 
> > The downside is a potential added delay during apply if origins aren't ready immediately, but that seems like a reasonable trade-off for cleaner resource modeling. Curious what others think about this approach, or if there are better alternatives, or reasons why the custom poller one wouldn't work?
> 
> That would likely be a more modern solution to the API’s provisioning order issue for this resource, as it would let Terraform handle the behavior more gracefully rather than relying on faux fields. However, the custom poller wasn’t really an option when this resource/PR was first created. I agree the custom poller approach is worth considering going forward, but for the scope of this PR, can we set that aside? I’m happy to open a follow-up PR to introduce the custom poller. For now, can we move this PR forward to address the current customer needs without that added functionality?

Yes, the delay would be regrettable. I'm sorry to ask more of you, but from the user's perspective, I believe the improved experience a custom poller would provide would be worth the additional wait. Are there time-sensitive situations that would make the delay too costly?

**Review by wyattfry — DISMISSED** [review]
Just a couple very small points.

File: website/docs/r/cdn_frontdoor_route.html.markdown (hunk 3 above)
Comment (WodansSon) [reply website/docs/r/cdn_frontdoor_route.html.markdown]: Fixed.

File: website/docs/r/cdn_frontdoor_route.html.markdown (hunk 4 above)
Comment (WodansSon) [reply website/docs/r/cdn_frontdoor_route.html.markdown]: Fixed.

**Review by catriona-m — DISMISSED** [review]
Hi @WodansSon thanks for fixing this up. It looks like there are some conflicts needing resolved on this, but otherwise it looks like this is nearly ready to go. Thanks!

**Comment by WodansSon** [comment]
> Hi @WodansSon thanks for fixing this up. It looks like there are some conflicts needing resolved on this, but otherwise it looks like this is nearly ready to go. Thanks!

Thanks for the calling that out, @catriona-m, I have fixed the conflicts and am running the tests again. 🙂 

```bash
--- PASS: TestAccCdnFrontDoorRoute_complete (1606.21s)
--- PASS: TestAccCdnFrontDoorRoute_requiresImport (1611.69s)
--- PASS: TestAccCdnFrontDoorRoute_basic (1622.74s)
--- PASS: TestAccCdnFrontDoorRoute_basicDependsOnAndField (1629.25s)
--- PASS: TestAccCdnFrontDoorRoute_basicDependsOn (1696.55s)
--- PASS: TestAccCdnFrontDoorRoute_update (1746.74s)
--- PASS: TestAccCdnFrontDoorRoute_originPath (1752.09s)
```

**Comment by WodansSon** [comment]
Test after adding the `depends_on` step to update:
```
--- PASS: TestAccCdnFrontDoorRoute_update (1705.68s)
```

**Comment by wuxu92** [comment]
A custom poller can mitigate the issue in creation, but there are two cases:

1. it's not 100% sure that "If an origin group exists, I believe it's safe to assume that soon it will have at least one enabled origin", as customer may only config origin group and route with no origin, then the poller won't work
2. the dependency issue still exists in delete. that means we still need a specific depends on to all managed origin resources.

I agree we should make `cdn_frontdoor_origin_ids` as optional and update the document to mitigate the import issue

**Review by sreallymatt — APPROVED** [review]
Thanks @WodansSon - LGTM ✅
