### PR TITLE
`azurerm_lb` - fix zone behaviour bug introduced in recent API upgrade

### LINKED ISSUE #12215: azurerm_lb unable to set zone-redundant resource
Hello,

There is an issue when creating/updating azurerm_lb resource with azurerm provider v2.63.0. 
https://azure.microsoft.com/en-gb/updates/zone-behavior-change/ 
This relates to PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/11627 

Azurerm provider version: v2.63.0 
TF version: 0.13.2
```
### Loadbalancer configuration
resource "azurerm_lb" "indexer" {
  name                = "${var.environment}indexer-lb"
  location            = var.location
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "Standard"
  
  frontend_ip_configuration {
    name                          = "LoadBalancerFrontEnd"
    private_ip_address_allocation = "Static"
    subnet_id                     = data.azurerm_subnet.indexer.id
    private_ip_address_version    = "IPv4"
    private_ip_address            = var.indexer_lb_private_ip
  }
  lifecycle {
    ignore_changes = [
      tags
    ]
  }
}
```
The plan output (redacting most of the plan) when altering a different resource (i.e. the loadbalancer was already created and I had changed a different resource entirely): 
```
# azurerm_lb.indexer must be replaced
-/+ resource "azurerm_lb" "indexer" {
      ~ id                   = "*****" -> (known after apply)
        location             = "northeurope"
        name                 = "prdindexer-lb"
      ~ private_ip_address   = ****-> (known after apply)
      ~ private_ip_addresses = [
          - ****,
        ] -> (known after apply)
        resource_group_name  = "****"
        sku                  = "Standard"

~ frontend_ip_configuration {
          ~ id                            = "****" -> (known after apply)
          ~ inbound_nat_rules             = [] -> (known after apply)
          ~ load_balancer_rules           = [
              - "*****",
            ] -> (known after apply)
            name                          = "LoadBalancerFrontEnd"
          ~ outbound_rules                = [] -> (known after apply)
            private_ip_address            = "****"
          ~ private_ip_address_allocation = "Static" -> "static"
            private_ip_address_version    = "IPv4"
          + public_ip_address_id          = (known after apply)
          + public_ip_prefix_id           = (known after apply)
            subnet_id                     = "*****"
          - zones                         = [
              - "1",
              - "2",
              - "3",
            ] -> null # forces replacement
        }
    }

```
When adding `frontend_ip_configuration[0].zones` - the lb resource does not get recreated (as per tf plan). 

On previous versions of the provider - our pipelines ran and lb were not being recreated. This I believe is because, as per docs, when Zones is not specified (like in my configuration), the loadbalancer would be zone redundant. However, now it is following the new zone behaviour change (https://azure.microsoft.com/en-gb/updates/zone-behavior-change/) and when not specifying zone a non-zonal resource is created. 

You are also not able to specify zones = `["1","2","3"]`
```
Error: frontend_ip_configuration.0.zones: attribute supports 1 item maximum, config has 3 declared
```

 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_lb`

### PR DESCRIPTION
**Pull request by ms-henglu**
This PR fixed 2 issues.
1. For users who use azurerm 2.62.x, there'll be a [breaking change]( https://azure.microsoft.com/en-us/updates/zone-behavior-change/) when they update azurerm to latest version. This is fix is similar with [the fix for public ip resource](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/network/public_ip_resource.go#L64).

2. For users who updates to azurerm 2.63.0, resources will be deployed as `no-zone` by default and there's no way to set it as `zone-redundant`.

After this fix, 2.62.x users can update azurerm smoothly. But users who ever used 2.63.0, if they want to use a `zone-redundant` resource, they have modify config and add the following line.
```
availability_zone = "Zone-Redundant"
```

The tests are listed as the following.
```

=== RUN   TestAccAzureRMLoadBalancer_basic
=== PAUSE TestAccAzureRMLoadBalancer_basic
=== CONT  TestAccAzureRMLoadBalancer_basic
--- PASS: TestAccAzureRMLoadBalancer_basic (245.14s)
=== RUN   TestAccAzureRMLoadBalancer_requiresImport
=== PAUSE TestAccAzureRMLoadBalancer_requiresImport
=== CONT  TestAccAzureRMLoadBalancer_requiresImport
--- PASS: TestAccAzureRMLoadBalancer_requiresImport (239.84s)
=== RUN   TestAccAzureRMLoadBalancer_standard
=== PAUSE TestAccAzureRMLoadBalancer_standard
=== CONT  TestAccAzureRMLoadBalancer_standard
--- PASS: TestAccAzureRMLoadBalancer_standard (178.31s)
=== RUN   TestAccAzureRMLoadBalancer_frontEndConfigPublicIPPrefix
=== PAUSE TestAccAzureRMLoadBalancer_frontEndConfigPublicIPPrefix
=== CONT  TestAccAzureRMLoadBalancer_frontEndConfigPublicIPPrefix
--- PASS: TestAccAzureRMLoadBalancer_frontEndConfigPublicIPPrefix (223.97s)
=== RUN   TestAccAzureRMLoadBalancer_frontEndConfig
=== PAUSE TestAccAzureRMLoadBalancer_frontEndConfig
=== CONT  TestAccAzureRMLoadBalancer_frontEndConfig
--- PASS: TestAccAzureRMLoadBalancer_frontEndConfig (488.93s)
=== RUN   TestAccAzureRMLoadBalancer_tags
=== PAUSE TestAccAzureRMLoadBalancer_tags
=== CONT  TestAccAzureRMLoadBalancer_tags
--- PASS: TestAccAzureRMLoadBalancer_tags (312.32s)
=== RUN   TestAccAzureRMLoadBalancer_emptyPrivateIP
=== PAUSE TestAccAzureRMLoadBalancer_emptyPrivateIP
=== CONT  TestAccAzureRMLoadBalancer_emptyPrivateIP
--- PASS: TestAccAzureRMLoadBalancer_emptyPrivateIP (311.15s)
=== RUN   TestAccAzureRMLoadBalancer_privateIP
=== PAUSE TestAccAzureRMLoadBalancer_privateIP
=== CONT  TestAccAzureRMLoadBalancer_privateIP
--- PASS: TestAccAzureRMLoadBalancer_privateIP (259.72s)
=== RUN   TestAccAzureRMLoadBalancer_ZoneRedundant
=== PAUSE TestAccAzureRMLoadBalancer_ZoneRedundant
=== CONT  TestAccAzureRMLoadBalancer_ZoneRedundant
--- PASS: TestAccAzureRMLoadBalancer_ZoneRedundant (242.98s)
=== RUN   TestAccAzureRMLoadBalancer_NoZone
=== PAUSE TestAccAzureRMLoadBalancer_NoZone
=== CONT  TestAccAzureRMLoadBalancer_NoZone
--- PASS: TestAccAzureRMLoadBalancer_NoZone (245.47s)
=== RUN   TestAccAzureRMLoadBalancer_SingleZone
=== PAUSE TestAccAzureRMLoadBalancer_SingleZone
=== CONT  TestAccAzureRMLoadBalancer_SingleZone
--- PASS: TestAccAzureRMLoadBalancer_SingleZone (251.52s)
PASS


```

(fixes #12215)

### CODE REVIEW

**Comment by ms-henglu** [comment]
Hi @jackofallops , could you please help review this PR? Thanks!

**Comment by brendandburns** [comment]
Do we need to introduce some unit testing to prevent this (or similar errors) from happening in the future?

Thanks!

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @ms-henglu - could we add a couple tests here using the availability_zone property? this will make sure that going forward we will catch any changes that break this property going forward - thanks

**Comment by ms-henglu** [comment]
Hi @katbyte , I added acctest for `availability_zone`, please review again, thanks!

File: azurerm/internal/services/loadbalancer/loadbalancer_resource_test.go [hunk 1]
```diff
@@ -165,6 +165,36 @@ func TestAccAzureRMLoadBalancer_privateIP(t *testing.T) {
 	})
 }
 
+func TestAccAzureRMLoadBalancer_ZoneRedundant(t *testing.T) {
```
Comment (WodansSon) [inline azurerm/internal/services/loadbalancer/loadbalancer_resource_test.go:168]: Can we add one more test that takes a "1", "2" or "3"?

**Review by WodansSon — CHANGES_REQUESTED** [review]
Thanks for the changes, LGTM. Can we add one more test case maybe?

**Comment by ms-henglu** [comment]
Hi @WodansSon , I added a test for single zone

**Review by WodansSon — CHANGES_REQUESTED** [review]
@ms-henglu thanks for pushing those changes, this is really close. I have left a couple of comments around the documentation. Take a look and LMK when you have a chance.

**Comment by ms-henglu** [comment]
@WodansSon Thanks for the suggestions, I've applied them.

**Review by WodansSon — APPROVED** [review]
@ms-henglu thanks for pushing those changes so quickly. This LGTM now! 🚀 HBY @jackofallops  and @katbyte

**Comment by jackofallops** [comment]
Hi @ms-henglu 
I've run the acceptance tests on this and we're getting a bunch of failures around the Zone settings / behaviour, for example:
```shell
Error: creating/updating Load Balancer "acctestlb-210616060652758222" (Resource Group "acctestRG-210616060652758222"): network.LoadBalancersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ResourceCannotHaveMultipleZonesSpecified" Message="Resource /subscriptions/*******/resourceGroups/acctestRG-210616060652758222/providers/Microsoft.Network/loadBalancers/acctestlb-210616060652758222/frontendIPConfigurations/feip has 2 zones specified. Only one zone can be specified for this resource." Details=[]
```

and

```shell
Error: creating/updating Load Balancer "arm-test-loadbalancer-210616060912483394" (Resource Group "acctestRG-210616060912483394"): network.LoadBalancersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="LoadBalancerFrontendIPConfigCannotHaveZoneWhenReferencingPublicIPAddress" Message="Load balancer frontendIPConfiguration /subscriptions/*******/resourceGroups/acctestRG-210616060912483394/providers/Microsoft.Network/loadBalancers/arm-test-loadbalancer-210616060912483394/frontendIPConfigurations/one-210616060912483394 has 1 zone specified and is referencing a publicIPAddress /subscriptions/*******/resourceGroups/acctestRG-210616060912483394/providers/Microsoft.Network/publicIPAddresses/test-ip-210616060912483394. Networking supports zones only for frontendIpconfigurations which reference a subnet." Details=[]
```

Could you take a look?

**Comment by ms-henglu** [comment]
@jackofallops Thanks!!

I have fixed them all, please check.

File: azurerm/internal/services/loadbalancer/loadbalancer_resource.go [hunk 2]
```diff
@@ -352,13 +386,50 @@ func expandAzureRmLoadBalancerFrontendIpConfigurations(d *pluginsdk.ResourceData
...
+				properties.PrivateIPAddressVersion = network.IPVersion(v)
+			}
 			properties.Subnet = &network.Subnet{
 				ID: &v,
 			}
 		}
 
 		name := data["name"].(string)
-		zones := azure.ExpandZones(data["zones"].([]interface{}))
+		zones := &[]string{"1", "2"}
```
Comment (WodansSon) [inline azurerm/internal/services/loadbalancer/loadbalancer_resource.go:400]: The acceptance tests are failing with `frontendIPConfigurations has 2 zones specified. Only one zone can be specified for this resource.` So we should only set a single zone here?
```suggestion
		zones := &[]string{"2"}
```

File: azurerm/internal/services/loadbalancer/loadbalancer_resource.go [hunk 3]
```diff
@@ -352,13 +386,50 @@ func expandAzureRmLoadBalancerFrontendIpConfigurations(d *pluginsdk.ResourceData
...
+			}
+		}
+
+		if availabilityZones, ok := d.GetOk(fmt.Sprintf("frontend_ip_configuration.%d.availability_zone", index)); ok {
+			zonesSet = true
+			switch availabilityZones.(string) {
+			case "1", "2", "3":
+				zones = &[]string{availabilityZones.(string)}
+			case "Zone-Redundant":
+				zones = &[]string{"1", "2"}
```
Comment (WodansSon) [inline azurerm/internal/services/loadbalancer/loadbalancer_resource.go:417]: The acceptance tests are failing with `frontendIPConfigurations has 2 zones specified. Only one zone can be specified for this resource`. So we should only set a single zone here?
```suggestion
				zones = &[]string{"2"}
```

**Review by WodansSon — CHANGES_REQUESTED** [review]
@ms-henglu, it looks like loadbalancers only support a single zone due to the error msg that is returned via the acceptance tests. Should we change the default behavior?

File: azurerm/internal/services/loadbalancer/loadbalancer_resource.go [hunk 4]
```diff
@@ -352,13 +386,50 @@ func expandAzureRmLoadBalancerFrontendIpConfigurations(d *pluginsdk.ResourceData
...
 
 		name := data["name"].(string)
-		zones := azure.ExpandZones(data["zones"].([]interface{}))
+		zones := &[]string{"1", "2"}
+		zonesSet := false
+		// TODO - Remove in 3.0
+		if deprecatedZonesRaw, ok := d.GetOk(fmt.Sprintf("frontend_ip_configuration.%d.zones", index)); ok {
+			zonesSet = true
+			deprecatedZones := azure.ExpandZones(deprecatedZonesRaw.([]interface{}))
+			if deprecatedZones != nil {
```
Comment (WodansSon) [inline azurerm/internal/services/loadbalancer/loadbalancer_resource.go:406]: Should we add a len check here since it is only valid to send all zones or a single zone now?

File: azurerm/internal/services/loadbalancer/loadbalancer_resource.go [hunk 5]
```diff
@@ -352,13 +386,50 @@ func expandAzureRmLoadBalancerFrontendIpConfigurations(d *pluginsdk.ResourceData
...
+				return nil, fmt.Errorf("Availability Zones are not available on the `Basic` SKU")
+			}
+			zones = &[]string{}
+		} else if !subnetSet {
+			if zonesSet && len(*zones) > 0 {
+				return nil, fmt.Errorf("Networking supports zones only for frontendIpconfigurations which reference a subnet.")
+			}
+			zones = &[]string{}
+		}
 		frontEndConfig := network.FrontendIPConfiguration{
```
Comment (WodansSon) [inline azurerm/internal/services/loadbalancer/loadbalancer_resource.go:433]: Should we add a len check here since it is only valid to send all zones or a single zone now? If we detect that two zones have been defined we should return an error saying that `two zones have been specified, only one zone or all three zones can be specified for this resource.` We should also make sure that the passed strings are not duplicates of each other (e.g. block the user from passing "2", "2", "2").

Comment (ms-henglu) [reply azurerm/internal/services/loadbalancer/loadbalancer_resource.go:433]: > two zones have been specified, only one zone or all three zones can be specified for this resource

About these error, it happens when apply zones to a loadbalancer which reference a publicIp/publicIpPrefix (not a subnet)。
Availability zones should only be applied when use standard sku and reference a subnet. So I added check on sku and subnet to make sure of it, in other cases, it will be set to an empty array. So now the tests all passed.

> We should also make sure that the passed strings are not duplicates of each other (e.g. block the user from passing "2", "2", "2").

I think it's not necessary, because zones's maxItem is one.

**Review by WodansSon — APPROVED** [review]
@ms-henglu, looks like we finally got this all straightened out. Thanks for pushing the comment. LGTM! 🚀

**Comment by WodansSon** [comment]
image
