### PR TITLE
`azurerm_subnet` - fix `address_prefixes` update (1 -> 2) not take effect issue

### LINKED ISSUE #10818: Updating azurerm_subnet with ipv6 does not change the subnet to dual stack
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/azurerm v2.21.0

### Affected Resource(s)

* `azurerm_subnet`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

resource azurerm_resource_group "add-ipv6-to-subnet" {
    name = "add-ipv6-to-subnet"
    location = "eastus"
}

resource azurerm_virtual_network "add-ipv6-to-subnet" {
    name = "add-ipv6-to-subnet"
    resource_group_name = azurerm_resource_group.add-ipv6-to-subnet.name
    location = azurerm_resource_group.add-ipv6-to-subnet.location

    address_space = [
        "10.0.0.0/8",
        "2a05:f500::/56"
    ]
}

resource azurerm_subnet "add-ipv6-to-subnet" {
    name = "add-ipv6-to-subnet"
    virtual_network_name = azurerm_virtual_network.add-ipv6-to-subnet.name
    resource_group_name = azurerm_virtual_network.add-ipv6-to-subnet.resource_group_name

    # create with ipv4 only:
    # address_prefixes = ["10.0.0.0/16"]

    # update with ipv4 + ipv6:
    address_prefixes = ["10.0.0.0/16", "2a05:f500::/64"]
}
```

### Debug Output

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_subnet.add-ipv6-to-subnet will be updated in-place
  ~ resource "azurerm_subnet" "add-ipv6-to-subnet" {
      ~ address_prefixes                               = [
            "10.0.0.0/16",
          + "2a05:f500::/64",
        ]
        id                                             = "/subscriptions/XXXXXXXXXXXXX/resourceGroups/add-ipv6-to-subnet/providers/Microsoft.Network/virtualNetworks/add-ipv6-to-subnet/subnets/add-ipv6-to-subnet"
        name                                           = "add-ipv6-to-subnet"
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_subnet.add-ipv6-to-subnet: Modifying... [...]
azurerm_subnet.add-ipv6-to-subnet: Modifications complete after 1s [...]

Apply complete! Resources: 0 added, 2 changed, 0 destroyed.

✗ terraform state show azurerm_subnet.add-ipv6-to-subnet
# azurerm_subnet.add-ipv6-to-subnet:
resource "azurerm_subnet" "add-ipv6-to-subnet" {
    address_prefix                                 = "10.0.0.0/16"
    address_prefixes                               = [
        "10.0.0.0/16",      # <--- where's the ipv6 address prefix?
    ]
    ...
}
```

### Expected Behaviour

Update existing subnet with new IPv6 range.

### Actual Behaviour

Apply completes successfully, but IPv6 range is not added.

### Steps to Reproduce

1. `terraform apply`
2. Uncomment the "address_prefixes" line with two subnets. Comment the "address_prefixes" line with one subnet.
3. `terraform apply`

### References

These lines seem to be to blame:

https://github.com/terraform-providers/terraform-provider-azurerm/blob/fce3efa75eb952c34a067471f2ca9d468e25360a/azurerm/internal/services/network/subnet_resource.go#L285

### PR DESCRIPTION
**Pull request by magodo**
Fixes #10818.

This issue is caused by setting both `addressPrefixes` (two items) and `addressPrefix` (one item) in the request, in which case the service get confused and current behavior is only takes the `addressPrefix` into consideration.
In this case, meaning updating the amount of prefixes from 1 to N, we should ensure we only set the `addressPrefixes` and clear the `addressPrefix`.

### CODE REVIEW

File: azurerm/internal/services/network/subnet_resource.go [hunk 1]
```diff
@@ -69,6 +69,7 @@ func resourceSubnet() *schema.Resource {
 				Type:     schema.TypeList,
 				Optional: true,
 				Computed: true,
+				MinItems: 1,
```
Comment (tombuildsstuff) [inline azurerm/internal/services/network/subnet_resource.go:72]: alternatively we could make this and the `address_prefix` field uncomputed, set `address_prefix` to an empty value and then push people across - ignoring the value for this older field, since this has been superseded for a while now?

File: azurerm/internal/services/network/subnet_resource_test.go [hunk 2]
```diff
@@ -47,6 +47,50 @@ func TestAccSubnet_basic_addressPrefixes(t *testing.T) {
...
+	data.ResourceTest(t, r, []resource.TestStep{
+		{
+			Config: r.complete_addressPrefixes(data),
+			Check: resource.ComposeTestCheckFunc(
+				check.That(data.ResourceName).ExistsInAzure(r),
+			),
+		},
+		data.ImportStep(),
+	})
+}
```
Comment (tombuildsstuff) [inline azurerm/internal/services/network/subnet_resource_test.go:63]: this test is superfluous since it's included in the first step below?

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
hey @magodo 

Thanks for this PR - taking a look through here at this point the `address_prefixes` field should always have a value, so perhaps it's worth making the older `address_prefix` field un-computed and pushing people across to this new field (since it's been populated at this point) and just using the value of `address_prefixes` - WDYT?

Thanks!

File: azurerm/internal/services/network/subnet_resource.go (hunk 1 above)
Comment (magodo) [reply azurerm/internal/services/network/subnet_resource.go:72]: Perhaps we'd better do this when bumping towards 3.0 as it still might break some existing configs?

File: azurerm/internal/services/network/subnet_resource_test.go (hunk 2 above)
Comment (magodo) [reply azurerm/internal/services/network/subnet_resource_test.go:63]: This is for the sake of completeness and self-contained test.

File: azurerm/internal/services/network/subnet_resource.go (hunk 1 above)
Comment (katbyte) [reply azurerm/internal/services/network/subnet_resource.go:72]: its only been superseded for a couple of releases i think

**Comment by magodo** [comment]
@tombuildsstuff Is there anything I can do to make this merged?

**Review by katbyte — APPROVED** [review]
LGTM 👍
