### PR TITLE
azurerm_security_center_contact - override SDK creation function to handle `201` response code

### LINKED ISSUE #8317: azurerm_security_center_contact return error with status code 201
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
terraform v0.13.0
azurerm v2.24.0
````

### Affected Resource(s)

* `azurerm_security_center_contact`

### Terraform Configuration Files

```hcl
resource "azurerm_security_center_contact" "contact" {
  email                = var.security_settings.security_center.contact.email
  phone                = var.security_settings.security_center.contact.phone 
  alert_notifications  = var.security_settings.security_center.alert_notifications
  alerts_to_admins     = var.security_settings.security_center.alerts_to_admins
}
```

### Debug Output
```
Error creating Security Center Contact: security.ContactsClient#Create: Failure responding to request: StatusCode=201 
-- Original Error: autorest/azure: Service returned an error. Status=201 Code="Unknown" Message="Unknown service error"
Details=[
  {
    "etag":"\"11111111-1111-1111-1111-111111111111\"",
    "id":"/subscriptions/XXXXXXXX-XXXX-XXXX-XXXXXXXXXX/providers/Microsoft.Security/securityContact/default1",
    "location":"West Europe","name":"default1","properties": 
    {
        "alertNotifications":"On",
        "alertsToAdmins":"On",
        "email":"xxxxx.xxxxx@domain.com",
        "phone":"+33628345678"
    },
    "type":"Microsoft.Security/securityContact"
}]
```

### Panic Output

No panic

### Expected Behavior

Contact is created

### Actual Behavior

Contact is created but apply failed

### Steps to Reproduce

1. `terraform apply`

### PR DESCRIPTION
**Pull request by beandrad**
This allows to create a new security center contact.

The current issue is that the Azure Rest API may return a 201 upon resource
creation, however, the API specs don't include this status code as
successful, which causes the corresponding method from the Azure Go SDK
to return an error.

Fixes #8317

### CODE REVIEW

File: azurerm/internal/services/securitycenter/azuresdkhacks/security_center_contact.go [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+	if tracing.IsEnabled() {
+		ctx = tracing.StartSpan(ctx, fqdn+"/ContactsClient.Create")
+		defer func() {
+			sc := -1
+			if result.Response.Response != nil {
+				sc = result.Response.Response.StatusCode
+			}
+			tracing.EndSpan(ctx, sc, err)
+		}()
+	}
```
Comment (tombuildsstuff) [inline azurerm/internal/services/securitycenter/azuresdkhacks/security_center_contact.go:27]: can we remove the tracing here? we don't need it, so we can avoid the import here

File: azurerm/internal/services/securitycenter/resource_arm_security_center_contact.go [hunk 2]
```diff
@@ -104,7 +105,7 @@ func resourceArmSecurityCenterContactCreateUpdate(d *schema.ResourceData, meta i
 	}
 
 	if d.IsNewResource() {
-		if _, err := client.Create(ctx, name, contact); err != nil {
+		if _, err := azuresdkhacks.CreateSecurityCenterContact(client, ctx, name, contact); err != nil {
```
Comment (tombuildsstuff) [inline azurerm/internal/services/securitycenter/resource_arm_security_center_contact.go:108]: can we add a reference to the issue here so we know when this can be switched back:

```suggestion
		// TODO: switch back when the Swagger/API bug has been fixed: https://github.com/Azure/azure-rest-api-specs/issues/10717 (an undefined 201)
		if _, err := azuresdkhacks.CreateSecurityCenterContact(client, ctx, name, contact); err != nil {
```

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
hey @beandrad 

Thanks for this PR :)

Taking a look through this is looking good, if we can fix up a couple of minor comments then this otherwise LGTM 👍 

Thanks!

**Comment by beandrad** [comment]
@tombuildsstuff thanks for reviewing! changes made!

File: go.mod [hunk 3]
```diff
@@ -2,8 +2,9 @@ module github.com/terraform-providers/terraform-provider-azurerm
 
 require (
 	github.com/Azure/azure-sdk-for-go v46.4.0+incompatible
-	github.com/Azure/go-autorest/autorest v0.11.10
+	github.com/Azure/go-autorest/autorest v0.11.3
 	github.com/Azure/go-autorest/autorest/date v0.3.0
+	github.com/Azure/go-autorest/autorest/validation v0.3.0
```
Comment (tombuildsstuff) [inline go.mod:7]: Can we rebase this branch/revert these and re-run `go mod vendor && go mod tidy` - which should re-upgrade these? This is necessary since it fixes a potential security vulnerability in the Azure SDK/go-autorest

**Review by tombuildsstuff — COMMENTED** [review]
hey @beandrad 

Thanks for pushing those changes - if we can rebase this and update the vendoring then this otherwise LGTM 👍

**Review by tombuildsstuff — APPROVED** [review]
LGTM - thanks for pushing those changes @beandrad
