### PR TITLE
[azurerm_recovery_services_protected_vm] - changing `backup_policy_id` no longer forces a new resource

### LINKED ISSUE #3441: Changing a backup policy on a VM deletes existing backup(s)
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
terraform -v
Terraform v0.11.13
+ provider.azurerm v1.27.1
```

### Affected Resource(s)

* `azurerm_recovery_services_protected_vm`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name     = "rg-demo-backup"
  location = "australiasoutheast"
}

resource "azurerm_recovery_services_vault" "rsv" {
  name                = "rsv-demo"
  location            = "${azurerm_resource_group.rg.location}"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  sku                 = "Standard"
}

resource "azurerm_recovery_services_protection_policy_vm" "daily_standard" {
  name                = "daily-standard"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  recovery_vault_name = "${azurerm_recovery_services_vault.rsv.name}"

  timezone = "AUS Eastern Standard Time"

  backup {
    frequency = "Daily"

    time = "00:00"
  }

  retention_daily {
    count = "7"
  }

  retention_weekly {
    weekdays = ["Sunday"]
    count    = 5
  }

  retention_monthly {
    weekdays = ["Sunday"]
    weeks    = ["First"]
    count    = 13
  }
}

resource "azurerm_recovery_services_protection_policy_vm" "weekly_standard" {
  name                = "weekly-standard"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  recovery_vault_name = "${azurerm_recovery_services_vault.rsv.name}"

  timezone = "AUS Eastern Standard Time"

  backup {
    frequency = "Weekly"
    time      = "00:00"
    weekdays  = ["Sunday"]
  }

  retention_weekly {
    weekdays = ["Sunday"]
    count    = "13"
  }

  retention_monthly {
    weekdays = ["Sunday"]
    weeks    = ["First"]
    count    = 13
  }

  retention_yearly {
    weekdays = ["Sunday"]
    months   = ["January"]
    weeks    = ["First"]
    count    = "1"
  }
}

data "azurerm_subnet" "main" {
  name                 = "SomeSubnet"
  resource_group_name  = "rg-demo-backup"
  virtual_network_name = "SomeVNet"
}

resource "azurerm_network_interface" "nic" {
  name                = "demovm-nic"
  location            = "${azurerm_resource_group.rg.location}"
  resource_group_name = "${azurerm_resource_group.rg.name}"

  ip_configuration {
    name                          = "config"
    subnet_id                     = "${data.azurerm_subnet.main.id}"
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_virtual_machine" "vm" {
  name                  = "demovm"
  location              = "${azurerm_resource_group.rg.location}"
  resource_group_name   = "${azurerm_resource_group.rg.name}"
  vm_size               = "Standard_DS1_v2"
  network_interface_ids = ["${azurerm_network_interface.nic.id}"]

  delete_os_disk_on_termination = true
  delete_data_disks_on_termination = true

  storage_image_reference {
    version   = "latest"
    offer     = "CentOS"
    publisher = "OpenLogic"
    sku       = "7.5"
  }

  storage_os_disk {
    name              = "demovm-OS"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }

  os_profile {
    computer_name  = "demovm"
    admin_username = "josh"
    admin_password = "SuperS3cr3t!"
  }

  os_profile_linux_config {
    disable_password_authentication = false
  }
}

resource "azurerm_recovery_services_protected_vm" "protect_vm" {
  resource_group_name = "${azurerm_resource_group.rg.name}"
  recovery_vault_name = "${azurerm_recovery_services_vault.rsv.name}"
  source_vm_id        = "${azurerm_virtual_machine.vm.id}"

  backup_policy_id = "${azurerm_recovery_services_protection_policy_vm.weekly_standard.id}"
}
```

### Expected Behavior

When I change a backup policy on a VM, I would expect that the configuration changes and all the existing backups are retained.

### Actual Behavior

The backups are actually deleted.

### Steps to Reproduce

1. `terraform apply`
1. Change 
    ```hcl
    resource "azurerm_recovery_services_protected_vm" "protect_vm" {
      resource_group_name = "${azurerm_resource_group.rg.name}"
      recovery_vault_name = "${azurerm_recovery_services_vault.rsv.name}"
      source_vm_id        = "${azurerm_virtual_machine.vm.id}"
    
      backup_policy_id = "${azurerm_recovery_services_protection_policy_vm.weekly_standard.id}"
    }
    ```

    to

    ```hcl
    resource "azurerm_recovery_services_protected_vm" "protect_vm" {
      resource_group_name = "${azurerm_resource_group.rg.name}"
      recovery_vault_name = "${azurerm_recovery_services_vault.rsv.name}"
      source_vm_id        = "${azurerm_virtual_machine.vm.id}"
    
      backup_policy_id = "${azurerm_recovery_services_protection_policy_vm.daily_standard.id}"
    }
    ```

1. `terraform apply`
    Note: This may fail, but rerunning `terraform apply` should fix it

### References

* I've noticed that `terraform apply` **deletes** and **creates** a new backup policy link, instead of updating in place.
```bash
terraform apply
...
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

-/+ azurerm_recovery_services_protected_vm.protect_vm (new resource required)
      id:                  "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-demo-backup/providers/Microsoft.RecoveryServices/vaults/rsv-demo/backupFabrics/Azure/protectionContainers/IaasVMContainer;iaasvmcontainerv2;rg-demo-backup;demovm/protectedItems/VM;iaasvmcontainerv2;rg-demo-backup;demovm" => <computed> (forces new resource)
      backup_policy_id:    "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-demo-backup/providers/Microsoft.RecoveryServices/vaults/rsv-demo/backupPolicies/weekly-standard" => "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-demo-backup/providers/Microsoft.RecoveryServices/vaults/rsv-demo/backupPolicies/daily-standard" (forces new resource)
      recovery_vault_name: "rsv-demo" => "rsv-demo"
      resource_group_name: "rg-demo-backup" => "rg-demo-backup"
      source_vm_id:        "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-demo-backup/providers/Microsoft.Compute/virtualMachines/demovm" => "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-demo-backup/providers/Microsoft.Compute/virtualMachines/demovm"
      tags.%:              "0" => <computed>


Plan: 1 to add, 0 to change, 1 to destroy.
```

* Azure Portal showing backups being deleted and in this case, the configuration failed.

Azure Portal - backup jobs after terraform apply

* I reran `terraform apply`, and it was fixed.

Azure Portal - backups configured

### PR DESCRIPTION
**Pull request by hashitop**
Refer to #3441 now changing the behaviour of **backup_policy_id** so it should not trigger recreation of resource when value changed

(fixes #3441)

### CODE REVIEW

**Comment by hashitop** [comment]
Hi @katbyte 

As you reminded me about that I went for further testing and found the **destroy** operation is erratic and **always** failed on first attempt once updated the **backup_policy_id**, a rerun seems to fix it. I may need some more time to debug the **destroy** scenario. Thanks!

**Comment by katbyte** [comment]
Cool, thanks for the update @hashitop 🙂

**Comment by hashitop** [comment]
Hi @katbyte 

This would be a piece of information in relation to the commit for adding test case and a minor fix on top of previous commit so please have another review

The issue with **destroy** appeared to be related to the state of **azurerm_recovery_services_protection_policy_vm** resource went **out-of-sync**. 

The cause of the glitch in the state was due to a bug or may be a strange symptom in Azure API, checked the go sdk part and it looks ok. 

The trace logs below captured from when the change made to the resource and then read back the status from the same resource where it showed the discrepancy. It's ended up adding a slight delay prior to sending out next subsequent GET API request solved this strange symptom.

- Update backup policy id to `daily-standard-test14`, transaction was successful and the data put up to azure management server was good as per the highlight at the `policyId`

2019-07-13T02:38:29.288+1000 [DEBUG] plugin.terraform-provider-azurerm: 2019/07/13 02:38:29 =============================================
2019-07-13T02:38:29.288+1000 [DEBUG] plugin.terraform-provider-azurerm: 2019/07/13 02:38:29 668
2019-07-13T02:38:29.288+1000 [DEBUG] plugin.terraform-provider-azurerm: 2019/07/13 02:38:29 {"properties":{"friendlyName":"demovm-test14",**"policyId":"/subscriptions/xxxxx-xxx-xxx-xxxx-xxxxx/resourceGroups/rg-demo-backup-test14/providers/Microsoft.RecoveryServices/vaults/rsv-demo-test14/backupPolicies/daily-standard-test14"**,"protectedItemType":"Microsoft.Compute/virtualMachines","sourceResourceId":"/subscriptions/xxxxx-xxx-xxx-xxxx-xxxxx/resourceGroups/rg-demo-backup-test14/providers/Microsoft.Compute/virtualMachines/demovm-test14","virtualMachineId":"/subscriptions/xxxxx-xxx-xxx-xxxx-xxxxx/resourceGroups/rg-demo-backup-test14/providers/Microsoft.Compute/virtualMachines/demovm-test14","workloadType":"VM"},"tags":{}}
2019-07-13T02:38:29.288+1000 [DEBUG] plugin.terraform-provider-azurerm: 2019/07/13 02:38:29 =============================================
2019-07-13T02:38:29.288+1000 [DEBUG] plugin.terraform-provider-azurerm: 2019/07/13 02:38:29 ============================================
2019-07-13T02:38:29.288+1000 [DEBUG] plugin.terraform-provider-azurerm: 2019/07/13 02:38:29 api-version=2016-12-01
2019-07-13T02:38:29.288+1000 [DEBUG] plugin.terraform-provider-azurerm: 2019/07/13 02:38:29 ============================================
2019-07-13T02:38:29.288+1000 [DEBUG] plugin.terraform-provider-azurerm: 2019/07/13 02:38:29 [DEBUG] AzureRM Request:
2019-07-13T02:38:29.288+1000 [DEBUG] plugin.terraform-provider-azurerm: PUT /Subscriptions/xxxxx-xxx-xxx-xxxx-xxxxx/resourceGroups/rg-demo-backup-test14/providers/Microsoft.RecoveryServices/vaults/rsv-demo-test14/backupFabrics/Azure/protectionContainers/iaasvmcontainer%3Biaasvmcontainerv2%3Brg-demo-backup-test14%3Bdemovm-test14/protectedItems/VM%3Biaasvmcontainerv2%3Brg-demo-backup-test14%3Bdemovm-test14?api-version=2016-12-01 HTTP/1.1
2019-07-13T02:38:29.288+1000 [DEBUG] plugin.terraform-provider-azurerm: Host: management.azure.com
2019-07-13T02:38:29.288+1000 [DEBUG] plugin.terraform-provider-azurerm: User-Agent: Go/go1.12.5 (amd64-darwin) go-autorest/v12.2.0 Azure-SDK-For-Go/v31.0.0 backup/2017-07-01 Terraform/0.12.0 terraform-provider-azurerm/dev
2019-07-13T02:38:29.288+1000 [DEBUG] plugin.terraform-provider-azurerm: Content-Length: 668
2019-07-13T02:38:29.288+1000 [DEBUG] plugin.terraform-provider-azurerm: Content-Type: application/json; charset=utf-8
2019-07-13T02:38:29.288+1000 [DEBUG] plugin.terraform-provider-azurerm: X-Ms-Correlation-Request-Id: d3f0a808-a3fe-7cd8-3620-38f81a4cd86d
2019-07-13T02:38:29.288+1000 [DEBUG] plugin.terraform-provider-azurerm: Accept-Encoding: gzip
2019-07-13T02:38:29.288+1000 [DEBUG] plugin.terraform-provider-azurerm: 
2019-07-13T02:38:31.021+1000 [DEBUG] plugin.terraform-provider-azurerm: 2019/07/13 02:38:31 [DEBUG] AzureRM Response for https://management.azure.com/Subscriptions/xxxxx-xxx-xxx-xxxx-xxxxx/resourceGroups/rg-demo-backup-test14/providers/Microsoft.RecoveryServices/vaults/rsv-demo-test14/backupFabrics/Azure/protectionContainers/iaasvmcontainer%3Biaasvmcontainerv2%3Brg-demo-backup-test14%3Bdemovm-test14/protectedItems/VM%3Biaasvmcontainerv2%3Brg-demo-backup-test14%3Bdemovm-test14?api-version=2016-12-01:
2019-07-13T02:38:31.021+1000 [DEBUG] plugin.terraform-provider-azurerm: HTTP/2.0 202 Accepted
2019-07-13T02:38:31.021+1000 [DEBUG] plugin.terraform-provider-azurerm: Content-Length: 0
2019-07-13T02:38:31.021+1000 [DEBUG] plugin.terraform-provider-azurerm: Azure-Asyncoperation: https://management.azure.com/Subscriptions/xxxxx-xxx-xxx-xxxx-xxxxx/resourceGroups/rg-demo-backup-test14/providers/Microsoft.RecoveryServices/vaults/rsv-demo-test14/backupFabrics/Azure/protectionContainers/iaasvmcontainer;iaasvmcontainerv2;rg-demo-backup-test14;demovm-test14/protectedItems/VM;iaasvmcontainerv2;rg-demo-backup-test14;demovm-test14/operationsStatus/03b84392-7619-4227-b5ab-9b674aced3c5?api-version=2016-12-01
2019-07-13T02:38:31.021+1000 [DEBUG] plugin.terraform-provider-azurerm: Cache-Control: no-cache
2019-07-13T02:38:31.021+1000 [DEBUG] plugin.terraform-provider-azurerm: Date: Fri, 12 Jul 2019 16:38:30 GMT
2019-07-13T02:38:31.021+1000 [DEBUG] plugin.terraform-provider-azurerm: Expires: -1
2019-07-13T02:38:31.021+1000 [DEBUG] plugin.terraform-provider-azurerm: Location: https://management.azure.com/Subscriptions/xxxxx-xxx-xxx-xxxx-xxxxx/resourceGroups/rg-demo-backup-test14/providers/Microsoft.RecoveryServices/vaults/rsv-demo-test14/backupFabrics/Azure/protectionContainers/iaasvmcontainer;iaasvmcontainerv2;rg-demo-backup-test14;demovm-test14/protectedItems/VM;iaasvmcontainerv2;rg-demo-backup-test14;demovm-test14/operationResults/03b84392-7619-4227-b5ab-9b674aced3c5?api-version=2016-12-01
2019-07-13T02:38:31.021+1000 [DEBUG] plugin.terraform-provider-azurerm: Pragma: no-cache
2019-07-13T02:38:31.021+1000 [DEBUG] plugin.terraform-provider-azurerm: Retry-After: 60
2019-07-13T02:38:31.021+1000 [DEBUG] plugin.terraform-provider-azurerm: Strict-Transport-Security: max-age=31536000; includeSubDomains
2019-07-13T02:38:31.021+1000 [DEBUG] plugin.terraform-provider-azurerm: X-Content-Type-Options: nosniff
2019-07-13T02:38:31.022+1000 [DEBUG] plugin.terraform-provider-azurerm: X-Ms-Client-Request-Id: 247323da-c428-4a13-bf28-4f0a12d48d5a
2019-07-13T02:38:31.022+1000 [DEBUG] plugin.terraform-provider-azurerm: X-Ms-Client-Request-Id: 247323da-c428-4a13-bf28-4f0a12d48d5a
2019-07-13T02:38:31.022+1000 [DEBUG] plugin.terraform-provider-azurerm: X-Ms-Correlation-Request-Id: d3f0a808-a3fe-7cd8-3620-38f81a4cd86d
2019-07-13T02:38:31.022+1000 [DEBUG] plugin.terraform-provider-azurerm: X-Ms-Ratelimit-Remaining-Subscription-Writes: 1199
2019-07-13T02:38:31.022+1000 [DEBUG] plugin.terraform-provider-azurerm: X-Ms-Request-Id: d3f0a808-a3fe-7cd8-3620-38f81a4cd86d
2019-07-13T02:38:31.022+1000 [DEBUG] plugin.terraform-provider-azurerm: X-Ms-Routing-Request-Id: AUSTRALIAEAST:20190712T163831Z:3ee5e693-23e7-4378-b74c-a637dad7d384
2019-07-13T02:38:31.022+1000 [DEBUG] plugin.terraform-provider-azurerm: X-Powered-By: ASP.NET
2019-07-13T02:38:31.022+1000 [DEBUG] plugin.terraform-provider-azurerm: 
2019-07-13T02:38:31.022+1000 [DEBUG] plugin.terraform-provider-azurerm: 
2019-07-13T02:38:31.022+1000 [DEBUG] plugin.terraform-provider-azurerm: 2019/07/13 02:38:31 [DEBUG] Waiting for state to become: [Found]


- Read back the status of updated policy id. The `backup_policy_id` was still on `weekly-standard-test14`, at this point the UI shows correct policy id which is `daily-standard-test14` caused the discrepancy between Terraform state and the actual state of backend resource hence causing failure at the **destroy** operation

2019-07-13T02:38:41.363+1000 [DEBUG] plugin.terraform-provider-azurerm: GET /Subscriptions/xxxxx-xxx-xxx-xxxx-xxxxx/resourceGroups/rg-demo-backup-test14/providers/Microsoft.RecoveryServices/vaults/rsv-demo-test14/backupFabrics/Azure/protectionContainers/IaasVMContainer%3Biaasvmcontainerv2%3Brg-demo-backup-test14%3Bdemovm-test14/protectedItems/VM%3Biaasvmcontainerv2%3Brg-demo-backup-test14%3Bdemovm-test14?api-version=2016-12-01 HTTP/1.1
2019-07-13T02:38:41.363+1000 [DEBUG] plugin.terraform-provider-azurerm: Host: management.azure.com
2019-07-13T02:38:41.363+1000 [DEBUG] plugin.terraform-provider-azurerm: User-Agent: Go/go1.12.5 (amd64-darwin) go-autorest/v12.2.0 Azure-SDK-For-Go/v31.0.0 backup/2017-07-01 Terraform/0.12.0 terraform-provider-azurerm/dev
2019-07-13T02:38:41.363+1000 [DEBUG] plugin.terraform-provider-azurerm: X-Ms-Correlation-Request-Id: d3f0a808-a3fe-7cd8-3620-38f81a4cd86d
2019-07-13T02:38:41.363+1000 [DEBUG] plugin.terraform-provider-azurerm: Accept-Encoding: gzip
2019-07-13T02:38:41.363+1000 [DEBUG] plugin.terraform-provider-azurerm: 
2019-07-13T02:38:41.363+1000 [DEBUG] plugin.terraform-provider-azurerm: 
2019/07/13 02:38:41 [TRACE] dag/walk: vertex "provider.azurerm (close)", waiting for: "azurerm_recovery_services_protected_vm.protect_vm"
2019/07/13 02:38:41 [TRACE] dag/walk: vertex "meta.count-boundary (count boundary fixup)", waiting for: "azurerm_recovery_services_protected_vm.protect_vm"
2019/07/13 02:38:41 [TRACE] dag/walk: vertex "root", waiting for: "meta.count-boundary (count boundary fixup)"
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: 2019/07/13 02:38:41 [DEBUG] AzureRM Response for https://management.azure.com/Subscriptions/xxxxx-xxx-xxx-xxxx-xxxxx/resourceGroups/rg-demo-backup-test14/providers/Microsoft.RecoveryServices/vaults/rsv-demo-test14/backupFabrics/Azure/protectionContainers/IaasVMContainer%3Biaasvmcontainerv2%3Brg-demo-backup-test14%3Bdemovm-test14/protectedItems/VM%3Biaasvmcontainerv2%3Brg-demo-backup-test14%3Bdemovm-test14?api-version=2016-12-01:
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: HTTP/2.0 200 OK
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: Cache-Control: no-cache
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: Content-Type: application/json
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: Date: Fri, 12 Jul 2019 16:38:41 GMT
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: Expires: -1
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: Pragma: no-cache
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: Server: Microsoft-IIS/10.0
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: Strict-Transport-Security: max-age=31536000; includeSubDomains
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: Vary: Accept-Encoding
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: X-Content-Type-Options: nosniff
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: X-Ms-Client-Request-Id: xxxxx-xxx-xxx-xxxx-xxxxx
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: X-Ms-Client-Request-Id: xxxxx-xxx-xxx-xxxx-xxxxx
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: X-Ms-Correlation-Request-Id: d3f0a808-a3fe-7cd8-3620-38f81a4cd86d
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: X-Ms-Ratelimit-Remaining-Subscription-Reads: 11996
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: X-Ms-Request-Id: d3f0a808-a3fe-7cd8-3620-38f81a4cd86d
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: X-Ms-Routing-Request-Id: AUSTRALIAEAST:20190712T163841Z:140d41fa-b20a-4db7-9ce3-078f144be5ef
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: X-Powered-By: ASP.NET
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: 
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: 2019/07/13 02:38:41 ============================================
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: 2019/07/13 02:38:41 &{200 OK 200 HTTP/2.0 2 0 map[Cache-Control:[no-cache] Content-Type:[application/json] Date:[Fri, 12 Jul 2019 16:38:41 GMT] Expires:[-1] Pragma:[no-cache] Server:[Microsoft-IIS/10.0] Strict-Transport-Security:[max-age=31536000; includeSubDomains] Vary:[Accept-Encoding] X-Content-Type-Options:[nosniff] X-Ms-Client-Request-Id:[xxxxx-xxx-xxx-xxxx-xxxxx xxxxx-xxx-xxx-xxxx-xxxxx] X-Ms-Correlation-Request-Id:[d3f0a808-a3fe-7cd8-3620-38f81a4cd86d] X-Ms-Ratelimit-Remaining-Subscription-Reads:[11996] X-Ms-Request-Id:[d3f0a808-a3fe-7cd8-3620-38f81a4cd86d] X-Ms-Routing-Request-Id:[AUSTRALIAEAST:20190712T163841Z:140d41fa-b20a-4db7-9ce3-078f144be5ef] X-Powered-By:[ASP.NET]] {{"id":"/Subscriptions/xxxxx-xxx-xxx-xxxx-xxxxx/resourceGroups/rg-demo-backup-test14/providers/Microsoft.RecoveryServices/vaults/rsv-demo-test14/backupFabrics/Azure/protectionContainers/IaasVMContainer;iaasvmcontainerv2;rg-demo-backup-test14;demovm-test14/protectedItems/VM;iaasvmcontainerv2;rg-demo-backup-test14;demovm-test14","name":"VM;iaasvmcontainerv2;rg-demo-backup-test14;demovm-test14","type":"Microsoft.RecoveryServices/vaults/backupFabrics/protectionContainers/protectedItems","properties":{"friendlyName":"demovm-test14","virtualMachineId":"/subscriptions/xxxxx-xxx-xxx-xxxx-xxxxx/resourceGroups/rg-demo-backup-test14/providers/Microsoft.Compute/virtualMachines/demovm-test14","protectionStatus":"Healthy","protectionState":"IRPending","healthStatus":"Passed","lastBackupStatus":"","lastBackupTime":"2001-01-01T00:00:00Z","protectedItemDataId":"4737821993818295480","protectedItemType":"Microsoft.Compute/virtualMachines","backupManagementType":"AzureIaasVM","workloadType":"VM","containerName":"iaasvmcontainerv2;rg-demo-backup-test14;demovm-test14","sourceResourceId":"/subscriptions/xxxxx-xxx-xxx-xxxx-xxxxx/resourceGroups/rg-demo-backup-test14/providers/Microsoft.Compute/virtualMachines/demovm-test14",**"policyId":"/Subscriptions/xxxxx-xxx-xxx-xxxx-xxxxx/resourceGroups/rg-demo-backup-test14/providers/Microsoft.RecoveryServices/vaults/rsv-demo-test14/backupPolicies/weekly-standard-test14"**,"policyName":"weekly-standard-test14"}}} -1 [] false true map[] 0xc0003f2000 0xc000448580}
2019-07-13T02:38:41.666+1000 [DEBUG] plugin.terraform-provider-azurerm: 2019/07/13 02:38:41 ============================================

File: azurerm/resource_arm_recovery_services_protected_vm.go [hunk 1]
```diff
@@ -117,11 +117,17 @@ func resourceArmRecoveryServicesProtectedVmCreateUpdate(d *schema.ResourceData,
 	if _, err = client.CreateOrUpdate(ctx, vaultName, resourceGroup, "Azure", containerName, protectedItemName, item); err != nil {
 		return fmt.Errorf("Error creating/updating Recovery Service Protected VM %q (Resource Group %q): %+v", protectedItemName, resourceGroup, err)
 	}
+	// Due to issue reported in PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/3822
+	// Azure API, at the time, returned invalid state of the resource when backup_policy_id is updated
+	// Adding a graceful 15 seconds delay prior to the next call to Azure management seem to allow the API to correct itself
+	// and report back the correct status
+	time.Sleep(15 * time.Second)
```
Comment (katbyte) [inline azurerm/resource_arm_recovery_services_protected_vm.go]: While this works, sleeping can be fraught with uncertainty as its hard to know exactly how long to wait. We should use a `WaitForState` call here instead.

Comment (hashitop) [reply azurerm/resource_arm_recovery_services_protected_vm.go]: I have noted this block below in the method and the trace log in the previous comment was generated with the method `resourceArmRecoveryServicesProtectedVmWaitForState` executed which I believed `WaitForState` was also part of the method call.

The second part of the trace log in previous comment was from the method `resourceArmRecoveryServicesProtectedVmRead` yet it still showed incorrect status.

I have also observed a GET call, which is from `resourceArmRecoveryServicesProtectedVmWaitForState`, prior to state read and yet to see anything wrong with it hence my assumption was around a bug in Azure API or some strange symptom on how it responses to subsequent API request in a very short interval, perhaps with this particular type of resource. I may try to find another way without asking Azure to fix the issue but quite doubtful if it will work without adding a delay.

```
	if _, err = client.CreateOrUpdate(ctx, vaultName, resourceGroup, "Azure", containerName, protectedItemName, item); err != nil {
		return fmt.Errorf("Error creating/updating Recovery Service Protected VM %q (Resource Group %q): %+v", protectedItemName, resourceGroup, err)
	}
	// Due to issue reported in PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/3822
	// Azure API, at the time, returned invalid state of the resource when backup_policy_id is updated
	// Adding a graceful 15 seconds delay prior to the next call to Azure management seem to allow the API to correct itself
	// and report back the correct status
	time.Sleep(15 * time.Second)

	resp, err := resourceArmRecoveryServicesProtectedVmWaitForState(client, ctx, true, vaultName, resourceGroup, containerName, protectedItemName)
	if err != nil {
		return err
	}

	id := strings.Replace(*resp.ID, "Subscriptions", "subscriptions", 1)
	d.SetId(id)

	return resourceArmRecoveryServicesProtectedVmRead(d, meta)

```

Comment (hashitop) [reply azurerm/resource_arm_recovery_services_protected_vm.go]: I guess i understand a bit more about this when I had another quick look at the results
When updating `backup_policy_id`, it does not recreate any new resource so `resourceArmRecoveryServicesProtectedVmWaitForState` seems to return very fast with `Found` as the resource already exist but the response from Azure API is not fast enough to refresh the status from its actual backend data so it returned back with old attributes of the resource. I am looking to have another version of `resourceArmRecoveryServicesProtectedVmWaitForState` dedicated to update operation so we can compare the backup_policy_id before and after the request sent to Azure API. There should be only one attribute of the resource to compare on the update operation at this point given that only `backup_policy_id` is not `ForceNew` on change. I will submit another change for your review when I get back to update the code maybe in a day or so.

Comment (hashitop) [reply azurerm/resource_arm_recovery_services_protected_vm.go]: Hi @katbyte 

I have made change to use `StateChangeConf` instead of arbitrary wait
It is on the same shared function `resourceArmRecoveryServicesProtectedVmWaitForState` still and the behaviour is driven by additional parameters that support all Create,Update,Delete operations. I believe that the change should have no effect to Create operation but I ran a test against the whole `TestAccAzureRMRecoveryServicesProtectedVm` module regardless.

Please have another review

File: azurerm/resource_arm_recovery_services_protected_vm_test.go [hunk 2]
```diff
@@ -331,6 +379,209 @@ resource "azurerm_recovery_services_protected_vm" "test" {
...
+`, testAccAzureRMRecoveryServicesProtectedVm_withFirstPolicy(rInt, location), rInt)
+}
+
+// For update backup policy id test
+func testAccAzureRMRecoveryServicesProtectedVm_withVM(rInt int, location string) string {
+	return fmt.Sprintf(`
+%[1]s
+
+resource "azurerm_virtual_machine" "test" {
+		name                  = "acctestvm-%[2]d"
```
Comment (katbyte) [inline azurerm/resource_arm_recovery_services_protected_vm_test.go]: Could we use spaces here for consistency?

File: azurerm/resource_arm_recovery_services_protected_vm_test.go [hunk 3]
```diff
@@ -331,6 +379,209 @@ resource "azurerm_recovery_services_protected_vm" "test" {
...
+`, rInt, location, rstr[len(rstr)-5:])
+}
+
+// For update backup policy id test
+func testAccAzureRMRecoveryServicesProtectedVm_withVault(rInt int, location string) string {
+	return fmt.Sprintf(`
+%[1]s
+
+resource "azurerm_recovery_services_vault" "test" {
+		name                = "acctest-%[2]d"
```
Comment (katbyte) [inline azurerm/resource_arm_recovery_services_protected_vm_test.go]: Could we use spaces instead of tabs here for consistency?

File: azurerm/resource_arm_recovery_services_protected_vm.go [hunk 4]
```diff
@@ -54,7 +54,7 @@ func resourceArmRecoveryServicesProtectedVm() *schema.Resource {
 			"backup_policy_id": {
 				Type:         schema.TypeString,
 				Required:     true,
-				ForceNew:     true,
+				ForceNew:     false,
```
[the remark this answers is not in the document]
Comment (hashitop) [reply azurerm/resource_arm_recovery_services_protected_vm.go]: Removed, testing it now

File: azurerm/resource_arm_recovery_services_protected_vm.go [hunk 5]
```diff
@@ -118,10 +126,11 @@ func resourceArmRecoveryServicesProtectedVmCreateUpdate(d *schema.ResourceData,
 		return fmt.Errorf("Error creating/updating Recovery Service Protected VM %q (Resource Group %q): %+v", protectedItemName, resourceGroup, err)
 	}
 
-	resp, err := resourceArmRecoveryServicesProtectedVmWaitForState(client, ctx, true, vaultName, resourceGroup, containerName, protectedItemName)
+	resp, err := resourceArmRecoveryServicesProtectedVmWaitForState(client, ctx, true, vaultName, resourceGroup, containerName, protectedItemName, policyId, create)
```
[the remark this answers is not in the document]
Comment (hashitop) [reply azurerm/resource_arm_recovery_services_protected_vm.go]: Changed, testing it now

File: azurerm/resource_arm_recovery_services_protected_vm.go [hunk 6]
```diff
@@ -63,7 +63,15 @@ func resourceArmRecoveryServicesProtectedVm() *schema.Resource {
 	}
 }
 
-func resourceArmRecoveryServicesProtectedVmCreateUpdate(d *schema.ResourceData, meta interface{}) error {
+func resourceArmRecoveryServicesProtectedVmCreate(d *schema.ResourceData, meta interface{}) error {
+	return resourceArmRecoveryServicesProtectedVmCreateUpdate(d, true, meta)
```
[the remark this answers is not in the document]
Comment (hashitop) [reply azurerm/resource_arm_recovery_services_protected_vm.go]: Removed, testing it

File: azurerm/resource_arm_recovery_services_protected_vm_test.go [hunk 7]
```diff
@@ -321,7 +370,6 @@ resource "azurerm_recovery_services_protection_policy_vm" "test" {
 func testAccAzureRMRecoveryServicesProtectedVm_basic(rInt int, location string) string {
 	return fmt.Sprintf(`
 %s
-
```
[the remark this answers is not in the document]
Comment (hashitop) [reply azurerm/resource_arm_recovery_services_protected_vm_test.go]: Added

File: azurerm/resource_arm_recovery_services_protected_vm_test.go (hunk 2 above)
Comment (hashitop) [reply azurerm/resource_arm_recovery_services_protected_vm_test.go]: Converted to spaces

File: azurerm/resource_arm_recovery_services_protected_vm_test.go (hunk 3 above)
Comment (hashitop) [reply azurerm/resource_arm_recovery_services_protected_vm_test.go]: Converted to space
