### PR TITLE
r/media_services_account: tags are unsupported due to an api bug

### LINKED ISSUE #4536: Error during creating Media Service Account
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform v0.12.9
- azurerm_1.34.0

### Affected Resource(s)

`azurerm_media_services_account`

### Terraform Configuration Files

```hcl
resource "azurerm_media_services_account" "craft-search-indexer-media-services-account" {
  name                = "${var.resource_group_name}ms${var.environment}"
  location            = "${var.location}"
  resource_group_name = "${var.resource_group_name}"

  storage_account {
    id         = "${var.storage_id}"
    is_primary = true
  }
}
```

### Expected Behavior

Works without error

### Actual Behavior

Resource was created successful but got error:

```
Error setting `tags`: Invalid address to set: []string{"tags"}
```

### Steps to Reproduce

1. `terraform apply`

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Fixes #4536

### CODE REVIEW

File: azurerm/resource_arm_media_services_account.go [hunk 1]
```diff
@@ -136,7 +135,10 @@ func resourceArmMediaServicesAccountRead(d *schema.ResourceData, meta interface{
 		}
 	}
 
-	return tags.FlattenAndSet(d, resp.Tags)
+	// TODO: support Tags when this bug is fixed:
+	// https://github.com/Azure/azure-rest-api-specs/issues/5249
```
Comment (katbyte) [inline azurerm/resource_arm_media_services_account.go]: Should we add this to a deprecation message so the user knows why their tags aren't being set?
