### PR TITLE
VM: ensuring we nil-check items prior to accessing

### LINKED ISSUE #2359: terraform import azurerm_virtual_machine results in panic error
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
[coopem67@localhost bi-virtual-machines]$ terraform -v
Terraform v0.11.10
+ provider.azurerm v1.19.0
```

### Affected Resource(s)

* azurerm_virtual_machine

### Terraform Configuration Files

Please note I made my Azure subscription ID all zeros; I had the correct ID in the command I ran.
```hcl
terraform import -var-file=../storage.key -var-file=../tfvars/bi-prod.tfvars azurerm_virtual_machine.main[0] /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/BusinessIntelligence/providers/microsoft.compute/VirtualMachines/biprodintrunvm01
```

### Debug Output

[Debug gist](https://gist.githubusercontent.com/mlcooper/a753bdd928d364f595811c200ff9c1b1/raw/d67f7bdbdfcbc6e8522c346259f76ca2315deedc/gistfile1.txt)

### Panic Output

```
panic: runtime error: invalid memory address or nil pointer dereference
2018-11-19T14:14:53.080-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1cc194d]
2018-11-19T14:14:53.080-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: 
2018-11-19T14:14:53.080-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: goroutine 46 [running]:
2018-11-19T14:14:53.080-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmVirtualMachineRead(0xc000528700, 0x2156020, 0xc0005be000, 0xc000528700, 0x0)
2018-11-19T14:14:53.080-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_virtual_machine.go:732 +0x5bd
2018-11-19T14:14:53.081-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc0003878f0, 0xc0004101e0, 0x2156020, 0xc0005be000, 0xc0003aca78, 0x4c2201, 0x1dfbba0)
2018-11-19T14:14:53.081-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:352 +0x160
2018-11-19T14:14:53.081-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc00039e930, 0xc000410190, 0xc0004101e0, 0xc000588a80, 0x18, 0x7f670a9c5000)
2018-11-19T14:14:53.081-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x92
2018-11-19T14:14:53.081-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc00041dc80, 0xc000713440, 0xc0007136c0, 0x0, 0x0)
2018-11-19T14:14:53.082-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2018-11-19T14:14:53.082-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: reflect.Value.call(0xc0002d38c0, 0xc00000d160, 0x13, 0x218cf71, 0x4, 0xc000928f18, 0x3, 0x3, 0xc0004a5440, 0x532061696c617274, ...)
2018-11-19T14:14:53.082-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: 	/opt/goenv/versions/1.11.1/src/reflect/value.go:447 +0x449
2018-11-19T14:14:53.083-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: reflect.Value.Call(0xc0002d38c0, 0xc00000d160, 0x13, 0xc000800718, 0x3, 0x3, 0x6145206164616e61, 0x736557222c227473, 0x2c22322053552074)
2018-11-19T14:14:53.083-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: 	/opt/goenv/versions/1.11.1/src/reflect/value.go:308 +0xa4
2018-11-19T14:14:53.083-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: net/rpc.(*service).call(0xc0004a5740, 0xc000410f00, 0xc0003620f0, 0xc000362110, 0xc0000c6800, 0xc000123ce0, 0x1dfbb60, 0xc000713440, 0x16, 0x1dfbba0, ...)
2018-11-19T14:14:53.084-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: 	/opt/goenv/versions/1.11.1/src/net/rpc/server.go:384 +0x14e
2018-11-19T14:14:53.084-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: created by net/rpc.(*Server).ServeCodec
2018-11-19T14:14:53.084-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.19.0_x4: 	/opt/goenv/versions/1.11.1/src/net/rpc/server.go:481 +0x47e
2018/11/19 14:14:53 [ERROR] root: eval: *terraform.EvalRefresh, err: azurerm_virtual_machine.main: unexpected EOF
2018/11/19 14:14:53 [ERROR] root: eval: *terraform.EvalSequence, err: azurerm_virtual_machine.main: unexpected EOF
```

### Expected Behavior

I expected that terraform would import this first of two Azure VM's

### Actual Behavior

```
Error: azurerm_virtual_machine.main[0] (import id: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/BusinessIntelligence/providers/microsoft.compute/VirtualMachines/biprodintrunvm01): 1 error(s) occurred:

* import azurerm_virtual_machine.main[0] result: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/BusinessIntelligence/providers/microsoft.compute/VirtualMachines/biprodintrunvm01: azurerm_virtual_machine.main: unexpected EOF
```
See debug gist

### Steps to Reproduce

```hcl
terraform import -var-file=../storage.key -var-file=../tfvars/bi-prod.tfvars azurerm_virtual_machine.main[0] /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/BusinessIntelligence/providers/microsoft.compute/VirtualMachines/biprodintrunvm01
```

### Important Factoids

I'm running in `West US`.  This VM is one of two in an Azure Availability Set.  There is no auto-scaling of any type configured.

### References

* #0000

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Fixes #2359 - also adds a bunch of extra nil-checking where it made sense on the initial pass-through

Since we'll be doing some work in this area for 2.0 - this is a quick cleanup whilst passing through.

### CODE REVIEW

File: azurerm/resource_arm_virtual_machine.go [hunk 1]
```diff
@@ -721,91 +721,90 @@ func resourceArmVirtualMachineRead(d *schema.ResourceData, meta interface{}) err
...
-	if resp.VirtualMachineProperties.OsProfile != nil {
-		if err := d.Set("os_profile", schema.NewSet(resourceArmVirtualMachineStorageOsProfileHash, flattenAzureRmVirtualMachineOsProfile(resp.VirtualMachineProperties.OsProfile))); err != nil {
-			return fmt.Errorf("[DEBUG] Error setting Virtual Machine Storage OS Profile: %#v", err)
-		}
+			if osDisk := profile.OsDisk; osDisk != nil {
+				diskInfo, err := resourceArmVirtualMachineGetManagedDiskInfo(osDisk.ManagedDisk, meta)
+				if err != nil {
+					return fmt.Errorf("Error flattening `storage_os_disk`: %#v", err)
+				}
+				if err := d.Set("storage_os_disk", flattenAzureRmVirtualMachineOsDisk(osDisk, diskInfo)); err != nil {
```
Comment (jeffreyCline) [inline azurerm/resource_arm_virtual_machine.go]: I don't think that the `err` needs to be re-initialized here since it was already defined above in line 748, what do you think?

```
if err = d.Set("storage_os_disk", flattenAzureRmVirtualMachineOsDisk(osDisk, diskInfo)); err != nil {
```

File: azurerm/resource_arm_virtual_machine.go [hunk 2]
```diff
@@ -721,91 +721,90 @@ func resourceArmVirtualMachineRead(d *schema.ResourceData, meta interface{}) err
...
+			if err := d.Set("os_profile_windows_config", schema.NewSet(resourceArmVirtualMachineStorageOsProfileWindowsConfigHash, flattenAzureRmVirtualMachineOsProfileWindowsConfiguration(profile.WindowsConfiguration))); err != nil {
+				return fmt.Errorf("Error setting `os_profile_windows_config`: %+v", err)
 			}
-		}
-	}
 
-	if resp.VirtualMachineProperties.DiagnosticsProfile != nil && resp.VirtualMachineProperties.DiagnosticsProfile.BootDiagnostics != nil {
-		if err := d.Set("boot_diagnostics", flattenAzureRmVirtualMachineDiagnosticsProfile(resp.VirtualMachineProperties.DiagnosticsProfile.BootDiagnostics)); err != nil {
-			return fmt.Errorf("[DEBUG] Error setting Virtual Machine Diagnostics Profile: %#v", err)
+			if err := d.Set("os_profile_secrets", flattenAzureRmVirtualMachineOsProfileSecrets(profile.Secrets)); err != nil {
```
Comment (jeffreyCline) [inline azurerm/resource_arm_virtual_machine.go]: Same thing here, since the code was refactored the `err` object is in the same scope and doesn't need to be re-initialized in line 777, 781, and 785, shouldn't those lines be just `if err =`?

**Comment by jeffreyCline** [comment]
@tombuildsstuff the build failed with 3 test failures, but I don't think they had anything to do with your code changes, looked more like issues inside of azure to me. I will leave it to you to decide what to do here. Thanks.

File: azurerm/resource_arm_virtual_machine.go (hunk 1 above)
Comment (tombuildsstuff) [reply azurerm/resource_arm_virtual_machine.go]: whilst technically true at this point we're not reusing the variable `err` below within the inner scope - so I don't think it's a big deal either way?

File: azurerm/resource_arm_virtual_machine.go (hunk 2 above)
Comment (tombuildsstuff) [reply azurerm/resource_arm_virtual_machine.go]: (as above) since we're not using this variable below it doesn't matter this variables re-defined (since it's not going to conflict / which is why the linter isn't catching this) - so whilst we could, I don't _think_ we need to here

File: azurerm/resource_arm_virtual_machine.go (hunk 1 above)
Comment (tombuildsstuff) [reply azurerm/resource_arm_virtual_machine.go]: going to merge this either way, we can fix this up later if needed

File: azurerm/resource_arm_virtual_machine.go (hunk 2 above)
Comment (tombuildsstuff) [reply azurerm/resource_arm_virtual_machine.go]: going to merge this either way, we can fix this up later if needed

**Comment by tombuildsstuff** [comment]
Ignoring a few transitory test failures the tests pass:

screenshot 2018-12-04 at 12 52 29
