### PR TITLE
azurerm_managed_redis_geo_replication: bugfix: unable to create geo-replication group with 3 clusters or more

### LINKED ISSUE #31353: Create failure for Azure Managed Redis - Georeplicated database
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

Hi, my name is Riya from the Azure Managed Redis team. I've received a customer issue, where the user is not able to create geo-replicated database using terraform. 

Repository:
hashicorp/terraform-provider-azurerm

Description:
Problem
When creating geo-replicated Azure Redis Enterprise databases using azurerm_managed_redis followed by azurerm_managed_redis_geo_replication, the West US database creation fails with a timeout during the linking phase.

Root Cause: The Terraform provider creates databases sequentially with only self-references in [linkedDatabases](vscode-file://vscode-app/c:/Users/riyasimon/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html), causing the node agent to create standalone CRDBs. The subsequent forceLinkToReplicationGroup call cannot link these independent CRDBs, resulting in a ~10 minute timeout.

Forcelink is expected to be used to join databases to a crdb, not for creation of new crdb clusters.

Current Flow (Broken)
azurerm_managed_redis creates database with geo_replication_group_name but [linkedDatabases] contains only self
Node agent creates independent CRDB (no peer information)
azurerm_managed_redis_geo_replication calls forceLinkToReplicationGroup API
Link fails because CRDB is already created as standalone
Requested Change
Modify the Terraform Azure provider to support passing all peer database IDs during initial database creation, not just self-references.

Expected API call: https://learn.microsoft.com/en-us/rest/api/redis/redisenterprisecache/databases/create?view=rest-redis-redisenterprisecache-2025-07-01&tabs=HTTP#redisenterprisedatabasescreate-with-active-geo-replication

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.10.3

### AzureRM Provider Version

v4.56.0

### Affected Resource(s)/Data Source(s)

azurerm_managed_redis_geo_replication, azurerm_managed_redis

### Terraform Configuration Files

```hcl
# NON-SHARED MANAGED REDIS (when sharedcache == 0)
resource "azurerm_managed_redis" "managed_redis_nonshared" {
  for_each            = var.create_shared_environment.sharedcache == 0 ? { for r in var.regions : r.shortName => r } : {}
  name                = "${var.appCode}-${var.environment}-${each.key}-mr"
  resource_group_name = azurerm_resource_group.resourcegroup.name
  location            = each.value.redis_location
  sku_name            = var.redis_settings.sku_name
  high_availability_enabled = var.redis_settings.high_availability_enabled
  public_network_access = "Disabled"
 
  default_database {
    clustering_policy = var.redis_settings.clustering_policy
    eviction_policy   = var.redis_settings.eviction_policy  
    access_keys_authentication_enabled = true
    geo_replication_group_name = "${var.environment}-geo-linked"
    module {
      name = "RedisJSON"
    }
  }
 
  tags = {
    environment = var.environment
    group       = var.environmentGroup
    owner       = var.tag_owner_obx
    desk        = var.tag_desk_infrastructure
  }
}

# Geo replication group linking - only if not shared
resource "azurerm_managed_redis_geo_replication" "geo_linked" {
  count            = var.create_shared_environment.sharedcache == 0 ? 1 : 0
  managed_redis_id = azurerm_managed_redis.managed_redis_nonshared[var.regions[0].shortName].id
  
  linked_managed_redis_ids = [
    for i, r in var.regions :
    azurerm_managed_redis.managed_redis_nonshared[r.shortName].id
    if i > 0
  ]
  
  depends_on = [
    azurerm_managed_redis.managed_redis_nonshared
  ]
}

# Resource group (for testing)
resource "azurerm_resource_group" "resourcegroup" {
  name     = "${var.appCode}-${var.environment}-rg"
  location = var.regions[0].redis_location
}
```

### Debug Output/Panic Output

```shell
context deadline exceeded
│
│   with azurerm_managed_redis_geo_replication.geo_linked[0],
│
│   with azurerm_managed_redis_geo_replication.geo_linked[0],
│   on main.tf line 65, in resource "azurerm_managed_redis_geo_replication" "geo_linked":
│   65: resource "azurerm_managed_redis_geo_replication" "geo_linked" {
│   with azurerm_managed_redis_geo_replication.geo_linked[0],
│   on main.tf line 65, in resource "azurerm_managed_redis_geo_replication" "geo_linked":
│   65: resource "azurerm_managed_redis_geo_replication" "geo_linked" {
│   on main.tf line 65, in resource "azurerm_managed_redis_geo_replication" "geo_linked":
│   65: resource "azurerm_managed_redis_geo_replication" "geo_linked" {
│   65: resource "azurerm_managed_redis_geo_replication" "geo_linked" {
│
│ force link Database (Subscription: "fc2f20f5-602a-4ebd-97e6-4fae3f1f6424"
│ Resource Group Name: "myapp-test4-rg"
│ Database Name: "default"): polling after ForceLinkToReplicationGroup: context deadline exceeded
```

### Expected Behaviour

_No response_

### Actual Behaviour

_No response_

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by gerrytan**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

This PR fixes a bug in azurerm_managed_redis_geo_replication where geo-replication group with 3 or more clusters cannot be created. The bug was caused by undocumented API behaviour where force-linking can only be done against one cluster at a time, against the cluster that's not yet on the group.

To fix this, the linking and unlinking logic is updated to invoke the API iteratively until all clusters are linked.

Validation logic is also improved so that the geo-replication group member id cannot be the same as the primary id. While a CustomizeDiff validator has been added, the logic is also applied to Create and Update function because it most cases the values are not known after apply.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

https://hashicorp.teamcity.com/buildConfiguration/TF_AzureRM_AZURERM_SERVICE_PUBLIC_MANAGEDREDIS/564916

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-merging.md).

* `azurerm_managed_redis_geo_replication` - bugfix: unable to link 3 or more clusters [GH-31353]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)

Fixes #31353 

## AI Assistance Disclosure

- [ ] AI Assisted - This contribution was made by, or with the assistance of, AI/LLMs

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Comment by gerrytan** [comment]
@magodo & @ziyeqf can you please provide internal reviews for this PR. Thanks 🙏.

**Comment by ziyeqf** [comment]
LGTM! thanks @gerrytan

File: internal/services/managedredis/managed_redis_geo_replication_resource.go [hunk 1]
```diff
@@ -223,56 +242,82 @@ func (r ManagedRedisGeoReplicationResource) CustomizeDiff() sdk.ResourceFunc {
...
 
-		err = client.ForceLinkToReplicationGroupThenPoll(ctx, id, params)
+		err = client.ForceLinkToReplicationGroupThenPoll(ctx, *id, params)
 		if err != nil {
-			return fmt.Errorf("force link %s: %+v", id, err)
+			return fmt.Errorf("force link %s: %+v", *id, err)
+		}
+
+		// Workaround for race-condition bug after force-linking
+		// The API bug will be fixed in https://msazure.visualstudio.com/RedisCache/_workitems/edit/36267535
```
Comment (magodo) [inline internal/services/managedredis/managed_redis_geo_replication_resource.go]: Can we instead put another public link here, e.g. an issue in the Azure/azure-rest-api-?specs

File: internal/services/managedredis/databaselink/link_unlink.go [hunk 2]
```diff
@@ -0,0 +1,50 @@
+// Copyright IBM Corp. 2014, 2025
```
Comment (magodo) [inline internal/services/managedredis/databaselink/link_unlink.go:1]: Instead of implementing it manually, shall we consider to use a more generalized library like: github.com/hashicorp/go-set, e.g.:

- ret1 == stateSet.RemoveSet(planSet) 
- ret2 == stateSet.Intersect(planSet)
- ret3 == planSet.RemoveSet(stateSet)

File: internal/services/managedredis/managed_redis_geo_replication_resource.go (hunk 1 above)
Comment (gerrytan) [reply internal/services/managedredis/managed_redis_geo_replication_resource.go]: Fixed

File: internal/services/managedredis/databaselink/link_unlink.go (hunk 2 above)
Comment (gerrytan) [reply internal/services/managedredis/databaselink/link_unlink.go:1]: Hmm.. I'm not convinced with this because hashicorp/go-set hasn't been imported / used anywhere in azurerm. I think we need to consult first with Hashicorp as this might be another external dependency to maintain?

Comment (magodo) [reply internal/services/managedredis/databaselink/link_unlink.go:1]: I'll leave it to hashicorp's discretion.

File: internal/services/managedredis/custompollers/geo_replication_linking_poller.go [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+	if resp.Model == nil || resp.Model.Properties == nil {
+		return nil, fmt.Errorf("polling for %s: properties were empty", p.id)
+	}
+
+	idFound := make(map[string]bool, len(p.toIds))
+	for _, toId := range p.toIds {
+		idFound[toId] = false
+	}
+
+	for _, ldb := range pointer.From(resp.Model.Properties.GeoReplication.LinkedDatabases) {
```
Comment (sreallymatt) [inline internal/services/managedredis/custompollers/geo_replication_linking_poller.go:47]: GeoReplication is a pointer that could be nil, to avoid panics we should check it

File: internal/services/managedredis/custompollers/geo_replication_poller.go [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+				idFound[id] = true
+			}
+		}
+	}
+
+	for _, found := range idFound {
+		if !found {
+			return &pollingInProgress, nil
+		}
+	}
```
Comment (sreallymatt) [inline internal/services/managedredis/custompollers/geo_replication_poller.go]: If we flip the logic here, create a map of IDs from the Azure response, then for each `p.toIds` we check if it's present in the map, then we can cut this down to 2 loops

e.g.
```go
linkedDatabaseIDs := make(map[string]struct{})
	for _, ldb := range pointer.From(resp.Model.Properties.GeoReplication.LinkedDatabases) {
		if pointer.From(ldb.State) == databases.LinkStateLinked {
			linkedDatabaseIDs[pointer.From(ldb.Id)] = struct{}{}
		}
	}

	for _, id := range p.toIds {
		if _, ok := linkedDatabaseIDs[id]; !ok {
			return &pollingInProgress, nil
		}
	}
```

(note: map[string]struct{} is my personal preference but map[string]bool is fine as well, whichever you prefer)

File: internal/services/managedredis/managed_redis_geo_replication_resource.go [hunk 5]
```diff
@@ -86,6 +89,10 @@ func (r ManagedRedisGeoReplicationResource) Create() sdk.ResourceFunc {
 				return err
 			}
 
+			if slices.Contains(model.LinkedManagedRedisIds, model.ManagedRedisId) {
+				return fmt.Errorf("linked_managed_redis_ids cannot contain the same value as managed_redis_id: %s", model.ManagedRedisId)
```
Comment (sreallymatt) [inline internal/services/managedredis/managed_redis_geo_replication_resource.go]: We should be able to remove this, the CustomizeDiff will handle it. 

Terraform will do an initial plan, which may not trigger the error in the CustomizeDiff (e.g. if the value is unknown) but before Terraform calls Create/Update it will first provide the provider with a final plan containing known values, so the CustomizeDiff will then catch this

File: internal/services/managedredis/databaselink/force_unlink_invocations.go [hunk 6]
```diff
@@ -0,0 +1,31 @@
+// Copyright IBM Corp. 2014, 2025
+// SPDX-License-Identifier: MPL-2.0
+
+package databaselink
+
+type ForceUnlinkInvocation struct {
+	Id  string
+	Ids []string
+}
```
Comment (sreallymatt) [inline internal/services/managedredis/databaselink/force_unlink_invocations.go]: Other than the name and the name of the slice field, this is identical to the `ForceLinkInvocation` type, can we reuse the same type for both link and unlink

File: internal/services/managedredis/databaselink/link_unlink.go (hunk 2 above)
Comment (sreallymatt) [reply internal/services/managedredis/databaselink/link_unlink.go:1]: I think using an existing library for this makes sense, especially given it's owned by HashiCorp as well

File: internal/services/managedredis/managed_redis_geo_replication_resource_test.go [hunk 7]
```diff
@@ -36,7 +36,7 @@ func TestAccManagedRedisDatabaseGeoReplication_basic(t *testing.T) {
 	})
 }
 
-func TestAccManagedRedisDatabaseGeoReplication_update(t *testing.T) {
+func TestAccManagedRedisGeoReplication_update(t *testing.T) {
```
Comment (sreallymatt) [inline internal/services/managedredis/managed_redis_geo_replication_resource_test.go:39]: I see both configs only specify 1 ID for `linked_managed_redis_ids`, could you add test steps where we link multiple and another where we unlink multiple?

File: internal/services/managedredis/managed_redis_geo_replication_resource_test.go [hunk 8]
```diff
@@ -59,6 +59,17 @@ func TestAccManagedRedisDatabaseGeoReplication_update(t *testing.T) {
 	})
 }
 
+func TestAccManagedRedisGeoReplication_linkedManagedRedisIdsCannotContainSelf(t *testing.T) {
+	data := acceptance.BuildTestData(t, "azurerm_managed_redis_geo_replication", "test")
+	r := ManagedRedisGeoReplicationResource{}
+	data.ResourceTest(t, r, []acceptance.TestStep{
+		{
+			Config:      r.linkedManagedRedisIdsContainSelf(data),
```
Comment (sreallymatt) [inline internal/services/managedredis/managed_redis_geo_replication_resource_test.go:92]: We may want to add a config (or change this config) to reference resource's IDs rather than using literal strings, since that's likely how users will use this

File: internal/services/managedredis/custompollers/geo_replication_poller.go [hunk 9]
```diff
@@ -0,0 +1,62 @@
...
+	"github.com/hashicorp/go-azure-sdk/resource-manager/redisenterprise/2025-07-01/databases"
+	"github.com/hashicorp/go-azure-sdk/sdk/client/pollers"
+)
+
+var _ pollers.PollerType = &geoReplicationPoller{}
+
+type geoReplicationPoller struct {
+	client DatabasesClientInterface
+	id     databases.DatabaseId
+	toIds  []string
```
Comment (gerrytan) [inline internal/services/managedredis/custompollers/geo_replication_poller.go]: Rename to expectedIds

File: internal/services/managedredis/custompollers/geo_replication_linking_poller.go (hunk 3 above)
Comment (gerrytan) [inline internal/services/managedredis/custompollers/geo_replication_linking_poller.go:47]: Panic in GeoReplication

File: internal/services/managedredis/custompollers/geo_replication_linking_poller.go [hunk 10]
```diff
@@ -0,0 +1,62 @@
...
+				idFound[id] = true
+			}
+		}
+	}
+
+	for _, found := range idFound {
+		if !found {
+			return &pollingInProgress, nil
+		}
+	}
```
Comment (gerrytan) [inline internal/services/managedredis/custompollers/geo_replication_linking_poller.go:57]: Flip the loop / map so it's 1 less loop

File: internal/services/managedredis/managed_redis_geo_replication_resource.go [hunk 11]
```diff
@@ -223,56 +242,82 @@ func (r ManagedRedisGeoReplicationResource) CustomizeDiff() sdk.ResourceFunc {
 				return err
 			}
 
+			if model.ManagedRedisId != "" && slices.ContainsFunc(model.LinkedManagedRedisIds, func(id string) bool {
+				return id != "" && id == model.ManagedRedisId
+			}) {
+				return fmt.Errorf("linked_managed_redis_ids cannot contain the same value as managed_redis_id: %s", model.ManagedRedisId)
+			}
+
```
Comment (gerrytan) [inline internal/services/managedredis/managed_redis_geo_replication_resource.go:242]: Is this validation appropriate? Customer could have this config which is currently valid

File: internal/services/managedredis/managed_redis_geo_replication_resource.go [hunk 12]
```diff
@@ -162,6 +171,10 @@ func (r ManagedRedisGeoReplicationResource) Update() sdk.ResourceFunc {
 				return fmt.Errorf("decoding: %+v", err)
 			}
 
+			if slices.Contains(model.LinkedManagedRedisIds, model.ManagedRedisId) {
+				return fmt.Errorf("linked_managed_redis_ids cannot contain the same value as managed_redis_id: %s", model.ManagedRedisId)
+			}
+
```
Comment (gerrytan) [inline internal/services/managedredis/managed_redis_geo_replication_resource.go]: Dup check not necessary: customize diff will be invoked again

File: internal/services/managedredis/databaselink/link_unlink.go (hunk 2 above)
Comment (gerrytan) [reply internal/services/managedredis/databaselink/link_unlink.go:1]: Discussed with HC: it's ok to import this lib

File: internal/services/managedredis/databaselink/force_link_invocations.go [hunk 13]
```diff
@@ -0,0 +1,30 @@
+package databaselink
+
+import "slices"
+
+type ForceLinkInvocation struct {
+	Id                string
+	LinkedDatabaseIds []string
+}
```
Comment (gerrytan) [inline internal/services/managedredis/databaselink/force_link_invocations.go]: Can this be merged / DRY-ed with force unlink

File: internal/services/managedredis/managed_redis_geo_replication_resource_test.go [hunk 14]
```diff
@@ -230,3 +253,46 @@ resource "azurerm_managed_redis_geo_replication" "test" {
...
+
+resource "azurerm_managed_redis_geo_replication" "test" {
+  managed_redis_id = "/subscriptions/000000000-0000-000-000-000000000000/resourceGroups/my-rg/providers/Microsoft.Cache/redisEnterprise/amr1"
+  linked_managed_redis_ids = [
+    "/subscriptions/000000000-0000-000-000-000000000000/resourceGroups/my-rg/providers/Microsoft.Cache/redisEnterprise/amr1",
+    "/subscriptions/000000000-0000-000-000-000000000000/resourceGroups/my-rg/providers/Microsoft.Cache/redisEnterprise/amr2",
+  ]
+}
+`, data.RandomInteger, data.Locations.Primary, data.Locations.Secondary)
+}
```
Comment (gerrytan) [inline internal/services/managedredis/managed_redis_geo_replication_resource_test.go:299]: Add a test to add / remove 3 at the same time, check if can do same loc, or hardcode fourth if needed

File: internal/services/managedredis/managed_redis_geo_replication_resource_test.go [hunk 15]
```diff
@@ -230,3 +253,46 @@ resource "azurerm_managed_redis_geo_replication" "test" {
...
+  default_database {
+    geo_replication_group_name = "acctest-georep-%[1]d"
+  }
+}
+
+resource "azurerm_managed_redis_geo_replication" "test" {
+  managed_redis_id = "/subscriptions/000000000-0000-000-000-000000000000/resourceGroups/my-rg/providers/Microsoft.Cache/redisEnterprise/amr1"
+  linked_managed_redis_ids = [
+    "/subscriptions/000000000-0000-000-000-000000000000/resourceGroups/my-rg/providers/Microsoft.Cache/redisEnterprise/amr1",
+    "/subscriptions/000000000-0000-000-000-000000000000/resourceGroups/my-rg/providers/Microsoft.Cache/redisEnterprise/amr2",
```
Comment (gerrytan) [inline internal/services/managedredis/managed_redis_geo_replication_resource_test.go]: If no breaking change, do this using real value (apply the resource)

**Review by sreallymatt — COMMENTED** [review]
@gerrytan - I know you've added comments from our call (and looks like you've covered them all already) but just leaving my review here as well

File: internal/services/managedredis/custompollers/geo_replication_poller.go (hunk 9 above)
Comment (gerrytan) [reply internal/services/managedredis/custompollers/geo_replication_poller.go]: Fixed in 18ae778325

File: internal/services/managedredis/custompollers/geo_replication_linking_poller.go (hunk 3 above)
Comment (gerrytan) [reply internal/services/managedredis/custompollers/geo_replication_linking_poller.go:47]: Fixed in 18ae778325

Comment (gerrytan) [reply internal/services/managedredis/custompollers/geo_replication_linking_poller.go:47]: Fixed in 18ae778325

File: internal/services/managedredis/custompollers/geo_replication_poller.go (hunk 4 above)
Comment (gerrytan) [reply internal/services/managedredis/custompollers/geo_replication_poller.go]: Fixed in 18ae778325

File: internal/services/managedredis/custompollers/geo_replication_linking_poller.go (hunk 10 above)
Comment (gerrytan) [reply internal/services/managedredis/custompollers/geo_replication_linking_poller.go:57]: Fixed in 18ae778325

File: internal/services/managedredis/managed_redis_geo_replication_resource.go (hunk 11 above)
Comment (gerrytan) [reply internal/services/managedredis/managed_redis_geo_replication_resource.go:242]: @sreallymatt this validation is a dilemma.

I tested linking a managed redis with itself at current version v4.58:

```terraform
resource "azurerm_managed_redis_geo_replication" "georep1" {
  managed_redis_id = azurerm_managed_redis.amr1.id
  linked_managed_redis_ids = [
    azurerm_managed_redis.amr1.id
  ]
}
```

This plans and apply alright, no POST /forceLinkToReplication group call was made to link amr1 back to itself because the current logic already detects this as linked.

However on Read() we don't set into state our own id to `linked_managed_redis_ids`, so user will always have a `[] -> [amr1.id]` plan diff.

It is kind-of broken. Should we fail such 'bad' config, or should we let it be to avoid disrupting existing flow?

Note that this is already called out by the doc: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/managed_redis_geo_replication#linked_managed_redis_ids-1

> The ID of this Managed Redis is always included by default and does not need to be provided here

But not yet enforced

File: internal/services/managedredis/databaselink/link_unlink.go (hunk 2 above)
Comment (gerrytan) [reply internal/services/managedredis/databaselink/link_unlink.go:1]: Refactored to use go-set/v3 in 78b3b6814d

File: internal/services/managedredis/databaselink/force_link_invocations.go (hunk 13 above)
Comment (gerrytan) [reply internal/services/managedredis/databaselink/force_link_invocations.go]: Fixed in fb57e01f76

File: internal/services/managedredis/managed_redis_geo_replication_resource.go (hunk 5 above)
Comment (gerrytan) [reply internal/services/managedredis/managed_redis_geo_replication_resource.go]: Fixed in 49a4115767

File: internal/services/managedredis/managed_redis_geo_replication_resource.go (hunk 12 above)
Comment (gerrytan) [reply internal/services/managedredis/managed_redis_geo_replication_resource.go]: Fixed in 49a4115

File: internal/services/managedredis/managed_redis_geo_replication_resource_test.go (hunk 8 above)
Comment (gerrytan) [reply internal/services/managedredis/managed_redis_geo_replication_resource_test.go:92]: Fixed in 49a4115767

File: internal/services/managedredis/managed_redis_geo_replication_resource_test.go (hunk 7 above)
Comment (gerrytan) [reply internal/services/managedredis/managed_redis_geo_replication_resource_test.go:39]: Added 4 cluster link unlink case: 360eea63d7

File: internal/services/managedredis/managed_redis_geo_replication_resource_test.go (hunk 14 above)
Comment (gerrytan) [reply internal/services/managedredis/managed_redis_geo_replication_resource_test.go:299]: Fixed in 360eea63d7

**Comment by gerrytan** [comment]
Triggered acctest run: https://hashicorp.teamcity.com/buildConfiguration/TF_AzureRM_AZURERM_SERVICE_PUBLIC_MANAGEDREDIS/609531

**Comment by gerrytan** [comment]
Most recent acctest result:
image

Running another test against latest commit, but expected to yield same result because the only diff is a main merge (to pull the comment-on-fail fix): https://hashicorp.teamcity.com/buildConfiguration/TF_AzureRM_AZURERM_SERVICE_PUBLIC_MANAGEDREDIS/609590

@sreallymatt this PR is ready for another review. The main open concern is on [breaking-change-ness of 'contains-self' validation](https://github.com/hashicorp/terraform-provider-azurerm/pull/31385/changes#r2772217474)

File: internal/services/managedredis/managed_redis_geo_replication_resource.go (hunk 11 above)
Comment (sreallymatt) [reply internal/services/managedredis/managed_redis_geo_replication_resource.go:242]: @gerrytan Given it causes a permanent diff currently, I think it's acceptable to add the error in the CustomizeDiff, thanks for confirming!

**Comment by gerrytan** [comment]
Please hold off on further review on this PR, I found an eventual consistency problem on unlinking: https://hashicorp.teamcity.com/buildConfiguration/TF_AzureRM_AZURERM_SERVICE_PUBLIC_MANAGEDREDIS/609590

Will add a poller on the unlinking logic.

**Comment by gerrytan** [comment]
Added poller after unlinking to address eventual consistency. Waiting for latest acctest result: https://hashicorp.teamcity.com/buildConfiguration/TF_AzureRM_AZURERM_SERVICE_PUBLIC_MANAGEDREDIS/614006

**Comment by gerrytan** [comment]
@sreallymatt this PR is good to review again. I have added a poller on the unlinking logic, and latest acctest result is passing:

image

**Review by sreallymatt — DISMISSED** [review]
Thanks @gerrytan - LGTM ✅

**Review by sreallymatt — APPROVED** [review]
