### PR TITLE
`data.azurerm_postgresql_flexible_server` - add support for `zone` and `high_availability`

### LINKED ISSUE #31032: Support for zone and standby_availability_zone properties in data source azurerm_postgresql_flexible_server
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

When creating a server with HA enabled, the documentation recommends to ignore changes to the zone and standby availability zone properties.

This causes a situation wherein, when a failover happens, we cannot detect the change via terraform.

After the server is created, we apply `azurerm_postgresql_flexible_server_active_directory_administrator` resources to grant terraform access to the database via the SP and a federated SP token. What we are seeing is that after a failover happens, terraform is unable to connect to the database using a MID token in the `cyrilgdn/postgresql` provider because the previous standby DB (now made active) doesn't have the federation properly applied.

When we taint the `azurerm_postgresql_flexible_server_active_directory_administrator` resource so it gets recreated, then terraform can connect to the DB and make changes with the other provider.

Since we have to `ignore_changes` for the zone on the actual resource, we want to detect the zone change with a data source so that the new zone can be used as a value for `lifecycle.replace_triggered_by` on the `azurerm_postgresql_flexible_server_active_directory_administrator` resources, but the zone property is not returned by the data source.

### New or Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Potential Terraform Configuration

```hcl
resource "azurerm_postgresql_flexible_server" "server" {
  ...
  high_availability {
    mode                      = "ZoneRedundant"
    standby_availability_zone = 2
  }

  lifecycle {
    ignore_changes = [
      high_availability[0].standby_availability_zone,
      zone
    ]
  }

  zone = 1
}

# We have ignored changes to the zone and HA standby zone above but need to detect them
# to recreate the active directory admin resource
# Pull from the API via data source
data "azurerm_postgresql_flexible_server" "active_zone_detector" {
  name                = azurerm_postgresql_flexible_server.server.name
  resource_group_name = azurerm_postgresql_flexible_server.server.resource_group_name
}

# Read out only the zone value into a terraform_data resource that can be used in
# `lifecycle.replace_triggered_by` in the active directory admin resource below
resource "terraform_data" "detected_active_zone" {
  input = data.azurerm_postgresql_flexible_server.active_zone_detector.zone
}

resource "azurerm_postgresql_flexible_server_active_directory_administrator" "terraform_is_entra_admin" {
  object_id           = data.azuread_service_principal.current.object_id
  principal_name      = data.azuread_service_principal.current.display_name
  principal_type      = "ServicePrincipal"
  resource_group_name = var.resource_group_name
  server_name         = azurerm_postgresql_flexible_server.server.name
  tenant_id           = data.azurerm_client_config.current.tenant_id

  # Trigger replacement of this resource when the zone changes
  lifecycle {
    replace_triggered_by = [terraform_data.detected_active_zone]
  }
}

data "azurerm_client_config" "current" {}

data "azuread_service_principal" "current" {
  object_id = data.azurerm_client_config.current.object_id
}

# Here, we call the other provider using an azure identity token
provider "postgresql" {
  azure_identity_auth = true
  azure_tenant_id     = data.azurerm_client_config.current.tenant_id
  host                = var.server_fqdn
  sslmode             = "verify-full"
  superuser           = false
  username            = data.azuread_service_principal.current.display_name
}
```

### References

Terraform output:

Trying to read the zone from the data source fails:
```
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/postgres_server/server/main.tf line 396, in resource "terraform_data" "detected_active_zone":
│  396:   input = data.azurerm_postgresql_flexible_server.active_zone_detector.zone
│ 
│ This object has no argument, nested block, or exported attribute named
│ "zone".
```

The original error we are trying to solve involves the other provider mentioned above - when it tries to use azure identity auth after a failover:
```
Planning failed. OpenTofu encountered an error while generating this plan.
│ Error: error connecting to PostgreSQL server my-server.postgres.database.azure.com (scheme: postgres): pq: An error occurred while validating the access token. Acquire a new token and try again.
```

As a reminder, the only thing we needed to do to fix this error was manually taint the `azurerm_postgresql_flexible_server_active_directory_administrator.terraform_is_entra_admin` resource and run `tofu apply`. The goal with the data source, terraform_data resource, and lifecycle.replace_triggered by on the `azurerm_postgresql_flexible_server_active_directory_administrator.terraform_is_entra_admin` resource is to automatically recreate the resource without having to resort to manual tainting.

### PR DESCRIPTION
**Pull request by tspearconquest**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-merging.md).

* Data source: `azurerm_postgresql_flexible_server` - add support for the properties `zone`, `high_availability[0].mode` and `high_availability[0].standby_availability_zone`

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)

Fixes #31032 

## AI Assistance Disclosure

- [ ] AI Assisted - This contribution was made by, or with the assistance of, AI/LLMs

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/postgres/postgresql_flexible_server_data_source.go [hunk 1]
```diff
@@ -153,3 +178,21 @@ func dataSourceArmPostgresqlFlexibleServerRead(d *pluginsdk.ResourceData, meta i
 
 	return nil
 }
+
+func flattenDataSourceFlexibleServerHighAvailability(ha *servers.HighAvailability) []interface{} {
```
Comment (mbfrahry) [inline internal/services/postgres/postgresql_flexible_server_data_source.go]: We should be able to use the resources flatten here rather than write a new function since they both do the same thing

File: website/docs/d/postgresql_flexible_server.html.markdown [hunk 2]
```diff
@@ -57,8 +59,19 @@ In addition to the Arguments listed above - the following Attributes are exporte
...
 
+---
+
+A `high_availability` block exports the following:
+
+* `mode` - The high availability mode of the MySQL Flexible Server.
+
+* `standby_availability_zone` - The availability zone of the standby Flexible Server.
+
+
```
Comment (mbfrahry) [inline website/docs/d/postgresql_flexible_server.html.markdown]:
```suggestion
```

**Review by mbfrahry — CHANGES_REQUESTED** [review]
Hey @tspearconquest, this change looks good but I have just a couple clean things before we merge

File: internal/services/postgres/postgresql_flexible_server_data_source.go (hunk 1 above)
Comment (tspearconquest) [reply internal/services/postgres/postgresql_flexible_server_data_source.go]: Ok, I will appreciate any pointers on that, as I am not a Go developer, and I simply copy/pasted this function verbatim from the mysql flexible server data source: https://github.com/hashicorp/terraform-provider-azurerm/blob/944dfafd8f7e15e736c034c720b799b273e7801c/internal/services/mysql/mysql_flexible_server_data_source.go#L313-L329

Comment (tspearconquest) [reply internal/services/postgres/postgresql_flexible_server_data_source.go]: I think I see what needs to change. Will try it.

Comment (tspearconquest) [reply internal/services/postgres/postgresql_flexible_server_data_source.go]: I've pushed the change after getting a successful build.

**Comment by tspearconquest** [comment]
Hi- Any chance to get a review and merge before next week's release please?

**Review by mbfrahry — APPROVED** [review]
LGTM!
