### PR TITLE
`data.azurerm_api_management_subscription` : fixed a failure that occurred when reading the built-in subscription

### LINKED ISSUE #30579: Data source azurerm_api_management_subscription fails for built-in subscriptions
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.11.2

### AzureRM Provider Version

4.43.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_subscription

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name     = "example-rg"
  location = "westeurope"
}

resource "azurerm_api_management" "apim" {
  name                = "example-apim"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  publisher_name      = "test"
  publisher_email     = "test@test.com"
  sku_name            = "Consumption_0"
}

# az rest \
# --method get \
# --url "https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.ApiManagement/service/<APIM_NAME>/subscriptions?api-version=2022-08-01"
data "azurerm_api_management_subscription" "master" {
  api_management_id = azurerm_api_management.apim.id
  subscription_id   = "master"
}
```

### Debug Output/Panic Output

```shell
data.azurerm_api_management_subscription.master: Reading...
╷
│ Error: parsing scope into product/api id "/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.ApiManagement/service/<APIM_NAME>/": parsing "/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.ApiManagement/service/<APIM_NAME>/": parsing the Api ID: the number of segments didn't match
│
│ Expected a Api ID that matched (containing 10 segments):
│
│ > /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.ApiManagement/service/serviceName/apis/apiId
│
│ However this value was provided (which was parsed into 0 segments):
│
│ > /subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.ApiManagement/service/<APIM_NAME>/
```

### Expected Behaviour

Should successfully applied.

### Actual Behaviour

See error message above.

It seems, that implemented `scope` value verification doesn't consider scope of the built-in subscription.

```
$ az rest \
  --method get \
  --url "https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.ApiManagement/service/<APIM_NAME>/subscriptions?api-version=2022-08-01"
{
  "count": 1,
  "value": [
    {
      "id": "/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.ApiManagement/service/<APIM_NAME>/subscriptions/master",
      "name": "master",
      "properties": {
        "allowTracing": false,
        "createdDate": "2025-09-08T11:51:22.84Z",
        "displayName": "Built-in all-access subscription",
        "endDate": null,
        "expirationDate": null,
        "notificationDate": null,
        "scope": "/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.ApiManagement/service/<APIM_NAME>/",
        "startDate": null,
        "state": "active",
        "stateComment": null
      },
      "type": "Microsoft.ApiManagement/service/subscriptions"
    }
  ]
}
```

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by sinbai**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

When an API Management (APIM) service is created, a built-in subscription named `master` is automatically provisioned. I assume that users should not manage this built-in subscription via the AzureRM Provider resource `azurerm_api_management_subscription`. However, it should be possible for users to read and reference it through the data source `data.azurerm_api_management_subscription`.

Currently, the implementation of `data.azurerm_api_management_subscription` does not account for the built-in master subscription, which leads to issue #30579 during read operations, so submitted this PR to fix it.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

PASS: TestAccDataSourceApiManagementSubscription_basic (213.73s)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `data.azurerm_api_management_subscription` : fixed a failure that occurred when reading the built-in subscription [GH-30579]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #30579

### CODE REVIEW

File: internal/services/apimanagement/api_management_subscription_data_source.go [hunk 1]
```diff
@@ -135,9 +135,10 @@ func (ApiManagementSubscriptionDataSource) Read() sdk.ResourceFunc {
 
 			if model := resp.Model; model != nil {
 				if props := model.Properties; props != nil {
-					// check if the subscription is for all apis or a specific product/ api
-					if props.Scope != "" && !strings.HasSuffix(props.Scope, "/apis") {
-						// the scope is either a product or api id
+					// Check if the subscription is for all apis or a specific product/ api, excluding the built-in master subscription.
+					// The scope of the built-in subscription is the API Management service itself (service ID).
+					if state.SubscriptionId != "master" && props.Scope != "" && !strings.HasSuffix(props.Scope, "/apis") {
```
Comment (sreallymatt) [inline internal/services/apimanagement/api_management_subscription_data_source.go]: Instead of adding an exception specifically for `master`, would it makes sense to not return any error at all if parsing either ID fails?

e.g. try to parse the scope into either ID, if there are no parsing errors we set it into state, otherwise do nothing:

```
				if props := model.Properties; props != nil {
					if props.Scope != "" && !strings.HasSuffix(props.Scope, "/apis") {
						if productId, err := product.ParseProductIDInsensitively(props.Scope); err == nil {
							state.ProductId = productId.ID()
						}

						if apiId, err := api.ParseApiIDInsensitively(props.Scope); err == nil {
							state.ApiId = apiId.ID()
						}
					}
```

If the id/name of the built-in subscription changes, or if other exceptions are encountered we'd have to continually expand this set of conditions with more exceptions

Comment (sinbai) [reply internal/services/apimanagement/api_management_subscription_data_source.go]: Appreciate the feedback, the fix has been applied.

**Comment by sinbai** [comment]
> Thanks @sinbai, I've left a question inline regarding the implementation of this data source if you wouldn't mind taking a look.

Hi @sreallymatt thanks for the feedback! I've updated the code as suggested, could you please take another look?
