### PR TITLE
azurerm_cosmosdb_account: enable_analytical_storage

### LINKED ISSUE #9119: EnableAnalyticalStorage capabilities not detected in resource azurerm_cosmosdb_account
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When the EnableAnalyticalStorage capability is already added to your azurerm_cosmosdb_account. Terraform plan doesn't detect it and try to recreate the resource with the capability enabled during the plan.

### Affected Resource(s)

* `azurerm_cosmosdb_account`

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_account" "acdb" {
  name                = local.resource_name
  location            = data.azurerm_resource_group.project_resource_group.location
  resource_group_name = data.azurerm_resource_group.project_resource_group.name
  offer_type          = var.acdb_offer_type
  kind                = var.acdb_kind
  ...

  capabilities {
    name = "EnableAnalyticalStorage"
  }

  ...

}
```

### Plan Output
```hcl
  + capabilities { # forces replacement
          + name = "EnableAnalyticalStorage"
      }
```
### Expected Behavior

Terraform plan should have detected the already activated capability

### Actual Behavior

Terraform want to recreate the complete resource to activate the capability

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

The last update (2.34) give us control to enable the capability you can find the link to the PR below
https://github.com/terraform-providers/terraform-provider-azurerm/pull/9010

### PR DESCRIPTION
**Pull request by favoretti**
Initial implementation assumed it's a capability, whereas it's a
property. This PR implements it properly.

Fixes #9119

### CODE REVIEW

**Comment by favoretti** [comment]
```
$ TF_ACC=1 go test -v ./azurerm/internal/services/cosmos -timeout=600m -run TestAccAzureRMCosmosDBAccount_analytical_storage_enabled
=== RUN   TestAccAzureRMCosmosDBAccount_analytical_storage_enabled
=== PAUSE TestAccAzureRMCosmosDBAccount_analytical_storage_enabled
=== CONT  TestAccAzureRMCosmosDBAccount_analytical_storage_enabled
--- PASS: TestAccAzureRMCosmosDBAccount_analytical_storage_enabled (703.28s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cosmos	705.447s
```

**Comment by favoretti** [comment]
Also verified during the acceptance test that account had property set properly.

File: azurerm/internal/services/cosmos/cosmosdb_account_resource.go [hunk 1]
```diff
@@ -227,7 +234,6 @@ func resourceArmCosmosDbAccount() *schema.Resource {
 								"mongoEnableDocLevelTTL",
 								"DisableRateLimitingResponses",
 								"AllowSelfServeUpgradeToMongo36",
-								"EnableAnalyticalStorage",
```
Comment (katbyte) [inline azurerm/internal/services/cosmos/cosmosdb_account_resource.go:230]: This would be a breaking change, could we keep it in with a comment to remove in 3.0? (but we can remove it from the docs)

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @favoretti - overall looks good aside from one comment

File: azurerm/internal/services/cosmos/cosmosdb_account_resource.go (hunk 1 above)
Comment (favoretti) [reply azurerm/internal/services/cosmos/cosmosdb_account_resource.go:230]: @katbyte well... it won't be, in fact :), since this could have never worked. :) It's never ben a capability from what I can see. I tried reproducing the bug linked, see my comment there, it just doesn't work at all.

Comment (favoretti) [reply azurerm/internal/services/cosmos/cosmosdb_account_resource.go:230]: Other than that, I need to rebase this one on master, since @mbfrahry merged new test shim today, so leave this with me, I'll fix it all tomorrow. If you insist on leaving this in - I will, but I'm 99% positive this was broken from inception.

Comment (katbyte) [reply azurerm/internal/services/cosmos/cosmosdb_account_resource.go:230]: Its mostly if someone is using it (regardless of if it was working or not) we would break their tf plan/apply which is less then ideal

Comment (favoretti) [reply azurerm/internal/services/cosmos/cosmosdb_account_resource.go:230]: No prob, I'll leave it in.

**Comment by favoretti** [comment]
```
$ TF_ACC=1 go test -v ./azurerm/internal/services/cosmos -timeout=600m -run TestAccCosmosDBAccount_analyticalStorage
=== RUN   TestAccCosmosDBAccount_analyticalStorage
=== PAUSE TestAccCosmosDBAccount_analyticalStorage
=== CONT  TestAccCosmosDBAccount_analyticalStorage
--- PASS: TestAccCosmosDBAccount_analyticalStorage (699.30s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cosmos	700.600s
```

**Comment by favoretti** [comment]
@katbyte should be good to go now.

**Comment by T1loc** [comment]
@favoretti @katbyte Do you think it will be a good idea to also add the Analytical Storage Time to Live ?

**Comment by favoretti** [comment]
Sure, although I won’t be able to get to it until Monday. If you wanna do
it - I’d wait for this to be merged. Conflict resolution is painful :)

**Comment by favoretti** [comment]
Reminder to myself - rename `enable_analytical_storage` to `analytical_storage_enabled`.

**Review by tombuildsstuff — APPROVED** [review]
LGTM 👍

**Comment by favoretti** [comment]
@katbyte Renamed property as requested.

**Comment by favoretti** [comment]
@T1loc Quick googling didn't tell me anything on TTL, would you be so kind to point me to it, or better yet, log a separate issue for that property, I can tackle it in a separate PR then.

**Comment by T1loc** [comment]
> @T1loc Quick googling didn't tell me anything on TTL, would you be so kind to point me to it, or better yet, log a separate issue for that property, I can tackle it in a separate PR then.



> @T1loc Quick googling didn't tell me anything on TTL, would you be so kind to point me to it, or better yet, log a separate issue for that property, I can tackle it in a separate PR then.

@favoretti Yes we need a new issue. 
Some info about it : https://docs.microsoft.com/en-us/azure/cosmos-db/analytical-store-introduction#analytical-ttl

This options need at container creation time to have the AnalyticalStore enable. I will open an issue in ~1h

**Review by katbyte — DISMISSED** [review]
@favoretti - i'm getting this test failure:

```
------- Stdout: -------
=== RUN   TestAccCosmosDBAccount_analyticalStorage
=== PAUSE TestAccCosmosDBAccount_analyticalStorage
=== CONT  TestAccCosmosDBAccount_analyticalStorage
    testing.go:684: Step 0 error: Check failed: 1 error occurred:
        	* Check 2/2 error: azurerm_cosmosdb_account.test: Attribute 'enable_analytical_storage' not found
        
        
--- FAIL: TestAccCosmosDBAccount_analyticalStorage (681.00s)
FAIL
````

**Comment by favoretti** [comment]
@tombuildsstuff Fixed acceptance test too after the rename, so maybe this can go in 2.43 too.
```
$ TF_ACC=1 go test -v ./azurerm/internal/services/cosmos -timeout=1000m -run TestAccCosmosDBAccount_analyticalStorage
=== RUN   TestAccCosmosDBAccount_analyticalStorage
=== PAUSE TestAccCosmosDBAccount_analyticalStorage
=== CONT  TestAccCosmosDBAccount_analyticalStorage
--- PASS: TestAccCosmosDBAccount_analyticalStorage (689.06s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cosmos	690.502s
```

**Comment by jackofallops** [comment]
Tests are looking good now 👍
