### PR TITLE
`azurerm_*_virtual_machine` - `allow_extensions_operations` can now be updated

### LINKED ISSUE #7070: azurerm_*_virtual_machine: Change of allow_extension_operations forces recreation which is wrong
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
Provider 2.10

### Affected Resource(s)

* `azurerm_linux_virtual_machine`
* `azurerm_windows_virtual_machine`

### Expected Behavior

Via cli, you can change allow_extension_operations online, e.g.
```
az vm update -n instancename -g resourcegroup --set osProfile.allowExtensionOperations=true
```

This should be possible online via terraform as well.

### Actual Behavior
Change of allow_extension_operations via terraform template forces a recreation of the instance.

This behavior is documented, but wrong:
https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html
~~~
allow_extension_operations - (Optional) Should Extension Operations be allowed on this Virtual Machine? Changing this forces a new resource to be created.
~~~

### PR DESCRIPTION
**Pull request by mbfrahry**
Fixes #7070

### CODE REVIEW

File: azurerm/internal/services/compute/linux_virtual_machine_resource.go [hunk 1]
```diff
@@ -816,6 +815,23 @@ func resourceLinuxVirtualMachineUpdate(d *schema.ResourceData, meta interface{})
 		}
 	}
 
+	if d.HasChange("allow_extension_operations") {
+		provisionVMAgent := d.Get("provision_vm_agent").(bool)
+		allowExtensionOperations := d.Get("allow_extension_operations").(bool)
+
+		if !provisionVMAgent && allowExtensionOperations {
+			return fmt.Errorf("`allow_extension_operations` cannot be set to `true` when `provision_vm_agent` is set to `false`")
```
Comment (jpbuecken) [inline azurerm/internal/services/compute/linux_virtual_machine_resource.go:823]: This is not correct. provision_vm_agent affects the create process of a virtual machine.
Assume you did not install the agent (provision_vm_agent=false), then you can still install the agent manually

https://docs.microsoft.com/en-us/azure/virtual-machines/troubleshooting/install-vm-agent-offline

As far as I know, the manual installation does not affect provision_vm_agent value, but you can still use allow_extension_operations
