### PR TITLE
`azurerm_container_app_environment` - fix a panic when the `log_analytics_workspace_id` is from another subscription 

### LINKED ISSUE #29446: azurerm_container_app_environment: Panic in v4.27.0
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.11.4

### AzureRM Provider Version

4.27.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app_environment

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "scim_bridge" {
  name     = module.naming_1Password.resource_group.name
  location = "uksouth"

  tags = local.default_tags
}

resource "azurerm_container_app_environment" "scim_bridge" {
  name                       = module.naming_1Password.container_app_environment.name
  location                   = azurerm_resource_group.scim_bridge.location
  resource_group_name        = azurerm_resource_group.scim_bridge.name
  log_analytics_workspace_id = var.log_analytics_workspace_id
  logs_destination           = "log-analytics"

  tags = local.default_tags
}
```

### Debug Output/Panic Output

```shell
azurerm_container_app_environment.scim_bridge: Creating...
azurerm_container_app_environment.scim_bridge: Still creating... [10s elapsed]
azurerm_container_app_environment.scim_bridge: Still creating... [20s elapsed]
azurerm_container_app_environment.scim_bridge: Still creating... [30s elapsed]
azurerm_container_app_environment.scim_bridge: Still creating... [40s elapsed]
azurerm_container_app_environment.scim_bridge: Still creating... [50s elapsed]
╷
│ Error: Plugin did not respond
│
│   with azurerm_container_app_environment.scim_bridge,
│   on 1Password.tf line 13, in resource "azurerm_container_app_environment" "scim_bridge":
│   13: resource "azurerm_container_app_environment" "scim_bridge" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v4.27.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x5ebf185]

goroutine 94 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/containerapps.(*ContainerAppEnvironmentResource).Read.ContainerAppEnvironmentResource.Read.func1({0x93f4eb0, 0xc0007eccb0}, {0xc002394008, {0x93f8838, 0xc0005f94d0}, 0xc002d01c80, 0x0, {0x93f90b8, 0xe618420}})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/containerapps/container_app_environment_resource.go:369 +0x6c5
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.(*ResourceWrapper).Resource.func2({0x93f4eb0, 0xc0007eccb0}, 0x93dbb70?, {0x7b421e0?, 0xc002394008?})        
        github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:63 +0x1c8
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.(*ResourceWrapper).Resource.(*ResourceWrapper).diagnosticsWrapper.diagnosticsWrapper.func10({0x93f4eb0?, 0xc0007eccb0?}, 0x1a3185c5000?, {0x7b421e0?, 0xc002394008?})
        github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:188 +0x59
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000463700, {0x93f4e08, 0xc002d47470}, 0xc002d01c80, {0x7b421e0, 0xc002394008})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:838 +0x119
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000463700, {0x93f4e08, 0xc002d47470}, 0xc001acf860, 0xc002d01b00, {0x7b421e0, 0xc002394008})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:969 +0xa8b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000d0a4b0, {0x93f4e08?, 0xc002d473b0?}, 0xc000714500)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/grpc_provider.go:1188 +0xd1a
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc000277100, {0x93f4e08?, 0xc002d470e0?}, 0xc000714500)
        github.com/hashicorp/terraform-plugin-mux@v0.17.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x18d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001b9c960, {0x93f4e08?, 0xc002d46600?}, 0xc0007ec770)
        github.com/hashicorp/terraform-plugin-go@v0.26.0/tfprotov5/tf5server/server.go:866 +0x3b9
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x89ee2a0, 0xc001b9c960}, {0x93f4e08, 0xc002d46600}, 0xc002d01280, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.26.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:611 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00086e200, {0x93f4e08, 0xc002d465a0}, 0xc002322420, 0xc001803f20, 0xe5bfd58, 0x0)
        google.golang.org/grpc@v1.69.4/server.go:1392 +0xfbe
google.golang.org/grpc.(*Server).handleStream(0xc00086e200, {0x93f8da8, 0xc00178e000}, 0xc002322420)
        google.golang.org/grpc@v1.69.4/server.go:1802 +0xb88
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.69.4/server.go:1030 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 36
        google.golang.org/grpc@v1.69.4/server.go:1041 +0x11d

Error: The terraform-provider-azurerm_v4.27.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

The resource should be created

### Actual Behaviour

The resource is not created (panics) 

### Steps to Reproduce

paste, plan, apply. 
Nothing specific about the setup

EDIT: The `var.log_analytics_workspace_id` points to a log analytics workspace in a different subscription, in case that matters.

### Important Factoids

_No response_

### References

_No response_

### LINKED ISSUE #29816: `azurerm_container_app_environment` panic on reading state of a resource with log analytics workspace in another subscrption.
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.11.4

### AzureRM Provider Version

4.32.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app_environment

### Terraform Configuration Files

```hcl
# Container App Environment
resource "azurerm_container_app_environment" "env" {
  name                     = "${local.full_resource_prefix}-cae"
  resource_group_name      = data.azurerm_resource_group.main.name
  location                 = data.azurerm_resource_group.main.location
  infrastructure_subnet_id = data.azurerm_subnet.container_app.id

  internal_load_balancer_enabled     = true
  zone_redundancy_enabled            = false
  infrastructure_resource_group_name = "${data.azurerm_resource_group.main.name}_CAE"

  # Log Analytics workspace for container app monitoring
  # logs_destination           = "log-analytics"
  # log_analytics_workspace_id = var.SHARED_LOG_ANALYTICS_WORKSPACE_ID

  mutual_tls_enabled = false

  workload_profile {
    name                  = "Consumption"
    workload_profile_type = "Consumption"
    minimum_count         = 0
    maximum_count         = 0
  }

  lifecycle {
    # adjusted manually see: https://github.com/hashicorp/terraform-provider-azurerm/issues/29756
    ignore_changes = [
      logs_destination,
      log_analytics_workspace_id,
    ]
  }
}
```

### Debug Output/Panic Output

```shell
Stack trace from the terraform-provider-azurerm_v4.32.0_x5 plugin:

panic: can't use ElementIterator on null value

goroutine 556 [running]:
github.com/hashicorp/go-cty/cty.Value.ElementIterator({{{0x8a2a4b8?, 0xc00259e2f0?}}, {0x0?, 0x0?}})
	github.com/hashicorp/go-cty@v1.4.1/cty/value_ops.go:1038 +0xbe
github.com/hashicorp/go-cty/cty.Value.AsValueMap({{{0x8a2a4b8?, 0xc00259e2f0?}}, {0x0?, 0x0?}})
	github.com/hashicorp/go-cty@v1.4.1/cty/value_ops.go:1243 +0x99
github.com/hashicorp/terraform-provider-azurerm/internal/services/containerapps.(*ContainerAppEnvironmentResource).Read.ContainerAppEnvironmentResource.Read.func1({0x8a269e0, 0xc0002508c0}, {0xc0014ee908, {0x8a2a3a0, 0xc000527488}, 0xc000307480, 0x0, {0x8a2ac18, 0xdc65640}})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/containerapps/container_app_environment_resource.go:362 +0x5f0
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.(*ResourceWrapper).Resource.func3({0x8a269e0, 0xc0002508c0}, 0x8a0d630?, {0x7152a40?, 0xc0014ee908?})
	github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:69 +0x145
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.(*ResourceWrapper).Resource.(*ResourceWrapper).diagnosticsWrapper.diagnosticsWrapper.func11({0x8a269e0?, 0xc0002508c0?}, 0x1176592e000?, {0x7152a40?, 0xc0014ee908?})
	github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:188 +0x59
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000650600, {0x8a26938, 0xc004f59380}, 0xc000307480, {0x7152a40, 0xc0014ee908})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:855 +0x119
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000650600, {0x8a26938, 0xc004f59380}, 0xc001bb3380, {0x7152a40, 0xc0014ee908})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:1149 +0x53a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0009aba40, {0x8a26938?, 0xc004f592c0?}, 0xc0013702c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/grpc_provider.go:739 +0x6c5
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ReadResource(0xc000307a00, {0x8a26938?, 0xc004f58ff0?}, 0xc0013702c0)
	github.com/hashicorp/terraform-plugin-mux@v0.17.0/tf5muxserver/mux_server_ReadResource.go:35 +0x190
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000996320, {0x8a26938?, 0xc004f58810?}, 0xc0002502a0)
	github.com/hashicorp/terraform-plugin-go@v0.26.0/tfprotov5/tf5server/server.go:784 +0x2f3
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x8020740, 0xc000996320}, {0x8a26938, 0xc004f58810}, 0xc000307080, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.26.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:575 +0x1a9
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0015c2000, {0x8a26938, 0xc004f587b0}, 0xc005436900, 0xc001597bf0, 0xdc31bc8, 0x0)
	google.golang.org/grpc@v1.69.4/server.go:1392 +0xfbe
google.golang.org/grpc.(*Server).handleStream(0xc0015c2000, {0x8a2a908, 0xc001c65d40}, 0xc005436900)
	google.golang.org/grpc@v1.69.4/server.go:1802 +0xb88
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.69.4/server.go:1030 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 23
	google.golang.org/grpc@v1.69.4/server.go:1041 +0x11d

Error: The terraform-provider-azurerm_v4.32.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

Refreshing the state should work, instead the provider panics.

### Actual Behaviour

The provider panics

### Steps to Reproduce

1. Container App Environment is deployed without any analytics settings
2. A Log Analytics Workspace from another subscription is set via UI.
3. Terraform is unable to refresh the state afterwards, even though all changes regarding the 2 fields are supposed to be ignored.

The resource json of the adjusted resource:

```json
{
    "id": "/subscriptions/REDACTED/REDACTED/providers/Microsoft.App/managedEnvironments/REDACTED-cae",
    "name": "REDACTED-cae",
    "type": "Microsoft.App/managedEnvironments",
    "location": "Sweden Central",
    "systemData": {
        "createdBy": "REDACTED",
        "createdByType": "Application",
        "createdAt": "REDACTED",
        "lastModifiedBy": "REDACTED",
        "lastModifiedByType": "User",
        "lastModifiedAt": "REDACTED"
    },
    "properties": {
        "provisioningState": "Succeeded",
        "daprAIInstrumentationKey": null,
        "daprAIConnectionString": null,
        "vnetConfiguration": {
            "internal": true,
            "infrastructureSubnetId": "/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Network/virtualNetworks/REDACTED/subnets/REDACTED-CAE",
            "dockerBridgeCidr": null,
            "platformReservedCidr": null,
            "platformReservedDnsIP": null
        },
        "defaultDomain": "REDACTED.azurecontainerapps.io",
        "staticIp": "REDACTED",
        "appLogsConfiguration": {
            "destination": "log-analytics",
            "logAnalyticsConfiguration": {
                "customerId": "REDACTED",
                "sharedKey": null,
                "dynamicJsonColumns": false
            }
        },
        "openTelemetryConfiguration": null,
        "zoneRedundant": false,
        "availabilityZones": null,
        "kedaConfiguration": {
            "version": "2.16.1"
        },
        "daprConfiguration": {
            "version": "1.13.6-msft.2"
        },
        "ingressConfiguration": null,
        "eventStreamEndpoint": "https://swedencentral.azurecontainerapps.dev/subscriptions/REDACTED/resourceGroups/REDACTED/managedEnvironments/REDACTED-cae/eventstream",
        "customDomainConfiguration": {
            "customDomainVerificationId": "REDACTED",
            "dnsSuffix": null,
            "certificateKeyVaultProperties": null,
            "certificateValue": null,
            "certificatePassword": null,
            "thumbprint": null,
            "subjectName": null,
            "expirationDate": null
        },
        "workloadProfiles": [
            {
                "workloadProfileType": "Consumption",
                "name": "Consumption",
                "enableFips": false
            }
        ],
        "appInsightsConfiguration": null,
        "infrastructureResourceGroup": "REDACTED_CAE",
        "peerAuthentication": {
            "mtls": {
                "enabled": false
            }
        },
        "peerTrafficConfiguration": {
            "encryption": {
                "enabled": false
            }
        },
        "publicNetworkAccess": "Disabled",
        "diskEncryptionConfiguration": null
    }
}
```

### Important Factoids

_No response_

### References

Maybe related to: https://github.com/hashicorp/terraform-provider-azurerm/issues/29756, but the setting is somewhat different.

### PR DESCRIPTION
**Pull request by ziyeqf**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

When the `log_anaylytics_workspace_id`  is from another subscription, the original code can not retire the id. And during refreshing stage, the provider can not get raw configuration. Thus I set the property during creation and updating. 

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)
image
The failed test shall not relate to this PR

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_container_app_environment` - fix a panic when the `log_analytics_workspace_id` is from another subscription [GH-00000]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #29816
Fixes #29446 

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/containerapps/container_app_environment_resource.go [hunk 1]
```diff
@@ -311,6 +311,10 @@ func (r ContainerAppEnvironmentResource) Create() sdk.ResourceFunc {
 				return fmt.Errorf("creating %s: %+v", id, err)
 			}
 
+			// Set the `log_analytics_workspace_id` during creation, in case the workspcae is created on another subscription.
```
Comment (rbange) [inline internal/services/containerapps/container_app_environment_resource.go]:
```suggestion
			// Set the `log_analytics_workspace_id` during creation, in case the workspace is created on another subscription.
```

File: internal/services/containerapps/container_app_environment_resource.go [hunk 2]
```diff
@@ -491,6 +491,10 @@ func (r ContainerAppEnvironmentResource) Update() sdk.ResourceFunc {
 								SharedKey:  sharedKey,
 							},
 						}
+						// Set the `log_analytics_workspace_id` during creation, in case the workspcae is created on another subscription.
```
Comment (rbange) [inline internal/services/containerapps/container_app_environment_resource.go]:
```suggestion
						// Set the `log_analytics_workspace_id` during creation, in case the workspace is created on another subscription.
```

**Comment by benjamin-rousseau-shift** [comment]
It's weird locally on my laptop I can apply container_app_environment with a log analytics workspace id that is in another subscription.

However when I try to do the same thing using a federated identity in a pipeline, it fails with panic error from terraform.

Indeed I removed the log analytics workspace id and it works in my pipeline. Any plan to release the fix ?

**Comment by ziyeqf** [comment]
new test result:
image

**Review by catriona-m — APPROVED** [review]
Thanks for adding the additional test @ziyeqf LGTM!
