### PR TITLE
Changed admin_username and key_data to require a new resource. 

### LINKED ISSUE #903: Leaving azurerm_kubernetes_cluster ssh_key key_data blank causes a terraform crash
### Terraform Version
```
Terraform v0.11.3
+ provider.azurerm (unversioned)
+ provider.random v1.1.0
```

### Affected Resource(s)
- terraform-provider-azurerm

### Terraform Configuration Files
```hcl
#from example
resource "azurerm_kubernetes_cluster" "aks_container" {
    name        = "akc-${random_integer.random_int.result}"
    location    = "${var.resource_group_location}"
    dns_prefix  = "akc-${random_integer.random_int.result}"

    resource_group_name = "${azurerm_resource_group.akc-rg.name}"
    kubernetes_version  = "1.8.7"


    linux_profile {
        admin_username = "${var.linux_admin_username}"
        ssh_key {
            key_data = ""
        }
    }

    agent_pool_profile {
        name        = "agentpool"
        count       = "2"
        vm_size     = "Standard_DS2_v2"
        os_type     = "Linux"
    }

    service_principal {
        client_id     = "${var.client_id}"
        client_secret = "${var.client_secret}"
    }
}
```

### Debug Output
https://gist.github.com/katbyte/102cc21b01c10901386e1b564cfd17ab

### Panic Output
https://gist.github.com/katbyte/102cc21b01c10901386e1b564cfd17ab

### Expected Behavior
A graceful failure.

### Actual Behavior
Terraform actually crashed.

### Steps to Reproduce
Leave the ssh_key data blank

### Important Factoids
no

### References
- GH-896

### PR DESCRIPTION
**Pull request by katbyte**
Also fixed a terraform crash when key_data is empty. Added Kubernetes cluster example. Fixes #903, #895

### CODE REVIEW

File: azurerm/resource_arm_kubernetes_cluster.go [hunk 1]
```diff
@@ -376,9 +379,10 @@ func expandAzureRmKubernetesClusterLinuxProfile(d *schema.ResourceData) containe
...
-	key := linuxKeys[0].(map[string]interface{})
-	keyData := key["key_data"].(string)
-
+	keyData := ""
+	if key, ok := linuxKeys[0].(map[string]interface{}); ok {
+		keyData = key["key_data"].(string)
+	}
 	sshPublicKey := containerservice.SSHPublicKey{
 		KeyData: &keyData,
 	}
```
Comment (tombuildsstuff) [inline azurerm/resource_arm_kubernetes_cluster.go]: _minor_ this'd probably be simpler as:

```
sshPublicKey := containerservice.SSHPublicKey{}
if key, ok := linuxKeys[0].(map[string]interface{}); ok {
  keyData = key["key_data"].(string)
  sshPublicKey.KeyData = &keyData
}
```

**Comment by katbyte** [comment]
Tests pass:
screen shot 2018-02-28 at 12 00 53
