### PR TITLE
azurerm_cosmosdb_account: ignore 500 responses from CheckNameExists() call

### LINKED ISSUE #3739: Error checking if CosmosDB Account 'XX' already exists
### Terraform (and AzureRM Provider) Version
* `Terraform v0.11.14`
* `provider.azurerm: version = "~> 1.30.1"`

### Affected Resource(s)

* `azurerm_cosmosdb_account`

### Terraform Configuration Files

We are using standard `azurerm_cosmosdb_account` resource and everything was working till this morning.

### Expected Behavior

Cosmos DB account is created.

### Actual Behavior

Apply fails with an error:
```
 azurerm_cosmosdb_account.cosmosdb_account: 1 error occurred:
 azurerm_cosmosdb_account.cosmosdb_account: Error checking if CosmosDB Account "xxx-ab-745dr" already exists (Resource Group "RG123_745dr_AB"): documentdb.DatabaseAccountsClient#CheckNameExists: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF
```

### PR DESCRIPTION
**Pull request by katbyte**
The API is suddenly failing with 500s when we check the DB name, so lets ignore it for now.

SDK issue: https://github.com/Azure/azure-sdk-for-go/issues/5157

fixes #3739

### CODE REVIEW

File: azurerm/resource_arm_cosmosdb_account.go [hunk 1]
```diff
@@ -328,7 +328,10 @@ func resourceArmCosmosDbAccountCreate(d *schema.ResourceData, meta interface{})
 
 	r, err := client.CheckNameExists(ctx, name)
 	if err != nil {
-		return fmt.Errorf("Error checking if CosmosDB Account %q already exists (Resource Group %q): %+v", name, resourceGroup, err)
+		// todo remove when https://github.com/Azure/azure-sdk-for-go/issues/5157 is fixed
+		if !utils.ResponseWasStatusCode(r, 500) {
```
Comment (tombuildsstuff) [inline azurerm/resource_arm_cosmosdb_account.go]: for consistency with the other resources it'd be nice to make this

```suggestion
		if !utils.ResponseWasStatusCode(r, http.StatusInternalServerError) {
```
