### PR TITLE
`azurerm_data_factory` - support for `global_parameter`

### LINKED ISSUE #11659: data_factory redeploy removes parameter within data_factory
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform 15.1 Azurerm 2.57

### Affected Resource(s)

* `azurerm_data_factory`

### Terraform Configuration Files

```hcl
resource "azurerm_data_factory" "datafactory" {
  # oparulesv1: "azurerm_data_factory": {"delete": 100, "create": 10, "modify": 1}
  name                = var.data_factory_name == null ? module.datafactoryname.azurecaf_name_result : var.data_factory_name
  location            = var.region
  resource_group_name = var.resource_group_name
  tags                = merge(var.extra_tags, var.service_tags, local.common_tags)

  identity {
    type = var.data_factory_identity_type
  }
}
```

### Expected Behaviour

We are creating datafactory with tags (works great), and the dev team is publishing datafactory content using git connection and azdevops pipelines. These pipelines removes the tags unfortunatly, but this is not the issue

On redeploy of terraform it says the tags are removes and adds them
```hcl
# azurerm_data_factory.datafactory will be updated in-place
  ~ resource "azurerm_data_factory" "datafactory" {
        id                     = "/subscriptions/*****"
        name                   = "adf-****"
      ~ tags                   = {
          + "Application" = "1"
          + "CloudType"   = "2"
          + "DebitCode"   = "3"
          + "Environment" = "4"
          + "Region"      = "5"
          + "SLA"         = "6"
        }
        # (3 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```
### Actual Behaviour

Tags are added fine, BUT it also removes all globalParameters within the azure datafactory. not sure if this is terraform of azure behavior, but it lists the changes in activity log from my account during terraform redeploy of tags

### Steps to Reproduce

1. `terraform apply` 

On subsequent datafactories that are pushed to via azdevops pipelines (which removes tags in arm template deployment)

### References

* #0000

### LINKED ISSUE #12042: Support for setting global parameters on Azure Data Factory
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am looking for an options to set [global parameters](https://docs.microsoft.com/en-us/azure/data-factory/author-global-parameters) on a Azure Data Factory.

### New or Affected Resource(s)

1. azurerm_data_factory (add argument to set the global parameters
2. azurerm_data_factory_global_parameters (have a separate resource to set global parameters).

### Potential Terraform Configuration

```hcl
resource "azurerm_data_factory" "example" {
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  global_parameters = {
         parameter1 = value1
         parameter2 = value2
  }
}
```

### References

- https://docs.microsoft.com/en-us/azure/data-factory/author-global-parameters

### PR DESCRIPTION
**Pull request by njuCZ**
fix #12042 
fix #11659

image

### CODE REVIEW

File: azurerm/internal/services/datafactory/data_factory_resource.go [hunk 1]
```diff
@@ -410,6 +453,27 @@ func expandDataFactoryRepoConfiguration(d *pluginsdk.ResourceData) (bool, datafa
 	return false, nil
 }
 
+func expandDataFactoryGlobalParameters(input []interface{}) (map[string]*datafactory.GlobalParameterSpecification, error) {
+	if len(input) == 0 || input[0] == nil {
```
Comment (mbfrahry) [inline azurerm/internal/services/datafactory/data_factory_resource.go:457]: We can remove this whole check because there can be any number of `global_parameters` specified. The for loop should handle any potential nil checks on individual items

File: azurerm/internal/services/datafactory/data_factory_resource.go [hunk 2]
```diff
@@ -410,6 +453,27 @@ func expandDataFactoryRepoConfiguration(d *pluginsdk.ResourceData) (bool, datafa
...
+		return nil, nil
+	}
+	result := make(map[string]*datafactory.GlobalParameterSpecification)
+	for _, item := range input {
+		v := item.(map[string]interface{})
```
Comment (mbfrahry) [inline azurerm/internal/services/datafactory/data_factory_resource.go:462]: We do need to make sure that this isn't nil before casting to it

**Review by mbfrahry — CHANGES_REQUESTED** [review]
This looks nearly there but I do have just a few comments on potential nil issues

**Comment by njuCZ** [comment]
@mbfrahry thanks for your suggestions. I have refined this PR.

**Review by mbfrahry — APPROVED** [review]
LGTM!
