### PR TITLE
apimanagement 2.0 todos and associated tests

### LINKED ISSUE #5612: Changing SKU of existing azurerm_api_management has no effect
Althought Terraform PLAN and APPLY both indicate they are altering the configuration of the APIM, the SKU is not updated.

image

I have left the operation 2+ hours to see if it is just delayed, but still no change.

There is an entry in the activity log for the APIM, but does not specifically show the change of SKU operation:

    "operationName": {
        "value": "Microsoft.ApiManagement/service/portalsettings/write",
        "localizedValue": "Update Settings or Update Settings or Update Settings or Update Settings or Update Settings or Update Settings"
    },
    "resourceGroupName": "RGNAME",
    "resourceProviderName": {
        "value": "Microsoft.ApiManagement",
        "localizedValue": "Microsoft.ApiManagement"
    },
    "resourceType": {
        "value": "Microsoft.ApiManagement/service/portalsettings",
        "localizedValue": "Microsoft.ApiManagement/service/portalsettings"
    },
    "resourceId": "/subscriptions/xxxxxxx/resourceGroups/RGNAME/providers/Microsoft.ApiManagement/service/apim/portalsettings/signup",
    "status": {
        "value": "Succeeded",
        "localizedValue": "Succeeded"
    },
    "subStatus": {
        "value": "OK",
        "localizedValue": "OK (HTTP Status Code: 200)"

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.20
provider "azurerm" (hashicorp/azurerm) 1.42.0

### Affected Resource(s)

* `azurerm_api_management`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

Create azurerm_api_management with 'Developer_1' sku_name. Change sku_name to 'Basic_1' and redeploy. Sku in portal shows no change.

### References

* #0000

### PR DESCRIPTION
**Pull request by jackofallops**
Fixes #5612

### CODE REVIEW

File: azurerm/internal/services/apimanagement/tests/resource_arm_api_management_api_operation_test.go [hunk 1]
```diff
@@ -239,7 +239,8 @@ resource "azurerm_api_management_api_operation" "test" {
 }
 
 func testAccAzureRMApiManagementApiOperation_requiresImport(data acceptance.TestData) string {
-	template := testAccAzureRMApiManagementApiOperation_template(data)
+	//template := testAccAzureRMApiManagementApiOperation_template(data)
```
Comment (tombuildsstuff) [inline azurerm/internal/services/apimanagement/tests/resource_arm_api_management_api_operation_test.go]:
```suggestion
```

**Comment by tombuildsstuff** [comment]
Tests look good 👍
