### PR TITLE
`azurerm_service_plan` -  fix `sku_name` case difference issue

### LINKED ISSUE #30745: azurerm_service_plan sku_name casing changing in place every run
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.5

### AzureRM Provider Version

4.44.0

### Affected Resource(s)/Data Source(s)

azurerm_service_plan

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_service_plan" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  os_type             = "Windows"
  sku_name            = "I1mv2"
}
```

### Debug Output/Panic Output

```shell
Can provide if necessary.
```

### Expected Behaviour

No changes when NOT updating the azurerm_service_plan resource. 

### Actual Behaviour

# azurerm_service_plan.plan will be updated in-place
~ resource "azurerm_service_plan" "plan" {
        id                = "..."
        name          = "example"
    ~ sku_name    = "I1mV2" -> "I1mv2"
        tags             = {}
        # (9 unchanged attributes hidden)
  }

### Steps to Reproduce

1) Deploy an azurerm_service_plan with a sku_name of "I1mv2", "I2mv2", "I3mv2", "I4mv2", or "I5mv2"
2) Trigger a new run after successful deployment

The sku_name attribute in the Azure Portal resource object is stored as "size": "I1mV2", instead of "size": "I1mv2", as both the terraform provider and azure documentation state. Therefore, each new successive run will update the service plan sku name to the lower case, per the provider, causing excess time and output.  

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by xiaxyi**
…alue in enum, this will address case difference issue

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Terraform provider defined a set of allowed sku value for the property `sku_name`, however, the api ignored the case format.  This PR will check the value in a case insensitive way then set the allowed format back

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-merging.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)

Fixes #30745 

## AI Assistance Disclosure

- [ ] AI Assisted - This contribution was made by, or with the assistance of, AI/LLMs

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Comment by xiaxyi** [comment]
Thanks @mbfrahry , of course we can add the suppress diff func directly, I just think it might be better if we parse the api response to macth with the value that we allowed before setting it back to state?

File: internal/services/appservice/service_plan_resource.go [hunk 1]
```diff
@@ -248,7 +248,11 @@ func (r ServicePlanResource) Read() sdk.ResourceFunc {
 				// sku read
 				if sku := model.Sku; sku != nil {
 					if sku.Name != nil {
-						state.Sku = *sku.Name
+						for _, item := range helpers.AllKnownServicePlanSkus() {
+							if strings.EqualFold(*sku.Name, item) {
```
Comment (mbfrahry) [inline internal/services/appservice/service_plan_resource.go]: We tend to want to use DiffSuppressFunc rather than custom code in the read function. Could we do that here instead or is there a reason we're going this route?

**Review by mbfrahry — CHANGES_REQUESTED** [review]
Hey @xiaxyi, I left a design question and then could you open an issue on the rest-api-specs and link that as a comment in the code?

**Review by sreallymatt — APPROVED** [review]
Thanks @xiaxyi LGTM ✅
