### PR TITLE
`azurerm_application_insights` - support for the MobileCenter kind

### LINKED ISSUE #1815: azurerm_application_insights could not target application_type = "MobileCenter"
hi, I'm trying import existing application insight resource. I faced to when Application Insight is made for MobileCenter, application_type would not match with any value.

## Step to reproduce

1. Create Application insight from AppCenter.
2. Import resource with Terraform.
3. run `terraform plan` will get mis-match for "application_type".

## terraform configuration

```
resource "azurerm_application_insights" "AppCenter" {
  name                = "AppCenter"
  location            = "westus2"
  resource_group_name = "resourceGroupName"
  application_type    = "other"
}
```

## Actual result

```
application_type:    "MobileCenter" => "Other" (forces new resource)
```

## Expected

If I can set `MobileCenter` as a application_type, issue will not happen.

```
resource "azurerm_application_insights" "AppCenter" {
  name                = "AppCenter"
  location            = "westus2"
  resource_group_name = "resourceGroupName"
  application_type    = "MobileCenter"
}
```

terraform plan will not detect change.

```
no diff
```

## Question

Am I missing some feature to match application_type?

### PR DESCRIPTION
**Pull request by tombuildsstuff**
```
$ acctests azurerm TestAccAzureRMApplicationInsights_basicMobileCenter
=== RUN   TestAccAzureRMApplicationInsights_basicMobileCenter
--- PASS: TestAccAzureRMApplicationInsights_basicMobileCenter (76.28s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	76.616s
```

Fixes #1815

### CODE REVIEW

File: azurerm/resource_arm_application_insights.go [hunk 1]
```diff
@@ -41,6 +41,7 @@ func resourceArmApplicationInsights() *schema.Resource {
 					"web",
 					"other",
 					"java",
+					"MobileCenter",
```
Comment (radeksimko) [inline azurerm/resource_arm_application_insights.go]: Nitpick: I'm assuming that given the `DiffSuppressFunc` we can keep the casing consistent here? i.e. `mobilecenter`?

Comment (tombuildsstuff) [reply azurerm/resource_arm_application_insights.go]: we could - however I'm hoping we can remove the diffSuppressFunc here in future, so I'm going to leave this as-is for the moment.
