### PR TITLE
azurerm_bot_channel_directline_speech: Change location and key to optional

### LINKED ISSUE #30234: azurerm_bot_channel_direct_line_speech: access_key and location should be optional
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.12.0

### AzureRM Provider Version

4.37.0

### Affected Resource(s)/Data Source(s)

azurerm_bot_channel_direct_line_speech

### Terraform Configuration Files

```hcl
resource "azurerm_bot_channel_direct_line_speech" "bot" {
  bot_name             = azurerm_bot_service_azure_bot.bot.name
  location             = azurerm_bot_service_azure_bot.bot.location
  resource_group_name  = azurerm_resource_group.bot.name
  cognitive_account_id = local.cognitive_account
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

It should be possible to provide *either* `cognitive_account_id` *or* `cognitive_service_access_key`+`cognitive_service_location`.

When configuring in the UI, you choose an account, and don't have to enter key+location.

### Actual Behaviour

key and location are required.

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by orgads**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

The resource input should contain either `cognitive_account_id` or both `cognitive_service_access_key` and `cognitive_service_location`.

## PR Checklist

- [X] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [X] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [X] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [X] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [X] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [X] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [X] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [X] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [X] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [X] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [X] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #30234

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Comment by orgads** [comment]
ping @WodansSon @magodo @sreallymatt

**Comment by orgads** [comment]
Acceptance tests:
```
=== RUN   TestAccBotChannelDirectLineSpeech_basic
=== PAUSE TestAccBotChannelDirectLineSpeech_basic
=== RUN   TestAccBotChannelDirectLineSpeech_requiresImport
=== PAUSE TestAccBotChannelDirectLineSpeech_requiresImport
=== RUN   TestAccBotChannelDirectLineSpeech_withAccessKey
=== PAUSE TestAccBotChannelDirectLineSpeech_withAccessKey
=== CONT  TestAccBotChannelDirectLineSpeech_basic
=== CONT  TestAccBotChannelDirectLineSpeech_withAccessKey
=== CONT  TestAccBotChannelDirectLineSpeech_requiresImport
--- PASS: TestAccBotChannelDirectLineSpeech_requiresImport (508.24s)
--- PASS: TestAccBotChannelDirectLineSpeech_basic (537.30s)
--- PASS: TestAccBotChannelDirectLineSpeech_withAccessKey (543.54s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/bot   554.864s
```

**Comment by orgads** [comment]
@jackofallops Can you please review this?

**Comment by orgads** [comment]
Rebased. Can anyone PLEASE review this?

@jackofallops @sreallymatt @mbfrahry

**Comment by orgads** [comment]
@jackofallops @sreallymatt @mbfrahry @catriona-m

This is not a large change, and I really need it to avoid ugly hacks. Please review it.

**Comment by orgads** [comment]
This is really frustrating. I spent hours fixing this and it has been ignored for nearly 3 months!

**Comment by orgads** [comment]
@jackofallops

**Comment by orgads** [comment]
@wyattfry @jackofallops anybody?

**Comment by orgads** [comment]
@catriona-m maybe?

**Comment by orgads** [comment]
@katbyte Can you maybe approve this? It's been hanging here for 6 months 😞

**Comment by orgads** [comment]
Rebased. @sreallymatt Can you please approve this too?

File: internal/services/bot/bot_channel_direct_line_speech_resource.go [hunk 1]
```diff
@@ -57,18 +57,28 @@ func resourceBotChannelDirectLineSpeech() *pluginsdk.Resource {
...
-				Type:         schema.TypeString,
-				Required:     true,
-				Sensitive:    true,
-				ValidateFunc: validation.StringIsNotEmpty,
+				Type:          schema.TypeString,
+				Optional:      true,
+				Sensitive:     true,
+				ValidateFunc:  validation.StringIsNotEmpty,
+				RequiredWith:  []string{"cognitive_service_location"},
+				ConflictsWith: []string{"cognitive_account_id"},
```
Comment (sreallymatt) [inline internal/services/bot/bot_channel_direct_line_speech_resource.go]: This is a breaking change, currently it is possible for users to have all of `cognitive_service_access_key`, `cognitive_service_location`, and `cognitive_account_id` in their configs, we cannot introduce `ConflictsWith` as that would break that behaviour

File: internal/services/bot/bot_channel_direct_line_speech_resource.go [hunk 2]
```diff
@@ -57,18 +57,28 @@ func resourceBotChannelDirectLineSpeech() *pluginsdk.Resource {
...
+				AtLeastOneOf:  []string{"cognitive_service_access_key", "cognitive_account_id"},
 			},
 
-			"cognitive_service_location": commonschema.LocationWithoutForceNew(),
+			"cognitive_service_location": {
+				Type:          schema.TypeString,
+				Optional:      true,
+				RequiredWith:  []string{"cognitive_service_access_key"},
+				ConflictsWith: []string{"cognitive_account_id"},
```
Comment (sreallymatt) [inline internal/services/bot/bot_channel_direct_line_speech_resource.go]: Same as above, also breaking

File: internal/services/bot/bot_channel_direct_line_speech_resource.go [hunk 3]
```diff
@@ -57,18 +57,28 @@ func resourceBotChannelDirectLineSpeech() *pluginsdk.Resource {
...
+			},
 
 			"cognitive_account_id": {
-				Type:         schema.TypeString,
-				Optional:     true,
-				ValidateFunc: cognitiveservicesaccounts.ValidateAccountID,
+				Type:          schema.TypeString,
+				Optional:      true,
+				ValidateFunc:  cognitiveservicesaccounts.ValidateAccountID,
+				ConflictsWith: []string{"cognitive_service_access_key", "cognitive_service_location"},
```
Comment (sreallymatt) [inline internal/services/bot/bot_channel_direct_line_speech_resource.go]: Same as above, also breaking

File: internal/services/bot/bot_channel_direct_line_speech_resource_test.go [hunk 4]
```diff
@@ -203,15 +202,95 @@ func (BotChannelDirectLineSpeechResource) update(data acceptance.TestData) strin
...
+  location                   = azurerm_bot_channels_registration.test.location
+  resource_group_name        = azurerm_resource_group.test.name
+  cognitive_account_id       = azurerm_cognitive_account.test2.id
+  custom_speech_model_id     = "cf7a4202-9be3-4195-9619-5a747260626d"
+  custom_voice_deployment_id = "b815f623-c217-4327-b765-f6e0fd7dceef"
+}
+`, BotChannelDirectLineSpeechResource{}.cognitiveAccountForUpdate(data))
+}
+
+func TestAccBotChannelDirectLineSpeech_validation(t *testing.T) {
```
Comment (sreallymatt) [inline internal/services/bot/bot_channel_direct_line_speech_resource_test.go]: This test can be removed, we don't add acceptance tests that test core functionalities of the terraform-plugin-sdk

File: internal/services/bot/bot_channel_direct_line_speech_resource_test.go [hunk 5]
```diff
@@ -6,6 +6,7 @@ package bot_test
 import (
```
Comment (sreallymatt) [inline internal/services/bot/bot_channel_direct_line_speech_resource_test.go:6]: Could you include a test that changes from `cognitive_account_id` to `cognitive_services_access_key` and `cognitive_service_location` and vice versa?

**Review by sreallymatt — CHANGES_REQUESTED** [review]

File: internal/services/bot/bot_channel_direct_line_speech_resource.go (hunk 1 above)
Comment (orgads) [reply internal/services/bot/bot_channel_direct_line_speech_resource.go]: Done

File: internal/services/bot/bot_channel_direct_line_speech_resource.go (hunk 2 above)
Comment (orgads) [reply internal/services/bot/bot_channel_direct_line_speech_resource.go]: Done

File: internal/services/bot/bot_channel_direct_line_speech_resource.go (hunk 3 above)
Comment (orgads) [reply internal/services/bot/bot_channel_direct_line_speech_resource.go]: Done

File: internal/services/bot/bot_channel_direct_line_speech_resource_test.go (hunk 4 above)
Comment (orgads) [reply internal/services/bot/bot_channel_direct_line_speech_resource_test.go]: Done

File: internal/services/bot/bot_channel_direct_line_speech_resource_test.go (hunk 5 above)
Comment (orgads) [reply internal/services/bot/bot_channel_direct_line_speech_resource_test.go:6]: Done (I hope).

**Review by sreallymatt — APPROVED** [review]
Thanks @orgads - I pushed some small changes as it appears the API does not support removal of `cognitive_account_id` when set, which was causing a failure in the update test.

New test results:

Image

**Review by catriona-m — APPROVED** [review]

**Comment by orgads** [comment]
Thank you!
