### PR TITLE
`azurerm_storage_account` - Support RAGZRS and GZRS `account_replication_type`

### LINKED ISSUE #7051: azurerm_storage_account account_replication_type GZRS
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
>  terraform version                                                                                                                                                                                                   
Terraform v0.12.23
+ provider.azurerm v1.43.0
+ provider.errorcheck v2.0.3
```

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl

resource "azurerm_storage_account" "backend" {
  name                      = var.storage_account_name
  resource_group_name       = azurerm_resource_group.backend.name
  location                  = var.location
  account_kind              = "StorageV2"
  account_tier              = "Standard"
  account_replication_type  = "GZRS"
  enable_https_traffic_only = true

  tags = local.common_tags
}
```

### Expected Behavior

Resource Created with GZRS replication type 

### Actual Behavior

```
Error: expected account_replication_type to be one of [LRS ZRS GRS RAGRS], got GZRS

  on main.tf line 13, in resource "azurerm_storage_account" "backend":
  13: resource "azurerm_storage_account" "backend" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The [terraform documentation does not mention a GZRS type](https://www.terraform.io/docs/providers/azurerm/r/storage_account.html#account_replication_type), if this is a provider version problem (we have lots of code using the old provider) than this is a docs issue and the terraform docs should be updated to reflect [the GZRS replication type](https://docs.microsoft.com/en-us/azure/storage/common/storage-redundancy?toc=/azure/storage/blobs/toc.json#geo-zone-redundant-storage)

### PR DESCRIPTION
**Pull request by lrxtom2**
Fixes #7051

### CODE REVIEW

File: azurerm/internal/services/storage/resource_arm_storage_account.go [hunk 1]
```diff
@@ -95,6 +95,8 @@ func resourceArmStorageAccount() *schema.Resource {
 					"ZRS",
 					"GRS",
 					"RAGRS",
+					"GZRS",
+					"RAGZRS",
```
Comment (tombuildsstuff) [inline azurerm/internal/services/storage/resource_arm_storage_account.go:99]: can we add a test-case for these? these can require a newer version of the Azure API

File: website/docs/r/storage_account.html.markdown [hunk 2]
```diff
@@ -90,7 +90,7 @@ The following arguments are supported:
 
 * `account_tier` - (Required) Defines the Tier to use for this storage account. Valid options are `Standard` and `Premium`. For `FileStorage` accounts only `Premium` is valid. Changing this forces a new resource to be created.
 
-* `account_replication_type` - (Required) Defines the type of replication to use for this storage account. Valid options are `LRS`, `GRS`, `RAGRS` and `ZRS`.
+* `account_replication_type` - (Required) Defines the type of replication to use for this storage account. Valid options are `LRS`, `GRS`, `RAGRS`, `ZRS`, `GZRS`, `RAGZRS`.
```
Comment (tombuildsstuff) [inline website/docs/r/storage_account.html.markdown:93]:
```suggestion
* `account_replication_type` - (Required) Defines the type of replication to use for this storage account. Valid options are `LRS`, `GRS`, `RAGRS`, `ZRS`, `GZRS` and `RAGZRS`.
```

**Comment by lrxtom2** [comment]
@tombuildsstuff Thanks for your comments! Updated testcase there.
