### PR TITLE
`azurerm_synapse_managed_private_endpoint` - migrate to `go-azure-sdk` and add `fully_qualified_domain_names` arg

### LINKED ISSUE #17305: azurerm_synapse_managed_private_endpoint add private link service needs additional field FQDN
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_synapse_managed_private_endpoint

### Terraform Configuration Files

```hcl
data "azurerm_private_link_service" "wan" {
  name                = "osdp-prod-wan"
  resource_group_name = "osdp-prod-wan-pls"
}
resource "azurerm_synapse_managed_private_endpoint" "wan" {
  name                 = "wan"
  synapse_workspace_id = azurerm_synapse_workspace.asa.id
  target_resource_id   = data.azurerm_private_link_service.wan.id
  subresource_name     = "" # empty according to the MS documentation
}
```

### Debug Output/Panic Output

```shell
│ Error: creating Managed Private Endpoint: (Name "wan" / Managed Virtual Network Name "default" / Workspace Name "osdp-chbsynapse" / Resource Group "osdp-prod-asa-chbsynapse"): managedvirtualnetwork.ManagedPrivateEndpointsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="UnknownError" Message="{\"CorrelationId\":\"\",\"StatusCode\":400,\"Message\":\"Invalid Request: Message=Invalid payload received. FQDN needs to be specified for the private endpoint targeting Private Link Service: /subscriptions/f2e16b2d-d5a1-4930-8b71-e28493120107/resourceGroups/osdp-prod-wan-pls/providers/Microsoft.Network/privateLinkServices/osdp-prod-wan.\",\"ExceptionDetail\":\"Microsoft.Analytics.Clusters.Common.ClusterServiceException: Invalid payload received. FQDN needs to be specified for the private endpoint targeting Private Link Service: /subscriptions/f2e16b2d-d5a1-4930-8b71-e28493120107/resourceGroups/osdp-prod-wan-pls/providers/Microsoft.Network/privateLinkServices/osdp-prod-wan.\\r\\n ---> System.ArgumentException: FQDN needs to be specified for the private endpoint targeting Private Link Service: /subscriptions/f2e16b2d-d5a1-4930-8b71-e28493120107/resourceGroups/osdp-prod-wan-pls/providers/Microsoft.Network/privateLinkServices/osdp-prod-wan.\\r\\n   at Microsoft.Analytics.Clusters.Services.NetworkService.Contract.PrivateEndpointRequest.Validate(IServiceConfiguration conf, ILog logger) in C:\\\\source\\\\Services\\\\NetworkService\\\\Contracts\\\\DataContracts\\\\PrivateEndpointRequest.cs:line 205\\r\\n   at Microsoft.Analytics.Clusters.Services.NetworkService.StatefulBE.Controllers.NetworkController.AddPrivateEndpointAsync(String clientId, String privateEndpointReferenceName, PrivateEndpointRequest request) in C:\\\\source\\\\Services\\\\NetworkService\\\\NetworkServiceBE\\\\Controllers\\\\NetworkController.cs:line 258\\r\\n   --- End of inner exception stack trace ---\\r\\n   at Microsoft.Analytics.Clusters.Services.NetworkService.StatefulBE.Controllers.NetworkController.AddPrivateEndpointAsync(String clientId, String privateEndpointReferenceName, PrivateEndpointRequest request) in C:\\\\source\\\\Services\\\\NetworkService\\\\NetworkServiceBE\\\\Controllers\\\\NetworkController.cs:line 258\\r\\n   at lambda_method(Closure , Object )\\r\\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\\r\\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\\r\\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\\r\\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\\r\\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\\r\\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\\r\\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\\r\\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\\r\\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\\r\\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\\r\\n   at Microsoft.Analytics.Clusters.Services.NetworkService.StatefulBE.ActivePartitionInstanceMiddleware.InvokeAsync(HttpContext context) in C:\\\\source\\\\Services\\\\NetworkService\\\\NetworkServiceBE\\\\ActivePartitionInstanceMiddleware.cs:line 90\\r\\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at Microsoft.Analytics.Clusters.Common.Web.ServiceFabricResourceNotFoundMiddleware.InvokeAsync(HttpContext httpContext) in C:\\\\source\\\\Shared\\\\Web\\\\ServiceFabricResourceNotFoundMiddleware.cs:line 50\\r\\n   at Microsoft.Analytics.Clusters.Common.Web.ExceptionMiddleware.InvokeAsync(HttpContext httpContext) in C:\\\\source\\\\Shared\\\\Web\\\\ExceptionMiddleware.cs:line 54\",\"ErrorType\":\"InvalidRequest\",\"ErrorNumber\":2190,\"ErrorOn\":\"2022-06-20T13:35:53.6620455+00:00\"}"
│ 
│   with module.azure-synapse-workspace.azurerm_synapse_managed_private_endpoint.wan,
│   on ../modules/azure-synapse-analytics/main.tf line 581, in resource "azurerm_synapse_managed_private_endpoint" "wan":
│  581: resource "azurerm_synapse_managed_private_endpoint" "wan" {
│
```

### Expected Behaviour

Creation of the Private Link Service Managed Private Endpoint

### Actual Behaviour

The above error is thrown. 

### Steps to Reproduce

Change the above code to your needs and apply it. 

In the end, it's about the fqdns field missing and not configurable in tf, while mandatory by azure. 

A successful config would look like this: 

```json
{
    "name": "PrivateLinkService416",
    "properties": {
        "privateLinkResourceId": "/subscriptions/.../resourceGroups/osdp-prod-wan-pls/providers/Microsoft.Network/privateLinkServices/osdp-prod-wan",
        "groupId": "",
        "fqdns": [
            "mysqlserver.example.com"
        ]
    }
}
```

### Important Factoids

_No response_

### References

_No response_

### LINKED ISSUE #23516: azurerm_synapse_managed_private_endpoint is not creating Synapse managed PE for PLS.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

Terraform v1.0.4

### AzureRM Provider Version

 v3.24.0 

### Affected Resource(s)/Data Source(s)

azurerm_synapse_managed_private_endpoint

### Terraform Configuration Files

```hcl
Config file, var-synapsemanagedpe.auto.tfvars
==================================
resource_group_name      = "[__resource_group_name__]"
synapse_workspace_name   = "synapse-test-ws01"

# Targets of managed private endpoint to be created in Synapse workspace
managedpe_targets = { 
   "pe1" = {
     name                           = "[__key_vault_name__]-mpe"
     private_connection_endpoint_id = "/subscriptions/[__subscription_id__]/resourceGroups/[__resource_group_name__]/providers/Microsoft.KeyVault/vaults/[__key_vault_name__]"
     subresource_name               =  "vault"
   },
   "pe2" = {
     name                           = "[__storage_account_name__]-mpe"
     private_connection_endpoint_id = "/subscriptions/[__subscription_id__]/resourceGroups/[__resource_group_name__]/providers/Microsoft.Storage/storageAccounts/[__storage_account_name__]"
     subresource_name               =  "blob"
   },
   "pe3" = {
     name                           = "[__bastion_mpe_name__]-mpe"
     private_connection_endpoint_id = "/subscriptions/xxxxxxxxxxxxx/resourceGroups/cnxs04-westus2-lb-rg-001/providers/Microsoft.Network/privateLinkServices/30050-cnxs04-westus2-001-proxy-pls"
     subresource_name               =  ""
   }
}


Root Module, synapsemanagedpe.tf
======================================

provider "azurerm" {
  tenant_id        = var.tenant_id
  subscription_id  = var.subscription_id
  client_id        = var.client_id
  client_secret    = var.client_secret
  partner_id       = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
    }
  }
}

provider "azurerm" {
  alias            = "ado"
  tenant_id        = var.tenant_id
  subscription_id  = var.ado_subscription_id
  client_id        = var.client_id
  client_secret    = var.client_secret
  partner_id       = "xxxxxxxxxxxxxxxxxxxxxxxx"
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
    }
  }
}

variable "subscription_id" {
  description = "ID of the workload subscription"
  type        = string
}

variable "tenant_id" {
  description = "ID of the workload tenant"
  type        = string
}

variable "client_id" {
  description = "ID of the workload subscription"
  type        = string
  default     = null
}

variable "client_secret" {
  description = "ID of the workload subscription"
  type        = string
  default     = null
}

variable "resource_group_name" {
  description = "Application resource group name where Synapse workspace resides."
}

variable "synapse_workspace_name" {
  description = "The name of the Synapse workspace where the managed private endpoints should be created."
}

variable "managedpe_targets" {
  type = map(object({
    name                           = string
    private_connection_endpoint_id = string
    subresource_name               = string
  }))
  description                        = "List of targeted resources info whose managed PE to be created in Synapse workspace."
}

data "azurerm_synapse_workspace" "this" {
  name                = var.synapse_workspace_name
  resource_group_name = var.resource_group_name
}

module "synapsemanagedpe" {
  source = "./modules/synapse_managed_pe"

  synapse_workspace_id      = data.azurerm_synapse_workspace.this.id
  managedpe_targets         = var.managedpe_targets

}

Child module, ./modules/synapse_managed_pe/main.tf
=====================================

resource "azurerm_synapse_managed_private_endpoint" "managed_private_endpoint" {
  for_each             = var.managedpe_targets

  name                 = each.value.name
  target_resource_id   = each.value.private_connection_endpoint_id
  subresource_name     = each.value.subresource_name
  
  synapse_workspace_id = var.synapse_workspace_id
}
```

### Debug Output/Panic Output

```shell
Error: creating Managed Private Endpoint: (Name "PLS-conexus-mpe" / Managed Virtual Network Name "default" / Workspace Name "synapse-test-ws01" / Resource Group "sm-westus2-smtest-app-rg"): managedvirtualnetwork.ManagedPrivateEndpointsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="UnknownError" Message="{\"CorrelationId\":\"\",\"StatusCode\":400,\"Message\":\"Invalid Request: Message=Invalid payload received. FQDN needs to be specified for the private endpoint targeting Private Link Service: /subscriptions/xxxx/resourceGroups/xxxxxxxx-rg-001/providers/Microsoft.Network/privateLinkServices/xxxxxxxxxxx-proxy-pls.\",\"ExceptionDetail\":\"Microsoft.Analytics.Clusters.Common.ClusterServiceException:

~~~
~~~
~~~
~~~

  with module.synapsemanagedpe.azurerm_synapse_managed_private_endpoint.managed_private_endpoint["pe3"],
  on modules/synapse_managed_pe/main.tf line 5, in resource "azurerm_synapse_managed_private_endpoint" "managed_private_endpoint":
   5: resource "azurerm_synapse_managed_private_endpoint" "managed_private_endpoint" {
```

### Expected Behaviour

There can be two expected behaviors.

1. The managed PE for private link service (PLS) should have been created without FQDN given at the time of creation and later it may be entered manually.
2. The azurerm_synapse_managed_private_endpoint resource should take FQDN as input to create the PLS.

But I believe we prefer the latter.

### Actual Behaviour

As shown in Debug output, which was from Terraform Plan pipeline, error was spitted...

Invalid Request: Message=Invalid payload received. FQDN needs to be specified for the private endpoint targeting Private Link Service

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

It looks like the issue I reported was taken care of for Azure Data Factory as shown below bug report and PR.

- hashicorp#15640 azurerm_data_factory_managed_private_endpoint with fqdns not defined will force replace resource.
- hashicorp #15644 making fqdns in data_factory_managed_private_endp…

### PR DESCRIPTION
**Pull request by sreallymatt**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

- migrates to new `go-azure-sdk` data plane SDK
- updates API version to `2021-06-01-preview` (from preview to new preview that is already used by this service package, will need to investigate migrating to stable in the future, out of scope for this change)
- adds the `fully_qualified_domain_names` argument

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-merging.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)

Fixes #17305 
Fixes #23516

## AI Assistance Disclosure

- [ ] AI Assisted - This contribution was made by, or with the assistance of, AI/LLMs

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Review by toddgiguere — DISMISSED** [review]

File: internal/services/synapse/custompollers/synapse_managed_private_endpoint_create_poller.go [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+	}
+
+	if *resp.Model.Properties.ProvisioningState == "Succeeded" {
+		return &pollers.PollResult{
+			Status: pollers.PollingStatusSucceeded,
+		}, nil
+	}
+
+	// The API spec doesn't document the provisioning states, so unless it's `Succeeded` we'll continue polling
+	// ideally we'd exit early on any terminal states that are not `Succeeded` but they are unknown.
```
Comment (jackofallops) [inline internal/services/synapse/custompollers/synapse_managed_private_endpoint_create_poller.go]: ARM spec states that the "standard" TerminalStates _should_ apply everywhere, so we should be fine to expect `Failed`, `Updating` etc. The spec also allows for any custom state, so maybe we only care about `Failed`, `Cancelled`, `InProgress` and `Succeeded`? (Use the const from the `pollers` package, rather than magic strings)

**Review by jackofallops — DISMISSED** [review]
Thanks @sreallymatt - looking good. Just one thing to take a look at for the custom poller and I think this should be good to go if the tests all pass.

**Comment by toddgiguere** [comment]
@sreallymatt LGTM ✅ 
There have been other vendor changes merged recently, you can rebase your branch from main and run the vendor command and it should get rid of existing conflicts.

**Comment by hc-github-team-tf-azure** [comment]
Build: [652932](https://hashicorp.teamcity.com/viewLog.html?buildId=652932)
PR: #32153

**Total:** 2
**Passed:** 0
**Failed:** 2

<details>
<summary>Test Details</summary>

<table>
<tr><td><b>Status</b></td><td><b>Test Name</b></td><td><b>Duration</b></td></tr>
<tr><td>❌ FAIL</td><td>TestAccSynapseManagedPrivateEndpoint_requiresImport</td><td>783.55s</td></tr>
<tr><td>❌ FAIL</td><td>TestAccSynapseManagedPrivateEndpoint_basic</td><td>804.80s</td></tr></table>
</details>

**Comment by sreallymatt** [comment]
Tests failed due to the Dalek cleaning up resources in the subscription. Subsequent run passed:

image

**Review by toddgiguere — APPROVED** [review]
