### PR TITLE
Fix missing schema definition in terraform state

### LINKED ISSUE #12002: azurerm_api_management_api_schema always updated
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
> terraform -version
Terraform v0.15.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.58.0
```
### Affected Resource(s)

* `azurerm_api_management_api_schema`

### Terraform Configuration Files

```hcl
data "azurerm_api_management" "apim" {
  name                = "api-bug-test"
  resource_group_name = var.resource_group
}

resource "azurerm_api_management_api" "api_definition" {
  name                = "bug-schema"
  resource_group_name = var.resource_group
  api_management_name = data.azurerm_api_management.apim.name
  protocols           = ["https"]
  revision            = "1"
  display_name        = "bug-schema"
  path                = "bug-schema"
}

resource "azurerm_api_management_api_schema" "schema" {
  api_name            = azurerm_api_management_api.api_definition.name
  api_management_name = data.azurerm_api_management.apim.name
  resource_group_name = var.resource_group
  schema_id           = "schema"
  content_type        = "application/vnd.ms-azure-apim.swagger.definitions+json"
  value               = <<JSON
    {
      "schema-bug-example": {
          "type": "object",
          "properties": {
              "field1": {
                  "type": "string",
                  "description": "Field1"
              },
              "Field2": {
                  "type": "string",
                  "description": "Field2"
              },
          },
          "required": [
              "field1",
              "Field2",
          ]
      }
    }
JSON
}
```

### Debug Output

```
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe: [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/XXX/resourceGroups/XRGX/providers/Microsoft.ApiManagement/service/api-bug-test/apis/bug-schema/schemas/schema?api-version=2020-12-01: 
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe: HTTP/2.0 200 OK
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe: Cache-Control: no-cache
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe: Content-Type: application/json; charset=utf-8
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe: Date: Fri, 28 May 2021 10:13:08 GMT
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe: Etag: "AAAAAAAAFXk="
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe: Expires: -1
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe: Pragma: no-cache
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe: Server: Microsoft-HTTPAPI/2.0
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe: Strict-Transport-Security: max-age=31536000; includeSubDomains
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe: Vary: Accept-Encoding
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe: X-Content-Type-Options: nosniff
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe: X-Ms-Correlation-Request-Id: df5970f6-821a-f820-1714-409fedce6fd6
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe: X-Ms-Ratelimit-Remaining-Subscription-Reads: 11996
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe: X-Ms-Request-Id: b7d22b8c-1ee1-4024-b784-ddbce605612c
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe: X-Ms-Routing-Request-Id: GERMANYNORTH:20210528T101309Z:8be57fa6-cd4e-48f2-b4ee-1052d76d4b11
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe: 
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe: {
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:   "id": "/subscriptions/XXX/resourceGroups/XRGX/providers/Microsoft.ApiManagement/service/api-bug-test/apis/bug-schema/schemas/schema",
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:   "type": "Microsoft.ApiManagement/service/apis/schemas",
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:   "name": "schema",
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:   "properties": {
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:     "contentType": "application/vnd.ms-azure-apim.swagger.definitions+json",
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:     "document": {
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:       "definitions": {
2021-05-28T12:13:09.301+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:         "schema-bug-example": {
2021-05-28T12:13:09.302+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:           "type": "object",
2021-05-28T12:13:09.302+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:           "properties": {
2021-05-28T12:13:09.302+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:             "field1": {
2021-05-28T12:13:09.302+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:               "type": "string",
2021-05-28T12:13:09.302+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:               "description": "Field1"
2021-05-28T12:13:09.302+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:             },
2021-05-28T12:13:09.302+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:             "Field2": {
2021-05-28T12:13:09.302+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:               "type": "string",
2021-05-28T12:13:09.302+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:               "description": "Field2"
2021-05-28T12:13:09.302+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:             }
2021-05-28T12:13:09.302+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:           },
2021-05-28T12:13:09.302+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:           "required": [
2021-05-28T12:13:09.302+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:             "field1",
2021-05-28T12:13:09.302+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:             "Field2"
2021-05-28T12:13:09.302+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:           ]
2021-05-28T12:13:09.302+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:         }
2021-05-28T12:13:09.303+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:       }
2021-05-28T12:13:09.303+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:     }
2021-05-28T12:13:09.303+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe:   }
2021-05-28T12:13:09.303+0200 [DEBUG] provider.terraform-provider-azurerm_v2.58.0_x5.exe: }
2021-05-28T12:13:09.301+0200 [WARN]  Provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value for azurerm_api_management_api_schema.schema, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .value: was cty.StringVal("    {\r\n      \"schema-bug-example\": {\r\n          \"type\": \"object\",\r\n          \"properties\": {\r\n              \"field1\": {\r\n                  \"type\": \"string\",\r\n                  \"description\": \"Field1\"\r\n              },\r\n              \"Field2\": {\r\n                  \"type\": \"string\",\r\n                  \"description\": \"Field2\"\r\n              },\r\n          },\r\n          \"required\": [\r\n              \"field1\",\r\n              \"Field2\",\r\n          ]\r\n      }\r\n    }\r\n"), but now cty.StringVal("")
```

### Expected Behaviour

After apply of this HCL script calling `terraform plan` should result in no changes to be deployed.

### Actual Behaviour

After apply of this HCL script, all following `terraform plan` updates the content of API Schema object

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### References

I suspect following [line of code](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/apimanagement/api_management_api_schema_resource.go#L143). As far as I did some debugging of azure-go-sdk, it looks like the response is in `documentProperties.Definitions` not `.Value`.

### PR DESCRIPTION
**Pull request by wiktorn**
Add support for Swagger based schema definitions.

Additional changes:
* add checks in test that verify, that state includes requested schema
* wait in `resourceApiManagementApiSchemaCreateUpdate` until resource is created to avoid race with following GET, which results in inconsistent state (resource created but not present in state)
* add suppress.JsonDiff for suppression of non-essential changes in JSON's
 
Fixes  #12002.

Test results:
```
TF_ACC=1 go test -v ./azurerm/internal/services/apimanagement -run=TestAccApiManagementApiSchema -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
2021/06/12 03:19:48 [DEBUG] not using binary driver name, it's no longer needed
2021/06/12 03:19:48 [WARN] could not locate a terraform executable on system path; continuing
2021/06/12 03:19:53 [DEBUG] not using binary driver name, it's no longer needed
2021/06/12 03:19:53 [WARN] could not locate a terraform executable on system path; continuing
=== RUN   TestAccApiManagementApiSchema_basic
=== PAUSE TestAccApiManagementApiSchema_basic
=== RUN   TestAccApiManagementApiSchema_basicSwagger
=== PAUSE TestAccApiManagementApiSchema_basicSwagger
=== RUN   TestAccApiManagementApiSchema_requiresImport
=== PAUSE TestAccApiManagementApiSchema_requiresImport
=== CONT  TestAccApiManagementApiSchema_basic
=== CONT  TestAccApiManagementApiSchema_requiresImport
=== CONT  TestAccApiManagementApiSchema_basicSwagger
--- PASS: TestAccApiManagementApiSchema_basicSwagger (3998.26s)
--- PASS: TestAccApiManagementApiSchema_requiresImport (4125.60s)
--- PASS: TestAccApiManagementApiSchema_basic (4404.69s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/apimanagement       4413.150s
```

### CODE REVIEW

**Comment by wiktorn** [comment]
I'd welcome any guidance on how to prepare test cases for that issue. It's not clear for me, how to test for specific value in nested structures currently.

**Comment by katbyte** [comment]
Looks like we have some test failures now:
```
------- Stdout: -------
=== RUN   TestAccApiManagementApiSchema_basic
=== PAUSE TestAccApiManagementApiSchema_basic
=== CONT  TestAccApiManagementApiSchema_basic
    testing.go:620: Step 1/2 error: Error running pre-apply refresh: exit status 1
        
        Error: Invalid function argument
        
          on terraform_plugin_test.tf line 38, in resource "azurerm_api_management_api_schema" "test":
          38:   value               = file("testdata/api_management_api_pluginsdk.xml")
        
        Invalid value for "path" parameter: no file exists at
        testdata/api_management_api_pluginsdk.xml; this function works only with
        files that are distributed as part of the configuration source code, so if
        this file will be created by a resource in this configuration you must
        instead obtain this result from an attribute of that resource.
--- FAIL: TestAccApiManagementApiSchema_basic (7.35s)
FAIL

------- Stderr: -------
2021/06/03 16:50:35 [DEBUG] not using binary driver name, it's no longer needed
2021/06/03 16:50:35 [DEBUG] not using binary driver name, it's no longer needed
```

**Comment by wiktorn** [comment]
@katbyte 
missing `testdata/api_management_api_pluginsdk.xml` is a result of   f989e9b2fb2ea42a09726061f045fb0e279d848f.

It changes `testdata/api_management_api_schema.xml` to `testdata/api_management_api_pluginsdk.xml` but doesn't provide necessary file in the commit.

File: azurerm/internal/services/apimanagement/api_management_api_schema_resource.go [hunk 1]
```diff
@@ -140,7 +140,7 @@ func resourceApiManagementApiSchemaRead(d *pluginsdk.ResourceData, meta interfac
 	if properties := resp.SchemaContractProperties; properties != nil {
 		d.Set("content_type", properties.ContentType)
 		if documentProperties := properties.SchemaDocumentProperties; documentProperties != nil {
-			d.Set("value", documentProperties.Value)
+			d.Set("value", documentProperties.Definitions)
```
[the remark this answers is not in the document]
Comment (wiktorn) [reply azurerm/internal/services/apimanagement/api_management_api_schema_resource.go:143]: I'll check the Azure docs and prepare solution that checks necessary field based on content type.

**Comment by wiktorn** [comment]
@tombuildsstuff I reviewed Azure docs and added necessary logic
@katbyte For now, I used as a base 46174df4a7fd859984189b31d037054f4f5e7e49 (parent commit of the one that introduced breaking change in the tests. This PR of course needs adaptation to sdkv2 shim. But the tests will start to fail and I'm not sure how they should be fixed. I'd love if you could point me out, how these tests can be fixed.

**Comment by wiktorn** [comment]
I see that the tests were fixed, I've rebased the changes to recent master.

**Comment by katbyte** [comment]
Thanks @wiktorn - looks like we have a different type of test failure now:
```
------- Stdout: -------
=== RUN   TestAccApiManagementApiSchema_basic
=== PAUSE TestAccApiManagementApiSchema_basic
=== CONT  TestAccApiManagementApiSchema_basic
    testing.go:620: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # azurerm_api_management_api_schema.test will be updated in-place
          ~ resource "azurerm_api_management_api_schema" "test" {
                id                  = "/subscriptions/*******/resourceGroups/acctestRG-210611210113978406/providers/Microsoft.ApiManagement/service/acctestAM-210611210113978406/apis/acctestapi-210611210113978406/schemas/acctestSchema210611210113978406"
              + value               = <<-EOT
                    <s:schema elementFormDefault=\"qualified\" targetNamespace=\"http://ws.cdyne.com/WeatherWS/\" xmlns:tns=\"http://ws.cdyne.com/WeatherWS/\" xmlns:s=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap12=\"http://schemas.xmlsoap.org/wsdl/soap12/\" xmlns:mime=\"http://schemas.xmlsoap.org/wsdl/mime/\" xmlns:soap=\"http://schemas.xmlsoap.org/wsdl/soap/\" xmlns:tm=\"http://microsoft.com/wsdl/mime/textMatching/\" xmlns:http=\"http://schemas.xmlsoap.org/wsdl/http/\" xmlns:soapenc=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\" xmlns:apim-wsdltns=\"http://ws.cdyne.com/WeatherWS/\">\r\n  <s:element name=\"GetWeatherInformation\">\r\n    <s:complexType />\r\n  </s:element>\r\n  <s:element name=\"GetWeatherInformationResponse\">\r\n    <s:complexType>\r\n      <s:sequence>\r\n        <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"GetWeatherInformationResult\" type=\"tns:ArrayOfWeatherDescription\" />\r\n      </s:sequence>\r\n    </s:complexType>\r\n  </s:element>\r\n  <s:complexType name=\"ArrayOfWeatherDescription\">\r\n    <s:sequence>\r\n      <s:element minOccurs=\"0\" maxOccurs=\"unbounded\" name=\"WeatherDescription\" type=\"tns:WeatherDescription\" />\r\n    </s:sequence>\r\n  </s:complexType>\r\n  <s:complexType name=\"WeatherDescription\">\r\n    <s:sequence>\r\n      <s:element minOccurs=\"1\" maxOccurs=\"1\" name=\"WeatherID\" type=\"s:short\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"Description\" type=\"s:string\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"PictureURL\" type=\"s:string\" />\r\n    </s:sequence>\r\n  </s:complexType>\r\n  <s:element name=\"GetCityForecastByZIP\">\r\n    <s:complexType>\r\n      <s:sequence>\r\n        <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"ZIP\" type=\"s:string\" />\r\n      </s:sequence>\r\n    </s:complexType>\r\n  </s:element>\r\n  <s:element name=\"GetCityForecastByZIPResponse\">\r\n    <s:complexType>\r\n      <s:sequence>\r\n        <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"GetCityForecastByZIPResult\" type=\"tns:ForecastReturn\" />\r\n      </s:sequence>\r\n    </s:complexType>\r\n  </s:element>\r\n  <s:complexType name=\"ForecastReturn\">\r\n    <s:sequence>\r\n      <s:element minOccurs=\"1\" maxOccurs=\"1\" name=\"Success\" type=\"s:boolean\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"ResponseText\" type=\"s:string\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"State\" type=\"s:string\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"City\" type=\"s:string\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"WeatherStationCity\" type=\"s:string\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"ForecastResult\" type=\"tns:ArrayOfForecast\" />\r\n    </s:sequence>\r\n  </s:complexType>\r\n  <s:complexType name=\"ArrayOfForecast\">\r\n    <s:sequence>\r\n      <s:element minOccurs=\"0\" maxOccurs=\"unbounded\" name=\"Forecast\" nillable=\"true\" type=\"tns:Forecast\" />\r\n    </s:sequence>\r\n  </s:complexType>\r\n  <s:complexType name=\"Forecast\">\r\n    <s:sequence>\r\n      <s:element minOccurs=\"1\" maxOccurs=\"1\" name=\"Date\" type=\"s:dateTime\" />\r\n      <s:element minOccurs=\"1\" maxOccurs=\"1\" name=\"WeatherID\" type=\"s:short\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"Desciption\" type=\"s:string\" />\r\n      <s:element minOccurs=\"1\" maxOccurs=\"1\" name=\"Temperatures\" type=\"tns:temp\" />\r\n      <s:element minOccurs=\"1\" maxOccurs=\"1\" name=\"ProbabilityOfPrecipiation\" type=\"tns:POP\" />\r\n    </s:sequence>\r\n  </s:complexType>\r\n  <s:complexType name=\"temp\">\r\n    <s:sequence>\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"MorningLow\" type=\"s:string\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"DaytimeHigh\" type=\"s:string\" />\r\n    </s:sequence>\r\n  </s:complexType>\r\n  <s:complexType name=\"POP\">\r\n    <s:sequence>\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"Nighttime\" type=\"s:string\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"Daytime\" type=\"s:string\" />\r\n    </s:sequence>\r\n  </s:complexType>\r\n  <s:element name=\"GetCityWeatherByZIP\">\r\n    <s:complexType>\r\n      <s:sequence>\r\n        <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"ZIP\" type=\"s:string\" />\r\n      </s:sequence>\r\n    </s:complexType>\r\n  </s:element>\r\n  <s:element name=\"GetCityWeatherByZIPResponse\">\r\n    <s:complexType>\r\n      <s:sequence>\r\n        <s:element minOccurs=\"1\" maxOccurs=\"1\" name=\"GetCityWeatherByZIPResult\" type=\"tns:WeatherReturn\" />\r\n      </s:sequence>\r\n    </s:complexType>\r\n  </s:element>\r\n  <s:complexType name=\"WeatherReturn\">\r\n    <s:sequence>\r\n      <s:element minOccurs=\"1\" maxOccurs=\"1\" name=\"Success\" type=\"s:boolean\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"ResponseText\" type=\"s:string\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"State\" type=\"s:string\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"City\" type=\"s:string\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"WeatherStationCity\" type=\"s:string\" />\r\n      <s:element minOccurs=\"1\" maxOccurs=\"1\" name=\"WeatherID\" type=\"s:short\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"Description\" type=\"s:string\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"Temperature\" type=\"s:string\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"RelativeHumidity\" type=\"s:string\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"Wind\" type=\"s:string\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"Pressure\" type=\"s:string\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"Visibility\" type=\"s:string\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"WindChill\" type=\"s:string\" />\r\n      <s:element minOccurs=\"0\" maxOccurs=\"1\" name=\"Remarks\" type=\"s:string\" />\r\n    </s:sequence>\r\n  </s:complexType>\r\n  <s:element name=\"ArrayOfWeatherDescription\" nillable=\"true\" type=\"tns:ArrayOfWeatherDescription\" />\r\n  <s:element name=\"ForecastReturn\" nillable=\"true\" type=\"tns:ForecastReturn\" />\r\n  <s:element name=\"WeatherReturn\" type=\"tns:WeatherReturn\" />\r\n</s:schema>
                EOT
                # (5 unchanged attributes hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccApiManagementApiSchema_basic (4026.44s)
FAIL

------- Stderr: -------
2021/06/11 21:01:13 [DEBUG] not using binary driver name, it's no longer needed
2021/06/11 21:01:13 [DEBUG] not using binary driver name, it's no longer needed
```

**Comment by wiktorn** [comment]
Sorry, linting fixes broke the acceptance tests and I didn't rerun the tests (my bad).

```
TF_ACC=1 go test -v ./azurerm/internal/services/apimanagement -run=TestAccApiManagementApiSchema -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
2021/06/16 13:43:25 [DEBUG] not using binary driver name, it's no longer needed
2021/06/16 13:43:25 [WARN] could not locate a terraform executable on system path; continuing
2021/06/16 13:43:29 [DEBUG] not using binary driver name, it's no longer needed
2021/06/16 13:43:29 [WARN] could not locate a terraform executable on system path; continuing
=== RUN   TestAccApiManagementApiSchema_basic
=== PAUSE TestAccApiManagementApiSchema_basic
=== RUN   TestAccApiManagementApiSchema_basicSwagger
=== PAUSE TestAccApiManagementApiSchema_basicSwagger
=== RUN   TestAccApiManagementApiSchema_requiresImport
=== PAUSE TestAccApiManagementApiSchema_requiresImport
=== CONT  TestAccApiManagementApiSchema_basic
=== CONT  TestAccApiManagementApiSchema_requiresImport
=== CONT  TestAccApiManagementApiSchema_basicSwagger
--- PASS: TestAccApiManagementApiSchema_basicSwagger (4114.53s)
--- PASS: TestAccApiManagementApiSchema_basic (4116.91s)
--- PASS: TestAccApiManagementApiSchema_requiresImport (4370.86s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/apimanagement       4378.512s
```

**Comment by wiktorn** [comment]
@katbyte And one more idea come to my mind, as in this area - there Consumption based instance is enough to test, maybe it's worth to use it? It reduces dramatically time needed to run the tests. In my recent run it took 267 seconds with Consumption tier compared to 4378 seconds with Developer tier.

The only drawback is, that you need more comprehensive knowledge about specific service to know, when Consumption tier is enough and when you need to use Developer tier.

Are such optimizations welcomed?

File: azurerm/internal/services/apimanagement/api_management_api_schema_resource.go [hunk 2]
```diff
@@ -140,10 +156,32 @@ func resourceApiManagementApiSchemaRead(d *pluginsdk.ResourceData, meta interfac
...
+					value, err := json.Marshal(documentProperties.Definitions)
+					if err != nil {
+						return fmt.Errorf("[FATAL] Unable to serialize schema to json. Error: %+v. Schema struct: %+v", err, documentProperties.Definitions)
+					}
+					d.Set("value", string(value))
+				}
+			case "application/vnd.ms-azure-apim.xsd+xml", "application/vnd.ms-azure-apim.wadl.grammars+xml":
+				d.Set("value", documentProperties.Value)
+			default:
+				return fmt.Errorf("[FATAL] Unknown content type %q for schema %q (API Management Service %q / API %q / Resource Group %q)", *properties.ContentType, schemaID, serviceName, apiName, resourceGroup)
```
Comment (katbyte) [inline azurerm/internal/services/apimanagement/api_management_api_schema_resource.go:181]: instead of defaulting to an error can we just default to the odl behaviour?
```suggestion
			default:
				d.Set("value", documentProperties.Value)
```

**Comment by wiktorn** [comment]
@katbyte  Instead of having the same logic as you propose (having the advantage of being concise), I propose maybe a bit more verbose approach, but providing logging in case new content types will appear. Regardless if it will work or not, I hope that the log entry will help identify place requiring change.

File: azurerm/internal/services/apimanagement/api_management_api_schema_resource.go (hunk 2 above)
Comment (wiktorn) [reply azurerm/internal/services/apimanagement/api_management_api_schema_resource.go]: @katbyte Instead of having the same logic as you propose (having the advantage of being concise), I propose maybe a bit more verbose approach, but providing logging in case new content types will appear. Regardless if it will work or not, I hope that the log entry will help identify place requiring change.

**Comment by katbyte** [comment]
@wiktorn - i'm not very familiar with the api management service, what is the difference between the two tiers and would it compromise the test integrity? if it is still testing the exact same thing optimizations are always welcome 🙂

File: azurerm/internal/services/apimanagement/api_management_api_schema_resource.go (hunk 2 above)
Comment (katbyte) [reply azurerm/internal/services/apimanagement/api_management_api_schema_resource.go]: oh good call! i like it 🙂

File: azurerm/internal/tf/suppress/json.go [hunk 3]
```diff
@@ -0,0 +1,27 @@
+package suppress
+
+import (
+	"encoding/json"
+	"reflect"
+
+	"github.com/hashicorp/terraform-plugin-sdk/helper/schema"
+)
+
+func JsonDiff(_, old, new string, _ *schema.ResourceData) bool {
```
Comment (katbyte) [inline azurerm/internal/tf/suppress/json.go:10]: one last comment, is there a reason not to use `structure.SuppressJsonDiff` here?

**Review by katbyte — CHANGES_REQUESTED** [review]

**Comment by wiktorn** [comment]
> @wiktorn - i'm not very familiar with the api management service, what is the difference between the two tiers and would it compromise the test integrity? if it is still testing the exact same thing optimizations are always welcome 🙂
> 

So the difference is, that `Consumption_0` uses shared instance (hence quick provisioning) and `Developer_1` means using dedicated instance. In case of shared instance, there are some limitation what can be configured. To the list of unsupported features belong:
* assigning to dedicated VNET
* developer portal
* external cache configuration
* custom domain names

And if I remember correctly, the IP address of the instance is differently returned. And I'm not sure, if you can set your own CA certificates.

The plan then would be, to use the `Consumption_0` in these places, where functionality is supported and fallback to `Developer_1` when not. This would improve time on most of the tests, leaving few that will wait for provisioning of dedicated instance.

File: azurerm/internal/tf/suppress/json.go (hunk 3 above)
Comment (wiktorn) [reply azurerm/internal/tf/suppress/json.go:10]: only my lack of knowledge, that such method exists ;-) I'll remove `suppress/json*` stuff and fall back to `structure.SuppressJsonDiff`

Comment (wiktorn) [reply azurerm/internal/tf/suppress/json.go]: Done.

**Comment by katbyte** [comment]
oh 100% if `Consumption_0` works i'm all for it - but we can do that in a separate PR so i can get this merged for todays release 🙂

**Review by katbyte — APPROVED** [review]
Thanks @wiktorn - LGTM and provided tests pass will merge shortly 🚀
